src/Base/main/default/objects/GMBLASERP__Serial_Number__c/GMBLASERP__Serial_Number__c.object-meta.xml
<CustomObject>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GMBLASERP__Serial_Number__c/fields/Available_Retail__c.field-meta.xml
<CustomField>
    <fullName>Available_Retail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available Retail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GMBLASERP__Serial_Number__c/fields/Current_Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Current_Unit_Cost__c</fullName>
    <label>Current Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/fields/GMBLASERP__Product__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>BLANKVALUE( GMBLASERP__Inventory_Balance__r.AcctSeedERP__Warehouse__r.Name , &apos;OUT&apos;)</formula>
    <label>Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMBLASERP__Serial_Number__c/fields/Model_Year__c.field-meta.xml
<CustomField>
    <fullName>Model_Year__c</fullName>
    <label>Model Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/fields/Nest__c.field-meta.xml
<CustomField>
    <fullName>Nest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nest</label>
    <referenceTo>GMBLASERP__Serial_Number__c</referenceTo>
    <relationshipLabel>Nested Serial Numbers</relationshipLabel>
    <relationshipName>Nested_Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GMBLASERP__Serial_Number__c/fields/Product_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Record_Type__c</fullName>
    <formula>GMBLASERP__Product__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Record Type</label>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of serialized inventory items that indicate whether it is a display model, to be repaired, return to supplier, or specials list if we are selling as is.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>At Supplier</fullName>
            </value>
            <value>
                <fullName>Available for Sale</fullName>
            </value>
            <value>
                <fullName>Boatopia</fullName>
            </value>
            <value>
                <fullName>Boat Show</fullName>
            </value>
            <value>
                <fullName>Consignment</fullName>
                <isActive>false</isActive>
                <label>Consignment</label>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>Display Model</fullName>
            </value>
            <value>
                <fullName>In Showroom</fullName>
                <isActive>false</isActive>
                <label>In Showroom</label>
            </value>
            <value>
                <fullName>Reserved for Retail</fullName>
                <isActive>false</isActive>
                <label>Reserved for Retail</label>
            </value>
            <value>
                <fullName>Return to Supplier</fullName>
            </value>
            <value>
                <fullName>Specials List</fullName>
            </value>
            <value>
                <fullName>Stolen</fullName>
            </value>
            <value>
                <fullName>To Be Repaired</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Model_Year__c.field-meta.xml
<CustomField>
    <fullName>Model_Year__c</fullName>
    <label>Model Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field used to determine status of a part</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending_Approval</fullName>
                <default>true</default>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>Approved for Use</fullName>
            </value>
            <value>
                <fullName>Do_Not_Use</fullName>
                <label>Do Not Use</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Product2/recordTypes/Boat.recordType-meta.xml
<RecordType>
    <fullName>Boat</fullName>
    <active>true</active>
    <label>Boat</label>
</RecordType>

src/Base/main/default/objects/Product2/recordTypes/Motor.recordType-meta.xml
<RecordType>
    <fullName>Motor</fullName>
    <active>true</active>
    <description>Outboard Motors</description>
    <label>Motor</label>
</RecordType>

src/Base/main/default/objects/Product2/recordTypes/Trailer.recordType-meta.xml
<RecordType>
    <fullName>Trailer</fullName>
    <active>true</active>
    <description>Boat trailer</description>
    <label>Trailer</label>
</RecordType>

src/FactoryStoreSites/classes/FSInventory_Service.cls
/**
 * Created by Tim on 2021-06-15.
 */

public with sharing class FSInventory_Service {

    /**
    ┌─┐┬ ┬┬─┐┬─┐┌─┐┌┐┌┌┬┐  ┌─┐┌┬┐┌─┐┌─┐┬┌─
    │  │ │├┬┘├┬┘├┤ │││ │   └─┐ │ │ ││  ├┴┐
    └─┘└─┘┴└─┴└─└─┘┘└┘ ┴   └─┘ ┴ └─┘└─┘┴ ┴
     */
    @AuraEnabled public List<RiggedBoat> RiggedBoats;

    public FSInventory_Service(String location, Integer year, String modelId){
        init(getSerialObjects(location, year, modelId));
    }

    public void init(List<SerialNumberObject> serialNumbers){
        this.getRiggedEquipmentSerials(serialNumbers);
    }

    private List<SerialNumberObject> getSerialObjects(String location, Integer year, String modelId){
        //define a list of serial number objects
        List<SerialNumberObject> boatsSerialNumbers = new List<SerialNumberObject>();

        //loop through the serial number results of the following SOQL
        for( GMBLASERP__Serial_Number__c b : [SELECT Id,
                Name,
                GMBLASERP__Product__r.Name,
                Model_Year__c,
                GMBLASERP__Product__r.Make__c
        FROM GMBLASERP__Serial_Number__c
        WHERE Location__c = :location
        AND GMBLASERP__Product__r.Id = :modelId
        AND Product_Record_Type__c = 'Boat'
        AND GMBLASERP__Product__r.Make__c = 'Legend'
        AND Model_Year__c >= :year
        AND Status__c NOT IN ('Used', 'At Supplier', 'Return to Supplier')
        AND Available_Retail__c = true
        ORDER BY Model_Year__c ASC])
        {
            //create a SerialNumber out of each
            SerialNumberObject serialNumber = new SerialNumberObject( b );
            //Add the new Serial Number to the boatSerialNumbers List
            boatsSerialNumbers.add(serialNumber);
        }

        //return the list of boatSerialNumbers
        return boatsSerialNumbers;
    }

    private List<RiggedEquipment> getRiggedEquipmentSerials(List<SerialNumberObject> serialNumberObjects){
        //define a list of equipment rigged serials to all available boats (SerialNumbers)
        List<RiggedEquipment> equipment = new List<RiggedEquipment>();

        //create a list of just the serial number values from each serial number object
        // this will pass into the 'WHERE IN' of the SOQL query to get the equipment
        List<String> serialNumbers = new List<String>();
        for(SerialNumberObject sno : serialNumberObjects){
            serialNumbers.add(sno.serialNumberId);
        }

        //loop through the serial number objects returned
        for( GMBLASERP__Serial_Number__c e : [SELECT Id,
                Name,
                GMBLASERP__Product__r.Name,
                Model_Year__c,
                GMBLASERP__Product__r.Make__c,
                Current_Unit_Cost__c,
                Product_Record_Type__c
        FROM GMBLASERP__Serial_Number__c
        WHERE Nest__c IN :serialNumbers
        AND Product_Record_Type__c IN ('Motor', 'Trailer')])
        {
            System.debug('SOQL Equipment return: ' + e);

            //create an Equipment object out of each
            RiggedEquipment eq = new RiggedEquipment( e );
            //add the new Equipment to the equipment list
            equipment.add( eq );
        }

        this.setRiggedBoats(serialNumberObjects, equipment);

        return null;
    }

    private List<RiggedBoat> setRiggedBoats(List<SerialNumberObject> s, List<RiggedEquipment> e){
//        Map<String, RiggedEquipment> equipmentObjMap = new Map<String, RiggedEquipment>();

        System.debug('setRiggedBoats using Serial Numbers: ' + s);
        System.debug('setRiggedBoats using Rigged Equipment: ' + e);

//        List<RiggedBoat> rbs = new List<RiggedBoat>;
//
//        for(RiggedEquipment item : e){
//            equipmentObjMap.put(item.serialNumber, item);
//        }
//
//        for(SerialNumberObject snoItem : s){
//            RiggedEquipment relatedEquipment = equipmentObjMap.get(snoItem.serialNumberValue);
//            if(relatedEquipment != null){
//                //snoItem.equipment.add( relatedEquipment );
//                RiggedBoat rb = new RiggedBoat(snoItem, relatedEquipment);
//            }
//        }

        return null;
    }

    private class SerialNumberObject{
        @AuraEnabled public GMBLASERP__Serial_Number__c serialNumberObject;
        @AuraEnabled public String serialNumberId;
        @AuraEnabled public String serialNumberValue;
        @AuraEnabled public Decimal serialModelYear;
        @AuraEnabled public String productId;
        @AuraEnabled public String productMake;
        @AuraEnabled public String productName;
        @AuraEnabled public List<RiggedEquipment> equipment;

        public SerialNumberObject(GMBLASERP__Serial_Number__c s){
            serialNumberObject = s;
            serialNumberId = s.Id;
            serialNumberValue = s.Id;
            serialModelYear = s.Model_Year__c;
            productId = s.GMBLASERP__Product__r.Id;
            productMake = s.GMBLASERP__Product__r.Make__c;
            productName = s.GMBLASERP__Product__r.Name;

        }
    }

    private class RiggedEquipment{
        @AuraEnabled public Decimal unitCost;
        @AuraEnabled public String serialNumber;
        @AuraEnabled public String productManufacturer;
        @AuraEnabled public String productType;
        @AuraEnabled public String productName;
        @AuraEnabled public String productId;

        public RiggedEquipment(GMBLASERP__Serial_Number__c e){
            System.debug('Equipment eq: ' + e);
            unitCost = e.Current_Unit_Cost__c;
            serialNumber = e.Name;
            productManufacturer = e.GMBLASERP__Product__r.Make__c;
            productType = e.Product_Record_Type__c;
            productName = e.GMBLASERP__Product__r.Name;
            productId = e.GMBLASERP__Product__r.Id;
        }
    }
//
    private class RiggedBoat{
        @AuraEnabled public SerialNumberObject Serial;
        @AuraEnabled public List<RiggedEquipment> Equipment;

        public RiggedBoat(SerialNumberObject s, List<RiggedEquipment> e){
            Serial = s;
            Equipment = e;
        }
    }


}