src/Base/main/default/objects/Lead/fields/BoatModel__c.field-meta.xml
<CustomField>
    <fullName>BoatModel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the model of boat that the customer is most interested in</description>
    <label>Boat Model</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType_Name__c</field>
            <operation>equals</operation>
            <value>Boat</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Leads (Boat Model)</relationshipLabel>
    <relationshipName>LeadBoatModels</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Lead/fields/hubspot_Boat_Type__c.field-meta.xml
<CustomField>
    <fullName>hubspot_Boat_Type__c</fullName>
    <label>Boat Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Lead/fields/hubspot_plan_to_purchase__c.field-meta.xml
<CustomField>
    <fullName>hubspot_plan_to_purchase__c</fullName>
    <label>When do you plan on purchasing?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Within 3 months</fullName>
            </value>
            <value>
                <fullName>3 to 6 months</fullName>
            </value>
            <value>
                <fullName>6 to 12 months</fullName>
            </value>
            <value>
                <fullName>12+ months</fullName>
            </value>
            <value>
                <fullName>Not considering the purchase of a boat at this time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Lead/fields/hubspot_subscribe_legend_newsletter__c.field-meta.xml
<CustomField>
    <fullName>hubspot_subscribe_legend_newsletter__c</fullName>
    <description>Actual name in hubspot:

Subscribe to Receive Legend Boats Newsletter</description>
    <label>Subscribe to Legend Boats Newsletter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Lead/fields/Lead_Notification_Pending__c.field-meta.xml
<CustomField>
    <fullName>Lead_Notification_Pending__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lead Notification Pending</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/Lead/fields/Marketing_Cloud_Notes__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Cloud_Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/Base/main/default/objects/Lead/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <label>Preferred_Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Preferred_Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Preferred_Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>English</fullName>
        <default>true</default>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>Afrikaans</fullName>
    </customValue>
    <customValue>
        <fullName>Albanian</fullName>
    </customValue>
    <customValue>
        <fullName>Albanian - Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Iraq</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Libya</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Morocco</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Qatar</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Saudi Arabia</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Sudan</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Syria</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Tunisia</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - United Arab Emirates</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Yemen</fullName>
    </customValue>
    <customValue>
        <fullName>Armenian</fullName>
    </customValue>
    <customValue>
        <fullName>Basque</fullName>
    </customValue>
    <customValue>
        <fullName>Belarusian</fullName>
    </customValue>
    <customValue>
        <fullName>Belarusian - Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgarian - Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Catalan</fullName>
    </customValue>
    <masterLabel>Preferred Language</masterLabel>
</GlobalValueSet>

src/Base/main/default/classes/Lead_Selector.cls
/**
 * Created by dave on 2020-05-13.
 */

public without sharing class Lead_Selector extends Application_Selector
{

  public Lead_Selector()
  {
    this.sObjectName = 'Lead';
    this.fields = new List<String>
    {
      'Id',
      'CreatedDate',
      'FirstName',
      'LastName',
      'Phone',
      'MobilePhone',
      'Email',
      'LeadSource',
      'Company',
      'IsConverted',
      'Street',
      'City',
      'State',
      'StateCode',
      'Country',
      'CountryCode',
      'PostalCode',
      'Preferred_Language__c',
      'hubspot_plan_to_purchase__c',
      'hubspot_Boat_Type__c',
      'BoatModel__c',
      'hubspot_subscribe_legend_newsletter__c',
      'Marketing_Cloud_Notes__c',
      'Lead_Notification_Pending__c'
    };
  }

  public static List<Lead> allByIds( Set<Id> ids )
  {
    return new Lead_Selector()
      .addWhereIdIn( ids )
      .query();
  }

  public static Lead byIdIncludingCampaignMembers( Id recordId )
  {
    Lead_Selector selector = new Lead_Selector();
    selector.addWhereIdIn( new Set<Id>{ recordId } )
      .addChildQuery(
      '(SELECT Id, CampaignId, Campaign.Name FROM CampaignMembers)'
    );
    List<SObject> result = selector.query();
    if( result.size() == 0 )
    {
      throw new Application_Selector.SelectorException(
        'No Lead record found with supplied Id'
      );
    }
    else
    {
      return (Lead)result[0];
    }
  }

  public static List<Lead> allNonConvertedByEmail( String email )
  {
    Lead_Selector selector = new Lead_Selector();
    selector
      .addWhere('IsConverted = false')
      .addWhere( 'Email = \'' + email +'\'', 'AND' )
      .addOrderBy( 'CreatedDate DESC' );
    return (List<Lead>)selector.query();
  }
}