src/Base/main/default/objects/Lead/fields/Closest_Partner__c.field-meta.xml
<CustomField>
    <fullName>Closest_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Closest Partner to the Lead</description>
    <label>Closest Partner</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Closest Partner must be a Dealer</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>ClosestLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Lead/fields/hubspot_IP_City_Lead__c.field-meta.xml
<CustomField>
    <fullName>hubspot_IP_City_Lead__c</fullName>
    <label>IP City Lead</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Lead/fields/IP_City__c.field-meta.xml
<CustomField>
    <fullName>IP_City__c</fullName>
    <description>Field to allow for tracking the lead&apos;s city as determined by IP in Hubspot</description>
    <label>IP City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/Automation/main/default/classes/Lead/Tests/TA_Lead_SetClosestPartner_T.cls
/**
 * Created by dave on 2022-06-15.
 */

@IsTest
private class TA_Lead_SetClosestPartner_T {
  @testSetup
  static void dataSetup() {
    TA_Lead_TestHelper.dataSetup();
  }

  @IsTest
  static void afterInsert_Trigger_ByLeadSource() {
    Lead personLead = Factory_Lead.buildLead(true);
    List<String> leadSources = new List<String>(Lead_Service.factoryAccountIdByLeadSource.keySet());
    personLead.LeadSource = leadSources[0];
    Test.startTest();
    insert personLead;
    Test.stopTest();
    Lead result = [SELECT Id, Closest_Partner__c FROM Lead WHERE Id = :personLead.Id];
    System.assertEquals(Lead_Service.factoryAccountIdByLeadSource.get(leadSources[0]), result.Closest_Partner__c);
  }

  @IsTest
  static void afterInsert_Trigger_IpCity() {
    TA_Lead_TestHelper.setDealers();
    Lead personLead = Factory_Lead.buildLead(true);
    personLead.IP_City__c = 'Orillia';
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new Tests_CalloutMocks.GoogleDestinationsMatrixMock());
    insert personLead;
    Test.stopTest();
    Lead result = [SELECT Id, Closest_Partner__c FROM Lead WHERE Id = :personLead.Id];
    System.assertEquals(TA_Lead_TestHelper.orillia.Id, result.Closest_Partner__c);
  }

  @IsTest
  static void afterInsert_Trigger_HubSpotIpCity() {
    TA_Lead_TestHelper.setDealers();
    Lead personLead = Factory_Lead.buildLead(true);
    personLead.hubspot_IP_City_Lead__c = 'Orillia';
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new Tests_CalloutMocks.GoogleDestinationsMatrixMock());
    insert personLead;
    Test.stopTest();
    Lead result = [SELECT Id, Closest_Partner__c FROM Lead WHERE Id = :personLead.Id];
    System.assertEquals(TA_Lead_TestHelper.orillia.Id, result.Closest_Partner__c);
  }

  @IsTest
  static void afterInsert_Trigger_PostalCode() {
    TA_Lead_TestHelper.setDealers();
    Lead personLead = Factory_Lead.buildLead(true);
    personLead.PostalCode = 'L3V3V3';
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new Tests_CalloutMocks.GoogleDestinationsMatrixMock());
    insert personLead;
    Test.stopTest();
    Lead result = [SELECT Id, Closest_Partner__c FROM Lead WHERE Id = :personLead.Id];
    System.assertEquals(TA_Lead_TestHelper.orillia.Id, result.Closest_Partner__c);
  }

  @IsTest
  static void afterInsert_Trigger_100() {
    TA_Lead_TestHelper.setDealers();
    List<Lead> leads = new List<Lead>();
    for (Integer i = 0; i < 100; i++) {
      Lead l = Factory_Lead.buildLead(true);
      l.IP_City__c = 'Orillia';
      leads.add(l);
    }
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new Tests_CalloutMocks.GoogleDestinationsMatrixMock());
    insert leads;
    Test.stopTest();
    Lead result = [SELECT Id, Closest_Partner__c FROM Lead WHERE Id = :leads[0].Id];
    System.assertEquals(TA_Lead_TestHelper.orillia.Id, result.Closest_Partner__c);
  }

  @IsTest
  static void afterUpdate() {
    TA_Lead_TestHelper.setDealers();
    Lead personLead = Factory_Lead.buildLead(true);
    TriggerBase.bypass('Lead');
    insert personLead;
    TriggerBase.clearBypass('Lead');

    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new Tests_CalloutMocks.GoogleDestinationsMatrixMock());
    personLead.IP_City__c = 'Orillia';
    update personLead;
    Test.stopTest();
    Lead result = [SELECT Id, Closest_Partner__c FROM Lead WHERE Id = :personLead.Id];
    System.assertEquals(TA_Lead_TestHelper.orillia.Id, result.Closest_Partner__c);
  }
}