force-app/main/default/objects/Product_Upgrade__c/Product_Upgrade__c.object-meta.xml
<CustomObject>
    <label>Product Upgrade</label>
    <nameField>
        <displayFormat>PU-{0000}</displayFormat>
        <label>Product_Upgrade ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Upgrades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Upgrade__c/fields/From_Product__c.field-meta.xml
<CustomField>
    <fullName>From_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Upgrades (From Product)</relationshipLabel>
    <relationshipName>From_Product_Upgrades</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Product_Upgrade__c/fields/To_Product__c.field-meta.xml
<CustomField>
    <fullName>To_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Upgrades (To Product)</relationshipLabel>
    <relationshipName>To_Product_Upgrades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductMotorExt.cls
public with sharing class ProductMotorExt {

  private ApexPages.StandardController std;
  public ID recordId;

  public ProductMotorExt(ApexPages.StandardController stdCtrl) {
    std = stdCtrl;
    recordId = std.getID();
  }

  public List<Product_Upgrade__c> getMotorUpgrades(){
    return [SELECT Id, Price__c, To_Product__r.Name
            FROM Product_Upgrade__c
            WHERE From_Product__c = :recordId ];
  }

}