force-app/main/default/objects/Product_Upgrade__c/Product_Upgrade__c.object-meta.xml
<CustomObject>
    <label>Product Upgrade</label>
    <nameField>
        <displayFormat>PU-{0000}</displayFormat>
        <label>Product_Upgrade ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Upgrades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Upgrade__c/fields/From_Product__c.field-meta.xml
<CustomField>
    <fullName>From_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Upgrades (From Product)</relationshipLabel>
    <relationshipName>From_Product_Upgrades</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Product_Upgrade__c/fields/To_Product__c.field-meta.xml
<CustomField>
    <fullName>To_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Upgrades (To Product)</relationshipLabel>
    <relationshipName>To_Product_Upgrades</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/classes/UpgradeChart.cls
public with sharing class UpgradeChart {

  public ID to_Id { set; get; }
  public Product2 FromObj { set; get; }

    public UpgradeChart() {

    }

  public Product_Upgrade__c getProductUpgradeCost() {
    List<Product_Upgrade__c> ups = FromObj.From_Product_Upgrades__r;
    Product_Upgrade__c temp = new Product_Upgrade__c();
    if( ups.isEmpty()) {
       return temp;
    }
    if(FromObj.Id == to_Id) {
      return temp;
    }
    for(Product_Upgrade__c mu : ups) {
      if(mu.To_Product__c == to_Id && mu.From_Product__c == FromObj.Id) {
        temp = mu;
      }
    }
    return temp;
   }

  // public Trailer_Upgrade__c getTrailerUpgradeCost() {
  //   List<Trailer_Upgrade__c> ups = FromObj.From_Trailer_Upgrades__r;
  //   Trailer_Upgrade__c temp = new Trailer_Upgrade__c();
  //   if( ups.isEmpty()) {
  //      return temp;
  //   }
  //   if(FromObj.Id == to_Id) {
  //     return temp;
  //   }
  //   for(Trailer_Upgrade__c tu : ups) {
  //     if(tu.To_Trailer__c == to_Id && tu.From_Trailer__c == FromObj.Id) {
  //       temp = tu;
  //     }
  //   }
  //   return temp;
  // }

}