force-app/main/default/objects/Trade_In_Record__c/Trade_In_Record__c.object-meta.xml
<CustomObject>
    <label>Trade In Record</label>
    <nameField>
        <displayFormat>TIR-{0000}</displayFormat>
        <label>Trade In Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade In Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/Trade_In_Record__c/fields/IsSyncing__c.field-meta.xml
<CustomField>
    <fullName>IsSyncing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Syncing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trade_In_Record__c/fields/Lien_Amount__c.field-meta.xml
<CustomField>
    <fullName>Lien_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lien Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trade_In_Record__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Trade In Records</relationshipLabel>
    <relationshipName>Trade_In_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trade_In_Record__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Trade In Records</relationshipLabel>
    <relationshipName>Trade_In_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trade_In_Record__c/fields/Total_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Value__c</fullName>
    <label>Total Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/classes/Quote_TriggerHandler_Test.cls
@isTest
private class Quote_TriggerHandler_Test {
  static Opportunity opp;
  static Quote quot;

  @testSetup
  static void dataSetup() {
    new Factory_TestData();
    Factory_CustomSettings.setupInventorySettings();
    Account cust = Factory_Account.insertCustomerAccounts(1)[0];
    Opportunity o = Factory_Opportunity.insertOpportunity(cust, Test.getStandardPricebookId());
    Quote q = Factory_Quote.insertQuote(o);
  }

  private static void init() {
    opp = [SELECT Id, (SELECT Id FROM Quotes) FROM Opportunity LIMIT 1];
    quot = opp.Quotes[0];
  }

  private static Trade_In_Record__c insertTradeInRecord(Id qId) {
    Trade_In_Record__c tr = new Trade_In_Record__c(
      Quote__c = qId,
      Opportunity__c = opp.Id,
      Total_Value__c = 1000,
      Lien_Amount__c = 500,
      IsSyncing__c = false
    );
    insert tr;
    return tr;
  }

  @isTest
  static void trigger_Test() {
    init();
    quot.Name = 'Test Quote 2';
    update quot;
  }

  @isTest
  static void syncTradeInRecord_Test() {
    init();
    Trade_In_Record__c tr = insertTradeInRecord(quot.Id);
    opp.SyncedQuoteId = quot.Id;
    update opp;
    Trade_In_Record__c tr_after = [SELECT Id, IsSyncing__c FROM Trade_In_Record__c WHERE Id = :tr.Id];
    System.assertEquals(false, tr.IsSyncing__c);
    System.assertEquals(true, tr_after.IsSyncing__c);
  }

  @isTest
  static void deleteTradeInRecord_Test() {
    init();
    Id qId = quot.Id;
    Trade_In_Record__c tr = insertTradeInRecord(quot.Id);
    delete quot;
    Trade_In_Record__c[] trs = [SELECT Id FROM Trade_In_Record__c WHERE Quote__c = :qId];
    System.assertEquals(0, trs.size());
  }
}