force-app/main/default/objects/Case/fields/Inquiry_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Inquiry_Product_Name__c</fullName>
    <label>Inquiry Product Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Case/fields/Inquiry_Product_Year__c.field-meta.xml
<CustomField>
    <fullName>Inquiry_Product_Year__c</fullName>
    <label>Inquiry Product Year Unformatted</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Case/fields/Inquiry_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Inquiry_Serial_Number__c</fullName>
    <label>Inquiry Serial Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Partner_Reference__c.field-meta.xml
<CustomField>
    <fullName>Partner_Reference__c</fullName>
    <description>Dealer&apos;s work order number, shown here for their own reference</description>
    <label>Partner Reference</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Case/recordTypes/PartInquiry.recordType-meta.xml
<RecordType>
    <fullName>PartInquiry</fullName>
    <active>true</active>
    <businessProcess>Inquiry</businessProcess>
    <description>Part Inquiry</description>
    <label>PartInquiry</label>
</RecordType>

src/Base/main/default/classes/lgnd_partsInquiryController.cls
public with sharing class lgnd_partsInquiryController {
  @AuraEnabled
  public static String save(String sernoName, String model, Integer lot, String description, String partnerReference) {
    Id accountId;
    if (String.isBlank(sernoName)) {
      throw new SerialNumber_Exception('You must specify Boat serial number');
    }
    Case c = new Case(
      Inquiry_Serial_Number__c = sernoName,
      Inquiry_Product_Name__c = model,
      Inquiry_Product_Year__c = lot,
      Description = description,
      Partner_Reference__c = partnerReference,
      recordTypeId = LGND_Utilities.recordTypeIdFromName('Case', 'PartInquiry')
    );

    try {
      accountId = [SELECT AccountId FROM User WHERE Id = :Userinfo.getUserId()].AccountId;
      if (accountId != null) {
        c.AccountId = accountId;
      } else {
        c.AccountId = '';
      }
    } catch (Exception e) {
      System.debug(e);
    }

    System.debug(sernoName);

    upsert c;

    return c.Id;
    // throw new Exception('').getMessage();
    //return new Exception('invalid').getMessage();
  }
  public class SerialNumber_Exception extends Exception {
  }
}