force-app/main/default/objects/AcctSeed__Accounting_Period__c/AcctSeed__Accounting_Period__c.object-meta.xml
<CustomObject>
    <customHelpPage>AcctSeed__AccountingPeriodHelp</customHelpPage>
    <description>Used to capture all the financial activity that occurs during a specified time period. Accounting periods are typically defined to coincide with a calendar year month.</description>
    <label>Accounting  Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Journal_Entry__c/AcctSeed__Journal_Entry__c.object-meta.xml
<CustomObject>
    <description>Used to document accounting related entries into the transaction table.</description>
    <label>Journal Entry</label>
    <nameField>
        <label>Journal Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Journal_Entry__c/fields/AcctSeed__Accounting_Period__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Accounting_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Used to specify accounting period for financial reporting. Accounting period must have a value of Open.</inlineHelpText>
    <label>Accounting  Period</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Period__c.AcctSeed__Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </filterItems>
        <infoMessage>The accounting period status must be open</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Period__c</referenceTo>
    <relationshipLabel>Journal Entry</relationshipLabel>
    <relationshipName>Journal_Entry</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Journal_Entry__c/fields/AcctSeed__Ledger__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Ledger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes the associated ledger.</description>
    <label>Ledger</label>
    <referenceTo>AcctSeed__Ledger__c</referenceTo>
    <relationshipLabel>Journal Entries</relationshipLabel>
    <relationshipName>Journal_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Ledger__c/AcctSeed__Ledger__c.object-meta.xml
<CustomObject>
    <description>Used to associate and aggregate financial transaction or budget entries with a specific entity.</description>
    <label>Ledger</label>
    <nameField>
        <label>Ledger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Location__c/AcctSeedERP__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeedERP__Location__c/fields/AcctSeedERP__Warehouse__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Warehouse__c/AcctSeedERP__Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Automation/main/default/classes/JournelEntry/Tests/TA_JournalEntry_Legacy_T.cls
/**
 * Created by dave on 2022-01-26.
 */

@IsTest
private class TA_JournalEntry_Legacy_T
{
  @TestSetup
  static void dataSetup(){
    new Factory_TestData();
    Factory_CustomSettings.setupInventorySettings();
  }

  private static List<AcctSeed__Journal_Entry__c> newList;
  private static List<AcctSeed__Journal_Entry__c> oldList;

  private static void buildTriggerVariables( Boolean isUpdate ){
    newList = new List<AcctSeed__Journal_Entry__c>();
    oldList = new List<AcctSeed__Journal_Entry__c>();
//
//    AcctSeedERP__Location__c loc = new AcctSeedERP__Location__c(
//      Name = 'Test Loc',
//      AcctSeedERP__Warehouse__c = Test_Constants.idWarehouse
//    );
//    insert loc;
    AcctSeed__Journal_Entry__c je = new AcctSeed__Journal_Entry__c(
      Name = 'Test Journal',
      AcctSeed__Accounting_Period__c = Test_Constants.idPeriod,
      AcctSeed__Ledger__c =Test_Constants.idLedger
    );
    if( isUpdate ){
      je.Id = TestUtility.getFakeId(AcctSeed__Journal_Entry__c.SObjectType);
    }
    AcctSeed__Journal_Entry__c orig_je = je.clone(true, true, true,true);
    je.Name = 'Test Journal Two';
    oldList.add( orig_je );
    newLIst.add( je );
  }

  @IsTest
  static void beforeInsertTest() {
    buildTriggerVariables(false);
    Test.startTest();
    new TA_JournalEntry_Legacy().beforeInsert(newList);
    Test.stopTest();
  }

  @IsTest
  static void afterInsertTest() {
    buildTriggerVariables(true);
    Test.startTest();
    new TA_JournalEntry_Legacy().afterInsert(newList);
    Test.stopTest();
  }

  @IsTest
  static void beforeUpdateTest() {
    buildTriggerVariables(true);
    Test.startTest();
    new TA_JournalEntry_Legacy().beforeUpdate(newList, oldList);
    Test.stopTest();
  }

  @IsTest
  static void afterUpdateTest() {
    buildTriggerVariables(true);
    Test.startTest();
    new TA_JournalEntry_Legacy().afterUpdate(newList, oldList);
    Test.stopTest();
  }

  @IsTest
  static void beforeDeleteTest() {
    buildTriggerVariables(true);
    Test.startTest();
    new TA_JournalEntry_Legacy().beforeDelete(oldList);
    Test.stopTest();
  }

  @IsTest
  static void afterDeleteTest() {
    buildTriggerVariables(true);
    Test.startTest();
    new TA_JournalEntry_Legacy().afterDelete(oldList);
    Test.stopTest();
  }
}