force-app/main/default/objects/AcctSeed__Accounting_Period__c/AcctSeed__Accounting_Period__c.object-meta.xml
<CustomObject>
    <customHelpPage>AcctSeed__AccountingPeriodHelp</customHelpPage>
    <description>Used to capture all the financial activity that occurs during a specified time period. Accounting periods are typically defined to coincide with a calendar year month.</description>
    <label>Accounting  Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Accounting_Period__c/fields/AcctSeed__End_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__End_Date__c</fullName>
    <inlineHelpText>Accounting periods are typically used as months. This denotes the end of the period. Fiscal Months are supported. A period end date can not cross over into the start and end date range of another period.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Accounting_Period__c/fields/AcctSeed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Start_Date__c</fullName>
    <inlineHelpText>Accounting periods are typically used as months. This denotes the beginning of the period. Fiscal Months are supported. A period beginning date can not cross over into the start and end date range of another period.</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Accounting_Period__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>&quot;Open&quot; allows new transactions to be saved to this period. &quot;Closed&quot; prevents new records from being saved to this period.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeed__Accounting_Variable__c/AcctSeed__Accounting_Variable__c.object-meta.xml
<CustomObject>
    <description>Used to categorize or group general ledger transactions, profit centers, cost centers, geographies, or lines of offerings based on business need.</description>
    <label>Accounting Variable</label>
    <nameField>
        <label>Accounting Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Variables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Accounting_Variable__c/fields/AcctSeed__Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Type__c</fullName>
    <inlineHelpText>Used to determine GL Account Variables 1-4 and Time Card Variables 1-2.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GL Account Variable 1</fullName>
            </value>
            <value>
                <fullName>GL Account Variable 2</fullName>
            </value>
            <value>
                <fullName>GL Account Variable 3</fullName>
            </value>
            <value>
                <fullName>GL Account Variable 4</fullName>
            </value>
            <value>
                <fullName>Time Card Variable 1</fullName>
            </value>
            <value>
                <fullName>Time Card Variable 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeed__Accounting_Variable__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Relationship with the User for GL Account Variable 4</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounting_Variables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card_Period__c/AcctSeed__Time_Card_Period__c.object-meta.xml
<CustomObject>
    <description>Used to capture the specific time frame e.g. start date and end date associated with a time card.</description>
    <label>Time Card Period</label>
    <nameField>
        <label>Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Card Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Time_Card_Period__c/fields/AcctSeed__End_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__End_Date__c</fullName>
    <inlineHelpText>Last day of the Time Card Period. This field is automatically calculated to be 6 days after the start date entered for the Time Card Period.. A value entered directly into this field will be overwritten.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card_Period__c/fields/AcctSeed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Start_Date__c</fullName>
    <inlineHelpText>Beginning of the Time Card Period. Typically a Monday or Sunday.</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card_Period__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>&quot;Open&quot; indicates that Time Cards can be entered for this period. &quot;Closed&quot; indicates that no new Time Cards can be entered for this period.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/GL_Account_Variable_2__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Department</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 2</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Employees (This GLV2)</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Wage_Rate__c/Employee_Wage_Rate__c.object-meta.xml
<CustomObject>
    <label>Employee Wage Rate</label>
    <nameField>
        <displayFormat>EWR-{0000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Wage Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Wage_Rate__c/fields/Base__c.field-meta.xml
<CustomField>
    <fullName>Base__c</fullName>
    <label>Base</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Employee_Wage_Rate__c/fields/Benefits__c.field-meta.xml
<CustomField>
    <fullName>Benefits__c</fullName>
    <label>Benefits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Employee_Wage_Rate__c/fields/Effective_Time_Card_Period__c.field-meta.xml
<CustomField>
    <fullName>Effective_Time_Card_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Effective Time Card Period</label>
    <referenceTo>AcctSeed__Time_Card_Period__c</referenceTo>
    <relationshipLabel>Employee Wage Rates</relationshipLabel>
    <relationshipName>Employee_Wage_Rates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Wage_Rate__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Wage Rates</relationshipLabel>
    <relationshipName>Employee_Wage_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/Automation/main/default/classes/EmployeeWageRate/Tests/TA_EmployeeWageRate_Legacy_T.cls
@isTest
public class TA_EmployeeWageRate_Legacy_T {
    static  List<Employee_Wage_Rate__c> lstEmployeeWageRate;
    private static List<Employee_Wage_Rate__c> getData(){
        return [SELECT id, Effective_Time_Card_Period__c, Benefits__c, Base__c,Employee__c FROM Employee_Wage_Rate__c];
    }
    @TestSetup
    static void testData(){
        new Factory_TestData();
        User u = Factory_User.buildUser('Fname', 'Lname', 'System Administrator');
        insert u;
        Id idGLV2 = [SELECT Id FROM AcctSeed__Accounting_Variable__c WHERE AcctSeed__Type__c = 'GL Account Variable 2' LIMIT 1][0].Id;
        Employee__c employee = new Employee__c(
                GL_Account_Variable_2__c = idGLV2,
                Name = 'Test Employee',
                User__c = u.Id
        );

        insert employee;

        AcctSeed__Accounting_Period__c period = [SELECT Id, AcctSeed__Start_Date__c, AcctSeed__End_Date__c
        FROM AcctSeed__Accounting_Period__c LIMIT 1];
        AcctSeed__Time_Card_Period__c tcp = new AcctSeed__Time_Card_Period__c(
                AcctSeed__End_Date__c = period.AcctSeed__End_Date__c,
                AcctSeed__Start_Date__c = period.AcctSeed__Start_Date__c.toStartOfWeek().addDays(7),
                AcctSeed__Status__c = 'Open'
        );
        insert tcp;
        Employee_Wage_Rate__c ewr = new Employee_Wage_Rate__c(
                Employee__c = employee.Id,
                Effective_Time_Card_Period__c = tcp.Id,
                Benefits__c = 10,
                Base__c = 50);
        insert ewr;
    }
    @IsTest
    static void beforeInsertTest() {
        Test.startTest();
        lstEmployeeWageRate = getData();
        new TA_EmployeeWageRate_Legacy().beforeInsert(lstEmployeeWageRate);
        Test.stopTest();
    }
    @IsTest
    static void afterInsertTest() {
        Test.startTest();
        new TA_EmployeeWageRate_Legacy().afterInsert(getData());
        Test.stopTest();
    }
    @IsTest
    static void afterUpdateTest() {
        Test.startTest();
        lstEmployeeWageRate = getData();
        Employee_Wage_Rate__c empWagerateClone =lstEmployeeWageRate[0].clone(true, true, true, true);
        new TA_EmployeeWageRate_Legacy().afterUpdate(new List<Employee_Wage_Rate__c>{lstEmployeeWageRate[0]},new List<Employee_Wage_Rate__c>{empWagerateClone});
        Test.stopTest();
    }
    @IsTest
    static void beforeUpdateTest() {
        Test.startTest();
        lstEmployeeWageRate = getData();
        Employee_Wage_Rate__c empWagerateClone =lstEmployeeWageRate[0].clone(true, true, true, true);
        new TA_EmployeeWageRate_Legacy().beforeUpdate(new List<Employee_Wage_Rate__c>{lstEmployeeWageRate[0]},new List<Employee_Wage_Rate__c>{empWagerateClone});
        Test.stopTest();
    }
    @IsTest
    static void beforeDeleteTest() {
        Test.startTest();
        new TA_EmployeeWageRate_Legacy().beforeDelete(getData());
        Test.stopTest();
    }
    @IsTest
    static void afterDeleteTest() {
        Test.startTest();
        new TA_EmployeeWageRate_Legacy().afterDelete(getData());
        Test.stopTest();
    }

}