force-app/main/default/objects/AcctSeed__Accounting_Period__c/AcctSeed__Accounting_Period__c.object-meta.xml
<CustomObject>
    <customHelpPage>AcctSeed__AccountingPeriodHelp</customHelpPage>
    <description>Used to capture all the financial activity that occurs during a specified time period. Accounting periods are typically defined to coincide with a calendar year month.</description>
    <label>Accounting  Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Accounting_Period__c/fields/AcctSeed__End_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__End_Date__c</fullName>
    <inlineHelpText>Accounting periods are typically used as months. This denotes the end of the period. Fiscal Months are supported. A period end date can not cross over into the start and end date range of another period.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Accounting_Period__c/fields/AcctSeed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Start_Date__c</fullName>
    <inlineHelpText>Accounting periods are typically used as months. This denotes the beginning of the period. Fiscal Months are supported. A period beginning date can not cross over into the start and end date range of another period.</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Accounting_Period__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>&quot;Open&quot; allows new transactions to be saved to this period. &quot;Closed&quot; prevents new records from being saved to this period.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/classes/gcProjectLaborJobCost_BatchSchedulable.cls
public without sharing class gcProjectLaborJobCost_BatchSchedulable implements Schedulable {
  //To schedule the batch to run every hour at 10 minutes past the hour:
  //system.schedule('Job Cost Labor Cleansweep','0 10 * * * ?',new gcProjectLaborJobCost_BatchSchedulable());
  public void execute(SchedulableContext sc) {
    AcctSeed__Accounting_Period__c period;

    //find the current period, and if it's open, run the batch for the current period.
    for (AcctSeed__Accounting_Period__c p : [
      SELECT Id, AcctSeed__Start_Date__c, AcctSeed__End_Date__c, AcctSeed__Status__c
      FROM AcctSeed__Accounting_Period__c
      WHERE AcctSeed__Start_Date__c <= TODAY AND AcctSeed__End_Date__c >= TODAY
    ]) {
      period = p;
    }

    if (period == null)
      return;

    if (period.AcctSeed__Status__c == 'Open')
      Database.executeBatch(new gcProjectLaborJobCost_Batch(period.Id), 10);

    //if the prior period is still open, run the batch for that period too.
    for (AcctSeed__Accounting_Period__c p : [
      SELECT Id
      FROM AcctSeed__Accounting_Period__c
      WHERE AcctSeed__Start_Date__c < :period.AcctSeed__Start_Date__c AND AcctSeed__Status__c = 'Open'
      ORDER BY AcctSeed__Start_Date__c DESC
      LIMIT 1
    ]) {
      Database.executeBatch(new gcProjectLaborJobCost_Batch(period.Id), 10);
    }
  }
}