force-app/main/default/objects/AcctSeed__Accounting_Period__c/AcctSeed__Accounting_Period__c.object-meta.xml
<CustomObject>
    <customHelpPage>AcctSeed__AccountingPeriodHelp</customHelpPage>
    <description>Used to capture all the financial activity that occurs during a specified time period. Accounting periods are typically defined to coincide with a calendar year month.</description>
    <label>Accounting  Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Accounting_Period__c/fields/AcctSeed__End_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__End_Date__c</fullName>
    <inlineHelpText>Accounting periods are typically used as months. This denotes the end of the period. Fiscal Months are supported. A period end date can not cross over into the start and end date range of another period.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Accounting_Period__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>&quot;Open&quot; allows new transactions to be saved to this period. &quot;Closed&quot; prevents new records from being saved to this period.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/AcctSeed__Billing__c/AcctSeed__Billing__c.object-meta.xml
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Billing__c/fields/AcctSeed__Accounting_Period__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Accounting_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Used to specify accounting period for financial reporting. Accounting period must have a value of &quot;Open&quot; in order to be selected.</inlineHelpText>
    <label>Accounting  Period</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Period__c.AcctSeed__Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </filterItems>
        <infoMessage>The accounting period status must be open</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Period__c</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Project_Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Billing__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>Used in approvals of billing records and therefore related detail lines. A value of &quot;Posted&quot; indicates the record is final and a debit and credit line have been entered into the transaction object for each billing line.</inlineHelpText>
    <label>Posting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
                <default>true</default>
                <label>In Process</label>
            </value>
            <value>
                <fullName>Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeed__Billing__c/fields/AcctSeedERP__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>AcctSeedERP__Sales_Order__c</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Billing__c/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The value select for Tax Zone must be an Accounting Variable of Type 3.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 3</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Billing__c/fields/Tax_Rate_Federal__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_Federal__c</fullName>
    <label>Tax Rate - Federal</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Billing__c/fields/Tax_Rate_Provincial__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_Provincial__c</fullName>
    <label>Tax Rate - Provincial</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Billing_Line__c/AcctSeed__Billing_Line__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific product or service associated with a billing. The aggregation of multiple billing lines constitute a billing record.</description>
    <label>Billing Line</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Billing Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__Billing__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Billing__c</fullName>
    <inlineHelpText>Reference to parent object.</inlineHelpText>
    <label>Billing</label>
    <referenceTo>AcctSeed__Billing__c</referenceTo>
    <relationshipLabel>Billing Lines</relationshipLabel>
    <relationshipName>Project_Billing_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Billing_Line__c/fields/Shipment_Line__c.field-meta.xml
<CustomField>
    <fullName>Shipment_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>When a Billing line is created from Sales Order Shipment we will populate this lookup so that we can track the actual record.</description>
    <label>Shipment Line</label>
    <referenceTo>AcctSeedERP__Shipment_Line__c</referenceTo>
    <relationshipLabel>Billing Lines</relationshipLabel>
    <relationshipName>Billing_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Sales_Order__c/AcctSeedERP__Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Sales_Order__c/fields/AcctSeedERP__Customer__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Type__c</field>
            <operation>equals</operation>
            <value>Customer, Customer and Vendor</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Order</relationshipLabel>
    <relationshipName>Sales_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Sales_Order__c/fields/AcctSeedERP__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Sales_Order__c/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Sales Order</relationshipLabel>
    <relationshipName>Sales_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Sales_Order__c/fields/Tax_is_Harmonized__c.field-meta.xml
<CustomField>
    <fullName>Tax_is_Harmonized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax is Harmonized</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Sales_Order__c/fields/Tax_Rate_Federal__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_Federal__c</fullName>
    <label>Tax Rate - Federal</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Sales_Order__c/fields/Tax_Rate_Provincial__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_Provincial__c</fullName>
    <label>Tax Rate - Provincial</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Sales_Order__c/fields/Tax_Rate_Retail__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_Retail__c</fullName>
    <label>Tax Rate - Retail</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Sales_Order_Line__c/AcctSeedERP__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{00000}</displayFormat>
        <label>Sales Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeedERP__Sales_Order_Line__c/fields/AcctSeedERP__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Sales Order Line</relationshipLabel>
    <relationshipName>Sales_Order_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Sales_Order_Line__c/fields/AcctSeedERP__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>AcctSeedERP__Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Line</relationshipLabel>
    <relationshipName>Sales_Order_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Shipment__c/AcctSeedERP__Shipment__c.object-meta.xml
<CustomObject>
    <label>Shipment</label>
    <nameField>
        <displayFormat>SP-{00000}</displayFormat>
        <label>Shipment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Shipment__c/fields/AcctSeedERP__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>AcctSeedERP__Sales_Order__c</referenceTo>
    <relationshipName>Shipments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Shipment__c/fields/AcctSeedERP__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
                <default>true</default>
                <label>Scheduled</label>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Shipment_Line__c/AcctSeedERP__Shipment_Line__c.object-meta.xml
<CustomObject>
    <label>Shipment Line</label>
    <nameField>
        <displayFormat>SPL-{00000}</displayFormat>
        <label>Shipment Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipment Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Shipment_Line__c/fields/AcctSeedERP__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Product__c</fullName>
    <formula>AcctSeedERP__Sales_Order_Line__r.AcctSeedERP__Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Shipment_Line__c/fields/AcctSeedERP__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Sales_Order__c</fullName>
    <formula>AcctSeedERP__Shipment__r.AcctSeedERP__Sales_Order__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Order</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Shipment_Line__c/fields/AcctSeedERP__Shipment__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Shipment__c</fullName>
    <label>Shipment</label>
    <referenceTo>AcctSeedERP__Shipment__c</referenceTo>
    <relationshipLabel>Shipment Lines</relationshipLabel>
    <relationshipName>Shipment_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/classes/Shipment_Service.cls
/**
 * Created by Legend on 28/4/22.
 */

public without sharing class Shipment_Service {
    public static void Billing(Set<Id> setIdShipment) {
        Map<Id, AcctSeed__Billing__c> billingToBeSaved = new Map<Id, AcctSeed__Billing__c>();
        Map<Id, List<AcctSeed__Billing_Line__c>> mapShipmentListLine = new Map<Id, List<AcctSeed__Billing_Line__c>>();
        List<AcctSeed__Billing_Line__c> listBillingLines = new List<AcctSeed__Billing_Line__c>();
        Date billDate = Date.today();
        Map<Id, AcctSeedERP__Shipment__c> mapShipments = new Map<Id, AcctSeedERP__Shipment__c>();
        Id idPeriod;
        for (AcctSeedERP__Shipment__c shipment : [
                SELECT Id,
                        AcctSeedERP__Status__c,
                        AcctSeedERP__Sales_Order__r.AcctSeedERP__Customer__c,
                        AcctSeedERP__Sales_Order__r.GL_Account_Variable_3__c,
                        AcctSeedERP__Sales_Order__r.Tax_is_Harmonized__c,
                        AcctSeedERP__Sales_Order__r.Tax_Rate_Federal__c,
                        AcctSeedERP__Sales_Order__r.Tax_Rate_Provincial__c,
                        AcctSeedERP__Sales_Order__r.Tax_Rate_Retail__c
                FROM AcctSeedERP__Shipment__c
                WHERE ID IN:setIdShipment AND AcctSeedERP__Status__c = 'Shipped'
        ]) {
            mapShipments.put(shipment.Id, shipment);
            mapShipmentListLine.put(shipment.Id, new List<AcctSeed__Billing_Line__c>());
        }
        if (!mapShipments.isEmpty()) {
            /// Find The Period
            for (AcctSeed__Accounting_Period__c p : [SELECT Id FROM AcctSeed__Accounting_Period__c WHERE AcctSeed__End_Date__c >= :billDate AND AcctSeed__Status__c = 'Open' ORDER BY AcctSeed__End_Date__c LIMIT 1]) {
                idPeriod = p.Id;
            }

            for (AcctSeedERP__Shipment_Line__c shipmentLine : [
                    SELECT Id,
                            AcctSeedERP__Product__c,
                            AcctSeedERP__Quantity_Shipped__c,
                            AcctSeedERP__Sales_Order__c,
                            AcctSeedERP__Sales_Order_Line__c,
                            AcctSeedERP__Sales_Order_Line__r.AcctSeedERP__Product__r.AcctSeed__Inventory_Product__c,
                            AcctSeedERP__Sales_Order_Line__r.AcctSeedERP__Product__r.Composite_Type__c,
                            AcctSeedERP__Sales_Order_Line__r.AcctSeedERP__Quantity_Allocated__c,
                            AcctSeedERP__Sales_Order_Line__r.AcctSeedERP__Quantity_Ordered__c,
                            AcctSeedERP__Sales_Order_Line__r.AcctSeedERP__Quantity_Needed__c,
                            AcctSeedERP__Sales_Order_Line__r.AcctSeedERP__Unit_Price__c,
                            AcctSeedERP__Sales_Order_Line__r.Taxable_Federal__c,
                            AcctSeedERP__Sales_Order_Line__r.Taxable_Provincial__c,
                            AcctSeedERP__Sales_Order_Line__r.Taxable_Retail__c,
                            AcctSeedERP__Sales_Order_Line__r.AcctSeedERP__Total__c, (SELECT Id, AcctSeed__Hours_Units__c FROM Billing_Lines__r)
                    FROM AcctSeedERP__Shipment_Line__c
                    WHERE AcctSeedERP__Shipment__c IN:mapShipments.keySet()
            ]) {
                Decimal priorBillAmt = 0;
                Decimal priorBillQty = 0;
                Boolean hasPriorBill = false;
                for (AcctSeed__Billing_Line__c line : shipmentLine.Billing_Lines__r) {
                    priorBillAmt += (line.AcctSeed__Total__c == null ? 0 : line.AcctSeed__Total__c);
                    priorBillQty += (line.AcctSeed__Hours_Units__c == null ? 0 : line.AcctSeed__Hours_Units__c);
                    hasPriorBill = true;
                }

                priorBillAmt = priorBillAmt.setScale(6);
                Decimal matlAmt = shipmentLine.AcctSeedERP__Sales_Order_Line__r.AcctSeedERP__Total__c;
                Decimal matlQty = (shipmentLine.AcctSeedERP__Quantity_Shipped__c == null ? 0 : shipmentLine.AcctSeedERP__Quantity_Shipped__c);
                Decimal matlRate = shipmentLine.AcctSeedERP__Sales_Order_Line__r.AcctSeedERP__Unit_Price__c;
                Decimal thisBillQty = matlQty - priorBillQty;
                if (matlQty != 0) {
                    if (priorBillAmt != matlAmt || (hasPriorBill == false && matlAmt == 0) || (hasPriorBill == true && matlAmt == 0 && thisBillQty <> 0)) {
                        Decimal thisBillAmt = matlAmt - priorBillAmt;
                        Decimal thisBillRate = (thisBillQty == 0 ? 0 : thisBillAmt / thisBillQty);
                        if (thisBillQty != 0) {
                            List<AcctSeed__Billing_Line__c> listLine = mapShipmentListLine.get(shipmentLine.AcctSeedERP__Shipment__c);
                            listLine.add(new AcctSeed__Billing_Line__c(
                                    AcctSeedERP__Sales_Order_Line__c = shipmentLine.AcctSeedERP__Sales_Order_Line__c,
                                    AcctSeed__Product__c = shipmentLine.AcctSeedERP__Sales_Order_Line__r.AcctSeedERP__Product__c,
                                    AcctSeed__Hours_Units__c = thisBillQty,
                                    AcctSeed__Rate__c = thisBillRate,
                                    Shipment_Line__c = shipmentLine.Id,
                                    Taxable_Federal__c = shipmentLine.AcctSeedERP__Sales_Order_Line__r.Taxable_Federal__c,
                                    Taxable_Provincial__c = shipmentLine.AcctSeedERP__Sales_Order_Line__r.Taxable_Provincial__c,
                                    Taxable_Retail__c = shipmentLine.AcctSeedERP__Sales_Order_Line__r.Taxable_Retail__c
                            ));
                        }
                    }
                }
            }
            if (!mapShipmentListLine.isEmpty()) {
                for (Id shipId : mapShipments.keySet()) {
                    AcctSeedERP__Shipment__c shipment = mapShipments.get(shipId);
                    if (shipment.AcctSeedERP__Sales_Order__r.AcctSeedERP__Customer__c == null) {
                        throw new gcException('The Sales Order must have a Customer, in order to create a Billing.');
                    }

                    AcctSeed__Billing__c b = new AcctSeed__Billing__c(
                        AcctSeed__Date__c = billDate,
                        AcctSeed__Customer__c = shipment.AcctSeedERP__Sales_Order__r.AcctSeedERP__Customer__c,
                        AcctSeedERP__Sales_Order__c = shipment.AcctSeedERP__Sales_Order__c,
                        AcctSeed__Status__c = 'Approved',
                        GL_Account_Variable_3__c = shipment.AcctSeedERP__Sales_Order__r.GL_Account_Variable_3__c,
                        Tax_is_Harmonized__c = shipment.AcctSeedERP__Sales_Order__r.Tax_is_Harmonized__c,
                        Tax_Override__c = shipment.AcctSeedERP__Sales_Order__r.Tax_Override__c,
                        Tax_Rate_Federal__c = shipment.AcctSeedERP__Sales_Order__r.Tax_Rate_Federal__c,
                        Tax_Rate_Provincial__c = shipment.AcctSeedERP__Sales_Order__r.Tax_Rate_Provincial__c,
                        Tax_Rate_Retail__c = shipment.AcctSeedERP__Sales_Order__r.Tax_Rate_Retail__c,
                        AcctSeed__Accounting_Period__c = idPeriod
                    );

                    billingToBeSaved.put(shipment.Id,b);
                }
                if(!billingToBeSaved.isEmpty()){
                    for (Id idShip : mapShipments.keySet()) {
                        Id idBilling = billingToBeSaved.get(idShip).Id;
                        List<AcctSeed__Billing_Line__c> listLines = mapShipmentListLine.get(idShip);
                        for(AcctSeed__Billing_Line__c line : listLines) {
                            line.AcctSeed__Billing__c = idBilling;
                            listBillingLines.add(line);
                        }
                    }
                    Boolean boolOld = gcBillingLine.disableAutosetTaxable;
                    gcBillingLine.disableAutosetTaxable = true;
                    insert listBillingLines;
                    gcBillingLine.disableAutosetTaxable = boolOld;
                    AcctSeed.BillingPostService.postBillings(billingToBeSaved.values());
                }
            }
        }
    }
}