force-app/main/default/objects/AcctSeed__Accounting_Period__c/AcctSeed__Accounting_Period__c.object-meta.xml
<CustomObject>
    <customHelpPage>AcctSeed__AccountingPeriodHelp</customHelpPage>
    <description>Used to capture all the financial activity that occurs during a specified time period. Accounting periods are typically defined to coincide with a calendar year month.</description>
    <label>Accounting  Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Accounting_Period__c/fields/AcctSeed__End_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__End_Date__c</fullName>
    <inlineHelpText>Accounting periods are typically used as months. This denotes the end of the period. Fiscal Months are supported. A period end date can not cross over into the start and end date range of another period.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Accounting_Period__c/fields/AcctSeed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Start_Date__c</fullName>
    <inlineHelpText>Accounting periods are typically used as months. This denotes the beginning of the period. Fiscal Months are supported. A period beginning date can not cross over into the start and end date range of another period.</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Accounting_Settings__c/AcctSeed__Accounting_Settings__c.object-meta.xml
<CustomObject>
    <description>Main record used to define configuration and default settings used in the application.</description>
    <label>Accounting Settings</label>
    <nameField>
        <label>Account Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Accounting_Settings__c/fields/AcctSeed__AR_Control_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__AR_Control_GL_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This should be set to the main Accounts Receivable GL Account.</inlineHelpText>
    <label>AR Control GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Accounting_Settings (AR Control GL Account)</relationshipLabel>
    <relationshipName>PMA_Main</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Accounting_Settings__c/fields/AcctSeed__Unapplied_Cash_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Unapplied_Cash_GL_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This GL Account is credited upon entering a cash receipt.   After applying the cash receipt to a bill, the amount is removed (debits) from this account and a reduces (credits) Accounts Receivable.   Typical placement of this account is next to AR.</inlineHelpText>
    <label>Unapplied A/R GL Account</label>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Accounting_Settings (Unapplied Cash GL Account)</relationshipLabel>
    <relationshipName>Accounting_Settings7</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Billing__c/AcctSeed__Billing__c.object-meta.xml
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Billing__c/fields/AcctSeed__Accounting_Period__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Accounting_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Used to specify accounting period for financial reporting. Accounting period must have a value of &quot;Open&quot; in order to be selected.</inlineHelpText>
    <label>Accounting  Period</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Period__c.AcctSeed__Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </filterItems>
        <infoMessage>The accounting period status must be open</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Period__c</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Project_Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Billing__c/fields/AcctSeed__Customer__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Customer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>The organization you would like to pay you for your product or service. This is a filtered lookup to the Account where Accounting Status equals &quot;Customer&quot; or &quot;Customer and Vendor&quot;.</inlineHelpText>
    <label>Customer</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Type__c</field>
            <operation>contains</operation>
            <value>Customer, Customer and Vendor</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Billings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Billing_Cash_Receipt__c/AcctSeed__Billing_Cash_Receipt__c.object-meta.xml
<CustomObject>
    <description>Used to document the relationship a billing record has with a cash receipt record. A billing cash receipt record is created during the cash application process.</description>
    <label>Billing Cash Receipt</label>
    <nameField>
        <displayFormat>BCR-{00000}</displayFormat>
        <label>Billing Cash Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Cash Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Billing_Cash_Receipt__c/fields/AcctSeed__Accounting_Period__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Accounting_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Applied Accounting Period</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The accounting period status must be &quot;Open&quot;</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Period__c.AcctSeed__Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </filterItems>
        <infoMessage>The accounting period status must be open</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Period__c</referenceTo>
    <relationshipLabel>Billing Cash Receipts</relationshipLabel>
    <relationshipName>Billing_Cash_Receipts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Billing_Cash_Receipt__c/fields/AcctSeed__Billing__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Billing__c</fullName>
    <label>Billing</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Billing__c.AcctSeed__Status__c</field>
            <operation>equals</operation>
            <value>Posted</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Billing__c</referenceTo>
    <relationshipLabel>Applied Cash Receipts</relationshipLabel>
    <relationshipName>Billing_Cash_Receipts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Billing_Line__c/AcctSeed__Billing_Line__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific product or service associated with a billing. The aggregation of multiple billing lines constitute a billing record.</description>
    <label>Billing Line</label>
    <nameField>
        <displayFormat>BL-{00000}</displayFormat>
        <label>Billing Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__Billing__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Billing__c</fullName>
    <inlineHelpText>Reference to parent object.</inlineHelpText>
    <label>Billing</label>
    <referenceTo>AcctSeed__Billing__c</referenceTo>
    <relationshipLabel>Billing Lines</relationshipLabel>
    <relationshipName>Project_Billing_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Billing_Line__c/fields/AcctSeed__Transaction__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This field has been deprecated and is no longer used.</inlineHelpText>
    <label>zDep-Transaction</label>
    <referenceTo>AcctSeed__Transaction__c</referenceTo>
    <relationshipLabel>Billing Lines</relationshipLabel>
    <relationshipName>Project_Billing_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Scheduled_Revenue_Expense__c/AcctSeed__Scheduled_Revenue_Expense__c.object-meta.xml
<CustomObject>
    <description>Used to capture information related to deferred revenue and expenses.</description>
    <label>Amortization Entry</label>
    <nameField>
        <label>Amortization Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Amortization Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Scheduled_Revenue_Expense__c/fields/AcctSeed__Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account__c</fullName>
    <formula>IF(ISBLANK(AcctSeed__Account2__c),AcctSeed__Project__r.AcctSeed__Account__r.Name,AcctSeed__Account2__r.Name)</formula>
    <inlineHelpText>The account on the project associated with this record.</inlineHelpText>
    <label>Project Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Scheduled_Revenue_Expense__c/fields/AcctSeed__Accounting_Period__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Accounting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Used to specify accounting period for financial reporting. Accounting period must have a value of Open.</inlineHelpText>
    <label>Accounting  Period</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Period__c.AcctSeed__Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </filterItems>
        <infoMessage>The accounting period status must be open</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Period__c</referenceTo>
    <relationshipLabel>Amortization Entries</relationshipLabel>
    <relationshipName>Scheduled_Revenues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Scheduled_Revenue_Expense__c/fields/AcctSeed__Billing__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Billing__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Reference to a related Billing if using Scheduled Revenue.</inlineHelpText>
    <label>Billing</label>
    <referenceTo>AcctSeed__Billing__c</referenceTo>
    <relationshipLabel>Amortized Revenue</relationshipLabel>
    <relationshipName>Scheduled_Revenues</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Transaction__c/AcctSeed__Transaction__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific entry to a ledger. Transaction records are created when a source record is posted i.e. payable, billing, cash disbursement, cash receipt, journal entry, scheduled revenue expense, and time card.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{00000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Transaction__c/fields/AcctSeed__Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This field is populated based on the transaction source record. The mapping is Journal Entry Line Account field, Billing Customer, Accounts Payable Payee field, Cash Receipt Account field, or Cash Disbursement Payee field.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Transaction__c/fields/AcctSeed__Accounting_Period__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Accounting_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Used to specify accounting period for financial reporting.</inlineHelpText>
    <label>Accounting Period</label>
    <referenceTo>AcctSeed__Accounting_Period__c</referenceTo>
    <relationshipName>Project_Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Transaction__c/fields/AcctSeed__Billing__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Billing__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Related source record for the origin of the entry.</inlineHelpText>
    <label>Billing</label>
    <referenceTo>AcctSeed__Billing__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Transaction__c/fields/AcctSeed__Billing_Line__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Billing_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Reference to source transaction.</inlineHelpText>
    <label>Billing Line</label>
    <referenceTo>AcctSeed__Billing_Line__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Project_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/classes/AccountTransactions_ar.cls
public with sharing class AccountTransactions_ar {
  @AuraEnabled
  public static String retrieveTxnDetailsByAccount(String idAccount, String idPeriod, String strType) {
    List<Map<String, String>> listTxnData = new List<Map<String, String>>();
    set<Id> setIdPayee = new Set<Id>();
    set<Id> setIdPeriods = new Set<Id>();
    //retrieve all periods prior to and including the selected period
    AcctSeed__Accounting_Period__c period = [
      SELECT Id, AcctSeed__Start_Date__c, AcctSeed__End_Date__c
      FROM AcctSeed__Accounting_Period__c
      WHERE Id = :idPeriod
    ][0];
    //setIdPeriods.add(period.Id);
    for (AcctSeed__Accounting_Period__c p : [
      SELECT Id
      FROM AcctSeed__Accounting_Period__c
      WHERE AcctSeed__Start_Date__c <= :period.AcctSeed__Start_Date__c
    ]) {
      setIdPeriods.add(p.Id);
    }

    AcctSeed__Accounting_Settings__c accSetting = [
      SELECT AcctSeed__AR_Control_GL_Account__c, AcctSeed__Unapplied_Cash_GL_Account__c
      FROM AcctSeed__Accounting_Settings__c
      ORDER BY CreatedDate
    ][0];
    Id idGLAR = accSetting.AcctSeed__AR_Control_GL_Account__c;
    Id idGLUnapplied = accSetting.AcctSeed__Unapplied_Cash_GL_Account__c;
    Set<Id> setIdGL = new Set<Id>();
    System.debug(loggingLevel.error, 'strType:' + strType);
    if (strType == 'arcontrol')
      setIdGL.add(idGLAR);
    else
      setIdGL.add(idGLUnapplied);
    System.debug(loggingLevel.error, 'setIdGL:' + setIdGL);

    for (AcctSeed__Transaction__c txn : [
      SELECT
        Id,
        Name,
        AcctSeed__Account__c,
        AcctSeed__Billing_Line__r.AcctSeed__Billing__r.Name,
        AcctSeed__Billing_Line__r.AcctSeed__Billing__r.AcctSeed__Customer__c,
        AcctSeed__Billing_Cash_Receipt__r.AcctSeed__Billing__r.Name,
        AcctSeed__Billing_Cash_Receipt__r.AcctSeed__Billing__r.AcctSeed__Customer__c,
        AcctSeed__Scheduled_Revenue_Expense__r.AcctSeed__Billing__r.Name,
        AcctSeed__Scheduled_Revenue_Expense__r.AcctSeed__Billing__r.AcctSeed__Customer__c,
        AcctSeed__Amount__c
      FROM AcctSeed__Transaction__c
      WHERE
        AcctSeed__GL_Account__c IN :setIdGL
        AND AcctSeed__Accounting_Period__c IN :setIdPeriods
        AND (AcctSeed__Amount__c < 0
        OR AcctSeed__Amount__c > 0)
        AND (AcctSeed__Account__c = :idAccount
        OR AcctSeed__Billing_Line__r.AcctSeed__Billing__r.AcctSeed__Customer__c = :idAccount
        OR AcctSeed__Billing_Cash_Receipt__r.AcctSeed__Billing__r.AcctSeed__Customer__c = :idAccount
        OR AcctSeed__Scheduled_Revenue_Expense__r.AcctSeed__Billing__r.AcctSeed__Customer__c = :idAccount)
    ]) {
      String typeName = 'Transaction';
      String sourceName = txn.Name;
      Id idPayee = txn.AcctSeed__Account__c;
      if (idPayee == null) {
        typeName = 'Billing';
        sourceName = txn.AcctSeed__Billing_Line__r.AcctSeed__Billing__r.Name;
        idPayee = txn.AcctSeed__Billing_Line__r.AcctSeed__Billing__r.AcctSeed__Customer__c;
      }
      if (idPayee == null) {
        typeName = 'Billing Cash Receipt';
        sourceName = txn.AcctSeed__Billing_Cash_Receipt__r.AcctSeed__Billing__r.Name;
        idPayee = txn.AcctSeed__Billing_Cash_Receipt__r.AcctSeed__Billing__r.AcctSeed__Customer__c;
      }
      if (idPayee == null) {
        typeName = 'Scheduled Revenue Expense';
        sourceName = txn.AcctSeed__Scheduled_Revenue_Expense__r.AcctSeed__Billing__r.Name;
        idPayee = txn.AcctSeed__Scheduled_Revenue_Expense__r.AcctSeed__Billing__r.AcctSeed__Customer__c;
      }

      //if(idPayee == null) continue;

      Decimal amt = txn.AcctSeed__Amount__c;
      Map<String, String> m = new Map<String, String>();
      m.put('Id', txn.Id);
      m.put('type', typeName);
      m.put('sourceName', sourceName);
      m.put('txnAmount', String.valueOf(amt));
      listTxnData.add(m);
    }

    return JSON.serialize(listTxnData);
  }

  public static void coverage() {
    integer i;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
  }
}