force-app/main/default/objects/CommissionPayment2__c/CommissionPayment2__c.object-meta.xml
<CustomObject>
    <label>Commission Payment</label>
    <nameField>
        <displayFormat>CommPayment-{0000}</displayFormat>
        <label>Commission Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CommissionPayment2__c/fields/Commission_Record2__c.field-meta.xml
<CustomField>
    <fullName>Commission_Record2__c</fullName>
    <label>Commission Record</label>
    <referenceTo>CommissionRecord2__c</referenceTo>
    <relationshipLabel>Commission Payments</relationshipLabel>
    <relationshipName>Commission_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/objects/CommissionPayment2__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Commission_Payments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CommissionPayment2__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/CommissionPayment2__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/CommissionRecord2__c/CommissionRecord2__c.object-meta.xml
<CustomObject>
    <label>Commission Record</label>
    <nameField>
        <displayFormat>CommRec-{0000}</displayFormat>
        <label>Commission Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/CommissionRecord2__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Uncollected Balance</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/classes/CommissionPayment2_TriggerHandler.cls
/**
 * Created by dave on 2020-02-18.
 */

public without sharing class CommissionPayment2_TriggerHandler extends TriggerHandler
{

//  protected override void bulkBefore()
//  {
//  }

//  protected override void bulkAfter()
//  {
//  }

  protected override void beforeInsert()
  {
    CommissionPayment2_Service.setInitialValues( (List<CommissionPayment2__c>)Trigger.new );
  }

//  protected override void beforeUpdate()
//  {
//  }

//  protected override void beforeDelete()
//  {
//  }

  protected override void afterInsert()
  {
    Set<Id> setIdCommPay = new Set<Id>();
    for(CommissionPayment2__c cp : (List<CommissionPayment2__c>) Trigger.new){
      if(cp.Type__c != 'Manager')
        setIdCommPay.add(cp.Id);
    }
    if(!setIdCommPay.isEmpty()) {
      System.debug(setIdCommPay);
      CommissionPayment2_Service.createManagersCommissionFuture(setIdCommPay);
    }
  }

  protected override void afterUpdate()
  {
    Map<Id, CommissionPayment2__c> oldMap = (Map<Id, CommissionPayment2__c>)Trigger.oldMap;
    List<CommissionRecord2__c> disputedRecords = new List<CommissionRecord2__c>();
    Map<Id, Set<Id>> resolvedComRecId_paymentsMap = new Map<Id, Set<Id>>();
    for( CommissionPayment2__c payment : (List<CommissionPayment2__c>)Trigger.new )
    {
      if( payment.Status__c != oldMap.get( payment.Id ).Status__c )
      {
        if( payment.Status__c == 'Disputed' )
        {
          disputedRecords.add( new CommissionRecord2__c(
            Id = payment.Commission_Record2__c,
            Status__c = 'Disputed'
          ) );
        }
        if( oldMap.get( payment.Id ).Status__c == 'Disputed' )
        {
          if( !resolvedComRecId_paymentsMap.containsKey( payment.Commission_Record2__c) )
          {
            resolvedComRecId_paymentsMap.put( payment.Commission_Record2__c, new Set<Id>() );
          }
          resolvedComRecId_paymentsMap.get( payment.Commission_Record2__c ).add( payment.Owner__c );
        }
      }
    }
    if( disputedRecords.size() > 0 )
      update disputedRecords;
    if( resolvedComRecId_paymentsMap.size() > 0 )
    {
      CommissionRecord2_Service.postResolveMessage( resolvedComRecId_paymentsMap );
    }
  }

//  protected override void afterDelete()
//  {
//  }

//  protected override void afterUndelete()
//  {
//  }

//  protected override void finalActions()
//  {
//  }
}