src/Base/main/default/objects/Opportunity/fields/taxationProvince__c.field-meta.xml
<CustomField>
    <fullName>taxationProvince__c</fullName>
    <label>TaxationProvince</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>British Columbia</fullName>
            </value>
            <value>
                <fullName>Manitoba</fullName>
            </value>
            <value>
                <fullName>New Brunswick</fullName>
            </value>
            <value>
                <fullName>Newfoundland and Labrador</fullName>
            </value>
            <value>
                <fullName>Northwest Territories</fullName>
            </value>
            <value>
                <fullName>Nova Scotia</fullName>
            </value>
            <value>
                <fullName>Nunavut</fullName>
            </value>
            <value>
                <fullName>Ontario</fullName>
            </value>
            <value>
                <fullName>Prince Edward Island</fullName>
            </value>
            <value>
                <fullName>Quebec</fullName>
            </value>
            <value>
                <fullName>Saskatchewan</fullName>
            </value>
            <value>
                <fullName>Yukon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TaxRate__c.field-meta.xml
<CustomField>
    <fullName>TaxRate__c</fullName>
    <label>TaxRate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity_Document__c/Opportunity_Document__c.object-meta.xml
<CustomObject>
    <label>Opportunity Document</label>
    <nameField>
        <label>Opportunity Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Document</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Document__c/fields/Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Id__c</fullName>
    <description>The Id of the Document</description>
    <label>Document Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TaxRate__c/TaxRate__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>TaxRate</label>
</CustomObject>

src/Base/main/default/classes/OpportunityDocument.cls
global with sharing class OpportunityDocument {

  public BoatBuilder boatBuilder { get; private set; }
  public String renderType { get; private set; }
  public Boolean renderSeperateTaxes { get; private set; }
  public TaxRate__c provTaxRate { get; private set; }

  global OpportunityDocument()
  {
    Id oppId = ApexPages.currentPage().getParameters().get('opportunity_id');
    if( oppId == null )
    {
      oppId = ApexPages.currentPage().getParameters().get('id');
    }
    String rType = ApexPages.currentPAge().getParameters().get('render_type');
    //String validDate = ApexPages.currentPage().getParameters().get('valid_quote_date');
    //Date quoteDate;
    //if( validQuoteDate !== null )
    //  quoteDate = Date.parse( validDate );
    renderType = '';
    if( rType != null )
    {
      renderType = rType;
    }
    if( oppId != null )
    {
      this.boatBuilder = new BoatBuilder(oppId);
      //this.provTaxRate = TaxRate__c.getAll().get( this.boatBuilder.opportunity.TaxationProvince__c );
    }
  }

  global OpportunityDocument(ApexPages.StandardController ctr){ }

  global static void triggerHandler
    (map<Id,Opportunity_Document__c> oldMap,
     map<Id,Opportunity_Document__c> newMap,
     list<Opportunity_Document__c> listNew,
     Boolean boolIsBefore,
     Boolean boolIsInsert,
     Boolean boolIsUpdate,
     Boolean boolIsDelete)
  {

    if(oldMap == NULL) oldMap = new map<Id,Opportunity_Document__c>();
    if(newMap == NULL) newMap = new map<Id,Opportunity_Document__c>();
    if(listNew == NULL) listNew = new list<Opportunity_Document__c>();

    if(boolIsBefore)
    {
      //if(boolIsInsert)
      //{
      //  return;
      //}
      //if(boolIsUpdate)
      //{
      //  return;
      //}
      //if(boolIsDelete)
      //{
      //  return;
      //}
    }
    else //i.e. trigger.isAfter
    {
      //if(boolIsInsert)
      //{
      //  return;
      //}
      //if(boolIsUpdate)
      //{
      //  return;
      //}
      if(boolIsDelete)
      {
        Set<Id> docIds = new Set<Id>();
        for( Opportunity_Document__c od : oldMap.values() )
        {
          docIds.add(od.Document_Id__c);
        }
        if( !docIds.isEmpty() )
        {
          List<Document> docs = [SELECT Id FROM Document WHERE Id IN :docIds];
          delete docs;
        }
        return;
      }
    }


  }// /triggerHandler
}