src/Base/main/default/objects/AcctSeedERP__Warehouse__c/AcctSeedERP__Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Warehouse__c/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Tax Zone must be an Accounting Variable of Type 3.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 3</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Sales_Year__c.field-meta.xml
<CustomField>
    <fullName>Sales_Year__c</fullName>
    <label>Sales Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Pricebook2/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>The Version of the Pricebook</description>
    <label>Version</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Product2/recordTypes/Fees.recordType-meta.xml
<RecordType>
    <fullName>Fees</fullName>
    <active>true</active>
    <description>Fees</description>
    <label>Fees</label>
</RecordType>

src/Base/main/default/objects/Product2/recordTypes/Motor.recordType-meta.xml
<RecordType>
    <fullName>Motor</fullName>
    <active>true</active>
    <description>Outboard Motors</description>
    <label>Motor</label>
</RecordType>

src/Base/main/default/objects/Product2/recordTypes/Part.recordType-meta.xml
<RecordType>
    <fullName>Part</fullName>
    <active>true</active>
    <description>Part</description>
    <label>Part</label>
</RecordType>

src/Base/main/default/objects/Product_Fee_Amount__c/Product_Fee_Amount__c.object-meta.xml
<CustomObject>
    <label>Product Fee Amount</label>
    <nameField>
        <displayFormat>PFA-{0000}</displayFormat>
        <label>Product Fee Amount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Fee Amounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Fee_Amount__c/fields/Fee_Product__c.field-meta.xml
<CustomField>
    <fullName>Fee_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Fee Amounts</relationshipLabel>
    <relationshipName>Product_Fee_Amounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Product_Fee_Amount__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Product Fee Amounts</relationshipLabel>
    <relationshipName>Product_Fee_Amounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Fee_Amount__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <label>Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>British Columbia</fullName>
            </value>
            <value>
                <fullName>Manitoba</fullName>
            </value>
            <value>
                <fullName>New Brunswick</fullName>
            </value>
            <value>
                <fullName>Newfoundland and Labrador</fullName>
            </value>
            <value>
                <fullName>Northwest Territories</fullName>
            </value>
            <value>
                <fullName>Nova Scotia</fullName>
            </value>
            <value>
                <fullName>Nunavut</fullName>
            </value>
            <value>
                <fullName>Ontario</fullName>
            </value>
            <value>
                <fullName>Price Edward Island</fullName>
            </value>
            <value>
                <fullName>Quebec</fullName>
            </value>
            <value>
                <fullName>Saskatchewan</fullName>
            </value>
            <value>
                <fullName>Yukon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Upgrade__c/Product_Upgrade__c.object-meta.xml
<CustomObject>
    <label>Product Upgrade</label>
    <nameField>
        <displayFormat>PU-{0000}</displayFormat>
        <label>Product_Upgrade ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Upgrades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Upgrade__c/fields/From_Product__c.field-meta.xml
<CustomField>
    <fullName>From_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Upgrades (From Product)</relationshipLabel>
    <relationshipName>From_Product_Upgrades</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Product_Upgrade__c/fields/To_Product__c.field-meta.xml
<CustomField>
    <fullName>To_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Upgrades (To Product)</relationshipLabel>
    <relationshipName>To_Product_Upgrades</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Product_Upgrade_Cost__c/Product_Upgrade_Cost__c.object-meta.xml
<CustomObject>
    <label>Product Upgrade Cost</label>
    <nameField>
        <displayFormat>PUC-{0000}</displayFormat>
        <label>Product Upgrade Cost Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Upgrade Costs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/Product_Upgrade_Cost__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Cost</label>
    <precision>8</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Product_Upgrade_Cost__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Product Upgrade Costs</relationshipLabel>
    <relationshipName>Product_Upgrade_Costs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Upgrade_Cost__c/fields/Product_Upgrade__c.field-meta.xml
<CustomField>
    <fullName>Product_Upgrade__c</fullName>
    <label>Product Upgrade</label>
    <referenceTo>Product_Upgrade__c</referenceTo>
    <relationshipLabel>Product Upgrade Cost</relationshipLabel>
    <relationshipName>Product_Upgrade_Costs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/classes/Pricebook2_CloneController_Test_dh.cls
@isTest
private class Pricebook2_CloneController_Test_dh {
  static Pricebook2 pb;
  static User testUser;

  private static void buildPb() {
    Id rtId = LGND_Utilities.recordTypeIdFromName('Pricebook2', 'Sales');
    pb = new Pricebook2(
      Name = 'Test Pb',
      isActive = true,
      RecordTypeId = rtId,
      Sales_Year__c = String.valueOf(Date.today().year()),
      Version__c = 2
    );
    insert pb;
  }

  @testSetup
  static void dataSetup() {
    new Factory_TestData();
    Factory_CustomSettings.setupInventorySettings();
  }

  private static void buildTestUser() {
    AcctSeedERP__Warehouse__c wh;
    for (AcctSeedERP__Warehouse__c warehouse : [
      SELECT Id, Name, GL_Account_Variable_3__c
      FROM AcctSeedERP__Warehouse__c
    ]) {
      if (warehouse.Name == 'Whitefish')
        wh = warehouse;
    }
    testUser = Factory_User.newUser(
      'whitefish',
      'mcTesterson',
      'Standard User',
      wh
    );
  }

  @isTest
  static void fetchPricebook_Test() {
    buildPb();
    Pricebook2 pbReturned = Pricebook2_CloneController_dh.fetchPricebook(pb.Id);
    System.assertEquals(pb.Name, pbReturned.Name);
  }

  @isTest
  static void fetchPricebook_invalid_Test() {
    Account a = Factory_Account.insertDealerAccounts(1)[0];
    String errMsg;
    try {
      Pricebook2_CloneController_dh.fetchPricebook(a.Id);
    } catch (Exception e) {
      errMsg = e.getMessage();
    }
    System.assertEquals(
      'Pricebook not found! Id supplied was for Account object',
      errMsg
    );
  }

  @isTest
  static void fetchPricebook_noAccess_Test() {
    String errMsg;
    buildPb();
    buildTestUser();
    System.runAs(testUser) {
      try {
        Pricebook2 pbReturned = Pricebook2_CloneController_dh.fetchPricebook(
          pb.Id
        );
      } catch (Exception e) {
        errMsg = e.getMessage();
      }
      System.assertEquals(
        errMsg,
        'You do not have permission to create Pricebooks'
      );
    }
  }

  @isTest
  static void clonePricebookTest() {
    buildPb();
    Pricebook2 npb = new Pricebook2(
      Name = pb.Name + '-Clone',
      Description = 'Clone of Test Pb',
      RecordTypeId = pb.RecordTypeId,
      Sales_Year__c = pb.Sales_Year__c,
      Version__c = 3,
      isActive = true
    );
    Pricebook2 pb2 = Pricebook2_CloneController_dh.clonePricebook(
      pb.Id,
      npb,
      false,
      false,
      false
    );
    System.assertEquals(pb.RecordTypeId, pb2.RecordTypeId);
    System.assertEquals(npb.isActive, pb2.isActive);
  }

  @isTest
  static void clonePricebook_withEntries_Test() {
    buildPb();
    Product2[] parts = Factory_Product.buildNonSerializedProducts(
      'Part',
      'Hardware',
      20
    );
    insert parts;
    Factory_PricebookEntry.createStandardEntries(parts, 10.00);
    Factory_PricebookEntry.createEntries(parts, pb.Id, 10.00);
    Test.startTest();
    Pricebook2 npb = new Pricebook2(
      Name = pb.Name + '-Clone',
      Description = 'Clone of Test Pb',
      RecordTypeId = pb.RecordTypeId,
      Sales_Year__c = pb.Sales_Year__c,
      Version__c = 3,
      isActive = true
    );
    Pricebook2 pb2 = Pricebook2_CloneController_dh.clonePricebook(
      pb.Id,
      npb,
      true,
      false,
      false
    );
    Test.stopTest();
    PricebookEntry[] entries = [
      SELECT Id
      FROM PricebookEntry
      WHERE Pricebook2Id = :pb2.Id
    ];
    System.assertEquals(parts.size(), entries.size());
  }

  @isTest
  static void clonePricebook_withFees_Test() {
    buildPb();
    Product2[] fees = Factory_Product.buildNonSerializedProducts(
      'Fees',
      '',
      20
    );
    insert fees;
    Product_Fee_Amount__c[] pfas = new List<Product_Fee_Amount__c>();
    for (Product2 p : fees) {
      pfas.add(
        new Product_Fee_Amount__c(
          Amount__c = 10,
          Province__c = 'Ontario',
          Fee_Product__c = p.Id,
          Price_Book__c = pb.Id
        )
      );
    }
    insert pfas;
    Test.startTest();
    Pricebook2 npb = new Pricebook2(
      Name = pb.Name + '-Clone',
      Description = 'Clone of Test Pb',
      RecordTypeId = pb.RecordTypeId,
      Sales_Year__c = pb.Sales_Year__c,
      Version__c = 3,
      isActive = true
    );
    Pricebook2 pb2 = Pricebook2_CloneController_dh.clonePricebook(
      pb.Id,
      npb,
      false,
      true,
      false
    );
    Test.stopTest();
    Product_Fee_Amount__c[] pfas2 = [
      SELECT Id
      FROM Product_Fee_Amount__c
      WHERE Price_Book__c = :pb2.Id
    ];
    System.assertEquals(fees.size(), pfas2.size());
  }

  @isTest
  static void clonePricebook_withUpgrades_Test() {
    buildPb();
    Product2 motor = Factory_Product.createSerializedProduct('Motor', 'Remote');
    Product2[] uMotors = Factory_Product.createSerializedProducts(
      'Motor',
      'Remote',
      10
    );
    Product_Upgrade__c[] pus = new List<Product_Upgrade__c>();
    for (Product2 um : uMotors) {
      pus.add(
        new Product_Upgrade__c(
          From_Product__c = motor.Id,
          To_Product__c = um.Id
        )
      );
    }
    insert pus;
    Product_Upgrade_Cost__c[] pucs = new List<Product_Upgrade_Cost__c>();
    for (Product_Upgrade__c pu : pus) {
      pucs.add(
        new Product_Upgrade_Cost__c(
          Price_Book__c = pb.Id,
          Product_Upgrade__c = pu.Id,
          Cost__c = 10.00
        )
      );
    }
    insert pucs;
    Test.startTest();
    Pricebook2 npb = new Pricebook2(
      Name = pb.Name + '-Clone',
      Description = 'Clone of Test Pb',
      RecordTypeId = pb.RecordTypeId,
      Sales_Year__c = pb.Sales_Year__c,
      Version__c = 3,
      isActive = true
    );
    Pricebook2 pb2 = Pricebook2_CloneController_dh.clonePricebook(
      pb.Id,
      npb,
      false,
      false,
      true
    );
    Test.stopTest();
    Product_Upgrade_Cost__c[] result = [
      SELECT Id
      FROM Product_Upgrade_Cost__c
      WHERE Price_Book__c = :pb2.Id
    ];
    System.assertEquals(pucs.size(), result.size());
  }
}