force-app/main/default/objects/AcctSeed__Accounting_Variable__c/AcctSeed__Accounting_Variable__c.object-meta.xml
<CustomObject>
    <description>Used to categorize or group general ledger transactions, profit centers, cost centers, geographies, or lines of offerings based on business need.</description>
    <label>Accounting Variable</label>
    <nameField>
        <label>Accounting Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Variables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Accounting_Variable__c/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Tax Zone must be an Accounting Variable of Type 3.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 3</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Tax Zones (GLV3)</relationshipLabel>
    <relationshipName>Accounting_Variables_GLV3</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project__c/fields/AcctSeedERP__Work_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Work_Order_Number__c</fullName>
    <displayFormat>{00000}</displayFormat>
    <label>Work Order Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project__c/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The value selected for Tax Zone (GLV3) must be an Accounting Variable of Type 3.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 3</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>ERP Orders</relationshipLabel>
    <relationshipName>ERP_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <formula>IF(  AcctSeed__Account__r.RecordType.DeveloperName = &#39;Dealer&#39;  , &#39;Partner&#39;,
 IF( AcctSeed__Account__r.RecordType.DeveloperName = &#39;PersonAccount&#39;, &#39;Retail&#39;,
   IF( AcctSeed__Account__r.RecordType.DeveloperName = &#39;Business_Account&#39;, &#39;Retail&#39;,
     IF( AND( AcctSeed__Account__r.RecordType.DeveloperName = &#39;Supplier&#39;,  RecordType.Name = &#39;Retail Boat Sale&#39;), &#39;Retail&#39;, null))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sale Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/AcctSeedERP__Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <displayFormat>MAT-{00000}</displayFormat>
        <label>Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Project_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Project_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <formula>AcctSeedERP__Project__r.Sale_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sale Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ERP_document__c/ERP_document__c.object-meta.xml
<CustomObject>
    <label>ERP document</label>
    <nameField>
        <label>ERP document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/ERP_document__c/fields/DocumentID__c.field-meta.xml
<CustomField>
    <fullName>DocumentID__c</fullName>
    <label>DocumentID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/ERP_document__c/fields/Formatted_Certificate_Number__c.field-meta.xml
<CustomField>
    <fullName>Formatted_Certificate_Number__c</fullName>
    <formula>IF(TEXT(Report_Type__c) == &#39;Companion Maxum&#39;, (&#39;LBB&#39; &amp;  LPAD( TEXT(Certificate_Number__c) , 5 ,&#39;0&#39;)),
	(IF(TEXT(Report_Type__c) == &#39;Companion II&#39;, (&#39;LBD&#39; &amp;  LPAD( TEXT(Certificate_Number__c) , 5 ,&#39;0&#39;)),
		(IF(TEXT(Report_Type__c) == &#39;Advantage 70-P&#39;, (LPAD( TEXT(Certificate_Number__c) , 5 ,&#39;0&#39;)),&#39;&#39;)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Formatted Certificate Number</label>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/ERP_document__c/fields/isInvoice__c.field-meta.xml
<CustomField>
    <fullName>isInvoice__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Sets whether this should be included as an actual invoice for the ERP. The only time this is false is when it in an internal parts list for boat orders</description>
    <label>isInvoice</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/ERP_document__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>ERP documents</relationshipLabel>
    <relationshipName>ERP_documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ERP_document__c/fields/Report_Type__c.field-meta.xml
<CustomField>
    <fullName>Report_Type__c</fullName>
    <label>Report Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Companion II</fullName>
            </value>
            <value>
                <fullName>Companion Maxum</fullName>
            </value>
            <value>
                <fullName>Advantage 70-P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/classes/arInsuranceDocuments.cls
public without sharing class arInsuranceDocuments {
  @AuraEnabled
  public static String retrieveERPDetails(Id idProject) {
    Map<String,Object> m = new Map<String,Object>();
    m.put('canDelete', String.valueOf( LGND_Utilities.CustomPermissions.canDeleteInsuranceDocuments ) );
    AcctSeed__Project__c erp = [
      SELECT
        Id,
        Name,
        GL_Account_Variable_3__r.Name,
        First_Payment_Date__c,
      (
        SELECT
          Id,
          AcctSeedERP__Product__r.InsurancePlan__r.Name
        FROM AcctSeedERP__Project_Materials__r
        WHERE AcctSeedERP__Product__r.RecordTypeId = :LGND_Constants.productRtId_Insurance
        LIMIT 1
      )
      FROM AcctSeed__Project__c
      WHERE Id =:idProject
    ];
    m.put('projectName', erp.Name);
    m.put('taxZone', erp.GL_Account_Variable_3__r.Name);
    m.put('hasFirstPaymentDate', erp.First_Payment_Date__c != null);
    m.put('insuranceType', '');
    m.put('hasInsurance', 'false');
    if(!erp.AcctSeedERP__Project_Materials__r.isEmpty()){
      String planName = erp.AcctSeedERP__Project_Materials__r[0].AcctSeedERP__Product__r.InsurancePlan__r.Name;
      m.put('insuranceType', planName);
      if(planName.equals('Companion II'))
        m.put('planPageName', 'InsurancePDFComp_II');
      else if(planName.equals('Advantage 70-P'))
        m.put('planPageName', 'InsurancePDFAdvan');
      else
        m.put('planPageName', 'InsurancePDFComp_Maxum');
      m.put('hasInsurance', 'true');

    }
    return JSON.serialize(m);
  }
  @AuraEnabled
  public static String deleteDocument(Id idProject, Id idErpDoc, Id idDoc) {
    try{
      delete [select Id FROM Document WHERE Id=:idDoc];
      delete [select Id FROM ERP_document__c WHERE Id=:idErpDoc];
      return retrieveERPInsuranceDocuments(idProject);
    }catch(Exception e){
      throw new AuraHandledException(e.getMessage());
    }
  }
  @AuraEnabled
  public static String retrieveERPInsuranceDocuments(Id idProject) {
    List<Map<String,String>> listDocs = new List<Map<String,String>>();
    for(ERP_document__c doc :
    [SELECT Id,
      CreatedDate,
      Name,
      CreatedBy.Name,
      DocumentID__c,
      Project__c
    FROM ERP_document__c
    WHERE Project__c = :idProject
    AND (Report_Type__c != 'Invoice' AND Report_Type__c != null)
    ORDER BY CreatedDate DESC])
    {
      Map<String,String> m = new Map<String,String>();
      m.put('idErpDoc', doc.Id);
      m.put('Name', doc.Name);
      m.put('idDoc', doc.DocumentID__c);
      listDocs.add(m);
    }
    return JSON.serialize(listDocs);
  }



  @AuraEnabled
  public static String generateInsurancePDF(
    String idProject,
    String insuranceType
  )
  {
    return generateInsurancePDF(idProject, insuranceType, 'Eng');
  }

  @AuraEnabled
  public static String generateInsurancePDF(
    String idProject,
    String insuranceType,
    String language
  )
  {
    Savepoint sp = Database.setSavepoint();
    try{
      String pageName = '';
      if(insuranceType.equals('Companion II'))
        pageName = 'InsurancePDFComp_II';
      else if(insuranceType.equals('Advantage 70-P'))
        pageName = 'InsurancePDFAdvan_' + language; // Options: 'Eng' or 'Fr'
      else
        pageName = 'InsurancePDFComp_Maxum';
      AcctSeed__Project__c erpOrder = [SELECT Id, Name, AcctSeedERP__Work_Order_Number__c, Sale_Type__c, RecordTypeId FROM AcctSeed__Project__c WHERE Id = :idProject];
      /// insert the new document
      ERP_document__c doc = new ERP_document__c();
      doc.Project__c = erpOrder.Id;
      doc.Report_Type__c = insuranceType;
      doc.name = erpOrder.AcctSeedERP__Work_Order_Number__c + ' - ' + Datetime.Now().format() + '.pdf';
      doc.documentID__c = null;
      doc.isInvoice__c = false;
      insert doc;
      String certNo = [SELECT Formatted_Certificate_Number__c  FROM ERP_document__c WHERE Id=:doc.Id][0].Formatted_Certificate_Number__c;
      System.debug('certNo: ' + certNo);
      String pageUri = '/apex/' + pageName + '?id=' + erpOrder.Id+'&certNo='+certNo;
      String newName = erpOrder.AcctSeedERP__Work_Order_Number__c + ' - ' + certNo + ' - ' + Datetime.Now().format() + '.pdf';
      PageReference pdfLink =  new PageReference(pageUri);
      Document nd = generateDocument(pdfLink, newName);
      System.debug(nd);
      doc.Name = newName;
      doc.documentID__c = nd.Id;
      update doc;
      /*Map<String,String> m = new Map<String,String>();
      m.put('Name', doc.Name);
      m.put('idDoc', doc.DocumentID__c);
      return JSON.serialize(m);*/
      return retrieveERPInsuranceDocuments(idProject);
    }catch(Exception e){
      Database.rollback(sp);
      throw new AuraHandledException(e.getMessage());
    }
  }

  private static Document generateDocument(PageReference page, String docName)
  {
    System.debug('generateDocument');
    System.debug('page: ' + page);
    System.debug('docName: ' + docName);
    Document doc = new Document ();
    doc.Name = docName;
    doc.Type = 'pdf';
    Blob b;
    if (Test.IsRunningTest()) {
      b = Blob.valueOf('UNIT.TEST');
    }else{
      b = page.getContentAsPDF();
    }
    System.debug('dead yet?');
    doc.Body =  b;
    doc.ContentType = 'application/pdf';
    Folder f = [SELECT Id, Name, DeveloperName FROM Folder WHERE DeveloperName = 'ERP_Invoices'];
    doc.FolderId = f.Id;
    insert doc;
    System.debug(doc);
    return doc;
  }
}