force-app/main/default/objects/AcctSeed__Accounting_Variable__c/AcctSeed__Accounting_Variable__c.object-meta.xml
<CustomObject>
    <description>Used to categorize or group general ledger transactions, profit centers, cost centers, geographies, or lines of offerings based on business need.</description>
    <label>Accounting Variable</label>
    <nameField>
        <label>Accounting Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Variables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Accounting_Variable__c/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Tax Zone must be an Accounting Variable of Type 3.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 3</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Tax Zones (GLV3)</relationshipLabel>
    <relationshipName>Accounting_Variables_GLV3</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Warehouse__c/AcctSeedERP__Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Warehouse__c/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Tax Zone must be an Accounting Variable of Type 3.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 3</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeed__Expense_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Expense_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Balance Sheet, Revenue, Expense</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Products (Expense GL Account)</relationshipLabel>
    <relationshipName>Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeed__Inventory_Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Inventory_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes whether the product is a managed inventory product</description>
    <inlineHelpText>Denotes whether the product is a managed inventory product</inlineHelpText>
    <label>Inventory Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeed__Revenue_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Revenue_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Balance Sheet, Revenue, Expense</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Unique_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Unique_Product_Code__c</fullName>
    <description>A Unique product code that corresponds to the IEM product code</description>
    <label>Unique Product Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/Base/main/default/classes/Factory_TestData.cls
@isTest
public class Factory_TestData {

  public Factory_AccountingSettings accountingSettings;
  public Factory_AccountingVariables accountingVariables;
  public Map<String, AcctSeedERP__Warehouse__c> warehouses;
  public Product2[] productConstants;

  public Factory_TestData()
  {
    accountingSettings = new Factory_AccountingSettings();
    accountingVariables = new Factory_AccountingVariables();
    warehouses = buildWarehouses( accountingVariables.glv3s );
    productConstants = buildProductConstants();
    Factory_CustomSettings.setupUtilityProducts();
    Factory_CustomSettings.setupUtilityAccounts();
	}

  private Map<String, AcctSeedERP__Warehouse__c> buildWarehouses( Map<String, AcctSeed__Accounting_Variable__c> glv3s )
  {
    Map<String, AcctSeedERP__Warehouse__c> result = new Map<String, AcctSeedERP__Warehouse__c>();
    List<sObject> whs = Test.loadData( AcctSeedERP__Warehouse__c.sObjectType, 'TestData_Warehouses' );
    for( sObject obj : whs )
    {
      AcctSeedERP__Warehouse__c wh = (AcctSeedERP__Warehouse__c)obj;
      if( wh.Name == 'Barrie' || wh.Name == 'Whitefish' )
        wh.GL_Account_Variable_3__c = glv3s.get('Ontario').Id;
      if( wh.Name == 'Montreal' )
        wh.GL_Account_Variable_3__c = glv3s.get('Quebec').Id;
      result.put( wh.Name, wh );
    }
    update result.values();
    return result;
  }

  private Product2[] buildProductConstants()
  {
    Product2[] result = new List<Product2>();
    List<String> listUniquefier = new list<String>{
      'SalesTaxFederal',
      'SalesTaxHarmonized',
      'SalesTaxProvincial',
      'SalesTaxRetail',
      'TaxCanada',
      'Trade in',
      'Trade in Lien',
      'TradeInBoats',
      'PrecisionFix',
      'InternalLabour',
      'InternalBilling',
      'InternalBalance'
    };
    for( String uni : listUniquefier )
    {
      result.add( new Product2(
        Name = uni,
        RecordTypeId = LGND_Constants.productRtId_Fees,
        ProductCode = uni,
        Unique_Product_Code__c = uni,
        isActive = true,
        AcctSeed__Expense_GL_Account__c = accountingSettings.salesTaxPaid.Id,
        AcctSeed__Revenue_GL_Account__c = accountingSettings.salesTaxCollected.Id,
        AcctSeed__Inventory_Product__c = false
      ));
    }
    insert result;
    return result;
  }

}