force-app/main/default/objects/AcctSeed__Accounting_Variable__c/AcctSeed__Accounting_Variable__c.object-meta.xml
<CustomObject>
    <description>Used to categorize or group general ledger transactions, profit centers, cost centers, geographies, or lines of offerings based on business need.</description>
    <label>Accounting Variable</label>
    <nameField>
        <label>Accounting Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Variables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Accounting_Variable__c/fields/AcctSeed__Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Type__c</fullName>
    <inlineHelpText>Used to determine GL Account Variables 1-4 and Time Card Variables 1-2.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GL Account Variable 1</fullName>
            </value>
            <value>
                <fullName>GL Account Variable 2</fullName>
            </value>
            <value>
                <fullName>GL Account Variable 3</fullName>
            </value>
            <value>
                <fullName>GL Account Variable 4</fullName>
            </value>
            <value>
                <fullName>Time Card Variable 1</fullName>
            </value>
            <value>
                <fullName>Time Card Variable 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Warehouse__c/AcctSeedERP__Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Ecwid_API_Setting__mdt/Ecwid_API_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Ecwid API Setting</label>
    <pluralLabel>Ecwid API Settings</pluralLabel>
</CustomObject>

src/Base/main/default/objects/Ecwid_API_Setting__mdt/fields/Freight_Purolator_SKU__c.field-meta.xml
<CustomField>
    <fullName>Freight_Purolator_SKU__c</fullName>
    <label>Freight - Purolator SKU</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Ecwid_API_Setting__mdt/fields/GLV1__c.field-meta.xml
<CustomField>
    <fullName>GLV1__c</fullName>
    <label>GLV1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Ecwid_API_Setting__mdt/fields/GLV2__c.field-meta.xml
<CustomField>
    <fullName>GLV2__c</fullName>
    <label>GLV2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Ecwid_API_Setting__mdt/fields/Store_Id__c.field-meta.xml
<CustomField>
    <fullName>Store_Id__c</fullName>
    <label>Store Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Ecwid_API_Setting__mdt/fields/Verification_Key__c.field-meta.xml
<CustomField>
    <fullName>Verification_Key__c</fullName>
    <label>Verification Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Ecwid_Field_Mapping__mdt/Ecwid_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Ecwid Field Mapping</label>
    <pluralLabel>Ecwid Field Mapping</pluralLabel>
</CustomObject>

src/Base/main/default/objects/Ecwid_Field_Mapping__mdt/fields/Ecwid_Dynamic_Queries__c.field-meta.xml
<CustomField>
    <fullName>Ecwid_Dynamic_Queries__c</fullName>
    <label>Ecwid Dynamic Queries</label>
    <referenceTo>Ecwid_Object_Mapping__mdt</referenceTo>
    <relationshipLabel>Ecwid Field Mapping</relationshipLabel>
    <relationshipName>Ecwid_Field_Mapping</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

src/Base/main/default/objects/Ecwid_Object_Mapping__mdt/Ecwid_Object_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Ecwid Object Mapping</label>
    <pluralLabel>Ecwid Object Mappings</pluralLabel>
</CustomObject>

src/Base/main/default/objects/Ecwid_Query_Field_Mapping__mdt/Ecwid_Query_Field_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Ecwid Query Field Mapping</label>
    <pluralLabel>Ecwid Query Field Mapping</pluralLabel>
</CustomObject>

src/Base/main/default/objects/Ecwid_Query_Field_Mapping__mdt/fields/Ecwid_Dynamic_Queries__c.field-meta.xml
<CustomField>
    <fullName>Ecwid_Dynamic_Queries__c</fullName>
    <label>Ecwid Dynamic Queries</label>
    <referenceTo>Ecwid_Object_Mapping__mdt</referenceTo>
    <relationshipLabel>Ecwid Query Field Mapping</relationshipLabel>
    <relationshipName>Ecwid_Query_Field_Mapping</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

src/Base/main/default/objects/EcwidAPI__mdt/EcwidAPI__mdt.object-meta.xml
<CustomObject>
    <label>EcwidAPI</label>
    <pluralLabel>EcwidAPIs</pluralLabel>
</CustomObject>

src/Base/main/default/objects/EcwidAPI__mdt/fields/Ecwid_API_Setting__c.field-meta.xml
<CustomField>
    <fullName>Ecwid_API_Setting__c</fullName>
    <label>Ecwid API Setting</label>
    <referenceTo>Ecwid_API_Setting__mdt</referenceTo>
    <relationshipLabel>EcwidAPIs</relationshipLabel>
    <relationshipName>EcwidAPIs</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

src/Base/main/default/objects/EcwidAPI__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>POST</fullName>
                <default>true</default>
                <label>POST</label>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>GET</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/EcwidAPI__mdt/fields/Require_Public_Key__c.field-meta.xml
<CustomField>
    <fullName>Require_Public_Key__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Require Public Key</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/EcwidAPI__mdt/fields/Require_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Require_Secret_Key__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Require Secret Key</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/Rest_Service_Log__c/Rest_Service_Log__c.object-meta.xml
<CustomObject>
    <label>Rest Service Log</label>
    <nameField>
        <displayFormat>SL-{000000000}</displayFormat>
        <label>Service Log#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rest Service Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Rest_Service_Log__c/fields/Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>Entity_Id__c</fullName>
    <label>Entity Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Rest_Service_Log__c/fields/Store_Id__c.field-meta.xml
<CustomField>
    <fullName>Store_Id__c</fullName>
    <label>Store Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Rest_Service_Log__c/recordTypes/Ecwid_Inbound.recordType-meta.xml
<RecordType>
    <fullName>Ecwid_Inbound</fullName>
    <active>true</active>
    <label>Ecwid Inbound</label>
</RecordType>

src/Base/main/default/classes/EcwidRestUtils.cls
global without sharing class EcwidRestUtils {

    public final String WAREHOUSE='Wholesale';
    public final String GLV1='Wholesale';
    public final String GLV2='Sales';
    
    public static Ecwid_API_Setting__mdt  setting;
    public static Map<String,EcwidAPI__mdt> ApiSettingMap;
    public static Map<String,List<Ecwid_Query_Field_Mapping__mdt>> dynamicQueryFieldMap;
    public static Map<String,List<Ecwid_Field_Mapping__mdt>> dynamicFielddMap;
    public static map<String,String> dynamicQueryMap = new map<String,String>();
    public static String storeId;
    public static String wareHouseId;
    public static String glv1Id;
    public static String glv2Id;

    public static boolean verifySignature(String signatureFromEcwid , EcwidRestCommon.RequestPayloadBody requestBody){
        System.debug('signatureFromEcwid= '+signatureFromEcwid);
        if (signatureFromEcwid != null)
            return   signatureFromEcwid.equals(generateSignature(requestBody));

        return false;

    }
    public static void init(){
        System.debug('@@ in inti method');
        setting = getDataFromSetting();
        getEcwidApiConfiguration();
        getEwidDynamicQuery();
        getGLV1AndGLV2Values();
        getWarehouse();
    }
    private static void getWarehouse(){
       List<AcctSeedERP__Warehouse__c> warehouse = [Select id from AcctSeedERP__Warehouse__c where Name =:setting.GLV1__c];
        if(!warehouse.isEmpty()){
            wareHouseId = String.valueOf(warehouse[0].Id);
        }
    }
    private static void getGLV1AndGLV2Values(){
       List<AcctSeed__Accounting_Variable__c> acVariable_list = [SELECT Id,Name,AcctSeed__Type__c FROM AcctSeed__Accounting_Variable__c where 
                                                    (Name= :setting.GLV1__c and AcctSeed__Type__c = 'GL Account Variable 1') or (Name= :setting.GLV2__c and AcctSeed__Type__c = 'GL Account Variable 2')];
        for(AcctSeed__Accounting_Variable__c acc :acVariable_list){
            if(acc.AcctSeed__Type__c == 'GL Account Variable 1'){
                 glv1Id = acc.id;   
            }else if(acc.AcctSeed__Type__c == 'GL Account Variable 2'){
                glv2Id = acc.id;
            }
        }
        
    }
    private static String  generateSignature(EcwidRestCommon.RequestPayloadBody requestBody ){

        setting = getDataFromSetting();
        getEcwidApiConfiguration();
        getEwidDynamicQuery();
        String keyData = requestBody.eventCreated +'.'+requestBody.eventId ;
        System.debug('keyData= '+keyData);
        System.debug('setting= '+setting);
        Blob data = crypto.generateMac('HmacSHA256',Blob.valueOf(keyData), Blob.valueOf(setting.Verification_Key__c));
        System.debug('EncodingUtil.base64Encode(data)= '+EncodingUtil.base64Encode(data));
        return EncodingUtil.base64Encode(data);

    }

    public static Ecwid_API_Setting__mdt  getDataFromSetting(){

        System.debug('@@ storeId= '+storeId);
        setting  = [SELECT
                            Public_Key__c,
                            Secret_Key__c,
                            Base_URL__c,
                            Store_Id__c,
                            Verification_Key__c,
                            Freight_Purolator_SKU__c,
                            GLV1__c,
                            GLV2__c
                            
                    FROM
                            Ecwid_API_Setting__mdt 
                    WHERE
                            Store_Id__c =:storeId
                   ];

        System.debug('setting= '+setting);
        return setting  ;
    }
    private static void getEcwidApiConfiguration(){

        ApiSettingMap = new Map<String,EcwidAPI__mdt>();
        List<EcwidAPI__mdt> ecwidAPISettingList = [ SELECT
                                                       Method__c,
                                                       Require_Public_Key__c,
                                                       Require_Secret_Key__c,
                                                       URL__c,
                                                       DeveloperName
                                                    FROM
                                                        EcwidAPI__mdt
                                                    WHERE
                                                        Ecwid_API_Setting__c= :setting.Id
                                                    ];
        
        for(EcwidAPI__mdt api :ecwidAPISettingList){
            ApiSettingMap.put(api.DeveloperName,api);
        }

    }

    public static void getEwidDynamicQuery(){

        dynamicQueryFieldMap = new Map<String,List<Ecwid_Query_Field_Mapping__mdt>>();
        dynamicFielddMap = new Map<String,List<Ecwid_Field_Mapping__mdt>>();
        List<Ecwid_Object_Mapping__mdt> ecwidDynamicQueriesList =   [ SELECT
                                                                          DeveloperName,
                                                                          MasterLabel,
                                                                          Query__c,
                                                                          (
                                                                              SELECT
                                                                                DeveloperName,
                                                                                Field_Name__c,
                                                                                MasterLabel
                                                                              FROM
                                                                                Ecwid_Query_Field_Mapping__r
                                                                              WHERE
                                                                                Is_Active__c=TRUE
                                                                          )
                                                                      FROM
                                                                          Ecwid_Object_Mapping__mdt
                                                                      WHERE
                                                                          Is_Active__c=TRUE
                                                                    ];
        System.debug('ecwidDynamicQueriesList= '+ecwidDynamicQueriesList);

        for(Ecwid_Object_Mapping__mdt query :ecwidDynamicQueriesList ){
            List<Ecwid_Query_Field_Mapping__mdt> fieldList = new List<Ecwid_Query_Field_Mapping__mdt>();
            //List<Ecwid_Field_Mapping__mdt> lstFieldMapping = new List<Ecwid_Field_Mapping__mdt>();
            for(Ecwid_Query_Field_Mapping__mdt field : query.Ecwid_Query_Field_Mapping__r){
                fieldList.add(field);
            }
             /*for(Ecwid_Field_Mapping__mdt fieldMapping : query.Ecwid_Field_Mapping__r){
                lstFieldMapping.add(fieldMapping);
            }*/
            dynamicQueryMap.put(query.MasterLabel,query.Query__c);
            dynamicQueryFieldMap.put(query.MasterLabel,fieldList);
            //dynamicFielddMap.put(query.MasterLabel,lstFieldMapping);
            System.debug('dynamicQueryMap= '+dynamicQueryMap);

        }
    }

    public static EcwidRestCommon.RequestPayloadBody parseRequest(String requestBody){
        System.debug('requestBody= '+requestBody);
        System.debug('Encoded= '+(EncodingUtil.base64Decode(requestBody)).toString());
        return ( EcwidRestCommon.RequestPayloadBody ) JSON.deserialize((EncodingUtil.base64Decode(requestBody).toString()), EcwidRestCommon.RequestPayloadBody  .class);
    }
    public static String parseHeader(String request){

        List<Object> result = (List<Object>)JSON.deserializeUntyped('[' + request + ']');
        for(Object obj : result) {
            Map<String,Object> mapRequestParam = (Map<String,Object>)obj;
            for(String key : mapRequestParam.keyset()) {
                if(key.equalsIgnoreCase('headers')){
                    List<Object> resultHeader = (List<Object>)JSON.deserializeUntyped('[' + JSON.serialize(mapRequestParam.get(key)) + ']');
                    for(Object keyHeader : resultHeader) {

                        Map<String,Object> mapHeaderParam =(Map<String,Object>)keyHeader;
                        for(String mapHeaderkey : mapHeaderParam.keyset()) {
                            if(mapHeaderkey.equals('X-Ecwid-Webhook-Signature')) {
                                return (String)mapHeaderParam.get(mapHeaderkey );
                            }
                        }
                    }

                }
            }
        }
        return null;
    }
    public static Rest_Service_Log__c ServiceLog(RestRequest  request,EcwidRestCommon.RequestPayloadBody body){

        Rest_Service_Log__c serviceLog = new Rest_Service_Log__c();
        serviceLog.Request__c = JSON.serializePretty( request );
        serviceLog.Event_Id__c = body.eventId;
        serviceLog.Event_Type__c = body.eventType;
        serviceLog.Entity_Id__c = body.entityId;
        serviceLog.recordTypeId =  Schema.SObjectType.Rest_Service_Log__c.getRecordTypeInfosByDeveloperName().get('Ecwid_Inbound').getRecordTypeId();
        serviceLog.Store_Id__c = body.storeId;
        System.debug('@@ serviceLog.Store_Id__c= '+serviceLog.Store_Id__c);
        insert serviceLog;

        return serviceLog;

    }
    public static string getExceptionDetail(Exception ex){
        String errorMsg = '';
        errorMsg += 'Message: ' + ex.getMessage()+ '\n';
        errorMsg += 'Cause: ' + ex.getCause()+ '\n';
        errorMsg += 'Line: ' + ex.getLineNumber()+ '\n';
        errorMsg += 'Stack Trace: ' + ex.getStackTraceString()+ '\n';
        errorMsg += 'Type: ' + ex.getTypeName()+ '\n';

        return errorMsg + '\n';
    }

   /* public static void ecvidEvent(Rest_Service_Log__c serviceLog, EcwidRestCommon.RequestPayloadBody body){
        
        Ecwid_Event__c ecwidEvent = new Ecwid_Event__c();
        ecwidEvent.EntityId__c = body.eventId;
        ecwidEvent.EventId__c = body.eventType;
        ecwidEvent.EventType__c = body.eventType;
        ecwidEvent.Service_Log_Id__c = serviceLog.id;

        insert ecwidEvent;
    }*/
}