force-app/main/default/objects/AcctSeed__Accounting_Variable__c/AcctSeed__Accounting_Variable__c.object-meta.xml
<CustomObject>
    <description>Used to categorize or group general ledger transactions, profit centers, cost centers, geographies, or lines of offerings based on business need.</description>
    <label>Accounting Variable</label>
    <nameField>
        <label>Accounting Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Variables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Accounting_Variable__c/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Tax Zone must be an Accounting Variable of Type 3.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 3</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Tax Zones (GLV3)</relationshipLabel>
    <relationshipName>Accounting_Variables_GLV3</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Accounting_Variable__c/fields/Tax_is_Harmonized__c.field-meta.xml
<CustomField>
    <fullName>Tax_is_Harmonized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax is Harmonized</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Warehouse__c/AcctSeedERP__Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Warehouse__c/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Tax Zone must be an Accounting Variable of Type 3.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 3</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Insurance_Rate__c/Insurance_Rate__c.object-meta.xml
<CustomObject>
    <label>Insurance Rate</label>
    <nameField>
        <displayFormat>IR-{0000}</displayFormat>
        <label>Insurance Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Rate__c/fields/Joint__c.field-meta.xml
<CustomField>
    <fullName>Joint__c</fullName>
    <label>Joint</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Insurance_Rate__c/fields/Joint_Factor__c.field-meta.xml
<CustomField>
    <fullName>Joint_Factor__c</fullName>
    <label>Joint Factor</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insurance_Rate__c/fields/Lower_Finance_Term__c.field-meta.xml
<CustomField>
    <fullName>Lower_Finance_Term__c</fullName>
    <label>Lower Finance Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Insurance_Rate__c/fields/Lower_Term__c.field-meta.xml
<CustomField>
    <fullName>Lower_Term__c</fullName>
    <label>Lower Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Insurance_Rate__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Insurance Rates</relationshipLabel>
    <relationshipName>Insurance_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insurance_Rate__c/fields/Single__c.field-meta.xml
<CustomField>
    <fullName>Single__c</fullName>
    <label>Single</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insurance_Rate__c/fields/Tax_Zone__c.field-meta.xml
<CustomField>
    <fullName>Tax_Zone__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Tax Zone used to calculate rate.  ( GLV3 )</description>
    <label>Tax Zone</label>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Insurance Rates</relationshipLabel>
    <relationshipName>Insurance_Rates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insurance_Rate__c/fields/Upper_Finance_Term__c.field-meta.xml
<CustomField>
    <fullName>Upper_Finance_Term__c</fullName>
    <label>Upper Finance Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Insurance_Rate__c/fields/Upper_Term__c.field-meta.xml
<CustomField>
    <fullName>Upper_Term__c</fullName>
    <label>Upper Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/InsurancePlan__c/InsurancePlan__c.object-meta.xml
<CustomObject>
    <label>Insurance Plan</label>
    <nameField>
        <label>Insurance Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/InsurancePlan__c/fields/Dump_Id__c.field-meta.xml
<CustomField>
    <fullName>Dump_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Dump Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/InsurancePlan__c/fields/Profit_Percent__c.field-meta.xml
<CustomField>
    <fullName>Profit_Percent__c</fullName>
    <label>Profit Percent</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Tax_is_Harmonized__c.field-meta.xml
<CustomField>
    <fullName>Tax_is_Harmonized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax_is_Harmonized</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tax_Rate_Provincial__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_Provincial__c</fullName>
    <label>Tax Rate (Provincial)</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

src/Base/main/default/objects/OpportunityLineItem/fields/Insurance_Rate__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Rate__c</fullName>
    <label>Insurance Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/InsuranceCoverage__c.field-meta.xml
<CustomField>
    <fullName>InsuranceCoverage__c</fullName>
    <label>InsuranceCoverage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Joint</fullName>
            </value>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>Buyer Only</fullName>
                <isActive>false</isActive>
                <label>Buyer Only</label>
            </value>
            <value>
                <fullName>Co-Buyer Only</fullName>
                <isActive>false</isActive>
                <label>Co-Buyer Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Product2/fields/Dump_Id__c.field-meta.xml
<CustomField>
    <fullName>Dump_Id__c</fullName>
    <description>Used to help populate data into sandboxes</description>
    <externalId>true</externalId>
    <label>Dump Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Product2/fields/InsurancePlan__c.field-meta.xml
<CustomField>
    <fullName>InsurancePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance Plan</label>
    <referenceTo>InsurancePlan__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>InsuranceProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Product2/recordTypes/Insurance.recordType-meta.xml
<RecordType>
    <fullName>Insurance</fullName>
    <active>true</active>
    <label>Insurance</label>
</RecordType>

src/Base/main/default/objects/Product2/recordTypes/Part.recordType-meta.xml
<RecordType>
    <fullName>Part</fullName>
    <active>true</active>
    <description>Part</description>
    <label>Part</label>
</RecordType>

force-app/main/default/objects/Trade_In_Record__c/Trade_In_Record__c.object-meta.xml
<CustomObject>
    <label>Trade In Record</label>
    <nameField>
        <displayFormat>TIR-{0000}</displayFormat>
        <label>Trade In Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade In Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade_In_Record__c/fields/Lien_Amount__c.field-meta.xml
<CustomField>
    <fullName>Lien_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lien Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trade_In_Record__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Trade In Records</relationshipLabel>
    <relationshipName>Trade_In_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trade_In_Record__c/fields/Total_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Value__c</fullName>
    <label>Total Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Automation/main/default/classes/Opportunity/Tests/TA_Opportunity_TestHelper.cls
/**
 * Created by dhavalmacbook on 30/01/22.
 */
@isTest
public with sharing class TA_Opportunity_TestHelper {

    public static User whitefishUser;
    public static User blankUser;
    public static AcctSeedERP__Warehouse__c whitefishWarehouse;
    public static Opportunity opp;

    @testSetup
    public static void dataSetup()
    {
        new Factory_TestData();
        Factory_CustomSettings.setupInventorySettings();
    }
    public static void init() {
        whitefishWarehouse = [SELECT Id,
                Name,
                GL_Account_Variable_3__c,
                GL_Account_Variable_3__r.Name,
                GL_Account_Variable_3__r.Tax_is_Harmonized__c,
                GL_Account_Variable_3__r.Tax_Rate_Provincial__c
        FROM AcctSeedERP__Warehouse__c
        WHERE Name = 'Whitefish'
        LIMIT 1];
        User[] users = new List<User>();
        whitefishUser = Factory_User.newUser('whitefish', 'mcTesterson', 'System Administrator', whitefishWarehouse );
        blankUser = User_TestFactory.newUser( 'Jjjjjj', 'Hhhhh', 'System Administrator' );
        users.add( whitefishUser );
        users.add( blankUser );
        insert users;
    }
    public static void createOpportunityLineItem(){
    List<OpportunityLineItem>olis = new List<OpportunityLineItem>();
    Trade_In_Record__c trade = new Trade_In_Record__c(Lien_Amount__c=1000,Opportunity__c=opp.id,Total_Value__c=10000);    
    insert trade;
    InsurancePlan__c plan =  new InsurancePlan__c(
      Name = 'Insurance Plan One',
      Profit_Percent__c = 50
    );
    insert plan;
         Set<Id> prodIds = new Set<Id>();
    prodIds.add( Factory_Product.createInsuranceProduct(
      'Life Insurance Coverage',
      'Life (One)',
      plan.Id,
      false,
      LGND_Constants.retailPricebookId ).Id );
    Product2 warranty = Factory_Product.buildNonSerializedProduct('Part', 'Extended Warranty');
            insert warranty;
            prodIds.add( warranty.Id );
            Factory_PricebookEntry.createStandardEntry( warranty.Id, 100);
        
    		Insurance_Rate__c insuranceRate = new Insurance_Rate__c(Dump_Id__c='111111',
                                                           Joint__c=1,
                                                           Joint_Factor__c=10,
                                                           Product__c =warranty.id,
                                                           Lower_Term__c=5,
                                                           Lower_Finance_Term__c=5,
                                                           Single__c=3,
                                                           Upper_Finance_Term__c=10,
                                                           Upper_Term__c=10,
                                                           Tax_Zone__c = gcConstants.idGlv3Ontario);
        insert insuranceRate;
        
    		//Factory_PricebookEntry.createStandardEntryInPricebook( warranty.Id, opp.Pricebook2Id, 100);
    for( PricebookEntry pbe : [SELECT Id, Product2Id FROM PricebookEntry WHERE Pricebook2Id = :opp.Pricebook2Id AND Product2Id IN :prodIds ] )
    {
      OpportunityLineItem oli =  Factory_OpportunityLineItem.buildLineItem(
        pbe.Id,
        opp.Id,
        1000,
        1,
        null
      );
      oli.IsInsurance__c=true;
      oli.Insurance_Rate__c =10;
      oli.InsuranceCoverage__c = 'Joint';
      olis.add(oli);
    }
    insert olis;
    
    }

    public static List<Opportunity> getOldList() {
        Opportunity c = opp.clone(true, true, true, true);
        return new List<Opportunity>{ c };
    }
}