src/Base/main/default/objects/Rigger_Job__c/Rigger_Job__c.object-meta.xml
<CustomObject>
    <label>Rigger Job</label>
    <nameField>
        <label>Rigger Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rigger Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rigger_Job_Time_Entry__c/Rigger_Job_Time_Entry__c.object-meta.xml
<CustomObject>
    <label>Rigger Job Time Entry</label>
    <nameField>
        <displayFormat>RJTE-{0000}</displayFormat>
        <label>Rigger Job Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rigger Job Time Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rigger_Job_Time_Entry__c/fields/End_At__c.field-meta.xml
<CustomField>
    <fullName>End_At__c</fullName>
    <label>End At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Rigger_Job_Time_Entry__c/fields/Rigger_Job__c.field-meta.xml
<CustomField>
    <fullName>Rigger_Job__c</fullName>
    <label>Rigger Job</label>
    <referenceTo>Rigger_Job__c</referenceTo>
    <relationshipLabel>Rigger Job Time Entries</relationshipLabel>
    <relationshipName>Rigger_Job_Time_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/objects/Rigger_Job_Time_Entry__c/fields/Start_At__c.field-meta.xml
<CustomField>
    <fullName>Start_At__c</fullName>
    <label>Start At</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Rigger_Job_Time_Entry__c/fields/Total_Time__c.field-meta.xml
<CustomField>
    <fullName>Total_Time__c</fullName>
    <description>Total time the Job has been active</description>
    <label>Total Time</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RiggerJobTimeEntry_TriggerHandler_T.cls
/**
 * Created by dave on 2019-11-22.
 */

@IsTest
private class RiggerJobTimeEntry_TriggerHandler_T
{

  @testSetup static void dataSetup()
  {
    new Factory_TestData();
    Factory_CustomSettings.setupInventorySettings();
  }

  @IsTest
  static void TotalTimeShouldBeSetOnInsert_Test()
  {
    Rigger_Job__c rj = new Rigger_Job__c();
    insert rj;
    Rigger_Job_Time_Entry__c tj = new Rigger_Job_Time_Entry__c(
      Start_At__c = DateTime.now().addHours( -3 ),
      End_At__c = DateTime.now(),
      Rigger_Job__c = rj.Id
    );
    Test.startTest();
    insert tj;
    Test.stopTest();
    tj = [SELECT Id, Total_Time__c FROM Rigger_Job_Time_Entry__c WHERE Id = :tj.Id];
    System.assertEquals( 180, tj.Total_Time__c );
  }

  @IsTest
  static void TotalTimeShouldBeSetOnUpdate_Test()
  {
    Rigger_Job__c rj = new Rigger_Job__c();
    insert rj;
    Rigger_Job_Time_Entry__c tj = new Rigger_Job_Time_Entry__c(
      Start_At__c = DateTime.now().addHours( -3 ),
      Rigger_Job__c = rj.Id
    );
    insert tj;
    tj = [SELECT Id, Total_Time__c FROM Rigger_Job_Time_Entry__c WHERE Id = :tj.Id];
    System.assertEquals( null, tj.Total_Time__c );
    Test.startTest();
    tj.End_At__c = DateTime.now();
    update tj;
    Test.stopTest();
    tj = [SELECT Id, Total_Time__c FROM Rigger_Job_Time_Entry__c WHERE Id = :tj.Id];
    System.assertEquals( 180, tj.Total_Time__c );
  }
}