src/Base/main/default/objects/AcctSeedERP__Sales_Order__c/AcctSeedERP__Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Sales_Order_Line__c/AcctSeedERP__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{00000}</displayFormat>
        <label>Sales Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Sales_Order_Line__c/fields/AcctSeedERP__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>AcctSeedERP__Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Line</relationshipLabel>
    <relationshipName>Sales_Order_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/classes/SalesOrderLine.cls
public without sharing class SalesOrderLine {


	public static Boolean disableTrigger{
		get{
			if(disableTrigger == null) return false;
			else return disableTrigger;
		}
		set{
			if(value == null) disableTrigger = false;
			else disableTrigger = value;
		}
	}

	public static Boolean disableAutosetTaxable{
		get{
			if(disableAutosetTaxable == null) return false;
			else return disableAutosetTaxable;
		}
		set{
			if(value == null) disableAutosetTaxable = false;
			else disableAutosetTaxable = value;
		}
	}

	public static void triggerHandler
		(map<Id,AcctSeedERP__Sales_Order_Line__c> oldMap,
		 map<Id,AcctSeedERP__Sales_Order_Line__c> newMap,
		 list<AcctSeedERP__Sales_Order_Line__c> listNew,
		 Boolean boolIsBefore,
		 Boolean boolIsInsert,
		 Boolean boolIsUpdate,
		 Boolean boolIsDelete)
	{
		if(oldMap == NULL) oldMap = new map<Id,AcctSeedERP__Sales_Order_Line__c>();
		if(newMap == NULL) newMap = new map<Id,AcctSeedERP__Sales_Order_Line__c>();
		if(listNew == NULL) listNew = new list<AcctSeedERP__Sales_Order_Line__c>();

		if(boolIsBefore)
		{
			if(boolIsInsert)
			{

			}
			if(boolIsUpdate)
			{

			}
			if(boolIsDelete)
			{

			}
		}
		else //i.e. trigger.isAfter
		{
			set<Id> setIdBill = new set<Id>();
			if(boolIsInsert)
			{
				for(AcctSeedERP__Sales_Order_Line__c b : listNew)
					setIdBill.add(b.AcctSeedERP__Sales_Order__c);
                System.debug('setIdBill insert= '+setIdBill);
			}
			if(boolIsUpdate)
			{
				for(AcctSeedERP__Sales_Order_Line__c b : listNew)
					setIdBill.add(b.AcctSeedERP__Sales_Order__c);
				for(AcctSeedERP__Sales_Order_Line__c b : oldMap.values())
					setIdBill.add(b.AcctSeedERP__Sales_Order__c);
                System.debug('setIdBill update= '+setIdBill);
			}
			if(boolIsDelete)
			{
				for(AcctSeedERP__Sales_Order_Line__c b : oldMap.values())
					setIdBill.add(b.AcctSeedERP__Sales_Order__c);
			}
			SalesOrderLine_Service.updateSalesTax(setIdBill);
		}
	}
}