src/Base/main/default/objects/AcctSeedERP__Sales_Order__c/AcctSeedERP__Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Sales_Order_Line__c/AcctSeedERP__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{00000}</displayFormat>
        <label>Sales Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Sales_Order_Line__c/fields/AcctSeedERP__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>AcctSeedERP__Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Line</relationshipLabel>
    <relationshipName>Sales_Order_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/classes/TA_SalesOrderLine_UpdateTax.cls
public inherited sharing class TA_SalesOrderLine_UpdateTax implements  TriggerAction.AfterUpdate
{
    
  public void afterUpdate( List<AcctSeedERP__Sales_Order_Line__c> newList,
                           List<AcctSeedERP__Sales_Order_Line__c> oldList
                          
                         )
  {
      set<Id> setIdBill = new set<Id>();
      Map<Id, AcctSeedERP__Sales_Order_Line__c> oldMap= new Map<Id, AcctSeedERP__Sales_Order_Line__c>( oldList);
       
      for(AcctSeedERP__Sales_Order_Line__c b : newList){
          setIdBill.add(b.AcctSeedERP__Sales_Order__c);
      }
      for(AcctSeedERP__Sales_Order_Line__c b : oldMap.values()){
          setIdBill.add(b.AcctSeedERP__Sales_Order__c);
      }
      
      SalesOrderLineService.updateSalesTax(setIdBill);
  }
 
}