src/Base/main/default/objects/AcctSeedERP__Sales_Order__c/AcctSeedERP__Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Sales_Order_Line__c/AcctSeedERP__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{00000}</displayFormat>
        <label>Sales Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Sales_Order_Line__c/fields/AcctSeedERP__Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Sales_Order__c</fullName>
    <label>Sales Order</label>
    <referenceTo>AcctSeedERP__Sales_Order__c</referenceTo>
    <relationshipLabel>Sales Order Line</relationshipLabel>
    <relationshipName>Sales_Order_Line</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Automation/main/default/classes/SalesOrderLine/TA_SalesOrderLine_calculateTax_AI.cls
/**
 * Created by Legend on 11/5/22.
 */

public class TA_SalesOrderLine_calculateTax_AI implements  TriggerAction.AfterInsert{
    public void afterInsert( List<AcctSeedERP__Sales_Order_Line__c> newList)
    {
        set<Id> setId = new set<Id>();
        for(AcctSeedERP__Sales_Order_Line__c sol : newList){
            setId.add(sol.AcctSeedERP__Sales_Order__c);
        }
        SalesOrderLine_Service.updateSalesTax(setId);
    }
}