src/Base/main/default/objects/AcctSeed__Product_Part__c/AcctSeed__Product_Part__c.object-meta.xml
<CustomObject>
    <description>Used to document the relationship between products. The primary use of this record is to create product kits which are used in the Accounting Seed ERP application.</description>
    <label>Product Part</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Product Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Product_Part__c/fields/AcctSeed__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Parts</relationshipLabel>
    <relationshipName>Product_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Product_Part__c/fields/AcctSeed__Product_Part__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Part</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parent Product</relationshipLabel>
    <relationshipName>Product_Parts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Product_Part__c/fields/AcctSeed__Quantity__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Product2/recordTypes/Insurance.recordType-meta.xml
<RecordType>
    <fullName>Insurance</fullName>
    <active>true</active>
    <label>Insurance</label>
</RecordType>

src/Base/main/default/objects/Product2/recordTypes/Part.recordType-meta.xml
<RecordType>
    <fullName>Part</fullName>
    <active>true</active>
    <description>Part</description>
    <label>Part</label>
</RecordType>

src/Automation/main/default/classes/ProductPart/Tests/TA_ProductPart_Legacy_T.cls
@isTest
public class TA_ProductPart_Legacy_T {

    final static String RECORDTYPE = 'Insurance';
    final static String FAMILY = 'Insurance';
    static List<AcctSeed__Product_Part__c> product_parts;
    private static List<AcctSeed__Product_Part__c> getData(){
        return  [SELECT Id, AcctSeed__Product__c, AcctSeed__Product_Part__c FROM AcctSeed__Product_Part__c];
    }
    @TestSetup
    static void testData(){
        new Factory_TestData();
        Factory_CustomSettings.setupInventorySettings();
        Factory_AccountPayable.insertAccountPayable(5);
        new Factory_AccountingVariables();
        List<Product2> serializedProducts = Factory_Product.createSerializedProducts(RECORDTYPE, FAMILY, 10);
        List<Product2> Parts = Factory_Product.createSerializedProducts('Part', 'Safety', 10);

        List<AcctSeed__Product_Part__c> product_parts = new List<AcctSeed__Product_Part__c>();
        integer i=0;
        for(Product2 prod: serializedProducts){
            product_parts .add(new AcctSeed__Product_Part__c(
                    AcctSeed__Product__c=prod.Id,
                    AcctSeed__Quantity__c=2,
                    AcctSeed__Product_Part__c = parts[i].Id
            ));
            i++;
        }
        insert product_parts;
    }

    @IsTest
    static void beforeInsertTest() {
        Test.startTest();
        product_parts = getData();
        new TA_ProductPart_Legacy().beforeInsert(product_parts);
        Test.stopTest();
    }
    @IsTest
    static void afterInsertTest() {
        Test.startTest();
        new TA_ProductPart_Legacy().afterInsert(getData());
        Test.stopTest();
    }
    @IsTest
    static void afterUpdateTest() {
        Test.startTest();
        product_parts = getData();
        AcctSeed__Product_Part__c productPartClone =product_parts[0].clone(true, true, true, true);
        new TA_ProductPart_Legacy().afterUpdate(new List<AcctSeed__Product_Part__c>{product_parts[0]},new List<AcctSeed__Product_Part__c>{productPartClone});
        Test.stopTest();
    }
    @IsTest
    static void beforeUpdateTest() {
        Test.startTest();
        product_parts = getData();
        AcctSeed__Product_Part__c productPartClone =product_parts[0].clone(true, true, true, true);
        new TA_ProductPart_Legacy().beforeUpdate(new List<AcctSeed__Product_Part__c>{product_parts[0]},new List<AcctSeed__Product_Part__c>{productPartClone});
        Test.stopTest();
    }
    @IsTest
    static void beforeDeleteTest() {
        Test.startTest();
        new TA_ProductPart_Legacy().beforeDelete(getData());
        Test.stopTest();
    }
    @IsTest
    static void afterDeleteTest() {
        Test.startTest();
        new TA_ProductPart_Legacy().afterDelete(getData());
        Test.stopTest();
    }




}