src/Base/main/default/objects/AcctSeed__Product_Part__c/AcctSeed__Product_Part__c.object-meta.xml
<CustomObject>
    <description>Used to document the relationship between products. The primary use of this record is to create product kits which are used in the Accounting Seed ERP application.</description>
    <label>Product Part</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Product Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Product_Part__c/fields/AcctSeed__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Parts</relationshipLabel>
    <relationshipName>Product_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Product_Part__c/fields/AcctSeed__Product_Part__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Part</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parent Product</relationshipLabel>
    <relationshipName>Product_Parts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Product_Part__c/fields/AcctSeed__Quantity__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ProductPart_Selector.cls
/**
 * Created by dave on 2020-05-06.
 */

public with sharing class ProductPart_Selector extends Application_Selector
{


  public ProductPart_Selector()
  {
    this.sObjectName = 'AcctSeed__Product_Part__c';
    this.fields = new List<String>{
      'Id',
      'AcctSeed__Product__c',
      'AcctSeed__Product_Part__c',
      'AcctSeed__Product_Part__r.Name',
      'AcctSeed__Quantity__c'
    };
  }

  public static List<AcctSeed__Product_Part__c> allForPartKitsByParentIds( Set<Id> parentProductIds )
  {
    Id partRtId = LGND_Constants.productRtId_Part;
    ProductPart_Selector selector = new ProductPart_Selector();
    selector
      .addWhere( whereInClauseBuilder( 'AcctSeed__Product__c', parentProductIds ) )
      .addWhere( 'AcctSeed__Product__r.RecordTypeId = \'' + partRtId + '\'', 'AND' );
    return (List<AcctSeed__Product_Part__c>)selector.query();
  }
}