force-app/main/default/objects/AcctSeed__Project_Task__c/AcctSeed__Project_Task__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parts List</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/AcctSeedERP__Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <displayFormat>MAT-{00000}</displayFormat>
        <label>Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Promotion__c/Promotion__c.object-meta.xml
<CustomObject>
    <description>Promotions that dealers can claim when they sell boats to customers.</description>
    <label>Promotion</label>
    <nameField>
        <label>Promotion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Promotions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotion_Incentive_Product__c/Promotion_Incentive_Product__c.object-meta.xml
<CustomObject>
    <description>Products that get added to the Promotion ERP for free once the Promotion Case is Approved</description>
    <label>Promotion Incentive Product</label>
    <nameField>
        <displayFormat>PromoIncetive-{0000}</displayFormat>
        <label>Promotion Incentive Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promotion Incentive Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/Promotion_Incentive_Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>A promotional incentive product included in the promotion</description>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Promotion Incentive Products</relationshipLabel>
    <relationshipName>Promotion_Incentive_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Promotion_Incentive_Product__c/fields/Promotion__c.field-meta.xml
<CustomField>
    <fullName>Promotion__c</fullName>
    <label>Promotion</label>
    <referenceTo>Promotion__c</referenceTo>
    <relationshipLabel>Promotion Incentive Products</relationshipLabel>
    <relationshipName>Promotion_Incentive_Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/classes/Queueables/Promotion_Queueables.cls
/**
 * Created by dave on 2022-01-10.
 */

public with sharing class Promotion_Queueables {
  public class AddPromotionItems implements Queueable {
    public Map<String, String> erpToPromoMap;

    public AddPromotionItems() {
      this.erpToPromoMap = new Map<String, String>();
    }

    public AddPromotionItems(Map<String, String> erpToPromoMap) {
      this.erpToPromoMap = erpToPromoMap;
    }

    public void execute(QueueableContext context) {
      if (this.erpToPromoMap == null || this.erpToPromoMap.size() == 0)
        return;

      Map<Id, Promotion__c> promotions = new Map<Id, Promotion__c>(
        [
          SELECT Id, Name, (SELECT Id, Product__c, Quantity__c FROM Promotion_Incentive_Products__r)
          FROM Promotion__c
          WHERE Id IN :this.erpToPromoMap.values()
        ]
      );
      Map<Id, AcctSeed__Project_Task__c> erpToTaskMap = new Map<Id, AcctSeed__Project_Task__c>();
      for (String erpId : this.erpToPromoMap.keySet()) {
        String promoId = this.erpToPromoMap.get(erpId);
        if (promotions.get(promoId).Promotion_Incentive_Products__r.size() > 0) {
          erpToTaskMap.put(erpId, ProjectTask_Service.buildPromotionItemsTask(erpId));
        }
      }
      if (erpToTaskMap.values().size() > 0) {
        insert erpToTaskMap.values();
        List<AcctSeedERP__Material__c> mats = new List<AcctSeedERP__Material__c>();
        for (String erpId : this.erpToPromoMap.keySet()) {
          String promoId = this.erpToPromoMap.get(erpId);
          if (erpToTaskMap.containsKey(erpId)) {
            mats.addAll(
              Material_Service.buildFromPromotionalIncentiveProducts(
                promotions.get(promoId).Promotion_Incentive_Products__r,
                erpId,
                erpToTaskMap.get(erpId).Id,
                promotions.get(promoId).Name
              )
            );
          }
        }
        insert mats;
      }
    }
  }
}