src/Base/main/default/objects/AcctSeed__Cash_Receipt__c/AcctSeed__Cash_Receipt__c.object-meta.xml
<CustomObject>
    <description>Used to document the money received from a customer. Typically matched to billing invoices in the cash application process to denote satisfactory payment of billing invoice by customer.</description>
    <label>Cash Receipt</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Cash Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Cash_Receipt__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>AcctSeedERP__Sales_Order__c</referenceTo>
    <relationshipLabel>Cash Receipts</relationshipLabel>
    <relationshipName>Cash_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Sales_Order__c/AcctSeedERP__Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Ecwid_Sales_Order__e/Ecwid_Sales_Order__e.object-meta.xml
<CustomObject>
    <label>Ecwid Sales Order</label>
    <pluralLabel>Ecwid Sales Orders</pluralLabel>
</CustomObject>

src/Automation/main/default/objects/Ecwid_Sales_Order__e/fields/Sales_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Id__c</fullName>
    <description>ID OF THE SO</description>
    <label>Sales Order Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/Automation/main/default/objects/Ecwid_Sales_Order__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the CR is created then it will be checked (if not deleted)</description>
    <label>Status</label>
    <type>Checkbox</type>
</CustomField>

src/Automation/main/default/classes/EcwidSalesOrder/Tests/TA_EcwidSalesOrder_AI_T.cls
/**
 * Created by Legend on 16/5/22.
 */

@IsTest
private class TA_EcwidSalesOrder_AI_T {
  @testSetup
  static void dataSetup() {
    new Factory_TestData();
    Factory_CustomSettings.setupInventorySettings();
  }

  @IsTest
  static void afterInsert_Trigger() {
    Account customer = Factory_Account.insertCustomerAccounts(1)[0];
    AcctSeedERP__Sales_Order__c so = Factory_SalesOrder.createSalesOrder(customer, null);
    Ecwid_Sales_Order__e evt = new Ecwid_Sales_Order__e(Status__c = true, Sales_Order_Id__c = so.Id);
    Test.startTest();
    Database.SaveResult sr = EventBus.publish(evt);
    Test.stopTest();
    List<AcctSeed__Cash_Receipt__c> receipts = [SELECT Id FROM AcctSeed__Cash_Receipt__c WHERE Sales_Order__c = :so.Id];
    System.assertEquals(true, sr.isSuccess());
    System.assertEquals(1, receipts.size());
  }
}