src/Base/main/default/objects/AcctSeed__Cash_Receipt__c/AcctSeed__Cash_Receipt__c.object-meta.xml
<CustomObject>
    <description>Used to document the money received from a customer. Typically matched to billing invoices in the cash application process to denote satisfactory payment of billing invoice by customer.</description>
    <label>Cash Receipt</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Cash Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Cash_Receipt__c/fields/GMBLASG__Posted__c.field-meta.xml
<CustomField>
    <fullName>GMBLASG__Posted__c</fullName>
    <formula>TEXT(AcctSeed__Status__c) = &apos;Posted&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Posted</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Cash_Receipt__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>AcctSeedERP__Sales_Order__c</referenceTo>
    <relationshipLabel>Cash Receipts</relationshipLabel>
    <relationshipName>Cash_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/classes/AutoPostECWID_CashReceipts.cls
/**
 * Created by Legend on 25/4/22.
 */

public with sharing class AutoPostECWID_CashReceipts implements Schedulable, Database.Batchable<sObject> {
  public AutoPostECWID_CashReceipts() {
  }

  public Database.QueryLocator start(Database.BatchableContext BC) {
    String query = 'SELECT Id FROM AcctSeed__Cash_Receipt__c WHERE GMBLASG__Posted__c = false AND Sales_Order__c != null';
    return Database.getQueryLocator(query);
  }

  public void execute(Database.BatchableContext BC, List<sObject> scope) {
    List<AcctSeed__Cash_Receipt__c> listCR = new List<AcctSeed__Cash_Receipt__c>();
    for (SObject sObj : scope) {
      AcctSeed__Cash_Receipt__c p = (AcctSeed__Cash_Receipt__c) sObj;
      listCR.add(p);
    }
    if (!listCR.isEmpty())
      AcctSeed.CashReceiptPostService.postCashReceipts(listCR);
  }

  public void execute(SchedulableContext sc) {
    AutoPostECWID_CashReceipts b = new AutoPostECWID_CashReceipts();
    database.executeBatch(b, 1);
  }

  public void finish(Database.BatchableContext BC) {
  }
}