force-app/main/default/objects/AcctSeedERP__Purchase_Order_Line__c/AcctSeedERP__Purchase_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POL-{00000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Line__c/fields/AcctSeedERP__Quantity_Unreceived__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Quantity_Unreceived__c</fullName>
    <formula>AcctSeedERP__Quantity__c- AcctSeedERP__Quantity_Received__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity Unreceived</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Purchase_Order_Line__c/fields/Reserved__c.field-meta.xml
<CustomField>
    <fullName>Reserved__c</fullName>
    <label>Reserved</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Automation/main/default/classes/PurchaseOrderLine/TA_POL_SetReserved.cls
/**
 * Created by dave on 2021-07-27.
 */

public inherited sharing class TA_POL_SetReserved
  implements TriggerAction.BeforeUpdate
{

  public void beforeUpdate(
    List<AcctSeedERP__Purchase_Order_Line__c> newList,
    List<AcctSeedERP__Purchase_Order_Line__c> oldList
  )
  {
    for( AcctSeedERP__Purchase_Order_Line__c pol :newList )
    {
      if( pol.AcctSeedERP__Quantity_Unreceived__c < pol.Reserved__c )
      {
        pol.Reserved__c = pol.AcctSeedERP__Quantity_Unreceived__c;
      }
    }
  }

}