force-app/main/default/objects/AcctSeedERP__Sales_Order_Line__c/AcctSeedERP__Sales_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Sales Order Line</label>
    <nameField>
        <displayFormat>SOL-{00000}</displayFormat>
        <label>Sales Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order Line</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Sales_Order_Line__c/fields/AcctSeedERP__Quantity_Ordered__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Quantity_Ordered__c</fullName>
    <label>Quantity Ordered</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Sales_Order_Line__c/fields/AcctSeedERP__Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>16</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Sales_Order_Line__c/fields/Part_Quantity_Specified_Multiplier__c.field-meta.xml
<CustomField>
    <fullName>Part_Quantity_Specified_Multiplier__c</fullName>
    <label>Part Quantity Specified Multiplier</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Sales_Order_Line__c/fields/Sales_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Kit Lookup</description>
    <label>Sales Order Line</label>
    <referenceTo>AcctSeedERP__Sales_Order_Line__c</referenceTo>
    <relationshipLabel>Sales Order Line</relationshipLabel>
    <relationshipName>Sales_Order_Line</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Automation/main/default/classes/SalesOrderLine/TA_SalesOrderLine_BU.cls
/**
 * Created by Legend on 21/4/22.
 */

public inherited sharing class TA_SalesOrderLine_BU implements TriggerAction.BeforeUpdate {
  public Boolean allowPartUpdate = false;
  public void beforeUpdate(
    List<AcctSeedERP__Sales_Order_Line__c> newList,
    List<AcctSeedERP__Sales_Order_Line__c> oldList
  ) {
    Map<Id, AcctSeedERP__Sales_Order_Line__c> oldMap = new Map<Id, AcctSeedERP__Sales_Order_Line__c>(oldList);

    for (AcctSeedERP__Sales_Order_Line__c sol : newList) {
      if (!allowPartUpdate && sol.Sales_Order_Line__c != null) {
        sol.AcctSeedERP__Quantity_Ordered__c = oldMap.get(sol.Id).AcctSeedERP__Quantity_Ordered__c;
        sol.Part_Quantity_Specified_Multiplier__c = oldMap.get(sol.Id).Part_Quantity_Specified_Multiplier__c;
        sol.AcctSeedERP__Unit_Price__c = oldMap.get(sol.Id).AcctSeedERP__Unit_Price__c;
      }
    }
  }
}