force-app/main/default/objects/Boat_Rigging_Checklist_Item__c/Boat_Rigging_Checklist_Item__c.object-meta.xml
<CustomObject>
    <label>Boat Rigging Checklist Item</label>
    <nameField>
        <displayFormat>BRCI-{0000}</displayFormat>
        <label>Boat Rigging Checklist Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boat Rigging Checklist Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Boat_Rigging_Checklist_Item__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>External</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Boat_Rigging_Checklist_Map__c/Boat_Rigging_Checklist_Map__c.object-meta.xml
<CustomObject>
    <description>Maps Boat Rigging checklist items to products</description>
    <label>Boat Rigging Checklist Map</label>
    <nameField>
        <displayFormat>BRCM-{0000}</displayFormat>
        <label>Boat Rigging Checklist Map Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boat Rigging Checklist Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GMBLASERP__Lot__c/GMBLASERP__Lot__c.object-meta.xml
<CustomObject>
    <label>Lot</label>
    <nameField>
        <label>Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/GMBLASERP__Lot__c/fields/GMBLASERP__Product__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lots</relationshipLabel>
    <relationshipName>Lots</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Lot__c/fields/GMBLASERP__Uniquefier__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Uniquefier__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Uniquefier</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/GMBLASERP__Serial_Number__c.object-meta.xml
<CustomObject>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/fields/GMBLASERP__Lot__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Lot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lot</label>
    <referenceTo>GMBLASERP__Lot__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/fields/GMBLASERP__Product__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/fields/GMBLASERP__Uniquefier__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Uniquefier__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Uniquefier</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/fields/Nest__c.field-meta.xml
<CustomField>
    <fullName>Nest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nest</label>
    <referenceTo>GMBLASERP__Serial_Number__c</referenceTo>
    <relationshipLabel>Nested Serial Numbers</relationshipLabel>
    <relationshipName>Nested_Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeed__Inventory_Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Inventory_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes whether the product is a managed inventory product</description>
    <inlineHelpText>Denotes whether the product is a managed inventory product</inlineHelpText>
    <label>Inventory Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeedERP__Serialized__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Serialized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Serialized</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Standard_Motor__c.field-meta.xml
<CustomField>
    <fullName>Standard_Motor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Standard_Motor</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products (Standard Motor)</relationshipLabel>
    <relationshipName>Products_SM</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Standard_Trailer__c.field-meta.xml
<CustomField>
    <fullName>Standard_Trailer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Standard Trailer</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products (Standard Trailer)</relationshipLabel>
    <relationshipName>Products_ST</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Standard_Trolling_Motor__c.field-meta.xml
<CustomField>
    <fullName>Standard_Trolling_Motor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Standard Trolling Motor</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products (Standard Trolling Motor)</relationshipLabel>
    <relationshipName>Products_STM</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Product2/recordTypes/Boat.recordType-meta.xml
<RecordType>
    <fullName>Boat</fullName>
    <active>true</active>
    <label>Boat</label>
</RecordType>

src/Base/main/default/objects/Product2/recordTypes/Motor.recordType-meta.xml
<RecordType>
    <fullName>Motor</fullName>
    <active>true</active>
    <description>Outboard Motors</description>
    <label>Motor</label>
</RecordType>

src/Base/main/default/objects/Product2/recordTypes/Trailer.recordType-meta.xml
<RecordType>
    <fullName>Trailer</fullName>
    <active>true</active>
    <description>Boat trailer</description>
    <label>Trailer</label>
</RecordType>

src/Base/main/default/classes/BoatRiggingChecklistController_Test.cls
@isTest
private class BoatRiggingChecklistController_Test {
  static Product2 boat;
  static List<Boat_Rigging_Checklist_Map__c> checklistItems;

  static {
    InventoryTestFactory factory = new InventoryTestFactory();
    boat = factory.buildTestBoat();
    boat.AcctSeedERP__Serialized__c = true;
    boat.AcctSeed__Inventory_Product__c = true;
    Boolean orig = gcProduct.disableTrigger;
    gcProduct.disableTrigger = true;
    System.debug(boat);
    insert boat;
    gcProduct.disableTrigger = orig;
    checklistItems = factory.insertFullRiggingChecklistForBoat(boat.Id, 5);
  }

  @isTest
  static void buildChecklistFromProduct_Test() {
    Test.startTest();
    PageReference pageRef = Page.BoatRiggingChecklist_View;
    pageRef.getParameters().put('Id', boat.Id);
    Test.setCurrentPage(pageRef);
    BoatRiggingChecklistController ctr = new BoatRiggingChecklistController();
    String[] categories = LGND_Utilities.getPicklistValues('Boat_Rigging_Checklist_Item__c', 'Category__c');
    Test.stopTest();

    System.assert(ctr.getHasRiggingChecklistItems());
    System.assertEquals(categories.size(), ctr.riggingChecklistItems.keySet().size());
    System.assertEquals(5, ctr.riggingChecklistItems.get(categories[0]).size());
    System.assertEquals('', ctr.boatSerialNumber);
    System.assertEquals('', ctr.trailerSerialNumber);
    System.assertEquals('', ctr.trollingMotorSerialNumber);
  }

  @isTest
  static void buildChecklistFromSerialNumber_Test() {
    Test.startTest();
    Map<Id, GMBLASERP__Lot__c> lotMap = buildLotMap(boat);
    Map<Id, GMBLASERP__Serial_Number__c> serialMap = new Map<Id, GMBLASERP__Serial_Number__c>();
    for (Id prodId : lotMap.keySet()) {
      String serNum = '123';
      if (prodId == boat.Id)
        serNum += 'BOAT';
      if (prodId == boat.Standard_Motor__c)
        serNum += 'MOTOR';
      if (prodId == boat.Standard_Trailer__c)
        serNum += 'TRAILER';
      if (prodId == boat.Standard_Trolling_Motor__c)
        serNum += 'TROLLINGMOTOR';

      GMBLASERP__Serial_Number__c ser = Factory_SerialNumber.buildSerial(prodId, lotMap.get(prodId).Id, serNum);
      serialMap.put(prodId, ser);
    }
    insert serialMap.values();
    for (Id prodId : serialMap.keySet()) {
      if (prodId != boat.Id)
        serialMap.get(prodId).Nest__c = serialMap.get(boat.Id).Id;
    }
    update serialMap.values();
    PageReference pageRef = Page.BoatRiggingChecklist_View;
    pageRef.getParameters().put('Id', serialMap.get(boat.Id).Id);
    Test.setCurrentPage(pageRef);
    BoatRiggingChecklistController ctr = new BoatRiggingChecklistController();
    String[] categories = LGND_Utilities.getPicklistValues('Boat_Rigging_Checklist_Item__c', 'Category__c');
    Test.stopTest();

    System.assertEquals(categories.size(), ctr.riggingChecklistItems.keySet().size());
    System.assertEquals(5, ctr.riggingChecklistItems.get(categories[0]).size());
    System.assertEquals('123BOAT', ctr.boatSerialNumber);
    System.assertEquals('123TRAILER', ctr.trailerSerialNumber);
    System.assertEquals('123TROLLINGMOTOR', ctr.trollingMotorSerialNumber);
    System.assertEquals('', ctr.ignitionKeyNumber);
    System.assertEquals('', ctr.compartmentKeyNumber);
  }

  private static Map<Id, GMBLASERP__Lot__c> buildLotMap(Product2 boat) {
    Map<Id, GMBLASERP__Lot__c> lotMap = new Map<Id, GMBLASERP__Lot__c>();
    Date today = Date.today();
    lotMap.put(
      boat.Id,
      new GMBLASERP__Lot__c(
        GMBLASERP__Product__c = boat.Id,
        Name = String.valueOf(today.year()),
        GMBLASERP__Uniquefier__c = boat.Id + '-' + String.valueOf(today.year())
      )
    );
    lotMap.put(
      boat.Standard_Motor__c,
      new GMBLASERP__Lot__c(
        GMBLASERP__Product__c = boat.Standard_Motor__c,
        Name = String.valueOf(today.year()),
        GMBLASERP__Uniquefier__c = boat.Standard_Motor__c + '-' + String.valueOf(today.year())
      )
    );
    lotMap.put(
      boat.Standard_Trailer__c,
      new GMBLASERP__Lot__c(
        GMBLASERP__Product__c = boat.Standard_Trailer__c,
        Name = String.valueOf(today.year()),
        GMBLASERP__Uniquefier__c = boat.Standard_Trailer__c + '-' + String.valueOf(today.year())
      )
    );
    lotMap.put(
      boat.Standard_Trolling_Motor__c,
      new GMBLASERP__Lot__c(
        GMBLASERP__Product__c = boat.Standard_Trolling_Motor__c,
        Name = String.valueOf(today.year()),
        GMBLASERP__Uniquefier__c = boat.Standard_Trolling_Motor__c + '-' + String.valueOf(today.year())
      )
    );
    insert lotMap.values();
    return lotMap;
  }
}