force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <label>Dealer</label>
</RecordType>

src/Base/main/default/objects/Partner_Customer__c/Partner_Customer__c.object-meta.xml
<CustomObject>
    <label>Partner Customer</label>
    <nameField>
        <label>Partner Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Customers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Partner_Customer__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Customers (Customer)</relationshipLabel>
    <relationshipName>Partner_Customers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Customer__c/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Customers</relationshipLabel>
    <relationshipName>Partner_Customers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Customer__c/fields/Uniqueifier__c.field-meta.xml
<CustomField>
    <fullName>Uniqueifier__c</fullName>
    <label>Uniqueifier</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/Base/main/default/classes/Partner_Customer_Trigger_Handler_Test.cls
@isTest
private class Partner_Customer_Trigger_Handler_Test {
  @isTest
  static void trigger_test() {
    Account dealer = AccountFactory.buildDealerAccount('Test Dealer');
    insert dealer;
    Account customer = AccountFactory.insertPersonAccount();
    Partner_Customer__c pc = new Partner_Customer__c(Partner__c = dealer.Id, Customer__c = customer.Id);
    insert pc;
    pc = [SELECT Id, Uniqueifier__c FROM Partner_Customer__c WHERE Id = :pc.Id];
    System.assertEquals(dealer.Id + '-' + customer.Id, pc.Uniqueifier__c);
  }
}