force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <label>Dealer</label>
</RecordType>

force-app/main/default/objects/Dealer_Order__c/Dealer_Order__c.object-meta.xml
<CustomObject>
    <label>Dealer Order</label>
    <nameField>
        <displayFormat>DealerOrder-{0000}</displayFormat>
        <label>Dealer Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Dealer_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account not found or not a Dealer Account</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Orders</relationshipLabel>
    <relationshipName>Dealer_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Dealer_Order__c/fields/Is_Booking_Order__c.field-meta.xml
<CustomField>
    <fullName>Is_Booking_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Booking Order</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/Dealer_Order__c/fields/Model_Year__c.field-meta.xml
<CustomField>
    <fullName>Model_Year__c</fullName>
    <label>Model Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Dealer_Program_Settings__c/Dealer_Program_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Hopes variables for the Dealer Program</description>
    <label>Dealer Program Settings</label>
</CustomObject>

src/Base/main/default/objects/Dealer_Program_Settings__c/fields/Early_Order_Discount_Date__c.field-meta.xml
<CustomField>
    <fullName>Early_Order_Discount_Date__c</fullName>
    <label>Early Order Discount Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Dealer_Program_Settings__c/fields/Early_Order_Discount_Rate__c.field-meta.xml
<CustomField>
    <fullName>Early_Order_Discount_Rate__c</fullName>
    <label>Early Order Discount Rate</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

src/Base/main/default/classes/DealerOrderDiscounts_Test.cls
@isTest
private class DealerOrderDiscounts_Test {
  //  @testSetup static void dataSetup()
  //  {
  //    //new Factory_TestData();
  //    Factory_CustomSettings.setupInventorySettings();
  //  }
  //
  //  static Account acct;
  //  static {
  //    acct = AccountFactory.buildDealerAccount('Test Dealer');
  //    acct.BillingStreet = '666 Test Drive';
  //    acct.BillingState = 'Ontario';
  //    acct.BillingCity = 'Lovely Place';
  //    acct.BillingCountry = 'Canada';
  //    acct.BillingPostalCode = 'A1B2C3';
  //    insert acct;
  //  }
  //
  //  @isTest
  //  static void constructor_reOrder_test() {
  //    Test.startTest();
  //    Dealer_Order__c dOrder = new Dealer_Order__c(
  //      Account__c = acct.Id,
  //      Is_Booking_Order__c = false,
  //      Model_Year__c = String.valueOf( Date.today().year() )
  //    );
  //    insert dOrder;
  //    DealerOrderDiscounts dod = new DealerOrderDiscounts( dOrder.Id );
  //    Test.stopTest();
  //    System.assertEquals( 1, dod.availableDiscounts.size() );
  //  }
  //
  //  @isTest
  //  static void constructor_bookingOrder_test() {
  //    Test.startTest();
  //    insert new Dealer_Program_Settings__c(Name = '2018', Early_Order_Discount_Date__c = Date.today().addDays(3), Early_Order_Discount_Rate__c = 2.0 );
  //    Dealer_Order__c dOrder = new Dealer_Order__c(
  //      Account__c = acct.Id,
  //      Is_Booking_Order__c = true,
  //      Model_Year__c = String.valueOf( Date.today().year() )
  //    );
  //    insert dOrder;
  //    DealerOrderDiscounts dod = new DealerOrderDiscounts( dOrder.Id );
  //    Test.stopTest();
  //    System.assertEquals( 2, dod.availableDiscounts.size() );
  //  }
}