force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <label>Dealer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>Suppliers</description>
    <label>Supplier</label>
</RecordType>

src/Base/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Serial Number</label>
    <referenceTo>GMBLASERP__Serial_Number__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project__c/fields/Supplier_Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Claim_Number__c</fullName>
    <label>Supplier Claim Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project__c/fields/Warranty_Case__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warranty Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>ERP Orders</relationshipLabel>
    <relationshipName>ERP_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registration</label>
    <referenceTo>Registration__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Case/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Serial Number</label>
    <referenceTo>GMBLASERP__Serial_Number__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/GMBLASERP__Serial_Number__c.object-meta.xml
<CustomObject>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/classes/SmokercraftAPI_Callout_Test.cls
@isTest
private class SmokercraftAPI_Callout_Test {
  static Account supplier;
  static Account dealer;
  static Account customer;
  static Case theCase;
  static AcctSeed__Project__c recoverableERP;
  static GMBLASERP__Serial_Number__c serial;
  static Registration__c boatRegistration;

  @testSetup
  static void dataSetup() {
    new Factory_TestData();
    Factory_CustomSettings.setupInventorySettings();
  }

  private static void initWarranty() {
    supplier = AccountFactory.insertSupplierAccount('testSupplier');
    theCase = Factory_Case.createWarrantyCase(supplier);
    recoverableERP = Factory_ERPOrder.createWarrantyERP(supplier, theCase.Serial_Number__c, 3);
    recoverableERP.Warranty_Case__c = theCase.Id;
    update recoverableERP;
  }

  private static void initRegistration() {
    dealer = Factory_Account.insertDealerAccounts(1)[0];
    customer = Factory_Account.insertFullPersonAccount('FTest', 'LTest');
    serial = Factory_SerialNumber.insertFullSerial('Boat', 'Pontoon', 'Test12345DATA');
    boatRegistration = Factory_Registration.buildRegistration(dealer.Id, customer.Id, serial.Id);
    insert boatRegistration;
  }

  private static String buildData() {
    String data = 'hin=666TEST66&';
    data += 'dealer_number=1515&';
    data += 'dealer_seq=0';
    return data;
  }

  public class SmokerMock_Claim implements HttpCalloutMock {
    public HTTPResponse respond(HTTPRequest req) {
      HttpResponse res = new HttpResponse();
      res.setHeader('Content-Type', 'application/xml');
      res.setBody('<XMLRESPONSE><RESPONSE>1234567890</RESPONSE><STATUSCODE>200</STATUSCODE></XMLRESPONSE>');
      res.setStatusCode(200);
      return res;
    }
  }

  public class SmokerMock_Registration implements HttpCalloutMock {
    public HTTPResponse respond(HTTPRequest req) {
      HttpResponse res = new HttpResponse();
      res.setHeader('Content-Type', 'application/xml');
      res.setBody('<XMLRESPONSE><RESPONSE>Success</RESPONSE><STATUSCODE>200</STATUSCODE></XMLRESPONSE>');
      res.setStatusCode(200);
      return res;
    }
  }

  public class SmokerMock_Error implements HttpCalloutMock {
    public HTTPResponse respond(HTTPRequest req) {
      HttpResponse res = new HttpResponse();
      res.setHeader('Content-Type', 'application/xml');
      res.setBody(
        '<XMLRESPONSE><RESPONSE></RESPONSE><STATUSCODE>400</STATUSCODE><RESPONSEERROR>A test Error</RESPONSEERROR></XMLRESPONSE>'
      );
      res.setStatusCode(200);
      return res;
    }
  }

  @isTest
  static void submitClaimToSmoker_Test() {
    initWarranty();
    Test.setMock(HttpCalloutMock.class, new SmokerMock_Claim());
    Test.startTest();
    SmokercraftAPI_Callout.submitClaimToSmokercraft(recoverableERP.Id);
    Test.stopTest();
    AcctSeed__Project__c erp = [
      SELECT Id, Supplier_Claim_Number__c
      FROM AcctSeed__Project__c
      WHERE Id = :recoverableERP.Id
    ];

    System.assertEquals('1234567890', erp.Supplier_Claim_Number__c);
  }

  @isTest
  static void registerSerialNumber_Test() {
    Test.setMock(HttpCalloutMock.class, new SmokerMock_Registration());
    Test.startTest();
    String data = buildData();
    Map<String, String> result = SmokercraftAPI_Callout.registerSerialNumber(data, '666TEST666');
    Test.stopTest();
    System.assertEquals('success', result.get('status'));
  }

  @isTest
  static void submitClaimToSmoker_Error_Test() {
    initWarranty();
    Test.setMock(HttpCalloutMock.class, new SmokerMock_Error());
    String msg;
    Test.startTest();
    try {
      SmokercraftAPI_Callout.submitClaimToSmokercraft(recoverableERP.Id);
    } catch (SmokercraftAPI_Callout.SmokerAPIException e) {
      msg = e.getMessage();
    }
    Test.stopTest();

    System.assert(msg.contains('A test Error'));
  }

  @isTest
  static void registerSerialNumber_Error_Test() {
    Test.setMock(HttpCalloutMock.class, new SmokerMock_Error());
    String data = buildData();
    Test.startTest();
    Map<String, String> result = SmokercraftAPI_Callout.registerSerialNumber(data, '666TEST666');
    Test.stopTest();

    System.assertEquals('error', result.get('status'));
    System.assertEquals('Test Error', result.get('errorMessage'));
  }
}