force-app/main/default/objects/Boat_Sample_Retail_Sale__c/Boat_Sample_Retail_Sale__c.object-meta.xml
<CustomObject>
    <label>Boat Sample Retail Sale</label>
    <nameField>
        <displayFormat>BSRS-{0000}</displayFormat>
        <label>Boat Sample Retail Sale Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Boat Sample Retails Sales</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Boat_Sample_Retail_Sale__c/fields/BatteryCost__c.field-meta.xml
<CustomField>
    <fullName>BatteryCost__c</fullName>
    <label>Cranking Battery Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Boat_Sample_Retail_Sale__c/fields/Boat__c.field-meta.xml
<CustomField>
    <fullName>Boat__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Boat</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Boat Sample Retail Sales</relationshipLabel>
    <relationshipName>Sample_Retail_Sales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Boat_Sample_Retail_Sale__c/fields/BoatShowDiscount__c.field-meta.xml
<CustomField>
    <fullName>BoatShowDiscount__c</fullName>
    <label>Legend Boat Show Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Boat_Sample_Retail_Sale__c/fields/MercuryEngineRebate__c.field-meta.xml
<CustomField>
    <fullName>MercuryEngineRebate__c</fullName>
    <label>Mercury Boat Show Loose Engine Rebate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Boat_Sample_Retail_Sale__c/fields/PropCost__c.field-meta.xml
<CustomField>
    <fullName>PropCost__c</fullName>
    <label>Prop Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Pricebook2/recordTypes/Factory.recordType-meta.xml
<RecordType>
    <fullName>Factory</fullName>
    <active>true</active>
    <description>Price book used for Factory Store Pricing</description>
    <label>Factory</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Boat.recordType-meta.xml
<RecordType>
    <fullName>Boat</fullName>
    <active>true</active>
    <label>Boat</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Motor.recordType-meta.xml
<RecordType>
    <fullName>Motor</fullName>
    <active>true</active>
    <description>Outboard Motors</description>
    <label>Motor</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Trailer.recordType-meta.xml
<RecordType>
    <fullName>Trailer</fullName>
    <active>true</active>
    <description>Boat trailer</description>
    <label>Trailer</label>
</RecordType>

force-app/main/default/classes/BoatSampleRetailSale_Ext_Test.cls
@isTest(seeAllData = true)
public with sharing class BoatSampleRetailSale_Ext_Test {

  static Product2 boat;
  static Boat_Sample_Retail_Sale__c srs;
  static BoatSampleRetailSale_Ext ext;

  static {
    BoatTestFactory factory = new BoatTestFactory();
    Pricebook2 pb =  new Pricebook2( Name = 'Test PB 1', isActive = true);
    insert pb;
    boat = factory.insertFullTestBoats(1, pb, 'Pontoon')[0];
    srs = new Boat_Sample_Retail_Sale__c(Boat__c = boat.Id);
    ext = new BoatSampleRetailSale_Ext( new ApexPages.StandardController(srs) );
  }

  /*
    FROM BoatTestFactory.insertFullTestBoats() we get...
    9 motor upgrades
    9 trailer upgrades
    9 trolling motor upgrades
    15 options > 5 families X 3 options per family
    1 Service Contract Option
    -- 43 total options
  */

  @isTest static void constructor_test()
  {
    System.assertEquals( null, ext.recordId );
    System.assertEquals( srs, ext.record );
    System.assertEquals( 0, ext.exampleProducts.size() );
    System.assertEquals( 0, ext.exampleProductsToDelete.size() );
    System.assertEquals( 43, ext.resultOptionsMap.size() );
    System.assertEquals( 12, ext.fieldList().size() );
  }

  @isTest static void productSearch_test()
  {
    PageReference pageRef = Page.BoatSampleRetailSale_Form;
    //BoatTestFactory uses the first 5 picklist values in family
    List<String> fams = LGND_Utilities.getPicklistValues('Product2', 'Family');
    pageRef.getParameters().put('qString', fams[0]);
    Test.setCurrentPage(pageRef);

    ext.productSearch();

    System.assertEquals( 3, ext.resultOptionsMap.size() );
  }

  @isTest static void getResultOptionsTest()
  {
    System.assertEquals( 43, ext.getResultOptions().size() );
  }

  @isTest static void select_and_remove_Product_test()
  {
    Id poId = ext.getResultOptions()[0].Id;
    PageReference pageRef = Page.BoatSampleRetailSale_Form;
    pageRef.getParameters().put('product_option_id', poId);
    Test.setCurrentPage(pageRef);
    ext.selectProduct();

    System.assertEquals(1, ext.exampleProducts.size() );
    System.assertEquals( 42, ext.getResultOptions().size() );

    ext.removeProduct();

    System.assertEquals(0, ext.exampleProducts.size() );
    System.assertEquals( 43, ext.getResultOptions().size() );
  }

  @isTest static void save_test()
  {
    ext.record.BatteryCost__c = 100;
    ext.record.BoatShowDiscount__c = 100;
    ext.record.MercuryEngineRebate__c = 100;
    ext.record.PropCost__c = 100;
    Id poId = ext.getResultOptions()[0].Id;
    PageReference pageRef = Page.BoatSampleRetailSale_Form;
    pageRef.getParameters().put('product_option_id', poId);
    Test.setCurrentPage(pageRef);
    ext.selectProduct();
    ext.save();
    ext = new BoatSampleRetailSale_Ext( new ApexPages.StandardController(srs) );

    System.assert( ext.record.Id != null);
    System.assertEquals( 100, ext.record.BatteryCost__c );
    System.assertEquals(1, ext.exampleProducts.size() );
    System.assertEquals( 42, ext.getResultOptions().size() );

    ext.removeProduct();

    System.assertEquals(0, ext.exampleProducts.size() );
    System.assertEquals( 43, ext.getResultOptions().size() );
    System.assertEquals( 1, ext.exampleProductsToDelete.size() );

    ext.save();

    ext = new BoatSampleRetailSale_Ext( new ApexPages.StandardController(srs) );

    System.assertEquals(0, ext.exampleProducts.size() );
    System.assertEquals( 43, ext.getResultOptions().size() );
  }


}