force-app/main/default/objects/Square_Setting__mdt/Square_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Contains Setting related to Square Payment API</description>
    <label>Square Setting</label>
    <pluralLabel>Square Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Square_Setting__mdt/fields/ApplicationId__c.field-meta.xml
<CustomField>
    <fullName>ApplicationId__c</fullName>
    <description>Square Application Id</description>
    <inlineHelpText>Square Application Id</inlineHelpText>
    <label>Application Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Square_Setting__mdt/fields/AuthToken__c.field-meta.xml
<CustomField>
    <fullName>AuthToken__c</fullName>
    <description>Square Auth Token</description>
    <label>Auth Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Square_Setting__mdt/fields/IsSandbox__c.field-meta.xml
<CustomField>
    <fullName>IsSandbox__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If is true uses Squares Sandbox details</description>
    <label>Is Sandbox</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/Square_Setting__mdt/fields/LocationId__c.field-meta.xml
<CustomField>
    <fullName>LocationId__c</fullName>
    <label>Location Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Square_Setting__mdt/fields/Payment_Form_JS__c.field-meta.xml
<CustomField>
    <fullName>Payment_Form_JS__c</fullName>
    <description>The square payment form Javascript URL</description>
    <label>Payment_Form_JS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Square_Setting__mdt/fields/PaymentEndpoint__c.field-meta.xml
<CustomField>
    <fullName>PaymentEndpoint__c</fullName>
    <description>The Square API Payment endpoint</description>
    <label>Payment Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Square_Setting__mdt/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>The Square Version</description>
    <label>Version</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/classes/SquarePaymentForm_Controller_T.cls
/**
 * Created by dave on 2020-05-14.
 */

@IsTest
private class SquarePaymentForm_Controller_T {
  static final Boolean runningInASandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;

  @testSetup
  static void dataSetup() {
    new Factory_TestData();
    Factory_CustomSettings.setupInventorySettings();
  }

  public class SquareSuccessResponse implements HttpCalloutMock {
    public HTTPResponse respond(HTTPRequest req) {
      String resString = '{"payment":{';
      resString += '"id":"6aVfIp7gEaxzracrrrZPexample","created_at":"2019-07-14T02:51:35.984Z","updated_at":"2019-07-14T02:51:36.701Z",';
      resString += '"amount_money":{"amount":1000,"currency":"CAD"},';
      resString += '"status":"COMPLETED", "source_type":"CARD", "card_details":{';
      resString += ' "status":"CAPTURED","card":{';
      resString += '"card_brand":"MASTERCARD","last_4":"5809","exp_month":9,"exp_year":2022,"fingerprint":"sq-1-..."},';
      resString += '"entry_method":"KEYED","cvv_status":"CVV_ACCEPTED","avs_status":"AVS_ACCEPTED","auth_result_code":"01721P"},';
      resString += ' "location_id":"X9XWRESTK1CZ1","order_id":"jQa7fkUAAaGPFqg251PKrVexample",';
      resString += '"total_money":{"amount":1000,"currency":"CAD"}}}';
      HttpResponse res = new HttpResponse();
      res.setHeader('Content-Type', 'application/json');
      res.setBody(resString);
      res.setStatusCode(200);
      return res;
    }
  }

  @IsTest
  static void postToSquare_Test() {
    Test.setMock(HttpCalloutMock.class, new SquareSuccessResponse());
    Test.startTest();
    String resultJSON = SquarePaymentForm_Controller.postToSquare(1000, 'recordId', 'hfjsghfs87fsdgj');
    Test.stopTest();
    SquareProcessor.PaymentResponse result = (SquareProcessor.PaymentResponse) JSON.deserialize(
      resultJSON,
      SquareProcessor.PaymentResponse.class
    );

    System.assertEquals(1000, result.payment.amount_money.amount);
    System.assertEquals('COMPLETED', result.payment.status);
  }

  @IsTest
  static void getter_Tests() {
    Square_Setting__mdt settings = [
      SELECT ApplicationId__c, AuthToken__c, LocationId__c, Version__c, PaymentEndpoint__c, Payment_Form_JS__c
      FROM Square_Setting__mdt
      WHERE IsSandbox__c = :runningInASandbox
    ];
    SquarePaymentForm_Controller ctr = new SquarePaymentForm_Controller();

    System.assertEquals(settings.ApplicationId__c, ctr.getApplicationId());
    System.assertEquals(settings.Payment_Form_JS__c, ctr.getPaymentFormJsUrl());
    System.assertEquals(settings.LocationId__c, ctr.getLocationId());
  }
}