src/Base/main/default/objects/Product_Fee_Map__c/Product_Fee_Map__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <displayFormat>PFM-{0000}</displayFormat>
        <label>Product_Fee_Map Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Product_Fee_Map__c/fields/Fee_Product__c.field-meta.xml
<CustomField>
    <fullName>Fee_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Actual Fee Product</description>
    <label>Fee_Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Fees</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Fee_Product_Maps</relationshipLabel>
    <relationshipName>Fee_Product_Maps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Fee_Map__c/fields/Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Product the Fee is being assigned to.</description>
    <label>Parent Product</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.RecordType.Name</field>
            <operation>equals</operation>
            <value>Fees</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Fee Products</relationshipLabel>
    <relationshipName>Parent_Product_Fee_Maps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductFeeMap_Selector.cls
/**
 * Created by dave on 2020-05-07.
 */

public with sharing class ProductFeeMap_Selector extends Application_Selector
{

  public ProductFeeMap_Selector()
  {
    this.sObjectName = 'Product_Fee_Map__c';
    this.fields = new List<String>{
      'Fee_Product__c',
      'Parent_Product__c'
    };
  }

  public static List<Product_Fee_Map__c> allProductFeeMapsByParentProductId( Set<Id> parentProductIds )
  {
    ProductFeeMap_Selector selector = new ProductFeeMap_Selector();
    selector.addWhere( whereInClauseBuilder( 'Parent_Product__c', parentProductIds ) );
    return (List<Product_Fee_Map__c>)selector.query();
  }
}