force-app/main/default/objects/Product2/fields/AcctSeed__Expense_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Expense_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Balance Sheet, Revenue, Expense</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Products (Expense GL Account)</relationshipLabel>
    <relationshipName>Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeed__Inventory_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Inventory_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Balance Sheet, Revenue, Expense</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Products (Inventory GL Account)</relationshipLabel>
    <relationshipName>Products2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeed__Inventory_Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Inventory_Type__c</fullName>
    <label>Inventory Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchased</fullName>
            </value>
            <value>
                <fullName>Manufactured</fullName>
            </value>
            <value>
                <fullName>Kit</fullName>
            </value>
            <value>
                <fullName>Raw Material</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeed__Revenue_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Revenue_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Balance Sheet, Revenue, Expense</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Allocated__c.field-meta.xml
<CustomField>
    <fullName>Allocated__c</fullName>
    <description>The number of inventory items that have been allocated to customer orders</description>
    <inlineHelpText>The number of inventory items that are needed to fill customer orders</inlineHelpText>
    <label>Allocated</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Availability_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Availability_Percentage__c</fullName>
    <label>Availability Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Landed_Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>Landed_Unit_Cost__c</fullName>
    <label>Landed Unit Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Product2/fields/Partner_Price__c.field-meta.xml
<CustomField>
    <fullName>Partner_Price__c</fullName>
    <label>Factory Store Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Product2/fields/Parts_Count__c.field-meta.xml
<CustomField>
    <fullName>Parts_Count__c</fullName>
    <label>Parts Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Product2/fields/Sizes__c.field-meta.xml
<CustomField>
    <fullName>Sizes__c</fullName>
    <description>Sizes for clothing</description>
    <label>Sizes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
                <default>true</default>
                <label>Small</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
            <value>
                <fullName>Extra Large</fullName>
            </value>
            <value>
                <fullName>XXL</fullName>
            </value>
            <value>
                <fullName>XXXL</fullName>
            </value>
            <value>
                <fullName>XXXXL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Product2/recordTypes/Insurance.recordType-meta.xml
<RecordType>
    <fullName>Insurance</fullName>
    <active>true</active>
    <label>Insurance</label>
</RecordType>

src/Automation/main/default/classes/Product/Tests/TA_Product_Legacy_T.cls
@isTest
public class TA_Product_Legacy_T {

    final static String RECORDTYPE = 'Insurance';
    final static String FAMILY = 'Insurance';
    static List<Product2> products;
    private static List<Product2> getData(){
        return [Select
                id,
                Allocated__c,
                Availability_Percentage__c,
                Sizes__c,
                Parts_Count__c,
                Landed_Unit_Cost__c,
                Partner_Price__c,
                AcctSeed__Inventory_GL_Account__c,
                AcctSeed__Expense_GL_Account__c,
                AcctSeed__Revenue_GL_Account__c,
                AcctSeed__Inventory_Type__c,
                RecordTypeId,
                Family
        From Product2
        ];
    }
    @TestSetup
    static void testData(){
        new Factory_TestData();
        Factory_CustomSettings.setupInventorySettings();
        Factory_AccountPayable.insertAccountPayable(5);
        new Factory_AccountingVariables();
        List<Product2> serializedProducts = Factory_Product.createSerializedProducts(RECORDTYPE, FAMILY, 10);
    }

    @IsTest
    static void beforeInsertTest() {
        Test.startTest();
        products = getData();
        new TA_Product_Legacy().beforeInsert(products);
        Test.stopTest();
    }
    @IsTest
    static void afterInsertTest() {
        Test.startTest();
        new TA_Product_Legacy().afterInsert(getData());
        Test.stopTest();
    }
    @IsTest
    static void afterUpdateTest() {
        Test.startTest();
        products = getData();
        Product2 productClone =products[0].clone(true, true, true, true);
        new TA_Product_Legacy().afterUpdate(new List<Product2>{products[0]},new List<Product2>{productClone});
        Test.stopTest();
    }
    @IsTest
    static void beforeUpdateTest() {
        Test.startTest();
        products = getData();
        Product2 productClone =products[0].clone(true, true, true, true);
        new TA_Product_Legacy().beforeUpdate(new List<Product2>{products[0]},new List<Product2>{productClone});
        Test.stopTest();
    }
    @IsTest
    static void beforeDeleteTest() {
        Test.startTest();
        new TA_Product_Legacy().beforeDelete(getData());
        Test.stopTest();
    }
    @IsTest
    static void afterDeleteTest() {
        Test.startTest();
        new TA_Product_Legacy().afterDelete(getData());
        Test.stopTest();
    }


}