force-app/main/default/objects/Account/fields/AcctSeed__Accounting_Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Accounting_Type__c</fullName>
    <inlineHelpText>Used in filtered lookups for Accounts Payable and Billing screens to limit selection of Accounts to those marked as Customers or Vendors for use by Accounting.</inlineHelpText>
    <label>Accounting Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Customer and Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Legend_Settings__c/Legend_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Legend Settings</label>
</CustomObject>

force-app/main/default/objects/Legend_Settings__c/fields/Default_Retail_Pricebook__c.field-meta.xml
<CustomField>
    <fullName>Default_Retail_Pricebook__c</fullName>
    <label>Default Retail Pricebook</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Legend_Settings__c/fields/FederalTaxRate__c.field-meta.xml
<CustomField>
    <fullName>FederalTaxRate__c</fullName>
    <label>FederalTaxRate</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

src/Base/main/default/objects/Legend_Settings__c/fields/TaxRate__c.field-meta.xml
<CustomField>
    <fullName>TaxRate__c</fullName>
    <defaultValue>13</defaultValue>
    <label>TaxRate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FederalTaxAmount__c.field-meta.xml
<CustomField>
    <fullName>FederalTaxAmount__c</fullName>
    <formula>Taxable_Total__c * $Setup.Legend_Settings__c.FederalTaxRate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FederalTaxAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <displayFormat>INV-{00000}</displayFormat>
    <label>InvoiceNumber</label>
    <type>AutoNumber</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <description>Indicates whether the customer is financing or paying cash for the products</description>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>American Express</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
                <default>true</default>
                <label>Finance</label>
            </value>
            <value>
                <fullName>Gift Card</fullName>
            </value>
            <value>
                <fullName>Mastercard</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ProvincialTaxTotal__c.field-meta.xml
<CustomField>
    <fullName>ProvincialTaxTotal__c</fullName>
    <formula>Taxable_Total__c  *  ProvincialTaxRate__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ProvincialTaxTotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Sales_Department__c.field-meta.xml
<CustomField>
    <fullName>Sales_Department__c</fullName>
    <description>Department which sales should get accounted to</description>
    <label>Sales Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Barrie</fullName>
            </value>
            <value>
                <fullName>Whitefish</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
            <value>
                <fullName>Montreal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TaxableTotal_LineItems__c.field-meta.xml
<CustomField>
    <fullName>TaxableTotal_LineItems__c</fullName>
    <description>Taxable total of all the Product Line Items</description>
    <label>TaxableTotal_LineItems</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/taxationProvince__c.field-meta.xml
<CustomField>
    <fullName>taxationProvince__c</fullName>
    <label>TaxationProvince</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>British Columbia</fullName>
            </value>
            <value>
                <fullName>Manitoba</fullName>
            </value>
            <value>
                <fullName>New Brunswick</fullName>
            </value>
            <value>
                <fullName>Newfoundland and Labrador</fullName>
            </value>
            <value>
                <fullName>Northwest Territories</fullName>
            </value>
            <value>
                <fullName>Nova Scotia</fullName>
            </value>
            <value>
                <fullName>Nunavut</fullName>
            </value>
            <value>
                <fullName>Ontario</fullName>
            </value>
            <value>
                <fullName>Prince Edward Island</fullName>
            </value>
            <value>
                <fullName>Quebec</fullName>
            </value>
            <value>
                <fullName>Saskatchewan</fullName>
            </value>
            <value>
                <fullName>Yukon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TaxOverRide__c.field-meta.xml
<CustomField>
    <fullName>TaxOverRide__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TaxOverRide</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TaxOverRideRate__c.field-meta.xml
<CustomField>
    <fullName>TaxOverRideRate__c</fullName>
    <label>TaxOverRideRate</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TaxRate__c.field-meta.xml
<CustomField>
    <fullName>TaxRate__c</fullName>
    <label>TaxRate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>Amount  +  TotalTaxes__c - Trade_In_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalTaxes__c.field-meta.xml
<CustomField>
    <fullName>TotalTaxes__c</fullName>
    <formula>Tax_Amount_Federal__c +  Tax_Amount_Provincial__c + Tax_Amount_Retail__c</formula>
    <label>Total Taxes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalTaxRate__c.field-meta.xml
<CustomField>
    <fullName>TotalTaxRate__c</fullName>
    <formula>Tax_Rate_Federal__c  +  Tax_Rate_Provincial__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TotalTaxRate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Retail.recordType-meta.xml
<RecordType>
    <fullName>Retail</fullName>
    <active>true</active>
    <businessProcess>Retail Sales Process</businessProcess>
    <description>Retail Sale</description>
    <label>Retail</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/TotalTaxes__c.field-meta.xml
<CustomField>
    <fullName>TotalTaxes__c</fullName>
    <formula>IF( PricebookEntry.Product2.Taxable__c,
  IF( IsInsurance__c,
    IF( ISPICKVAL(Opportunity.taxationProvince__c , &apos;Quebec&apos;), 0,  TotalPrice *  Opportunity.ProvincialTaxRate__c ),
    TotalPrice * ( Opportunity.ProvincialTaxRate__c +   $Setup.Legend_Settings__c.FederalTaxRate__c ) ),
  0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TotalTaxes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeed__Accounting_Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Accounting_Type__c</fullName>
    <label>Tax Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Taxable Product</fullName>
                <default>true</default>
                <label>Taxable Product</label>
            </value>
            <value>
                <fullName>Tax Exempt Product</fullName>
            </value>
            <value>
                <fullName>Tax Rate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Description_FR__c.field-meta.xml
<CustomField>
    <fullName>Description_FR__c</fullName>
    <label>Description_FR</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/Base/main/default/objects/Product2/fields/Name_FR__c.field-meta.xml
<CustomField>
    <fullName>Name_FR__c</fullName>
    <label>French Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Product2/recordTypes/Fees.recordType-meta.xml
<RecordType>
    <fullName>Fees</fullName>
    <active>true</active>
    <description>Fees</description>
    <label>Fees</label>
</RecordType>

src/Base/main/default/objects/Product_Fee_Amount__c/Product_Fee_Amount__c.object-meta.xml
<CustomObject>
    <label>Product Fee Amount</label>
    <nameField>
        <displayFormat>PFA-{0000}</displayFormat>
        <label>Product Fee Amount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Fee Amounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Fee_Amount__c/fields/Fee_Product__c.field-meta.xml
<CustomField>
    <fullName>Fee_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Fee Amounts</relationshipLabel>
    <relationshipName>Product_Fee_Amounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Fee_Amount__c/fields/Province__c.field-meta.xml
<CustomField>
    <fullName>Province__c</fullName>
    <label>Province</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alberta</fullName>
            </value>
            <value>
                <fullName>British Columbia</fullName>
            </value>
            <value>
                <fullName>Manitoba</fullName>
            </value>
            <value>
                <fullName>New Brunswick</fullName>
            </value>
            <value>
                <fullName>Newfoundland and Labrador</fullName>
            </value>
            <value>
                <fullName>Northwest Territories</fullName>
            </value>
            <value>
                <fullName>Nova Scotia</fullName>
            </value>
            <value>
                <fullName>Nunavut</fullName>
            </value>
            <value>
                <fullName>Ontario</fullName>
            </value>
            <value>
                <fullName>Price Edward Island</fullName>
            </value>
            <value>
                <fullName>Quebec</fullName>
            </value>
            <value>
                <fullName>Saskatchewan</fullName>
            </value>
            <value>
                <fullName>Yukon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Product_Option__c/Product_Option__c.object-meta.xml
<CustomObject>
    <label>Product Option</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Product Option ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Option__c/fields/Maximum__c.field-meta.xml
<CustomField>
    <fullName>Maximum__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Maximum</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Product_Option__c/fields/Standard__c.field-meta.xml
<CustomField>
    <fullName>Standard__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Standard</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Product_Option__c/fields/To_Product__c.field-meta.xml
<CustomField>
    <fullName>To_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is generally the &apos;boat&apos; product an optional product is getting attached to</description>
    <label>To Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Available Options</relationshipLabel>
    <relationshipName>To_Product_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/User/fields/Sales_Department__c.field-meta.xml
<CustomField>
    <fullName>Sales_Department__c</fullName>
    <label>Sales_Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Barrie</fullName>
            </value>
            <value>
                <fullName>Whitefish</fullName>
            </value>
            <value>
                <fullName>Montreal</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
            <value>
                <fullName>Boat Better</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/classes/RetailCounterSaleController.cls
global with sharing class RetailCounterSaleController {
    global Decimal fedTaxRate {
    get {
      return Legend_Settings__c.getOrgDefaults().FederalTaxRate__c;
      }
    private set;
  }
  global class MyException extends Exception {}

  global class LineItemWrapper {

    public String id { get; set; }
    public String lineItemId { get; set; }
    public String opportunityId{ get; set; }
    public String productRecordType { get; set; }
    public String productFamily { get; set; }
    public Decimal quantity { get; set; }
    public Decimal listPrice { get; set; }
    public Decimal unitPrice { get; set; }
    public String pricebookEntryId { get; set; }
    public String description { get; set; }
    public String name { get; set; }
    public String nameFR { get; set; }
    public String descriptionFR { get; set; }
    public String productCode { get; set; }
    public Boolean isTaxableProduct { get; set; }
    public Boolean isKit { get; set; }
    public List<Product_Option__c> kitComponents { get; set; }

    global LineItemWrapper(Product2 prod, OpportunityLineItem oli)
    {
      this.isKit = false;
      this.id = prod.Id;
      this.lineItemId = oli.Id;
      this.opportunityId = oli.OpportunityId;
      this.quantity = oli.Quantity;
      this.listPrice = oli.PricebookEntry.UnitPrice;
      this.unitPrice = oli.UnitPrice;
      this.pricebookEntryId = oli.PricebookEntryId;
      this.name = oli.Description;
      this.nameFR = oli.PricebookEntry.Product2.Name_FR__c;
      this.productCode = prod.ProductCode == null ? '-' : prod.ProductCode;
      this.productRecordType = prod.recordType.Name;
      this.isTaxableProduct =  oli.PricebookEntry.Product2.AcctSeed__Accounting_Type__c == 'Taxable Product' ? true : false;
      processKitComponents(prod.To_Product_Options__r);
    }

    global LineItemWrapper(Product_Fee_Amount__c pfa, Id pbEntryId)
    {
      this.Id = pfa.Fee_Product__c;
      this.isKit = false;
      this.productRecordType = 'Fees';
      this.quantity = 1;
      this.name = pfa.Fee_Product__r.Name;
      this.nameFR = pfa.Fee_Product__r.Name_FR__c;
      this.description = pfa.Fee_Product__r.Description;
      this.descriptionFR = pfa.Fee_Product__r.Description_FR__c;
      this.productFamily = pfa.Fee_Product__r.Family;
      this.productCode = pfa.Fee_Product__r.ProductCode;
      this.isTaxableProduct = pfa.Fee_Product__r.AcctSeed__Accounting_Type__c == 'Taxable Product' ? true : false;
      this.pricebookEntryId = pbEntryId;
      this.listPrice = pfa.Amount__c;
      this.unitPrice = pfa.Amount__c;
    }

    global LineItemWrapper(Product2 prod)
    {
      this.Id = prod.Id;
      this.isKit = false;
      this.productCode = prod.ProductCode == null ? '-' : prod.ProductCode;
      this.quantity = 1;
      this.productRecordType = prod.RecordType.Name;
      this.productFamily = prod.Family;
      this.name = prod.Name;
      this.nameFR = prod.Name_FR__c;
      this.description = prod.Description;
      this.descriptionFR = prod.Description_FR__c;
      this.isTaxableProduct =  prod.AcctSeed__Accounting_Type__c == 'Taxable Product' ? true : false;
      if(prod.pricebookEntries.size() > 0)
      {
        this.listPrice = prod.pricebookEntries[0].UnitPrice;
        this.unitPrice = prod.pricebookEntries[0].UnitPrice;
        this.pricebookEntryId = prod.pricebookEntries[0].Id;
      }
      processKitComponents(prod.To_Product_Options__r);
    }

    private void processKitComponents(List<Product_Option__c> components)
    {
      if( components.size() > 0 )
      {
        this.kitComponents = new List<Product_Option__c>();
        for( Product_Option__c po : components )
        {
          if( po.Standard__c > 0 && po.Standard__c == po.Maximum__c )
          {
            this.kitComponents.add(po);
          }
        }
        if( this.kitComponents.size() > 0 )
        {
          this.isKit = true;
        }
        else
        {
          this.kitComponents = null;
        }
      }
    }

  }

  static Id personTypeAccountId;
  static Id retailCounterSaleOppTypeId;
  static Id defaultRetailPriceBookId;

  static {
    personTypeAccountId = LGND_Utilities.recordTypeIdFromName('Account', 'Person Account');
    retailCounterSaleOppTypeId = LGND_Utilities.recordTypeIdFromName('Opportunity', 'Retail Counter Sale');
    defaultRetailPriceBookId = Legend_Settings__c.getOrgDefaults().Default_Retail_Pricebook__c;
  }

  /* we need to run the init method in OppId setter method as this
     is called as a component controller and the "assignTo" setter
     method from the component runs AFTER the class constructor
     so oppId is null when the constructor is fired
  */
  public String oppId {
    get {
      return oppId;
    }
    set {
      oppId = value;
      init();
    }
  }
  public Opportunity opp { get; set; }
  public List<LineItemWrapper> lineItems { get; set; }
  public LGND_Store lgnd_store { get; set; }
  public Decimal currentTaxRate { get; set; }
  public TaxRate__C provTaxRate { get; set; }

	global RetailCounterSaleController() {

	}

  global RetailCounterSaleController(ApexPages.StandardController std) {
    oppId = std.getId();
  }

  public void init() {
    User currentUser = [SELECT Id, Name, Sales_Department__c
                        FROM User
                        WHERE Id = :UserInfo.getUserId()];
    if( oppId != null )
    {
      this.opp = [SELECT Id,
                         CreatedDate,
                         Pricebook2Id,
                         Payment_Method__c,
                         Amount,
                         TaxOverRideRate__c,
                         TaxOverRide__c,
                         TaxationProvince__c,
                         TotalTaxRate__c,
                         TotalTaxes__c,
                         Total_Amount__c,
                         TaxableTotal_LineItems__c,
                         FederalTaxAmount__c,
                         ProvincialTaxTotal__c,
                         AccountId,
                         Owner.FirstName,
                         Owner.LastName,
                         Owner.Sales_Department__c,
                         ContactEmail__c,
                         CloseDate,
                         InvoiceNumber__c,
                         Account.Phone,
                         Account.PersonHomePhone,
                         Account.PersonMobilePhone,
                         Account.FirstName,
                         Account.LastName,
                         Account.PersonEmail,
                         Pricebook2.Id,
                         Account.Name,
                         Account.BillingCity,
                         Account.BillingState,
                         Account.BillingStateCode,
                         Account.BillingStreet,
                         Account.BillingCountry,
                         Account.BillingCountryCode,
                         Account.BillingPostalCode,
        (SELECT Id,
                PricebookEntryId,
                Description,
                OpportunityId,
                Quantity,
                UnitPrice,
                PricebookEntry.Product2Id,
                PricebookEntry.UnitPrice,
                PricebookEntry.Product2.Name_FR__c,
                PricebookEntry.Product2.Description_FR__c,
                PricebookEntry.Product2.AcctSeed__Accounting_Type__c
          FROM OpportunityLineItems)
        FROM Opportunity
        WHERE Id = :oppId];
      if( opp.OpportunityLineItems.size() > 0 )
      {
        lineItems = buildLineItems(opp.OpportunityLineItems, opp.Pricebook2Id );
      }
      lgnd_store = new LGND_Store( this.opp.Owner.Sales_Department__c);
    }
    else {
      lgnd_store = new LGND_Store(currentUser.Sales_Department__c);
      opp = new Opportunity(Pricebook2Id = defaultRetailPriceBookId,
                                    RecordTypeId = retailCounterSaleOppTypeId,
                                    TaxationProvince__c = lgnd_store.Province,
                                    TaxOverRide__c = false,
                                    Account = new Account(RecordTypeId = personTypeAccountId,
                                                          BillingCountryCode = '',
                                                          BillingStateCode = '')
                                    );
    }
    provTaxRate = TaxRate__c.getAll().get(opp.taxationProvince__c);
    //find current Tax Rate
    currentTaxRate = opp.TaxOverRide__c == true ?
      opp.TaxOverRideRate__c :
      TaxRate__c.getAll().get(opp.taxationProvince__c).ProvincialRate__c + fedTaxRate;
  }

  public String getOpportunityJSON(){
    if( opp == null){
      return null;
    }
    return JSON.serialize(opp);
  }

  public String getLineItemsJSON()
  {
    if( lineItems == null )
    {
      return null;
    }
    return JSON.serialize( lineItems );
  }

  public List<SelectOption> getProvinceOptions()
  {
    List<SelectOption> options = new List<SelectOption>();
    options.add( new SelectOption('', '-- Select --') );
    for( String prov : TaxRate__c.getAll().keySet() )
    {
      options.add( new SelectOption(prov, prov) );
    }
    return options;
  }

  public String getProvincialTaxRates()
  {
    Map<String, String> result = new Map<String, String>();
    Decimal total;
    for(String prov : taxRate__c.getAll().keySet() )
    {
      total = prov == 'Tax Exempt' ? 0 : TaxRate__c.getAll().get(prov).ProvincialRate__c + fedTaxRate;
      result.put( prov, String.valueOf(total) );
    }
    return JSON.serialize(result);
  }

  public PageReference getCancelURL(){
    if( opp == null || opp.Id == null){
      return new PageReference('/');
    }
    return new PageReference('/'+opp.Id);
  }

  public List<Pricebook2> getPriceBooks(){
    return [SELECT Id, Name FROM Pricebook2 WHERE IsStandard = false AND IsActive = true ORDER BY Name DESC];
  }

  /*
    @params String searchString = the string to query for
            String pricebookId = ID of the pricebook we are working with

    returns List<Product2> - where Name or Product code contains the passed in string
                             and there is an entry in the pricebook we are working with

    used on a form with javascript remoting

  */
  @RemoteAction
  global static List<LineItemWrapper> productSearch(String searchString, String pricebookId) {
    List<LineItemWrapper> result = new List<LineItemWrapper>();
    Id feeRT = LGND_Utilities.recordTypeIdFromName('Product2', 'Fees');
    String s = '%' + searchString + '%';
    List<Product2> products = [SELECT Id, Name, Name_FR__c, ProductCode, Description, Description_FR__c, Family, RecordType.Name, AcctSeed__Accounting_Type__c, AcctSeed__Inventory_Type__c,
            (SELECT Id,
                    Standard__c,
                    Maximum__c,
                    From_Product__r.Id,
                    From_Product__r.Name,
                    From_Product__r.Name_FR__c,
                    From_Product__r.RecordType.Name,
                    From_Product__r.Family
             FROM To_Product_Options__r
             ORDER BY From_Product__r.Name),
            (SELECT Id, UnitPrice
              FROM PricebookEntries
              WHERE Pricebook2Id = :pricebookId
              AND isActive = true
              AND UnitPrice != null
              AND UnitPrice > 0
              LIMIT 1)
            FROM Product2
            WHERE ( Name LIKE :s OR ProductCode LIKE :s OR IEM_Unique_Part_Number__c LIKE :s)
            AND isActive = true
            AND RecordTypeId <> :feeRT
            AND Id IN (SELECT Product2Id FROM PricebookEntry WHERE Product2Id != '' AND Pricebook2Id =:pricebookId
              AND isActive = true
              AND UnitPrice != null
              AND UnitPrice > 0)];
    for(Product2 p : products)
    {
      result.add( new LineItemWrapper(p) );
    }
    return result;
  }

  @RemoteAction
  global static List<Account> accountSearch(String searchString){
    String s = '%' + searchString + '%';
    System.debug('****************** ' + s);
    return [SELECT Id,
                   Name,
                   PersonEmail,
                   FirstName,
                   LastName,
                   Phone,
                   PersonHomePhone,
                   PersonMobilePhone,
                   BillingCity,
                   BillingCountryCode,
                   BillingStreet,
                   BillingStateCode,
                   BillingPostalCode
            FROM Account
            WHERE ( Name LIKE :s OR PersonHomePhone Like :s OR PersonMobilePhone Like :s )
            AND RecordTypeId = :personTypeAccountId];
  }

  @RemoteAction
  global static Map<String, Map<String, LineItemWrapper>> fetchFees(String pricebookId)
  {
    Map<String, Map<String, LineItemWrapper>> result = new Map<String, Map<String, LineItemWrapper>>();
    for( String prov : TaxRate__c.getAll().keySet() )
    {
      result.put(prov, new Map<String, LineItemWrapper>() );
    }
    Id feeRT = LGND_Utilities.recordTypeIdFromName('Product2', 'Fees');
    Set<Id> prodIds = new Set<Id>();
    List<Product_Fee_Amount__c> feeAmounts = [SELECT Id,
                                                     Province__c,
                                                     Amount__c,
                                                     Fee_Product__c,
                                                     Fee_Product__r.Name,
                                                     Fee_Product__r.Name_FR__c,
                                                     Fee_Product__r.Description,
                                                     Fee_Product__r.Description_FR__c,
                                                     Fee_Product__r.ProductCode,
                                                     Fee_Product__r.Family,
                                                     Fee_Product__r.AcctSeed__Accounting_Type__c,
                                                     Fee_Product__r.AcctSeed__Inventory_Type__c
                                              FROM Product_Fee_Amount__c
                                              WHERE Price_Book__c = :pricebookId];
    for( Product_Fee_Amount__c pfa : feeAmounts )
    {
      prodIds .add( pfa.Fee_Product__c);
    }
    Map<Id, Id> prodPbMap = new Map<Id, Id>();
    for( PricebookEntry pbe : [SELECT Id, Product2Id FROM PricebookEntry WHERE Pricebook2Id = : pricebookId AND Product2Id IN : prodIds] )
    {
      prodPbMap.put( pbe.Product2Id, pbe.Id );
    }
    for( Product_Fee_Amount__c pfa : feeAmounts )
    {
      if( result.containsKey(pfa.Province__c) )
      {
        result.get(pfa.Province__c).put( pfa.Id, new LineItemWrapper(pfa, prodPbMap.get(pfa.Fee_Product__c) ) );
      }
    }
    return result;
  }


  @RemoteAction
  global static PageReference createSale(String accountData,
                                         String products,
                                         String oppDataJSON)
  {
    Account acct = (Account)JSON.deserializeStrict(accountData, Account.class);
    Map<String, String> oppData = (Map<String, String>)JSON.deserialize(oppDataJSON, Map<String,String>.class);
    List<OpportunityLineItem> lineItems = (List<OpportunityLineItem>)JSON.deserialize(products, List<OpportunityLineItem>.class);

    String stage;
    if( oppData.get('Payment_Method__c') == 'Pending' )
    {
      stage = 'Pending Pickup';
      //paymentMethod = null;
    }
    else
    {
      stage = 'Picked Up / Won';
    }
    //if there is no Id then we have a new record, but we have to figure out the Record Type Id
    if(acct.Id == null)
    {
      acct.RecordTypeId = personTypeAccountId;
    }

    try
    {
       upsert acct;
    }
    catch(Exception e)
    {
      throw new MyException( e.getMessage() );
      return null;
    }

    Opportunity opp;
    if( oppData.get('Id') == null ){
      opp = new Opportunity(
        Name = 'Counter Sale - ' + String.valueOf(Date.today()) + ' - ' + acct.LastName,
        RecordTypeId = retailCounterSaleOppTypeId,
        Payment_Method__c = oppData.get('Payment_Method__c'),
        TaxationProvince__c = oppData.get('TaxationProvince__c'),
        TaxOverRide__c = Boolean.valueOf(oppData.get('TaxOverRide__c')),
        TaxOverRideRate__c = oppData.get('TaxOverRide__c') == 'true' ?
                              Decimal.valueOf( oppData.get('TaxOverRideRate__c') ) :
                              null,
        CloseDate= Date.today(),
        StageName = stage,
        AccountId = acct.Id
      );
      try
      {
        insert opp;
        opp.pricebook2Id = oppData.get('Pricebook2Id');
        update opp;

        // Save the line items
        for( Integer i=0; i<lineItems.size();i++)
        {
          if( lineItems.get(i).Quantity > 0 )
          {
            if( lineItems.get(i).Id == null )
            {
              lineItems.get(i).OpportunityId = opp.Id;
            }
          }
          else
          {
            lineItems.remove(i);
          }
        }
        if( lineItems.size() > 0 )
        {
          try
          {
            upsert lineItems;
          }
          catch(Exception e)
          {
            throw new MyException( e.getMessage() );
            return null;
          }
        }
      }

      catch(Exception e)
      {
        throw new MyException( e.getMessage() );
        return null;
      }
      //CommissionRecord.createCounterSaleCommissionRecord(opp.Id);
    } // End of Saving new Opportunity
    else
    {
      opp = [SELECT Id, Payment_Method__c, Pricebook2Id,
             ( SELECT Id FROM OpportunityLineItems )
             FROM Opportunity
             WHERE Id = :oppData.get('Id')];
      Boolean pbChanged = false;

      if( opp.Payment_Method__c != oppData.get('Payment_Method__c') )
      {
        opp.Payment_Method__c = oppData.get('Payment_Method__c');
        opp.StageName = stage;
      }
      opp.TaxationProvince__c = oppData.get('TaxationProvince__c');
      opp.TaxOverRide__c = Boolean.valueOf(oppData.get('TaxOverRide__c'));
      opp.TaxOverRideRate__c = oppData.get('TaxOverRide__c') == 'true' ?
                            Decimal.valueOf( oppData.get('TaxOverRideRate__c') ) :
                            null;

      Set<String> oLineItemids = new Set<String>();

      if( oppData.get('Pricebook2Id') != opp.Pricebook2Id )
      // if there is a new pricebook we first need to delete the OpportunityLineItems
      {
        pbChanged = true;

        for(OpportunityLineItem oli : opp.OpportunityLineItems )
        {
          oLineItemids.add(oli.Id);
        }
        try
        {
          delete opp.OpportunityLineItems;
        }
        catch(Exception e)
        {
          throw new MyException( e.getMessage() );
          return null;
        }
        opp.Pricebook2Id = oppData.get('Pricebook2Id');

      }// endIf pricebook conflict

      //Update Opportunity
      try {
        update opp;
      }
      catch(Exception e){
        if( pbChanged == true )
        {
          List<OpportunityLineItem> olis = [SELECT Id
                                             FROM OpportunityLineItem
                                             WHERE OpportunityId = :oppData.get('Id')
                                             ALL ROWS];
          undelete olis;
        }
        throw new MyException( e.getMessage() );
        return null;
      }

      //Save The Line Items

      List<OpportunityLineItem> deletedLineItems = new List<OpportunityLineItem>();
      List<OpportunityLineItem> goodLineItems = new List<OpportunityLineItem>();

      for( Integer i=0; i<lineItems.size(); i++ ){
        System.debug('9999999 ' + lineItems.get(i) );
        if( lineItems.get(i).Quantity == 0.0 )
        {
          System.debug('this item ' + lineItems.get(i).Description + ' has quantity of zero');
          if( lineItems.get(i).Id != null && !oLineItemids.contains(lineItems.get(i).Id) )
          {
            System.debug('this item  ' + lineItems.get(i).Description + ' needs deleting');
            deletedLineItems.add(lineItems.get(i));
          }
          //lineItems.remove(i);
        }
        else
        {
          goodLineItems.add( lineItems.get(i) );
        }
      }

      for( OpportunityLineItem oli : goodLineItems )
      {
        if( oli.Id == null )
        {
          oli.OpportunityId = opp.Id;
        }
      }

      if( deletedLineItems.size() > 0 ){
        try
        {
          delete deletedLineItems;
        }
        catch(Exception e){
          List<OpportunityLineItem> olis = [SELECT Id
                                             FROM OpportunityLineItem
                                             WHERE OpportunityId = :oppData.get('Id')
                                             ALL ROWS];
          undelete olis;
          throw new MyException( 'Cause we already deleted them -- ' + e.getMessage() );
          return null;
        }
      }
      if( goodLineItems.size() > 0 )
      {
        System.debug('OPP LINE ITEMS = ' + goodLineItems);
        try
        {
          upsert goodLineItems;
        }
        catch(Exception e)
        {
          throw new MyException( ' We are failing at the end '  + e.getMessage() );
          return null;
        }
      }
      //CommissionRecord.updateCounterSaleCommisionRecord(opp.Id);
    }// End Updating an Opportunity

    PageReference view = Page.Opportunity_CounterSaleView;
    view.getParameters().put('id', opp.Id);
    return view;

  }

  private LineItemWrapper[] buildLineItems(OpportunityLineItem[] items, Id pbId)
  {
    LineItemWrapper[] result = new List<LineItemWrapper>();
    Set<Id> productIds = new Set<Id>();
    for( OpportunityLineItem oli : items )
    {
      productIds.add(oli.PricebookEntry.Product2Id);
    }
    Map<Id, Product2> prods = new Map<Id, Product2>([SELECT Id,
                               Name,
                               Name_FR__c,
                               Description,
                               Description_FR__c,
                               Family,
                               RecordType.Name,
                               ProductCode,
                               AcctSeed__Accounting_Type__c,
                               AcctSeed__Inventory_Type__c,
                        (SELECT Id,
                                Standard__c,
                                Maximum__c,
                                From_Product__r.Id,
                                From_Product__r.Name,
                                From_Product__r.Name_FR__c,
                                From_Product__r.RecordType.Name,
                                From_Product__r.ProductCode,
                                From_Product__r.Family
                         FROM To_Product_Options__r
                         ORDER BY From_Product__r.Name)
                        FROM Product2
                        WHERE Id IN :productIds ]);
    for( OpportunityLineItem oli : items )
    {
      result.add( new LineItemWrapper( prods.get(oli.PricebookEntry.Product2Id), oli) );
    }
    return result;
  }

}