force-app/main/default/objects/Account/fields/AcctSeed__Billing_Format__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Billing_Format__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Used to configure formatting and display of fields in Billing PDF. Overrides the default Billing Format defined in Accounting Settings.</inlineHelpText>
    <label>Billing Format</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Billing_Format__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Billing</value>
        </filterItems>
        <infoMessage>The Type must equal &quot;Billing&quot;</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Billing_Format__c</referenceTo>
    <relationshipLabel>Accounts (Billing Format)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <label>Dealer</label>
</RecordType>

force-app/main/default/objects/AcctSeed__Accounting_Period__c/AcctSeed__Accounting_Period__c.object-meta.xml
<CustomObject>
    <customHelpPage>AcctSeed__AccountingPeriodHelp</customHelpPage>
    <description>Used to capture all the financial activity that occurs during a specified time period. Accounting periods are typically defined to coincide with a calendar year month.</description>
    <label>Accounting  Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Accounting_Period__c/fields/AcctSeed__End_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__End_Date__c</fullName>
    <inlineHelpText>Accounting periods are typically used as months. This denotes the end of the period. Fiscal Months are supported. A period end date can not cross over into the start and end date range of another period.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Accounting_Period__c/fields/AcctSeed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Start_Date__c</fullName>
    <inlineHelpText>Accounting periods are typically used as months. This denotes the beginning of the period. Fiscal Months are supported. A period beginning date can not cross over into the start and end date range of another period.</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Accounting_Period__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>&quot;Open&quot; allows new transactions to be saved to this period. &quot;Closed&quot; prevents new records from being saved to this period.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/AcctSeed__Billing__c/AcctSeed__Billing__c.object-meta.xml
<CustomObject>
    <description>Used to document products or services related sales to a customer.</description>
    <label>Billing</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Billing Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Billing__c/fields/AcctSeed__Accounting_Period__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Accounting_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Used to specify accounting period for financial reporting. Accounting period must have a value of &quot;Open&quot; in order to be selected.</inlineHelpText>
    <label>Accounting  Period</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Period__c.AcctSeed__Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </filterItems>
        <infoMessage>The accounting period status must be open</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Period__c</referenceTo>
    <relationshipLabel>Billings</relationshipLabel>
    <relationshipName>Project_Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Billing__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>Used in approvals of billing records and therefore related detail lines. A value of &quot;Posted&quot; indicates the record is final and a debit and credit line have been entered into the transaction object for each billing line.</inlineHelpText>
    <label>Posting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
                <default>true</default>
                <label>In Process</label>
            </value>
            <value>
                <fullName>Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/AcctSeed__Cash_Receipt__c/AcctSeed__Cash_Receipt__c.object-meta.xml
<CustomObject>
    <description>Used to document the money received from a customer. Typically matched to billing invoices in the cash application process to denote satisfactory payment of billing invoice by customer.</description>
    <label>Cash Receipt</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Cash Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Cash_Receipt__c/fields/AcctSeed__Accounting_Period__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Accounting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Used to specify accounting period for financial reporting. Accounting period must have a value of Open.</inlineHelpText>
    <label>Accounting  Period</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Period__c.AcctSeed__Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </filterItems>
        <infoMessage>The accounting period status must be open</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Period__c</referenceTo>
    <relationshipLabel>Cash Receipts</relationshipLabel>
    <relationshipName>Cash_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Receipt__c/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Cash Receipts</relationshipLabel>
    <relationshipName>Cash_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Receipt__c/fields/AcctSeed__Project_Task__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Project_Task__c.AcctSeed__Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.AcctSeed__Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Project_Task__c</referenceTo>
    <relationshipLabel>Cash Receipts</relationshipLabel>
    <relationshipName>Cash_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Receipt__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>A value of &quot;Posted&quot; indicates the record is final and a debit and credit line have been entered into the transaction object for the Cash Receipt.</inlineHelpText>
    <label>Posting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
                <default>true</default>
                <label>In Process</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>Used in filtered look ups to limit the selection of inactive projects.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Shop</fullName>
            </value>
            <value>
                <fullName>Pending Repair</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ready For Accounting</fullName>
            </value>
            <value>
                <fullName>Ready to Finalize W/O</fullName>
            </value>
            <value>
                <fullName>At Supplier</fullName>
            </value>
            <value>
                <fullName>In Storage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeed__Project_Task__c/AcctSeed__Project_Task__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__End_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__End_Date__c</fullName>
    <inlineHelpText>The date a project task ends on.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <inlineHelpText>Related Parent object.</inlineHelpText>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Start_Date__c</fullName>
    <inlineHelpText>The date this Project Task is set to start on.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>Used in filtered lookups to eliminate inactive and completed projects from selection.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeed__Project_Task__c/fields/GMBLASERP__Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Serial_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Serial Number</label>
    <referenceTo>GMBLASERP__Serial_Number__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Contact/fields/Receives_Monthly_Statements__c.field-meta.xml
<CustomField>
    <fullName>Receives_Monthly_Statements__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Receives Monthly Statements</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/classes/gcCashReceipt_Actions_T.cls
@IsTest(SeeAllData=false)
public class gcCashReceipt_Actions_T {
  final static String RECORDTYPE = 'Insurance';
  final static String FAMILY = 'Insurance';
  final static String SERIALNUMBER = '123450';
  @TestSetup
  static void testData() {
    new Factory_TestData();
    Factory_CustomSettings.setupInventorySettings();
    List<AcctSeed__Project__c> erps;
    Map<Id, AcctSeed__Project_Task__c> erp_task_map;
    Contact dealerContact;

    Date startDate = Date.today().toStartOfMonth().addMonths(-4);
    AcctSeed__Accounting_Period__c previousPeriod = new AcctSeed__Accounting_Period__c(
      AcctSeed__End_Date__c = Date.today().addMonths(-1).toStartOfMonth().addDays(-1),
      AcctSeed__Start_Date__c = startDate,
      AcctSeed__Status__c = 'Open',
      Name = Datetime.newInstance(startDate.year(), startDate.month(), startDate.day()).format('YYYY-MM')
    );
    insert previousPeriod;
    // Account
    Account dealer = AccountFactory.buildDealerAccount('Test Dealer UnitTester');
    insert dealer;
    String email = LGND_Utilities.generateRandomString(5) + '@' + LGND_Utilities.generateRandomString(5) + '.org';
    dealerContact = Factory_Contact.buildContact(dealer.Id, 'My Amazing', 'Tester', email);
    dealerContact.Receives_Monthly_Statements__c = true;
    update dealerContact;

    // Serial
    GMBLASERP__Serial_Number__c serial = Factory_SerialNumber.insertFullSerial(
      'Boat',
      'Pontoon',
      '1234567890-UNIT-TESTER'
    );

    // Projects
    //createPartnerPartSales( dealer, serial, 3 );
    integer count = 3;

    erps = new List<AcctSeed__Project__c>();
    for (Integer i = 0; i < count; i++) {
      erps.add(Factory_ERPOrder.buildERP(dealer, serial.Id, gcConstants.idRtPartnerPartsOrder));
    }
    Boolean origTrig = gcProject.disableTrigger;
    gcProject.disableTrigger = true;
    insert erps;
    gcProject.disableTrigger = origTrig;
    erp_task_map = new Map<Id, AcctSeed__Project_Task__c>();
    for (AcctSeed__Project__c erp : erps) {
      erp_task_map.put(erp.Id, Factory_ERPOrder.buildProjectTask(erp.Id, 'Dealer Order'));
    }
    insert erp_task_map.values();
    Product2[] parts = Factory_Product.buildNonSerializedProducts('Part', 'Hardware', 5);
    insert parts;
    List<Product2> serializedProducts = Factory_Product.createSerializedProducts(RECORDTYPE, FAMILY, 10);

    // Billing
    AcctSeed__Billing_Format__c format = [
      SELECT Id
      FROM AcctSeed__Billing_Format__c
      WHERE Name = 'Billing PDF Format'
      LIMIT 1
    ];
    AcctSeed__Ledger__c ledger = [SELECT Id FROM AcctSeed__Ledger__c LIMIT 1];
    List<AcctSeed__Billing__c> billings = new List<AcctSeed__Billing__c>();
    List<AcctSeed__Cash_Receipt__c> lstCashReceipt = new List<AcctSeed__Cash_Receipt__c>();
    for (AcctSeed__Project__c erp : erps) {
      lstCashReceipt.add(
        new AcctSeed__Cash_Receipt__c(
          AcctSeed__Account__c = dealer.Id,
          AcctSeed__Amount__c = 5.0,
          AcctSeed__Receipt_Date__c = Date.today(),
          AcctSeed__Payment_Reference__c = LGND_Utilities.generateRandomString(6)+String.valueOf(System.now()),
          AcctSeed__Ledger__c = ledger.Id,
          AcctSeed__Project__c = erp.Id,
          AcctSeed__Project_Task__c = erp_task_map.get(erp.Id).Id,
          AcctSeed__Product__c = serializedProducts[0].Id
        )
      );
    }

    insert lstCashReceipt;
  }
  @isTest
  static void testStandardController() {
    //AcctSeed__Cash_Receipt__c
    List<AcctSeed__Cash_Receipt__c> cash_receipts = [SELECT Id FROM AcctSeed__Cash_Receipt__c];
    Test.setCurrentPage(Page.gpCashReceipt_Actions);
    Test.setCurrentPageReference(Page.gpCashReceipt_Actions);
    ApexPages.currentPage().getParameters().put('idFilter', cash_receipts[0].Id);
    ApexPages.StandardController sc = new ApexPAges.StandardController((cash_receipts[0]));
    gcCashReceipt_Actions action = new gcCashReceipt_Actions(sc);

    Test.startTest();
    action.init();
    PageReference ret = action.back();
    System.assertEquals('/' + String.valueOf(cash_receipts[0].Id).left(15), ret.getUrl());
    Test.stopTest();
  }

  @isTest
  static void testStandardSetController() {
    //AcctSeed__Cash_Receipt__c
    List<AcctSeed__Cash_Receipt__c> cash_receipts = [SELECT Id FROM AcctSeed__Cash_Receipt__c];
    Test.setCurrentPage(Page.gpCashReceipt_Actions);
    Test.setCurrentPageReference(Page.gpCashReceipt_Actions);
    ApexPages.currentPage().getParameters().put('idFilter', cash_receipts[0].Id);
    ApexPages.currentPage().getParameters().put('retUrl', 'www.salesforce.com');
    ApexPages.StandardSetController ssc = new ApexPAges.StandardSetController((cash_receipts));
    ssc.setSelected(cash_receipts);

    gcCashReceipt_Actions action = new gcCashReceipt_Actions(ssc);

    Test.startTest();
    action.init();
    PageReference ret = action.back();
    System.assertEquals('www.salesforce.com', ret.getUrl());
    Test.stopTest();
  }
  @isTest
  static void testStandardSetControllerRetUrlNull() {
    //AcctSeed__Cash_Receipt__c
    List<AcctSeed__Cash_Receipt__c> cash_receipts = [SELECT Id FROM AcctSeed__Cash_Receipt__c];
    Test.setCurrentPage(Page.gpCashReceipt_Actions);
    Test.setCurrentPageReference(Page.gpCashReceipt_Actions);
    ApexPages.currentPage().getParameters().put('idFilter', cash_receipts[0].Id);
    ApexPages.StandardSetController ssc = new ApexPAges.StandardSetController((cash_receipts));
    ssc.setSelected(cash_receipts);

    gcCashReceipt_Actions action = new gcCashReceipt_Actions(ssc);

    Test.startTest();
    action.init();
    PageReference ret = action.back();
    System.assertEquals('/' + cash_receipts[0].Id, ret.getUrl());
    Test.stopTest();
  }

  @isTest
  static void testStandardSetControllerIdFilterNull() {
    //AcctSeed__Cash_Receipt__c
    List<AcctSeed__Cash_Receipt__c> cash_receipts = [SELECT Id FROM AcctSeed__Cash_Receipt__c];
    Test.setCurrentPage(Page.gpCashReceipt_Actions);
    Test.setCurrentPageReference(Page.gpCashReceipt_Actions);

    ApexPages.StandardSetController ssc = new ApexPAges.StandardSetController((cash_receipts));

    gcCashReceipt_Actions action = new gcCashReceipt_Actions(ssc);

    Test.startTest();
    action.init();
    Test.stopTest();
  }
}