force-app/main/default/objects/Account/fields/AcctSeed__GL_Account_Variable_1__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__GL_Account_Variable_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>General Ledger segment used for reporting of a business unit such as division or department.</inlineHelpText>
    <label>GL Variable 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 1</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Accounts (GL Variable 1)</relationshipLabel>
    <relationshipName>AccountsGLAV1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Account_Payable__c/AcctSeed__Account_Payable__c.object-meta.xml
<CustomObject>
    <description>Used to document liabilities to outside vendor, contact, or employee.</description>
    <label>Payable</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Payable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Account_Payable__c/fields/AcctSeed__Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Discount_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>The amount taken as a discount in the cash disbursements cycle if the invoice is paid within the number of days specified in the discount days field from the Invoice date.</inlineHelpText>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Account_Payable__c/fields/AcctSeed__Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Type__c</fullName>
    <formula>IF(AcctSeed__Total__c &lt; 0,&quot;Credit Memo&quot;, &quot;Invoice&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Automatically determined by the sum of the Accounts Payable Lines. If total Accounts Payable lines are negative the document is a Credit Memo. If Positive then it is an Invoice.</inlineHelpText>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Accounting_Settings__c/AcctSeed__Accounting_Settings__c.object-meta.xml
<CustomObject>
    <description>Main record used to define configuration and default settings used in the application.</description>
    <label>Accounting Settings</label>
    <nameField>
        <label>Account Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Accounting_Settings__c/fields/AcctSeed__Default_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Default_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is the account that the majority of payments are made from and that deposits are made to. When entering a cash receipt it will default to this bank account. When creating a cash disbursement batch it will default to this account.</inlineHelpText>
    <label>Default Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Bank__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Accounting_Settings (Default Bank Account)</relationshipLabel>
    <relationshipName>Accounting_Settings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__AP_Disbursement__c/AcctSeed__AP_Disbursement__c.object-meta.xml
<CustomObject>
    <description>Used to document the relationship an payable has with a cash disbursement.</description>
    <label>AP Disbursement</label>
    <nameField>
        <displayFormat>APD-{00000}</displayFormat>
        <label>AP Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP Disbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__AP_Disbursement__c/fields/AcctSeed__Account_Payable__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account_Payable__c</fullName>
    <label>Payable</label>
    <referenceTo>AcctSeed__Account_Payable__c</referenceTo>
    <relationshipLabel>Applied Cash Disbursements</relationshipLabel>
    <relationshipName>Account_Payable_Cash_Disbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeed__AP_Disbursement__c/fields/AcctSeed__Cash_Disbursement__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Cash_Disbursement__c</fullName>
    <label>Cash Disbursement</label>
    <referenceTo>AcctSeed__Cash_Disbursement__c</referenceTo>
    <relationshipLabel>Invoices Applied To</relationshipLabel>
    <relationshipName>Account_Payable_Cash_Disbursements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeed__AP_Disbursement__c/fields/AcctSeed__Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Discount_Amount__c</fullName>
    <formula>AcctSeed__Account_Payable__r.AcctSeed__Discount_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Discount Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Disbursement__c/AcctSeed__Cash_Disbursement__c.object-meta.xml
<CustomObject>
    <description>Used to document the payment made to an outside vendor, contact, or employee typically recorded as an payable. The aggregation of multiple cash disbursements constitute a cash disbursement batch.</description>
    <label>Cash Disbursement</label>
    <nameField>
        <displayFormat>CD-{00000}</displayFormat>
        <label>Cash Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Disbursements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Bank_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Upon posting a credit entry will be made to this account and a corresponding debit entry will be made to the AP Control account set in the Accounting Settings Tab.</inlineHelpText>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Bank__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Cash Disbursements</relationshipLabel>
    <relationshipName>Cash_Disbursements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Cash_Disbursement_Batch__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Cash_Disbursement_Batch__c</fullName>
    <label>Cash Disbursement Batch</label>
    <referenceTo>AcctSeed__Cash_Disbursement_Batch__c</referenceTo>
    <relationshipLabel>Cash Disbursements</relationshipLabel>
    <relationshipName>Cash_Disbursements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Cash_Flow_Category__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Cash_Flow_Category__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Used to categorize records in Cash Flow Statement.</inlineHelpText>
    <label>Cash Flow Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Cash Flow</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Cash Disbursements (Cash Flow Category)</relationshipLabel>
    <relationshipName>Cash_Disbursements2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Check_Number__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Check_Number__c</fullName>
    <label>Check Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Contact__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>A Cash Disbursement can have either the Account (Vendor), Contact or User (Employee) as the Payee. One object must be chosen.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cash Disbursements</relationshipLabel>
    <relationshipName>Cash_Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Disbursement_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Disbursement_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <inlineHelpText>The Date in which the Cash Disbursement was made.</inlineHelpText>
    <label>Disbursement Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Employee__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>A Cash Disbursement can have either the Account (Vendor), Contact or User (Employee) as the Payee. One object must be chosen.</inlineHelpText>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cash_Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__GL_Account_Variable_1__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__GL_Account_Variable_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GL Variable 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Cash Disbursements</relationshipLabel>
    <relationshipName>Cash_Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Type__c</fullName>
    <inlineHelpText>Denotes the method in which the disbursement was made. Check indicated traditional paper check. Electronic would be used to represent ACH, Wires or any other form of electronic payment.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wire</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Direct Deposit</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Disbursement__c/fields/AcctSeed__Vendor__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Vendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>A Cash Disbursement can have either the Account (Vendor), Contact or User (Employee) as the Payee. One object must be chosen.</inlineHelpText>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Type__c</field>
            <operation>contains</operation>
            <value>Vendor, Customer and Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cash Disbursements</relationshipLabel>
    <relationshipName>Cash_Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__GL_Account__c/AcctSeed__GL_Account__c.object-meta.xml
<CustomObject>
    <description>Used to document the general ledger accounts used by the financial suite accounting application. This is a traditional general ledger account.</description>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__GL_Account__c/fields/AcctSeed__Bank__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Bank__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates if the GL Account is a Bank account and can be selected to record Cash Receipts, Cash Disbursements and use the Bank Reconciliation.</inlineHelpText>
    <label>Bank</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AcctSeed__GL_Account__c/fields/AcctSeed__Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Type__c</fullName>
    <inlineHelpText>Denotes the major grouping for financial reporting.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Balance Sheet</fullName>
                <default>true</default>
                <label>Balance Sheet</label>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
            <value>
                <fullName>Cash Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/gcAccountPayable_payBatch.cls
global with sharing class gcAccountPayable_payBatch {
	
	private ApexPages.StandardSetController myStandardSetController;
	
	public AcctSeed__Cash_Disbursement__c cdHolder{get;set;}

	public String accData {get;set;}
	public String selectedApIds {get;set;}
	public String defaultAcc {get;set;}
	public String selectedAcc {get;set;}
	public String includedApId {get;set;}
	public String discountedApId {get;set;}

	public gcAccountPayable_payBatch(ApexPages.StandardSetController c)
	{
		myStandardSetController = c;
		cdHolder = new AcctSeed__Cash_Disbursement__c();
		cdHolder.AcctSeed__Disbursement_Date__c = date.Today();

		//Get the default bank account
		for(AcctSeed__Accounting_Settings__c s : 
			[SELECT Id,
					AcctSeed__Default_Bank_Account__c
			 FROM AcctSeed__Accounting_Settings__c
			 ORDER BY CreatedDate
			 LIMIT 1])
		{
			if(s.AcctSeed__Default_Bank_Account__c != null)
			{
				defaultAcc = String.valueOf(s.AcctSeed__Default_Bank_Account__c);
			}
		}

		//Get the Account Data
		List<Map<String, String>> listAccData = new List<Map<String, String>>();
		for(AcctSeed__GL_Account__c gl : [
			SELECT
				Id,
				Name,
				(	SELECT AcctSeed__Check_Number__c
					FROM AcctSeed__Cash_Disbursements__r
					WHERE AcctSeed__Check_Number__c != null
					ORDER BY AcctSeed__Check_Number__c DESC
					LIMIT 1)
			FROM AcctSeed__GL_Account__c
			WHERE AcctSeed__Bank__c = True
			ORDER BY Name ASC])
		{
			Map<String, String> m = new Map<String, String>();
			m.put('id', gl.Id);
			m.put('name', gl.Name);

			Decimal checkNum = 1;
			if(!gl.AcctSeed__Cash_Disbursements__r.isEmpty())
			{
				checkNum = gl.AcctSeed__Cash_Disbursements__r[0].AcctSeed__Check_Number__c + 1;
			}
			m.put('checkNum', String.valueOf(checkNum));

			listAccData.add(m);
		}
		accData = JSON.serialize(listAccData);

		//Get the selected APs
		Set<Id> setIdAP = new Set<Id>();
		for(AcctSeed__Account_Payable__c ap : (List<AcctSeed__Account_Payable__c>)myStandardSetController.getSelected())
		{
			setIdAP.add(ap.Id);
		}
		selectedApIds = JSON.serialize(setIdAP);
	}

	public pageReference cancel()
	{
		String prefix = AcctSeed__Account_Payable__c.sObjectType.getDescribe().getKeyPrefix();
		return new pageReference('/'+prefix+'?fcf='+myStandardSetController.getFilterId().LEFT(15));
	}

	public pageReference payBatch()
	{
		List<Object> listApId = (List<Object>)JSON.deserializeUntyped(includedApId);
		List<Object> listDiscountApId = (List<Object>)JSON.deserializeUntyped(discountedApId);

		Set<Id> setIdAp = new Set<Id>();
		for(Object apId : listApId)
		{
			Id idAp = Id.valueOf(String.valueOf(apId));
			setIdAp.add(idAp);
		}
		if(!listDiscountApId.isEmpty())
		{
			Map<String,Object> mapString = new Map<String,Object>();
			Set<String> setAPDiscountIds = new Set<String>();
			for(Object apIdDiscount : listDiscountApId)
			{
				Map<String,Object> m = (Map<String,Object>)apIdDiscount;
				mapString.putAll(m);
			}
			List<AcctSeed__Account_Payable__c> listAp = new List<AcctSeed__Account_Payable__c>();
			for(AcctSeed__Account_Payable__c ap : 
				[SELECT Id,
						AcctSeed__Discount_Amount__c
				 FROM AcctSeed__Account_Payable__c
				 WHERE Id IN :mapString.keySet()])
			{
				ap.AcctSeed__Discount_Amount__c = Decimal.valueOf(String.valueOf(mapString.get(ap.Id)));
				listAp.add(ap);
			}
			if(!listAp.isEmpty())
				update listAp;
		}
		//Id idGlBank = null;
		//if(!String.isBlank(selectedAcc)) idGlBank = Id.valueOf(selectedAcc);

		Id idBatch = pay(setIdAp, cdHolder);

		if(idBatch == null)
		{
			ApexPages.addMessage(new ApexPages.message(ApexPages.severity.WARNING,'There are no qualifying AP records.'));
			return null;  
		}
		else
		{
			return new pageReference('/' + idBatch);
		}
	}

	webservice static string payWS(Id idAp)
	{
		AcctSeed__Cash_Disbursement__c cdHolder = new AcctSeed__Cash_Disbursement__c();

		Id idBatch = pay(new set<Id>{idAp}, cdHolder);
		if(idBatch == null)
		{
			throw new gcException('The AP cannot be paid; check that it is posted, and that it has a positive balance.');
		}
		else
			return idBatch;
	}

	public static Id pay(set<Id> setIdAp, AcctSeed__Cash_Disbursement__c cdHolder)
	{
		list<AcctSeed__Cash_Disbursement__c> listCD = new list<AcctSeed__Cash_Disbursement__c>();
		list<AcctSeed__AP_Disbursement__c> listAPD = new list<AcctSeed__AP_Disbursement__c>();

		map<Id,AcctSeed__Cash_Disbursement__c> mapPayeeCD = new map<Id,AcctSeed__Cash_Disbursement__c>();
		map<Id,list<AcctSeed__AP_Disbursement__c>> mapPayeeAPD = new map<Id,list<AcctSeed__AP_Disbursement__c>>();


		Date disbursementDate = cdHolder.AcctSeed__Disbursement_Date__c;
		Id idGlBank = cdHolder.AcctSeed__Bank_Account__c;
		Id idGlV1 = cdHolder.AcctSeed__GL_Account_Variable_1__c;
		Id idCashFlowCategory = cdHolder.AcctSeed__Cash_Flow_Category__c;
		//Id idGlBank = selectedAcc;
		Id idGlDiscount = null;
		String accountType = cdHolder.AcctSeed__Type__c;
		Decimal startingCheckNumber = cdHolder.AcctSeed__Check_Number__c;
		Boolean noChequeRequired = false;
		Set<String> setCheckTypes = new Set<String>{'Cheque','Check','US Check'};
		if(accountType == null || !setCheckTypes.contains(accountType)){
			startingCheckNumber = 0;
			noChequeRequired = true;
		}

		//Populate disbursement date
		if(disbursementDate == null) disbursementDate = Date.today();

		//Populate bank and discount accounts
		for(AcctSeed__Accounting_Settings__c s : 
			[SELECT Id,
					AcctSeed__Default_Bank_Account__c,
					AcctSeed__Payment_Discount_GL_Account__c
			 FROM AcctSeed__Accounting_Settings__c
			 ORDER BY CreatedDate
			 LIMIT 1])
		{
			if(idGlBank == null) idGlBank = s.AcctSeed__Default_Bank_Account__c;
			idGlDiscount = s.AcctSeed__Payment_Discount_GL_Account__c;
		}

		//Populate starting check number
		if(startingCheckNumber == null && !noChequeRequired)
		{
			startingCheckNumber = 0;
			for(AcctSeed__Cash_Disbursement__c cd : [
				SELECT Id, AcctSeed__Check_Number__c
				FROM AcctSeed__Cash_Disbursement__c
				WHERE AcctSeed__Check_Number__c != null
				ORDER BY AcctSeed__Check_Number__c DESC
				LIMIT 1])
			{
				startingCheckNumber = cd.AcctSeed__Check_Number__c;
			}
			startingCheckNumber += 1;
		}
		Decimal nextCheckNumber = startingCheckNumber;

		List<payee> listPayee = new List<payee>();

		//Go through the payables
		for(AcctSeed__Account_Payable__c ap : 
			[SELECT Id,
					AcctSeed__Payee__c,
					AcctSeed__Vendor__c,
					AcctSeed__Contact__c,
					AcctSeed__Employee__c,
					AcctSeed__Total__c,
					AcctSeed__Discount_Amount__c,
					AcctSeed__Credit_Memo_Applied_Amount__c,
					AcctSeed__Paid_Amount__c,
					AcctSeed__Balance__c
			 FROM AcctSeed__Account_Payable__c
			 WHERE Id IN :setIdAp
			   AND AcctSeed__Status__c = 'Posted'
			   AND AcctSeed__Balance__c != 0])
		{
			Id idPayee = ap.AcctSeed__Vendor__c;
			if(idPayee == null)
				idPayee = ap.AcctSeed__Contact__c;
			if(idPayee == null)
				idPayee = ap.AcctSeed__Employee__c;

			if(!mapPayeeCD.containsKey(idPayee))
			{
				AcctSeed__Cash_Disbursement__c cd = new AcctSeed__Cash_Disbursement__c(
					AcctSeed__Amount__c = 0,
					AcctSeed__Bank_Account__c = idGlBank,
					AcctSeed__Type__c = accountType,
					AcctSeed__Disbursement_Date__c = disbursementDate,
					AcctSeed__Debit_GL_Account__c = gcConstants.idGlAPayable,
					AcctSeed__GL_Account_Variable_1__c = idGlV1,
					AcctSeed__Cash_Flow_Category__c = idCashFlowCategory,
					AcctSeed__Source__c = 'Account Payable'
					//AcctSeed__Check_Number__c = nextCheckNumber
				);
				//nextCheckNumber += 1;

				if(idPayee == ap.AcctSeed__Vendor__c)
					cd.AcctSeed__Vendor__c = ap.AcctSeed__Vendor__c;
				else if(idPayee == ap.AcctSeed__Contact__c)
					cd.AcctSeed__Contact__c = ap.AcctSeed__Contact__c;
				else if(idPayee == ap.AcctSeed__Employee__c)					
					cd.AcctSeed__Employee__c = ap.AcctSeed__Employee__c;

				//listCD.add(cd);
				listPayee.add(new payee(ap.AcctSeed__Payee__c, cd));
				mapPayeeCD.put(idPayee,cd);
				mapPayeeAPD.put(idPayee, new list<AcctSeed__AP_Disbursement__c>());
			}

			AcctSeed__AP_Disbursement__c apd = new AcctSeed__AP_Disbursement__c(
				AcctSeed__Account_Payable__c = ap.Id,
				AcctSeed__Paid_Amount__c = ap.AcctSeed__Balance__c
			); 

			listAPD.add(apd);
			mapPayeeAPD.get(idPayee).add(apd);
			mapPayeeCD.get(idPayee).AcctSeed__Amount__c += ap.AcctSeed__Balance__c;
		}

		//Sort the list then add the check numbers
		listPayee.sort();

		for(payee payeeObj : listPayee)
		{
			if(!noChequeRequired){
				payeeObj.disbursement.AcctSeed__Check_Number__c = nextCheckNumber;
				nextCheckNumber += 1;
			}
			listCD.add(payeeObj.disbursement);
		}

		for(AcctSeed__Cash_Disbursement__c cd : listCD)
		{
			if(cd.AcctSeed__Amount__c < 0)
			{
				ApexPages.addMessage(new ApexPages.message(ApexPages.severity.WARNING, 'A negative cash disbursement is not allowed.'));
				return null;
			}
		}
		//System.debug(LoggingLevel.ERROR,'mapPayeeCD:'+mapPayeeCD);
		//throw new gcException('Stop Here');
		if(!mapPayeeCD.isEmpty())
		{
			//create the batch record
			AcctSeed__Cash_Disbursement_Batch__c cdb = new AcctSeed__Cash_Disbursement_Batch__c(
				Name = DateTime.now().format(), 
				AcctSeed__Starting_Check_Number__c = startingCheckNumber);
			insert cdb;

			for(AcctSeed__Cash_Disbursement__c cd : listCD)
			{
				cd.AcctSeed__Cash_Disbursement_Batch__c = cdb.Id;
			}

			//Let the Cash Disbursement know it is from AP
			//gcCashDisbursement.isApDisbursement = true;
			System.debug('listCD');
			System.debug(listCD);
			insert listCD;
			
			//Reset the Cash Disbursement
			//gcCashDisbursement.isApDisbursement = false;
			
			for(Id idPayee : mapPayeeCD.keySet())
			{
				Id idCD = mapPayeeCD.get(idPayee).Id;
				for(AcctSeed__AP_Disbursement__c apd : mapPayeeAPD.get(idPayee))
				{
					apd.AcctSeed__Cash_Disbursement__c = idCD;
				}
			}

			insert listAPD;

			return cdb.Id;
		}

		return null;
	}

	class payee implements Comparable
	{
		public String name;
		public AcctSeed__Cash_Disbursement__c disbursement;

		public payee(string payeeName, AcctSeed__Cash_Disbursement__c payeeDisbursement)
		{
			name = payeeName;
			disbursement = payeeDisbursement;
		}

		public Integer compareTo(Object obj)
		{
			payee payeeObj = (payee)obj;
			Integer result = 0;
			if(name > payeeObj.name) result = 1;
			else if (name < payeeObj.name) result = -1;
			return result;
		}
	}

	@RemoteAction @ReadOnly
	public static List<Map<String,String>> retrieveApData(String[] setId)
	{
		List<Map<String,String>> listResult = new List<Map<String,String>>();

		for(AcctSeed__Account_Payable__c ap : [
			SELECT
				Id,
				Name,
				AcctSeed__Date__c,
				AcctSeed__Payee__c,
				AcctSeed__Total__c,
				AcctSeed__Discount_Amount__c,
				AcctSeed__Credit_Memo_Applied_Amount__c,
				AcctSeed__Payee_Reference__c,
				AcctSeed__Paid_Amount__c,
				AcctSeed__Balance__c,
				AcctSeed__Vendor__c,
				AcctSeed__Contact__c,
				AcctSeed__Employee__c
			FROM AcctSeed__Account_Payable__c
			WHERE
				Id IN :setId AND
				AcctSeed__Status__c = 'Posted' AND
				AcctSeed__Balance__c != 0
			ORDER BY AcctSeed__Payee__c ASC, AcctSeed__Date__c])
		{
			Id idPayee = ap.AcctSeed__Vendor__c;
			if(idPayee == null) idPayee = ap.AcctSeed__Contact__c;
			if(idPayee == null) idPayee = ap.AcctSeed__Employee__c;

			Map<String,String> mapAp = new Map<String,String>();
			mapAp.put('id', ap.Id);
			mapAp.put('name', ap.Name);
			mapAp.put('date', ap.AcctSeed__Date__c.format());
			mapAp.put('payeeId', String.valueOf(idPayee));
			mapAp.put('payeeRef', ap.AcctSeed__Payee_Reference__c);
			mapAp.put('payee', ap.AcctSeed__Payee__c);
			mapAp.put('total', String.valueOf(ap.AcctSeed__Total__c.setScale(2)));
			mapAp.put('dbDiscountAmt', String.valueOf(ap.AcctSeed__Discount_Amount__c.setScale(2)));
			mapAp.put('discountAmt', String.valueOf(ap.AcctSeed__Discount_Amount__c.setScale(2)));
			mapAp.put('cmAppliedAmt', String.valueOf(ap.AcctSeed__Credit_Memo_Applied_Amount__c.setScale(2)));
			mapAp.put('paidAmt', String.valueOf(ap.AcctSeed__Paid_Amount__c.setScale(2)));
			mapAp.put('dbBalance', String.valueOf(ap.AcctSeed__Balance__c.setScale(2)));
			mapAp.put('balance', String.valueOf(ap.AcctSeed__Balance__c.setScale(2)));
			mapAp.put('preIncluded', 'true');
			listResult.add(mapAp);
		}
		return listResult;
	}

	@RemoteAction @ReadOnly
	public static List<Map<String,String>> retrieveApDataAll()
	{
		List<Map<String,String>> listResult = new List<Map<String,String>>();

		for(AcctSeed__Account_Payable__c ap : [
			SELECT
				Id,
				Name,
				AcctSeed__Date__c,
				AcctSeed__Payee__c,
				AcctSeed__Total__c,
				AcctSeed__Discount_Amount__c,
				AcctSeed__Credit_Memo_Applied_Amount__c,
				AcctSeed__Payee_Reference__c,
				AcctSeed__Paid_Amount__c,
				AcctSeed__Balance__c,
				AcctSeed__Vendor__c,
				AcctSeed__Contact__c,
				AcctSeed__Employee__c
			FROM AcctSeed__Account_Payable__c
			WHERE
				AcctSeed__Status__c = 'Posted' AND
				AcctSeed__Balance__c != 0 AND
				AcctSeed__Date__c < THIS_MONTH
			ORDER BY AcctSeed__Payee__c ASC, AcctSeed__Date__c])
		{
			Id idPayee = ap.AcctSeed__Vendor__c;
			if(idPayee == null) idPayee = ap.AcctSeed__Contact__c;
			if(idPayee == null) idPayee = ap.AcctSeed__Employee__c;

			Map<String,String> mapAp = new Map<String,String>();
			mapAp.put('id', ap.Id);
			mapAp.put('name', ap.Name);
			mapAp.put('date', ap.AcctSeed__Date__c.format());
			mapAp.put('payeeId', String.valueOf(idPayee));
			mapAp.put('payeeRef', ap.AcctSeed__Payee_Reference__c);
			mapAp.put('payee', ap.AcctSeed__Payee__c);
			mapAp.put('total', String.valueOf(ap.AcctSeed__Total__c.setScale(2)));
			mapAp.put('dbDiscountAmt', String.valueOf(ap.AcctSeed__Discount_Amount__c.setScale(2)));
			mapAp.put('discountAmt', String.valueOf(ap.AcctSeed__Discount_Amount__c.setScale(2)));
			mapAp.put('cmAppliedAmt', String.valueOf(ap.AcctSeed__Credit_Memo_Applied_Amount__c.setScale(2)));
			mapAp.put('paidAmt', String.valueOf(ap.AcctSeed__Paid_Amount__c.setScale(2)));
			mapAp.put('dbBalance', String.valueOf(ap.AcctSeed__Balance__c.setScale(2)));
			mapAp.put('balance', String.valueOf(ap.AcctSeed__Balance__c.setScale(2)));
			mapAp.put('preIncluded', 'true');
			listResult.add(mapAp);
		}
		return listResult;
	}

	public static void coverage(){
		integer i;	
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
	}
}