force-app/main/default/objects/Account/fields/AcctSeed__Accounting_Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Accounting_Type__c</fullName>
    <inlineHelpText>Used in filtered lookups for Accounts Payable and Billing screens to limit selection of Accounts to those marked as Customers or Vendors for use by Accounting.</inlineHelpText>
    <label>Accounting Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Vendor</fullName>
            </value>
            <value>
                <fullName>Customer and Vendor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/AcctSeed__GL_Account__c/AcctSeed__GL_Account__c.object-meta.xml
<CustomObject>
    <description>Used to document the general ledger accounts used by the financial suite accounting application. This is a traditional general ledger account.</description>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__GL_Account__c/fields/AcctSeed__Active__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Denotes if the GL Account is active. Most filtered lookups to the GL Account object look for an active status.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__GL_Account__c/fields/AcctSeed__Sub_Type_1__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Sub_Type_1__c</fullName>
    <inlineHelpText>Used in conjunction with the Type field to further classify GL Accounts in reports. This pick list is dependent on Type.</inlineHelpText>
    <label>Sub Type 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>AcctSeed__Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Assets</fullName>
            </value>
            <value>
                <fullName>Liabilities</fullName>
            </value>
            <value>
                <fullName>Owners Equity</fullName>
            </value>
            <value>
                <fullName>Product Revenue</fullName>
            </value>
            <value>
                <fullName>Service Revenue</fullName>
            </value>
            <value>
                <fullName>Cost of Goods Sold</fullName>
            </value>
            <value>
                <fullName>Facilities</fullName>
            </value>
            <value>
                <fullName>Labor</fullName>
            </value>
            <value>
                <fullName>Sales &amp; Marketing</fullName>
            </value>
            <value>
                <fullName>General &amp; Administrative</fullName>
            </value>
            <value>
                <fullName>Financing</fullName>
            </value>
            <value>
                <fullName>Training &amp; Travel</fullName>
            </value>
            <value>
                <fullName>Vehicle</fullName>
            </value>
            <value>
                <fullName>Corporate Taxes</fullName>
            </value>
            <value>
                <fullName>Operating</fullName>
            </value>
            <value>
                <fullName>Investing</fullName>
            </value>
            <value>
                <fullName>Other Revenue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeed__GL_Account__c/fields/AcctSeed__Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Type__c</fullName>
    <inlineHelpText>Denotes the major grouping for financial reporting.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Balance Sheet</fullName>
                <default>true</default>
                <label>Balance Sheet</label>
            </value>
            <value>
                <fullName>Revenue</fullName>
            </value>
            <value>
                <fullName>Expense</fullName>
            </value>
            <value>
                <fullName>Cash Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/InsurancePlan__c/InsurancePlan__c.object-meta.xml
<CustomObject>
    <label>Insurance Plan</label>
    <nameField>
        <label>Insurance Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/AcctSeed__Accounting_Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Accounting_Type__c</fullName>
    <label>Tax Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Taxable Product</fullName>
                <default>true</default>
                <label>Taxable Product</label>
            </value>
            <value>
                <fullName>Tax Exempt Product</fullName>
            </value>
            <value>
                <fullName>Tax Rate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeed__Expense_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Expense_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Expense GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Balance Sheet, Revenue, Expense</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Products (Expense GL Account)</relationshipLabel>
    <relationshipName>Products1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeed__Inventory_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Inventory_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Balance Sheet, Revenue, Expense</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Products (Inventory GL Account)</relationshipLabel>
    <relationshipName>Products2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeed__Inventory_Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Inventory_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes whether the product is a managed inventory product</description>
    <inlineHelpText>Denotes whether the product is a managed inventory product</inlineHelpText>
    <label>Inventory Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeed__Inventory_Type__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Inventory_Type__c</fullName>
    <label>Inventory Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Purchased</fullName>
            </value>
            <value>
                <fullName>Manufactured</fullName>
            </value>
            <value>
                <fullName>Kit</fullName>
            </value>
            <value>
                <fullName>Raw Material</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeed__Revenue_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Revenue_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revenue GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Balance Sheet, Revenue, Expense</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeed__Unit_Cost__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Unit_Cost__c</fullName>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeedERP__Serialized__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Serialized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Serialized</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Available_Online__c.field-meta.xml
<CustomField>
    <fullName>Available_Online__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Distinguishes this product as available for online purchase</description>
    <label>Available Online</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/Product2/fields/Can_be_Nest__c.field-meta.xml
<CustomField>
    <fullName>Can_be_Nest__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Serial Numbers of this Product can be the Nest for Serial Numbers of another product.</inlineHelpText>
    <label>Can be Nest</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/Product2/fields/Can_be_Nested__c.field-meta.xml
<CustomField>
    <fullName>Can_be_Nested__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Serial Numbers of this Product can be nested to Serial Numbers of other products.</inlineHelpText>
    <label>Can be Nested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/GMBLASERP__Lot_Tracked__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Lot_Tracked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lot Tracked</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/Product2/fields/InsurancePlan__c.field-meta.xml
<CustomField>
    <fullName>InsurancePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance Plan</label>
    <referenceTo>InsurancePlan__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>InsuranceProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Is_Residual_Insurance__c.field-meta.xml
<CustomField>
    <fullName>Is_Residual_Insurance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true we calculate the insurance amount on the residual amount else calculate on primary amount</description>
    <label>Is Residual Insurance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Unique_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Unique_Product_Code__c</fullName>
    <description>A Unique product code that corresponds to the IEM product code</description>
    <label>Unique Product Code</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/Base/main/default/objects/Product2/recordTypes/Boat.recordType-meta.xml
<RecordType>
    <fullName>Boat</fullName>
    <active>true</active>
    <label>Boat</label>
</RecordType>

src/Base/main/default/objects/Product2/recordTypes/Fees.recordType-meta.xml
<RecordType>
    <fullName>Fees</fullName>
    <active>true</active>
    <description>Fees</description>
    <label>Fees</label>
</RecordType>

src/Base/main/default/objects/Product2/recordTypes/Insurance.recordType-meta.xml
<RecordType>
    <fullName>Insurance</fullName>
    <active>true</active>
    <label>Insurance</label>
</RecordType>

src/Base/main/default/objects/Product2/recordTypes/Motor.recordType-meta.xml
<RecordType>
    <fullName>Motor</fullName>
    <active>true</active>
    <description>Outboard Motors</description>
    <label>Motor</label>
</RecordType>

src/Base/main/default/objects/Product2/recordTypes/Part.recordType-meta.xml
<RecordType>
    <fullName>Part</fullName>
    <active>true</active>
    <description>Part</description>
    <label>Part</label>
</RecordType>

src/Base/main/default/classes/Factory_Product.cls
@isTest
public with sharing class Factory_Product {

  static AcctSeed__GL_Account__c revenueAccount;
  static AcctSeed__GL_Account__c expenseAccount;
  static AcctSeed__GL_Account__c inventoryAccount;

  private static void buildGlAccounts()
  {
    List<AcctSeed__GL_Account__c> glAccts = new List<AcctSeed__GL_Account__c>();
    if( revenueAccount == null )
    {
      revenueAccount = new AcctSeed__GL_Account__c(Name='Test Revenue Account',
                                                   AcctSeed__Active__c = true,
                                                   AcctSeed__Type__c = 'Revenue');
      glAccts.add(revenueAccount);
    }
    if( expenseAccount == null )
    {
      expenseAccount = new AcctSeed__GL_Account__c(Name='Test Expense Account',
                                                   AcctSeed__Active__c = true,
                                                   AcctSeed__Type__c = 'Expense');
      glAccts.add(expenseAccount);
    }
    if( inventoryAccount == null )
    {
      inventoryAccount = new AcctSeed__GL_Account__c(Name='Test Inventory Account',
                                                   AcctSeed__Active__c = true,
                                                   AcctSeed__Sub_Type_1__c = 'Assets',
                                                   AcctSeed__Type__c = 'Balance Sheet');
      glAccts.add(inventoryAccount);
    }
    if( glAccts.size() > 0 )
      insert glAccts;
  }

  public static Product2 createSerializedProduct( String recordTypeName,
                                                  String family )
  {
    Product2 p = buildSerializedProduct( recordTypeName, family );
    Boolean orig = gcProduct.disableTrigger;
    gcProduct.disableTrigger = true;
    insert p;
    gcProduct.disableTrigger = orig;
    return p;
  }

  public static Product2[] buildSerializedProducts(
    String recordTypeName,
    String family,
    Integer count )
  {
    Product2[] prods = new List<Product2>();
    for( Integer i=0; i<count; i++ )
    {
      prods.add( buildSerializedProduct( recordTypeName, family ) );
    }
    return prods;
  }

  public static Product2[] createSerializedProducts( String recordTypeName,
                                                     String family,
                                                     Integer count )
  {
    Product2[] prods = buildSerializedProducts(
      recordTypeName,
      family,
      count
    );
    Boolean orig = gcProduct.disableTrigger;
    gcProduct.disableTrigger = true;
    insert prods;
    gcProduct.disableTrigger = orig;
    return prods;
  }

  public static Product2[] buildSerializedProducts_AvailableOnline(
    String recordTypeName,
    String family,
    Integer count )
  {
    Product2[] prods = new List<Product2>();
    for( Integer i=0; i<count; i++ )
    {
      Product2 p =  buildSerializedProduct( recordTypeName, family );
      p.Available_Online__c = true;
      prods.add( p );
    }
    return prods;
  }

  public static Product2[] createSerializedProducts_AvailableOnline( String recordTypeName,
                                                                     String family,
                                                                     Integer count )
  {
    Product2[] prods = buildSerializedProducts_AvailableOnline(
      recordTypeName,
      family,
      count
    );
    Boolean orig = gcProduct.disableTrigger;
    gcProduct.disableTrigger = true;
    insert prods;
    gcProduct.disableTrigger = orig;
    return prods;
  }

  public static Product2 createNonSerializedProduct( String recordTypeName,
                                                     String family )
  {
    Product2 p = buildNonSerializedProduct( recordTypeName, family );
    Boolean orig = gcProduct.disableTrigger;
    gcProduct.disableTrigger = true;
    insert p;
    gcProduct.disableTrigger = orig;
    return p;
  }

  public static Product2 buildSerializedProduct( String recordTypeName,
                                                 String family )
  {
    buildGlAccounts();
    Id rt = LGND_Utilities.recordTypeIdFromName('Product2', recordTypeName );
    String fam = recordTypeName == 'Motor' ? 'Mercury' : 'Legend';
    return new Product2(
      name = 'InventoryTest' + recordTypeName + Crypto.getRandomLong(),
      Family = family,
      recordTypeId = rt,
      AcctSeedERP__Serialized__c = true,
      GMBLASERP__Lot_Tracked__c = true,
      Can_be_Nest__c = recordTypeName == 'Boat',
      Can_be_Nested__c = recordTypeName != 'Boat',
      Make__c = fam,
      AcctSeed__Inventory_Product__c = true,
      AcctSeed__Inventory_Type__c = 'Purchased',
      AcctSeed__Accounting_Type__c = 'Taxable_Product',
      AcctSeed__Expense_GL_Account__c = expenseAccount.Id,
      AcctSeed__Inventory_GL_Account__c = inventoryAccount.Id,
      AcctSeed__Revenue_GL_Account__c = revenueAccount.Id,
      AcctSeed__Unit_Cost__c = 100.00,
      Unique_Product_Code__c = 'pcode-' + LGND_Utilities.generateRandomString(6),
      isActive = true
    );
  }

  public static Product2 buildNonSerializedProduct(String recordTypeName,
                                                   String family )
  {
    buildGlAccounts();
    Id rt = LGND_Utilities.recordTypeIdFromName('Product2', recordTypeName );
    return new Product2(
      name = 'InventoryTest' + recordTypeName + Crypto.getRandomLong(),
      recordTypeId = rt,
      Family = family,
      AcctSeedERP__Serialized__c = false,
      GMBLASERP__Lot_Tracked__c = false,
      Can_be_Nest__c = false,
      Can_be_Nested__c = true,
      AcctSeed__Inventory_Product__c = true,
      AcctSeed__Inventory_Type__c = 'Purchased',
      AcctSeed__Accounting_Type__c = 'Taxable_Product',
      AcctSeed__Expense_GL_Account__c = expenseAccount.Id,
      AcctSeed__Inventory_GL_Account__c = inventoryAccount.Id,
      AcctSeed__Revenue_GL_Account__c = revenueAccount.Id,
      AcctSeed__Unit_Cost__c = 100.00,
      Unique_Product_Code__c = 'pcode-' + LGND_Utilities.generateRandomString(6),
      isActive = true
    );
  }

  public static Product2[] createNonSerializedProducts( String recordTypeName,
                                                        String family,
                                                        Integer count )
  {
    Product2[] prods = buildNonSerializedProducts( recordTypeName, family, count);
    insert prods;
    return prods;
  }

  public static Product2[] buildNonSerializedProducts( String recordTypeName,
                                                       String family,
                                                       Integer count )
  {
    Product2[] products = new List<Product2>();
    for( Integer i=0; i<count; i++ )
    {
      products.add( buildNonSerializedProduct( recordTypeName, family ) );
    }
    return products;
  }

  public static Product2 createSavingsProduct()
  {
    buildGlAccounts();
    Id rt = LGND_Utilities.recordTypeIdFromName('Product2', 'Part' );
    Product2 savings = new Product2(
      Name = 'Savings',
      Unique_Product_Code__c = 'Savings',
      Family = 'Discount',
      RecordTypeId = rt,
      AcctSeed__Inventory_Product__c = false,
      AcctSeed__Expense_GL_Account__c = expenseAccount.Id,
      AcctSeed__Inventory_GL_Account__c = inventoryAccount.Id,
      AcctSeed__Revenue_GL_Account__c = revenueAccount.Id,
      AcctSeed__Inventory_Type__c = null,
      AcctSeedERP__Serialized__c = false,
      GMBLASERP__Lot_Tracked__c = false
    );
    insert savings;
    return savings;
  }

  public static Product2 createPPSA( Id pbId )
  {
    buildGlAccounts();
    Product2 ppsa;
    try {
      ppsa = [
        SELECT Id, Name, Family, RecordTypeId, RecordType.Name
        FROM Product2
        WHERE Id = :LGND_Constants.ppsaProductId ];
    }
    catch( Exception e )
    {
      ppsa = new Product2(
        RecordTypeId = LGND_Utilities.recordTypeIdFromName('Product2', 'Fees'),
        Name = 'PPSA Fee',
        Family = 'Bank Registration PPSA Fee',
        IsActive = true
      );
    }
    ppsa.AcctSeed__Revenue_GL_Account__c = revenueAccount.Id;
    ppsa.AcctSeed__Expense_GL_Account__c = expenseAccount.Id;
    ppsa.AcctSeed__Inventory_Product__c = false;
    ppsa.AcctSeed__Inventory_Type__c = null;
    ppsa.Unique_Product_Code__c = 'ppsa-' + LGND_Utilities.generateRandomString(6);
    ppsa.AcctSeed__Unit_Cost__c = 0;
    ppsa.AcctSeedERP__Serialized__c = false;
    ppsa.GMBLASERP__Lot_Tracked__c = false;
    //Boolean orig = gcProduct.disableTrigger;
    //gcProduct.disableTrigger = true;
    upsert ppsa;
    //gcProduct.disableTrigger = orig;
    Factory_PricebookEntry.createStandardEntries( new Set<Id>{ppsa.Id}, 0 );
    insert Factory_PricebookEntry.buildEntry( ppsa.Id, pbId, 0 );
    return ppsa;
  }

  public static Product2 buildInsuranceProduct( String family,
                                                String name,
                                                Id insurancePlanId,
                                                Boolean isResidual )
  {
    return new Product2(
      RecordTypeId = LGND_Utilities.recordTypeIdFromName('Product2', 'Insurance'),
      Name = name,
      Family = family,
      IsActive = true,
      InsurancePlan__c = insurancePlanId,
      Is_Residual_Insurance__c = isResidual,
      AcctSeed__Revenue_GL_Account__c = null,
      AcctSeed__Expense_GL_Account__c = null,
      AcctSeed__Inventory_Product__c = false,
      AcctSeed__Inventory_Type__c = null,
      Unique_Product_Code__c = 'name-' + LGND_Utilities.generateRandomString(6),
      AcctSeed__Unit_Cost__c = 0,
      AcctSeedERP__Serialized__c = false,
      GMBLASERP__Lot_Tracked__c = false
    );
  }

  public static Product2 createInsuranceProduct( String family,
                                                 String name,
                                                 Id insurancePlanId,
                                                 Boolean isResidual,
                                                 Id pbId )
  {
    Product2 p = buildInsuranceProduct( family, name, insurancePlanId, isResidual );
    //Boolean orig = gcProduct.disableTrigger;
    //gcProduct.disableTrigger = true;
    insert p;
    //gcProduct.disableTrigger = orig;
    Factory_PricebookEntry.createStandardEntries( new Set<Id>{p.Id}, 0 );
    insert Factory_PricebookEntry.buildEntry( p.Id, pbId, 0 );
    return p;
  }

}