force-app/main/default/objects/Account/fields/AcctSeed__GL_Account_Variable_2__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__GL_Account_Variable_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>General Ledger segment used for reporting of a business unit such as division or department.</inlineHelpText>
    <label>GL Variable 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 2</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Accounts (GL Variable 2)</relationshipLabel>
    <relationshipName>AccountsGLAV2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Accounting_Period__c/AcctSeed__Accounting_Period__c.object-meta.xml
<CustomObject>
    <customHelpPage>AcctSeed__AccountingPeriodHelp</customHelpPage>
    <description>Used to capture all the financial activity that occurs during a specified time period. Accounting periods are typically defined to coincide with a calendar year month.</description>
    <label>Accounting  Period</label>
    <nameField>
        <label>Accounting Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Accounting_Period__c/fields/AcctSeed__End_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__End_Date__c</fullName>
    <inlineHelpText>Accounting periods are typically used as months. This denotes the end of the period. Fiscal Months are supported. A period end date can not cross over into the start and end date range of another period.</inlineHelpText>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Accounting_Period__c/fields/AcctSeed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Start_Date__c</fullName>
    <inlineHelpText>Accounting periods are typically used as months. This denotes the beginning of the period. Fiscal Months are supported. A period beginning date can not cross over into the start and end date range of another period.</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Accounting_Period__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>&quot;Open&quot; allows new transactions to be saved to this period. &quot;Closed&quot; prevents new records from being saved to this period.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/AcctSeed__Accounting_Period__c/fields/Legend_Name__c.field-meta.xml
<CustomField>
    <fullName>Legend_Name__c</fullName>
    <formula>CASE(MONTH( AcctSeed__Start_Date__c ),
1, &quot;January&quot;,
2, &quot;February&quot;,
3, &quot;March&quot;, 
4, &quot;April&quot;, 
5, &quot;May&quot;, 
6, &quot;June&quot;,
7, &quot;July&quot;,
8, &quot;August&quot;,
9, &quot;September&quot;,
10, &quot;October&quot;,
11, &quot;November&quot;,
12, &quot;December&quot;,
&quot;None&quot;) + &apos; &apos; + TEXT( YEAR( AcctSeed__Start_Date__c ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Legend Name</label>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Cash_Receipt__c/AcctSeed__Cash_Receipt__c.object-meta.xml
<CustomObject>
    <description>Used to document the money received from a customer. Typically matched to billing invoices in the cash application process to denote satisfactory payment of billing invoice by customer.</description>
    <label>Cash Receipt</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Cash Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Receipts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Cash_Receipt__c/fields/AcctSeed__Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Filtered Look up to Salesforce account based on Accounting Status Field.</inlineHelpText>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Type__c</field>
            <operation>equals</operation>
            <value>Customer, Customer and Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cash Receipts</relationshipLabel>
    <relationshipName>Cash_Receipts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Receipt__c/fields/AcctSeed__Accounting_Period__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Accounting_Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Used to specify accounting period for financial reporting. Accounting period must have a value of Open.</inlineHelpText>
    <label>Accounting  Period</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Period__c.AcctSeed__Status__c</field>
            <operation>equals</operation>
            <value>Open</value>
        </filterItems>
        <infoMessage>The accounting period status must be open</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Period__c</referenceTo>
    <relationshipLabel>Cash Receipts</relationshipLabel>
    <relationshipName>Cash_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Receipt__c/fields/AcctSeed__Amount__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Amount__c</fullName>
    <inlineHelpText>The amount of money received in a check or electronic deposit.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Receipt__c/fields/AcctSeed__Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Upon posting a debit entry will be made to this account and a corresponding credit entry will be made to the AR Control account set in the Accounting Settings Tab.</inlineHelpText>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Bank__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Cash Receipts</relationshipLabel>
    <relationshipName>Cash_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Receipt__c/fields/AcctSeed__GL_Account_Variable_2__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__GL_Account_Variable_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
    <label>GL Variable 2</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Accounting Variable must have a Type of GL Account Variable 2.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 2</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Cash Receipts (GL Account Variable 2)</relationshipLabel>
    <relationshipName>Cash_Receipts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Receipt__c/fields/AcctSeed__Payment_Reference__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Payment_Reference__c</fullName>
    <inlineHelpText>Customer check number or electronic transaction reference to be used in working through collection issues with your customers. This should be a number that is referenced in their system or by a bank</inlineHelpText>
    <label>Payment Reference</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Receipt__c/fields/AcctSeed__Purpose__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Purpose__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Receipt</fullName>
                <default>true</default>
                <label>Customer Receipt</label>
            </value>
            <value>
                <fullName>Customer Deposit</fullName>
            </value>
            <value>
                <fullName>Vendor Refund</fullName>
            </value>
            <value>
                <fullName>Other Receipt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Receipt__c/fields/AcctSeed__Receipt_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Receipt_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Receipt Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Receipt__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>A value of &quot;Posted&quot; indicates the record is final and a debit and credit line have been entered into the transaction object for the Cash Receipt.</inlineHelpText>
    <label>Posting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Process</fullName>
                <default>true</default>
                <label>In Process</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeed__Cash_Receipt__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Accord D</fullName>
            </value>
            <value>
                <fullName>Bank Funding</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
                <default>true</default>
                <label>Cash</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
            <value>
                <fullName>Direct Deposit</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Gift Cards</fullName>
            </value>
            <value>
                <fullName>Legend Bucks</fullName>
            </value>
            <value>
                <fullName>MasterCard</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/AcctSeed__Cash_Receipt__c/fields/Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>Sales_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Order</label>
    <referenceTo>AcctSeedERP__Sales_Order__c</referenceTo>
    <relationshipLabel>Cash Receipts</relationshipLabel>
    <relationshipName>Cash_Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Sales_Order__c/AcctSeedERP__Sales_Order__c.object-meta.xml
<CustomObject>
    <label>Sales Order</label>
    <nameField>
        <displayFormat>SO-{00000}</displayFormat>
        <label>Sales Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Sales_Order__c/fields/AcctSeedERP__Customer__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Type__c</field>
            <operation>equals</operation>
            <value>Customer, Customer and Vendor</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Order</relationshipLabel>
    <relationshipName>Sales_Order</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Sales_Order__c/fields/AcctSeedERP__Total__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Total__c</fullName>
    <description>The total of all Sales Order Lines</description>
    <label>Total</label>
    <summarizedField>AcctSeedERP__Sales_Order_Line__c.AcctSeedERP__Total__c</summarizedField>
    <summaryForeignKey>AcctSeedERP__Sales_Order_Line__c.AcctSeedERP__Sales_Order__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Sales_Order__c/fields/GL_Account_Variable_2__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department (GLV2)</label>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Sales Order (Department (GLV2))</relationshipLabel>
    <relationshipName>Sales_Order2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/classes/Services/SalesOrder_Service.cls
public without sharing class SalesOrder_Service {
  private static map<Id, Account> mapAccount;
  private static map<Id, AcctSeed__Accounting_Variable__c> mapGlv;
  private static map<String, AcctSeed__Accounting_Variable__c> mapGlv3ByName;

  public static void generateCashReceipt(List<AcctSeedERP__Sales_Order__c> lstSalesOrder) {
    List<AcctSeed__Cash_Receipt__c> lstCashReceipt = new List<AcctSeed__Cash_Receipt__c>();
    Id idGlCashFloat = gcConstants.idGlCashFloat;
    Id idGlBank;
    //Currently payment method cash
    idGlBank = idGlCashFloat;
    List<AcctSeed__Accounting_Period__c> lstAccount = [
      SELECT Id, Name, AcctSeed__End_Date__c, AcctSeed__Start_Date__c, AcctSeed__Status__c, Legend_Name__c
      FROM AcctSeed__Accounting_Period__c
    ];
    for (AcctSeedERP__Sales_Order__c so : lstSalesOrder) {
      AcctSeed__Cash_Receipt__c newCR = new AcctSeed__Cash_Receipt__c(
        Sales_Order__c = so.id,
        AcctSeed__Account__c = so.AcctSeedERP__Customer__c != null ? so.AcctSeedERP__Customer__c : null,
        AcctSeed__Amount__c = so.AcctSeedERP__Total__c,
        AcctSeed__Bank_Account__c = idGlBank,
        AcctSeed__Payment_Reference__c = so.Name + '_' + System.now().format(),
        Payment_Method__c = 'Online Store',
        AcctSeed__Purpose__c = 'Customer Receipt',
        AcctSeed__Receipt_Date__c = System.today(),
        AcctSeed__GL_Account_Variable_2__c = so.GL_Account_Variable_2__c,
        AcctSeed__GL_Account_Variable_1__c = so.GL_Account_Variable_1__c,
        AcctSeed__Status__c = 'Approved'
      );
      lstCashReceipt.add(newCR);
    }
    if (!lstCashReceipt.isEmpty()) {
      insert lstCashReceipt;
    }
    AcctSeed.PostResult[] postResultsAP = AcctSeed.CashReceiptPostService.postCashReceipts(lstCashReceipt);
    for (AcctSeed.PostResult theResult : postResultsAP) {
      if (!theResult.isSuccess) {
        for (AcctSeed.PostResult.PostErrorResult errorResult : theResult.errors) {
          throw new gcException('Cash Receipt was not posted. Please try again. REASON: ' + errorResult.message);
        }
      } else {
        System.debug('Posted! CR');
      }
    }
  }

  public static void refreshStatics(list<AcctSeedERP__Sales_Order__c> listNew) {
    if (mapGlv == null) {
      mapAccount = new Map<Id, Account>();
      mapGlv = new Map<Id, AcctSeed__Accounting_Variable__c>();
      mapGlv3ByName = new Map<String, AcctSeed__Accounting_Variable__c>();
    }

    set<Id> setIdAccount = new Set<Id>();
    set<Id> setIdGlv = new Set<Id>();
    set<String> setNameGlv = new Set<String>();

    if (!mapGlv.containsKey(gcConstants.idGlv3Ontario))
      setIdGlv.add(gcConstants.idGlv3Ontario);

    for (AcctSeedERP__Sales_Order__c b : listNew) {
      if (b.GL_Account_Variable_3__c != null && !mapGlv.containsKey(b.GL_Account_Variable_3__c))
        setIdGlv.add(b.GL_Account_Variable_3__c);
      if (b.AcctSeedERP__Customer__c != null && !mapAccount.containsKey(b.AcctSeedERP__Customer__c))
        setIdAccount.add(b.AcctSeedERP__Customer__c);
    }

    if (!setIdAccount.isEmpty())
      for (Account a : [SELECT Id, BillingState FROM Account WHERE Id IN :setIdAccount]) {
        mapAccount.put(a.Id, a);
        if (a.BillingState != null && !mapGlv3ByName.containsKey(a.BillingState))
          setNameGlv.add(a.BillingState);
      }

    setIdGlv.remove(null);
    if (!setIdGlv.isEmpty() || !setNameGlv.isEmpty()) {
      for (AcctSeed__Accounting_Variable__c glv : [
        SELECT Id, Name, Tax_is_Harmonized__c, Tax_Rate_Provincial__c, Tax_Rate_Retail__c, AcctSeed__Type__c
        FROM AcctSeed__Accounting_Variable__c
        WHERE Id IN :setIdGlv OR Name IN :setNameGlv
      ]) {
        mapGlv.put(glv.Id, glv);
        if (glv.AcctSeed__Type__c.equals('GL Account Variable 3'))
          mapGlv3ByName.put(glv.Name, glv);
      }
    }
  }

  public static void updateSalesTax(
    List<AcctSeedERP__Sales_Order__c> SalesOrderList,
    map<Id, AcctSeedERP__Sales_Order__c> oldMap
  ) {
    set<Id> setIdSOUpdateTax = new Set<Id>();
    for (AcctSeedERP__Sales_Order__c b : SalesOrderList) {
      AcctSeedERP__Sales_Order__c oldRec = oldMap.get(b.Id);
      if (
        b.GL_Account_Variable_3__c != oldRec.GL_Account_Variable_3__c ||
        b.Tax_is_Harmonized__c != oldRec.Tax_is_Harmonized__c ||
        b.Tax_Override__c != oldRec.Tax_Override__c ||
        b.Tax_Rate_Federal__c != oldRec.Tax_Rate_Federal__c ||
        b.Tax_Rate_Provincial__c != oldRec.Tax_Rate_Provincial__c ||
        b.Tax_Rate_Retail__c != oldRec.Tax_Rate_Retail__c
      ) {
        setIdSOUpdateTax.add(b.Id);
      }
    }
    if (!setIdSOUpdateTax.isEmpty())
      SalesOrderLine_Service.updateSalesTax(setIdSOUpdateTax);
  }

  public static void setTaxVariablesBI(List<AcctSeedERP__Sales_Order__c> SalesOrderList) {
    for (AcctSeedERP__Sales_Order__c b : SalesOrderList) {
      if (b.AcctSeedERP__Status__c != 'Posted') {
        Account acct = mapAccount.get(b.AcctSeedERP__Customer__c);
        if (
          acct != null &&
          acct.BillingState != null &&
          mapGlv3ByName.containsKey(acct.BillingState) &&
          b.GL_Account_Variable_3__c == null
        ) {
          b.GL_Account_Variable_3__c = mapGlv3ByName.get(acct.BillingState).Id;
        }
        if (b.GL_Account_Variable_3__c == null) {
          //b.GL_Account_Variable_3__c = gcConstants.idGlv3Others; (Set in)
          b.Tax_Override__c = true;
          b.Tax_Rate_Federal__c = 0;
          b.Tax_Rate_Provincial__c = 0;
          b.Tax_Rate_Retail__c = 0;
        }

        if (!b.Tax_Override__c) {
          b.Tax_Rate_Federal__c = 5;

          AcctSeed__Accounting_Variable__c glvTaxZone = mapGlv.get(b.GL_Account_Variable_3__c);
          if (glvTaxZone != null) {
            b.Tax_is_Harmonized__c = glvTaxZone.Tax_is_Harmonized__c;
            b.Tax_Rate_Provincial__c = glvTaxZone.Tax_Rate_Provincial__c;
            b.Tax_Rate_Retail__c = glvTaxZone.Tax_Rate_Retail__c;
          }
        }
      }
    }
  }

  public static void setTaxVariablesBU(
    List<AcctSeedERP__Sales_Order__c> SalesOrderList,
    map<Id, AcctSeedERP__Sales_Order__c> oldMap
  ) {
    for (AcctSeedERP__Sales_Order__c b : SalesOrderList) {
      AcctSeedERP__Sales_Order__c oldRec;
      oldRec = oldMap.get(b.Id);
      if (b.AcctSeedERP__Status__c == 'Posted') {
        if (
          b.GL_Account_Variable_3__c != oldRec.GL_Account_Variable_3__c ||
          b.Tax_is_Harmonized__c != oldRec.Tax_is_Harmonized__c ||
          b.Tax_Override__c != oldRec.Tax_Override__c ||
          b.Tax_Rate_Federal__c != oldRec.Tax_Rate_Federal__c ||
          b.Tax_Rate_Provincial__c != oldRec.Tax_Rate_Provincial__c ||
          b.Tax_Rate_Retail__c != oldRec.Tax_Rate_Retail__c
        ) {
          b.addError('The Sales Tax settings of a Billing may not be changed, if the billing is Posted.');
        }
      } else {
        Account acct = mapAccount.get(b.AcctSeedERP__Customer__c);
        if (
          acct != null &&
          acct.BillingState != null &&
          mapGlv3ByName.containsKey(acct.BillingState) &&
          b.AcctSeedERP__Customer__c != oldRec.AcctSeedERP__Customer__c
        ) {
          b.GL_Account_Variable_3__c = mapGlv3ByName.get(acct.BillingState).Id;
        }
        if (b.GL_Account_Variable_3__c == null) {
          //b.GL_Account_Variable_3__c = gcConstants.idGlv3Others; (Set in)
          b.Tax_Override__c = true;
          b.Tax_Rate_Federal__c = 0;
          b.Tax_Rate_Provincial__c = 0;
          b.Tax_Rate_Retail__c = 0;
        }

        if (!b.Tax_Override__c) {
          if (
            b.GL_Account_Variable_3__c != oldRec.GL_Account_Variable_3__c ||
            b.Tax_is_Harmonized__c != oldRec.Tax_is_Harmonized__c ||
            b.Tax_Override__c != oldRec.Tax_Override__c ||
            b.Tax_Rate_Federal__c != oldRec.Tax_Rate_Federal__c ||
            b.Tax_Rate_Provincial__c != oldRec.Tax_Rate_Provincial__c ||
            b.Tax_Rate_Retail__c != oldRec.Tax_Rate_Retail__c
          ) {
            b.Tax_Rate_Federal__c = 5;

            AcctSeed__Accounting_Variable__c glvTaxZone = mapGlv.get(b.GL_Account_Variable_3__c);
            if (glvTaxZone != null) {
              b.Tax_is_Harmonized__c = glvTaxZone.Tax_is_Harmonized__c;
              b.Tax_Rate_Provincial__c = glvTaxZone.Tax_Rate_Provincial__c;
              b.Tax_Rate_Retail__c = glvTaxZone.Tax_Rate_Retail__c;
            }
          }
        }
      }
    }
  }
}