force-app/main/default/objects/Account/fields/Drivers_License__c.field-meta.xml
<CustomField>
    <fullName>Drivers_License__c</fullName>
    <inlineHelpText>Drivers License Number</inlineHelpText>
    <label>Drivers License</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <label>Preferred_Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Preferred_Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project__c/fields/AcctSeed__Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Organization for which this project exists for,</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project__c/fields/AcctSeed__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project__c/fields/AcctSeedERP__Work_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Work_Order_Number__c</fullName>
    <displayFormat>{00000}</displayFormat>
    <label>Work Order Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project__c/fields/Internal_Warranty__c.field-meta.xml
<CustomField>
    <fullName>Internal_Warranty__c</fullName>
    <formula>IF(AND(AcctSeed__Account__r.Is_Internal__c, RecordType.DeveloperName == &apos;Legend_Warranty&apos;), true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Internal Warranty</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project__c/fields/LastDocumentID__c.field-meta.xml
<CustomField>
    <fullName>LastDocumentID__c</fullName>
    <label>LastDocumentID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project__c/fields/Sale_Type__c.field-meta.xml
<CustomField>
    <fullName>Sale_Type__c</fullName>
    <formula>IF(  AcctSeed__Account__r.RecordType.DeveloperName = &#39;Dealer&#39;  , &#39;Partner&#39;,
 IF( AcctSeed__Account__r.RecordType.DeveloperName = &#39;PersonAccount&#39;, &#39;Retail&#39;,
   IF( AcctSeed__Account__r.RecordType.DeveloperName = &#39;Business_Account&#39;, &#39;Retail&#39;,
     IF( AND( AcctSeed__Account__r.RecordType.DeveloperName = &#39;Supplier&#39;,  RecordType.Name = &#39;Retail Boat Sale&#39;), &#39;Retail&#39;, null))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sale Type</label>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project__c/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ERP_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Drivers_License__c.field-meta.xml
<CustomField>
    <fullName>Drivers_License__c</fullName>
    <label>Drivers License</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ERP_document__c/ERP_document__c.object-meta.xml
<CustomObject>
    <label>ERP document</label>
    <nameField>
        <label>ERP document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ERP_document__c/fields/Billing__c.field-meta.xml
<CustomField>
    <fullName>Billing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing</label>
    <referenceTo>AcctSeed__Billing__c</referenceTo>
    <relationshipLabel>ERP documents</relationshipLabel>
    <relationshipName>ERP_documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ERP_document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/ERP_document__c/fields/DocumentID__c.field-meta.xml
<CustomField>
    <fullName>DocumentID__c</fullName>
    <label>DocumentID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ERP_document__c/fields/Inventory_Transfer__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Transfer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Transfer</label>
    <referenceTo>GMBLASERP__Inventory_Transfer__c</referenceTo>
    <relationshipLabel>ERP documents</relationshipLabel>
    <relationshipName>ERP_documents</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/ERP_document__c/fields/isInvoice__c.field-meta.xml
<CustomField>
    <fullName>isInvoice__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Sets whether this should be included as an actual invoice for the ERP. The only time this is false is when it in an internal parts list for boat orders</description>
    <label>isInvoice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ERP_document__c/fields/PDF_Link__c.field-meta.xml
<CustomField>
    <fullName>PDF_Link__c</fullName>
    <label>PDF Link</label>
    <type>Url</type>
</CustomField>

src/Base/main/default/objects/ERP_document__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>ERP documents</relationshipLabel>
    <relationshipName>ERP_documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ERP_document__c/fields/Report_Type__c.field-meta.xml
<CustomField>
    <fullName>Report_Type__c</fullName>
    <label>Report Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Companion II</fullName>
            </value>
            <value>
                <fullName>Companion Maxum</fullName>
            </value>
            <value>
                <fullName>Advantage 70-P</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/User/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Barrie</fullName>
            </value>
            <value>
                <fullName>Montreal</fullName>
            </value>
            <value>
                <fullName>Whitefish</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Preferred_Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>English</fullName>
        <default>true</default>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>Afrikaans</fullName>
    </customValue>
    <customValue>
        <fullName>Albanian</fullName>
    </customValue>
    <customValue>
        <fullName>Albanian - Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Iraq</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Libya</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Morocco</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Qatar</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Saudi Arabia</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Sudan</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Syria</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Tunisia</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - United Arab Emirates</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Yemen</fullName>
    </customValue>
    <customValue>
        <fullName>Armenian</fullName>
    </customValue>
    <customValue>
        <fullName>Basque</fullName>
    </customValue>
    <customValue>
        <fullName>Belarusian</fullName>
    </customValue>
    <customValue>
        <fullName>Belarusian - Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgarian - Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Catalan</fullName>
    </customValue>
    <masterLabel>Preferred Language</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ERPInvoiceDocumentBuilder.cls
global with sharing class ERPInvoiceDocumentBuilder {

  public class applicationException extends Exception {}

  public Id opportunityId { get; set; }
  public AcctSeed__Project__c erpOrder {get; set;}
  public String erpOrderID{get; set;}
  public String docType { get; set; }
  public String language { get; set; }
  public String erpRecordType { get; set; }
  //public String erpSaleType { get; set; }
  public Boolean renderDoc { get; set; }
  public String accountName { get; set; }
  public Boolean hasInternalCopy { get; set ;}
  public String version { get; set; }
  public List<ERP_Document__c> erpDocuments { get; set; }
  public Boolean creatingNew { get; set; }
  public Boolean hasDocHistory { get; set; }
  public String currentDocumentId { get; set; }
  public Boolean showCreateNew { get; set; }


  public  ERPInvoiceDocumentBuilder(){
    //Id counterSaleRtId = gcConstants.idRtProjectCounterSale;
    //Id serviceRtId = gcConstants.idRtProjectService;
    //Id retailBoatSaleRtId = gcConstants.idRtProjectBoatSale;
    //Id partnerBoatSaleRtId = gcConstants.idRtProjectPartnerBoatSale;
    Set<Id> rt_with_internal_copy = new Set<Id>{
      gcConstants.idRtProjectService,
      gcConstants.idRtProjectBoatSale,
      gcConstants.idRtProjectWarranty,
      gcConstants.idRtProjectPartnerBoatSale
    };
    this.erpOrderID = ApexPages.currentPage().getParameters().get('id');
    if ( this.erpOrderID == null )
    {
      this.erpOrderID = ApexPages.currentPage().getParameters().get('erpOrderId');
    }
    this.showCreateNew = true;
    this.currentDocumentId = null;
    this.hasDocHistory = false;
    this.renderDoc = false;
    this.hasInternalCopy = false;
    this.creatingNew = true;
    this.version = 'customer';
    this.erpOrder = [SELECT Id,
                            Name,
                            RecordTypeId,
                            CreatedDate,
                            LastDocumentID__c,
                            AcctSeedERP__Work_Order_Number__c,
                            Sale_Type__c,
                            AcctSeed__Opportunity__c,
                            AcctSeed__Account__c,
                            AcctSeed__Account__r.BillingStreet,
                            AcctSeed__Account__r.BillingCity,
                            AcctSeed__Account__r.BillingState,
                            AcctSeed__Account__r.BillingPostalCode,
                            AcctSeed__Account__r.BillingCountry,
						                AcctSeed__Account__r.PersonEmail,
                            AcctSeed__Account__r.Drivers_License__c,
                            AcctSeed__Account__r.Name,
                            AcctSeed__Account__r.LastName,
                            AcctSeed__Account__r.Phone,
                            AcctSeed__Account__r.PersonBirthdate,
                            AcctSeed__Account__r.Preferred_Language__c,
                            Salesperson__r.Name,
                            Salesperson__r.LastName,
                            Internal_warranty__c
						          FROM AcctSeed__Project__c
                      WHERE Id =: this.erpOrderID ];

    User currentUser = [SELECT Id, Warehouse__c FROM User WHERE Id = :UserInfo.getUserId() ];

    this.erpDocuments = [ SELECT Id,
                                 CreatedDate,
                                 Name,
                                 CreatedBy.Name,
                                 DocumentID__c,
                                 Project__c
                          FROM ERP_document__c
                          WHERE Project__c = :erpOrder.Id
                          AND Report_Type__c = 'Invoice'
                          ORDER BY CreatedDate DESC];
    if( erpDocuments.size() > 0 )
    {
      this.creatingNew = false;
      this.hasDocHistory = true;
      for( ERP_Document__c erpDoc : erpDocuments )
      {
        if( erpDoc.Project__c == erpOrder.LastDocumentID__c )
          currentDocumentId = erpDoc.DocumentId__c;
      }
      if( currentDocumentId == null )
        currentDocumentId = erpDocuments[0].DocumentId__c;
    }


    if( erpOrder.AcctSeed__Account__r.Preferred_Language__c != null )
      this.language = erpOrder.AcctSeed__Account__r.Preferred_Language__c.toLowerCase();
    else if( currentUser.Warehouse__c != null && currentUser.Warehouse__c == 'Montreal' )
      this.language = 'french';
    else
      this.language = 'english';

    this.erpRecordType = erpOrder.RecordTypeId;
    if(erpOrder.RecordTypeId == gcConstants.idRtProjectCounterSale
        || erpOrder.RecordTypeId == gcConstants.idRtPartnerPartsOrder )
       // || (erpOrder.Internal_warranty__c && erpOrder.RecordTypeId == gcConstants.idRtProjectWarranty))
        this.showCreateNew = false;
    ////this.erpSaleType = erpOrder.Sale_Type__c;
    if( rt_with_internal_copy.contains( this.erpRecordType ) )
      hasInternalCopy = true;

    this.docType = fetchPdfName( this.erpRecordType, this.language, this.version );

  }

  @AuraEnabled
  public static List<ERP_document__c> fetchErpDocuments( String recordId )
  {
    return [
      SELECT
        Id,
        CreatedDate,
        Name,
        CreatedBy.Name,
        DocumentID__c,
        Project__c
      FROM ERP_document__c
      WHERE Project__c = :recordId
      AND Report_Type__c = 'Invoice'
      ORDER BY CreatedDate DESC
    ];
  }

  global String getErpDocsJSON()
  {
    return JSON.serialize( this.erpDocuments );
  }

  global PageReference setupNew()
  {
    creatingNew = true;
    return null;
  }

  global PageReference cancelNewSetup()
  {
    creatingNew = false;
    return null;
  }

  global String getAccountId()
  {
    return this.erpOrder.AcctSeed__Account__c;
  }

  @RemoteAction
  global static List<String> fetchEmailAddresses(String accountId)
  {
    List<String> result = new List<String>();
    for( Contact c : [SELECT Email FROM Contact WHERE AccountId = : accountId] )
    {
      if( c.Email != null )
        result.add( c.Email );
    }
    return result;
  }

  @RemoteAction
  global static PageReference savePDF(String erpId, String pageName) {
    ERP_Document__c doc = generateERPDocument( erpId, pageName );
    return new PageReference('/' + erpId);
  }

  @RemoteAction
  global static String savePDF_LEX(String erpId, String pageName) {
    ERP_Document__c doc = generateERPDocument( erpId, pageName );
    return doc.DocumentID__c;
  }

  @RemoteAction
  global static ERP_Document__c[] fetchDocuments( String erpId )
  {
    return [SELECT Id,
                   CreatedDate,
                   Name,
                   CreatedBy.Name,
                   DocumentID__c,
                   Project__c
            FROM ERP_document__c
            WHERE Project__c = :erpId
                AND (Report_Type__c = 'Invoice'
                    OR Report_Type__c = null)
            ORDER BY CreatedDate DESC];
  }

  @RemoteAction
  global static String emailPDF( String jsonData )
  {
    List<String> docIds = new List<String>();
    Map<String, String> emailData = (Map<String, String>)JSON.deserialize( jsonData, Map<String, String>.class);

    if( emailData.containsKey( 'documentId' ) )
      docIds.add( emailData.get( 'documentId' ) );
    else
      docIds.add( generateERPDocument( emailData.get('erpId'), emailData.get('pageName') ).DocumentId__c );

    // Define the email
    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

    String[] toAddresses;
    String[] ccAddresses;

    if( emailData.get('toAddresses') != '' )
      toAddresses = emailData.get('toAddresses').remove(' ').split(',');
    if( emailData.get('ccAddresses') != '' )
      ccAddresses = emailData.get('ccAddresses').remove(' ').split(',');


    email.subject = emailData.get('subject');
    email.setToAddresses( toAddresses );
    email.setCcAddresses( ccAddresses );
    email.setPlainTextBody( emailData.get('message') );
    email.setEntityAttachments( docIds );
    //email.setFileAttachments( new Messaging.EmailFileAttachment[] {efa} );
    email.setWhatId( emailData.get('erpId') );
    email.setSaveAsActivity( true );

    //Send the email
    Messaging.SendEmailResult[] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
    return docIds[0];
  }

  @RemoteAction
  global static String fetchPdfName(String recordType, String language, String version)
  {
    Id counterSaleRtId = gcConstants.idRtProjectCounterSale;
    Id partnerPartOrder = gcConstants.idRtPartnerPartsOrder;
    Id serviceRtId = gcConstants.idRtProjectService;
    Id manufacturingRtId = gcConstants.idRtProjectManufacturing;
    Id retailBoatSaleRtId = gcConstants.idRtProjectBoatSale;
    Id partnerBoatSaleRtId = gcConstants.idRtProjectPartnerBoatSale;
    Id warrantyRtId = gcConstants.idRtProjectWarranty;
    Id tradeInRtId = gcConstants.idRtTradeIn;
    Id fixedAssetRtId = gcConstants.idRtFixedAsset;
    String result;
    if( recordType == retailBoatSaleRtId )
    {
      //if( version == 'internal')
      //  result = 'ERPInvoicePDF_ServiceOrder';
      //else
        result = 'ERPInvoicePDF_RetailBoatSale';
    }

    if( recordType == partnerBoatSaleRtId )
    {
      if( version == 'internal')
        result = 'ERPInvoicePDF_RetailBoatSale';
      else
        result = 'ERPInvoicePDF_PartnerBoatSale';
    }

    if( recordType == counterSaleRtId ||
        recordType == partnerPartOrder)
      result = 'ERPInvoicePDF_RetailCounterSale';
      //result = 'ERPInvoicePDF_RetailCounterSaleNew';

    if( recordType == serviceRtId ||
        recordType == warrantyRtId ||
        recordType == tradeInRtId ||
        recordType == fixedAssetRtId)
      result = 'ERPInvoicePDF_ServiceOrder';

    if( recordType == manufacturingRtId )
      result = 'ERPInvoicePDF_ServiceOrderInt';

    if( version == 'internal' )
      result += 'Int';

    if( language == 'french' )
      result += '_French';

    return result;
  }

	public static ERP_Document__c generateBillingDocument(String erpId, String pageName, String idBill)
    {
        System.debug(loggingLevel.error,'we are here');
        if(idBill == null) throw new gcException('no idBill');
        AcctSeed__Project__c erpOrder = [SELECT Id, Name, Sale_Type__c, RecordTypeId FROM AcctSeed__Project__c WHERE Id = :erpId];
        String pageUri = '/apex/' + pageName + '?billId=' + idBill + '&erpOrderId='+erpOrder.Id;
        System.debug(loggingLevel.error,'pageUri:'+pageUri);
        String docName = 'Invoice - ';
        Boolean isInvoice = true;
        if( ( erpOrder.RecordTypeId == gcConstants.idRtProjectBoatSale ||
              erpOrder.RecordTypeId == gcConstants.idRtProjectPartnerBoatSale )
            && pageName == 'ERPInvoicePDF_ServiceOrderInt' )
        {
          pageUri += '&version=internal';
          docName = 'Parts List - ';
          isInvoice = false;
        }
        PageReference pdfLink =  new PageReference(pageUri);
        ERP_document__c doc = new ERP_document__c();
        doc.Project__c = erpOrder.Id;
        doc.Billing__c = idBill;
        doc.Report_Type__c = 'Invoice';
        doc.name = docName + (erpOrder.Name).LEFT(35) + ' - ' + Datetime.Now().format() + '.pdf';
        doc.documentID__c = generateDocument(pdfLink, doc.name).id;
        doc.isInvoice__c = isInvoice;
        doc.Document_Type__c = erpOrder.Sale_Type__c;
        doc.Report_Type__c = 'Invoice';
        //doc.PDF_Link__c = 'https://' + ApexPages.currentPage().getHeaders().get('Host') + '/apex/' + pageName + '?erpOrderId=' + erpOrder.Id;
        insert doc;
        return doc;
    }

    public static ERP_Document__c generateTransferDocument(String erpId, String pageName, String idTransfer)
    {
        System.debug(loggingLevel.error,'we are here');
        if(idTransfer == null) throw new gcException('no idTransfer');
        AcctSeed__Project__c erpOrder = [SELECT Id, Name, Sale_Type__c, RecordTypeId FROM AcctSeed__Project__c WHERE Id = :erpId];
        String pageUri = '/apex/' + pageName + '?transferId=' + idTransfer + '&erpOrderId='+erpOrder.Id;
        System.debug(loggingLevel.error,'pageUri:'+pageUri);
        String docName = 'Invoice - ';
        Boolean isInvoice = true;
        if( ( erpOrder.RecordTypeId == gcConstants.idRtProjectBoatSale ||
              erpOrder.RecordTypeId == gcConstants.idRtProjectPartnerBoatSale )
            && pageName == 'ERPInvoicePDF_ServiceOrderInt' )
        {
          pageUri += '&version=internal';
          docName = 'Parts List - ';
          isInvoice = false;
        }
        PageReference pdfLink =  new PageReference(pageUri);
        ERP_document__c doc = new ERP_document__c();
        doc.Project__c = erpOrder.Id;
        doc.Inventory_Transfer__c = idTransfer;
        doc.Report_Type__c = 'Invoice';
        doc.name = docName + (erpOrder.Name).LEFT(35) + ' - ' + Datetime.Now().format() + '.pdf';
        doc.documentID__c = generateDocument(pdfLink, doc.name).id;
        doc.isInvoice__c = isInvoice;
        doc.Document_Type__c = erpOrder.Sale_Type__c;
        doc.Report_Type__c = 'Invoice';
        //doc.PDF_Link__c = 'https://' + ApexPages.currentPage().getHeaders().get('Host') + '/apex/' + pageName + '?erpOrderId=' + erpOrder.Id;
        insert doc;
        return doc;
    }

    public static ERP_Document__c generateERPDocument(String erpId, String pageName)
    {
        AcctSeed__Project__c erpOrder = [SELECT Id, Name, Sale_Type__c, RecordTypeId FROM AcctSeed__Project__c WHERE Id = :erpId];
        String pageUri = '/apex/' + pageName + '?erpOrderId=' + erpOrder.Id;
        String docName = 'Invoice - ';
        Boolean isInvoice = true;
        if( ( erpOrder.RecordTypeId == gcConstants.idRtProjectBoatSale ||
              erpOrder.RecordTypeId == gcConstants.idRtProjectPartnerBoatSale )
            && pageName == 'ERPInvoicePDF_ServiceOrderInt' )
        {
          pageUri += '&version=internal';
          docName = 'Parts List - ';
          isInvoice = false;
        }
    		PageReference pdfLink =  new PageReference(pageUri);
    		ERP_document__c doc = new ERP_document__c();
    		doc.Project__c = erpOrder.Id;
            doc.Report_Type__c = 'Invoice';
    		doc.name = docName + (erpOrder.Name).LEFT(35) + ' - ' + Datetime.Now().format() + '.pdf';
    		doc.documentID__c = generateDocument(pdfLink, doc.name).id;
        doc.isInvoice__c = isInvoice;
    		doc.Document_Type__c = erpOrder.Sale_Type__c;
        doc.Report_Type__c = 'Invoice';
		//doc.PDF_Link__c = 'https://' + ApexPages.currentPage().getHeaders().get('Host') + '/apex/' + pageName + '?erpOrderId=' + erpOrder.Id;
		insert doc;
		return doc;
	}

	public static Document generateDocument(PageReference page, String docName)
  {
		Document doc = new Document ();
    doc.Name = docName;
    doc.Type = 'pdf';
    Blob b;
    if (Test.IsRunningTest()) {
        b = Blob.valueOf('UNIT.TEST');
    }else{
        b = page.getContentAsPDF();
   }
    doc.Body =  b;
    doc.ContentType = 'application/pdf';
    Folder f = [SELECT Id, Name, DeveloperName FROM Folder WHERE DeveloperName = 'ERP_Invoices'];
    doc.FolderId = f.Id;
    insert doc;
    return doc;
	}

  public static void coverage(){
    integer i;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
    i=1;
  }

}