force-app/main/default/objects/Account/fields/GL_Account_Variable_1__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Unit (GLV1)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Business Unit (GLV1) must be of type GL Account Variable 1</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project__c/fields/AcctSeed__Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Organization for which this project exists for,</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project__c/fields/GL_Account_Variable_1__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Unit (GLV1)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Accounting Variable must be of Type 1.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>ERP Orders (This Business Unit (GLV1))</relationshipLabel>
    <relationshipName>Projects_GLV1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project__c/fields/GL_Account_Variable_2__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department (GLV2)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Accounting Variable must be of Type 2.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 2</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>ERP Orders (This Department (GLV2))</relationshipLabel>
    <relationshipName>Projects_GLV2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project__c/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The value selected for Tax Zone (GLV3) must be an Accounting Variable of Type 3.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 3</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>ERP Orders</relationshipLabel>
    <relationshipName>ERP_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project__c/fields/GMBLASERP__Warehouse__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project_Task__c/AcctSeed__Project_Task__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <inlineHelpText>Related Parent object.</inlineHelpText>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/Commission_Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Commission_Calculation_Method__c</fullName>
    <label>Commission Calculation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commission_Calculation_Method</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeed__Project_Task__c/fields/GMBLASERP__Product__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project_Task__c/fields/GMBLASERP__Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Serial_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Serial Number</label>
    <referenceTo>GMBLASERP__Serial_Number__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parts List</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/AcctSeedERP__Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <displayFormat>MAT-{00000}</displayFormat>
        <label>Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Project_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Project_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Project_Task__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Project_Task__c.AcctSeed__Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.AcctSeedERP__Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Project_Task__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Quantity_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Quantity_Per_Unit__c</fullName>
    <label>Quantity Ordered</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Material__c/fields/GMBLASERP__Price_Override__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Price_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Price Override</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Material__c/fields/GMBLASERP__Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Serial_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Serial Number</label>
    <referenceTo>GMBLASERP__Serial_Number__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/GMBLASERP__Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Warehouse__c/AcctSeedERP__Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Warehouse__c/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Tax Zone must be an Accounting Variable of Type 3.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 3</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/CommissionLineItem2__c/CommissionLineItem2__c.object-meta.xml
<CustomObject>
    <label>Commission Line Item</label>
    <nameField>
        <displayFormat>CommLineItem-{0000}</displayFormat>
        <label>Commission Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/CommissionLineItem2__c/fields/CommissionRecord2__c.field-meta.xml
<CustomField>
    <fullName>CommissionRecord2__c</fullName>
    <label>Commission Record</label>
    <referenceTo>CommissionRecord2__c</referenceTo>
    <relationshipLabel>Commission Line Items</relationshipLabel>
    <relationshipName>Commission_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CommissionRecord2__c/CommissionRecord2__c.object-meta.xml
<CustomObject>
    <label>Commission Record</label>
    <nameField>
        <displayFormat>CommRec-{0000}</displayFormat>
        <label>Commission Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/CommissionRecord2__c/fields/Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Method__c</fullName>
    <label>Calculation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commission_Calculation_Method</valueSetName>
    </valueSet>
</CustomField>

src/Base/main/default/objects/CommissionRecord2__c/fields/Project_Task__c.field-meta.xml
<CustomField>
    <fullName>Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <referenceTo>AcctSeed__Project_Task__c</referenceTo>
    <relationshipLabel>Commission Records</relationshipLabel>
    <relationshipName>Commission_Records1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Utility_Products__c/Utility_Products__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Product Id which get used as not products ( ie Freight, Discount ... )</description>
    <label>Utility Products</label>
</CustomObject>

src/Base/main/default/objects/Utility_Products__c/fields/Back_Order_Prepaid__c.field-meta.xml
<CustomField>
    <fullName>Back_Order_Prepaid__c</fullName>
    <description>The Product used on the Retail / Service ERP that represents the cost of the items that where backordered</description>
    <label>Back Ordered Prepaid</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/globalValueSets/Commission_Calculation_Method.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Revenue</fullName>
        <default>true</default>
        <label>Revenue</label>
    </customValue>
    <customValue>
        <fullName>Gross Margin</fullName>
    </customValue>
    <description>Method used to calculate Commission</description>
    <masterLabel>Commission Calculation Method</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ERP_CreatePartsBackOrder_Controller_T.cls
/**
 * Created by dave on 2021-04-13.
 */

@IsTest
private class ERP_CreatePartsBackOrder_Controller_T
{
  private static final Integer PARTS_COUNT = 3;
  private static AcctSeed__Project__c erp;
  private static AcctSeed__Project_Task__c erpTask;
  private static  List<AcctSeedERP__Material__c> materials;
  private static List<Id> materialIds;
  private static CommissionRecord2__c commRec;

  @testSetup static void dataSetup()
  {
    new Factory_TestData();
    Factory_CustomSettings.setupInventorySettings();
    Account customer = Factory_Account.insertCustomerAccounts(1)[0];
    AcctSeedERP__Warehouse__c wh = [SELECT Id, Name FROM AcctSeedERP__Warehouse__c LIMIT 1][0];
    GMBLASERP__Serial_Number__c ser = Factory_SerialNumber.insertFullSerial(
      'Boat',
      'Full Windshield',
      'TEST-FULLWINDSHIELD-0001'
    );
    gcProject.disableTrigger = true;
    gcProjectTask.disableTrigger = true;
    gcMaterial.disableTrigger = true;
    AcctSeed__Project__c retailSale = Factory_ERPOrder.insertRetailBoatSale(
      customer,
      wh,
      DateTime.now().addDays(20),
      ser
    );
    retailSale.GL_Account_Variable_1__c = gcConstants.idGlv1Whitefish;
    retailSale.GL_Account_Variable_2__c = gcConstants.idGlv2Sales;
    retailSale.GL_Account_Variable_3__c = gcConstants.idGlv3Ontario;
    update retailSale;
    AcctSeed__Project_Task__c retailTask = [
      SELECT
        Id
      FROM AcctSeed__Project_Task__c
      WHERE AcctSeed__Project__c = :retailSale.Id
    ];
    List<Product2> parts = Factory_Product.createNonSerializedProducts(
      'Part',
      'Electronics',
      PARTS_COUNT
    );
    Factory_Material.insertMaterials(
      retailSale.Id,
      retailTask.Id,
      parts
    );
  }

  private static void initErpData()
  {
    erp = [
      SELECT
        Id,
        AcctSeed__Account__c,
        AcctSeed__Account__r.Name,
        GMBLASERP__Warehouse__c,
        GL_Account_Variable_1__c,
        GL_Account_Variable_2__c,
        GL_Account_Variable_3__c,
        RecordType.Name,
      ( SELECT
          Id,
          Commission_Calculation_Method__c
        FROM AcctSeed__Project_Tasks__r ),
      ( SELECT
          Id,
          AcctSeedERP__Product__c,
          AcctSeedERP__Product__r.Name,
          AcctSeedERP__Project_Task__c,
          AcctSeedERP__Quantity_Per_Unit__c,
          GMBLASERP__Unit_Price__c,
          GMBLASERP__Price_Override__c,
          AcctSeedERP__Comment__c
      FROM AcctSeedERP__Project_Materials__r
      WHERE AcctSeedERP__Product__r.RecordTypeId = :new Application_RecordType().getProductRecordTypes().getPartId() )
      FROM
        AcctSeed__Project__c
      LIMIT 1][0];
    erpTask = erp.AcctSeed__Project_Tasks__r[0];
    materialIds = new List<Id>();
    materials = new List<AcctSeedERP__Material__c>();
    for( AcctSeedERP__Material__c mat : erp.AcctSeedERP__Project_Materials__r )
    {
      materials.add( mat );
      materialIds.add( mat.Id );
    }
    commRec = new CommissionRecord2__c(
      Project_Task__c = erpTask.Id,
      Calculation_Method__c = erpTask.Commission_Calculation_Method__c
    );
    insert commRec;
  }

  @IsTest
  static void fetchMaterials_Test()
  {
    initErpData();
    Test.startTest();
    Map<String, Object> result = ERP_CreatePartsBackOrder_Controller.fetchMaterials( erp.Id );
    Test.stopTest();

    Utility_Products__c ups = Utility_Products__c.getOrgDefaults();
    List<AcctSeedERP__Material__c> returnedMaterials =
      (List<AcctSeedERP__Material__c>)result.get('materials');
    System.assert( (String)result.get('saleType') == 'retail');
    System.assertEquals( ups.Back_Order_Prepaid__c, (String)result.get('prepaidProductId') );
    System.assertEquals( ups.Back_Order_Credit__c, (String)result.get('creditProductId') );
    System.assertEquals( PARTS_COUNT, returnedMaterials.size() );
  }

  @IsTest
  static void findPartsRequestCases_NoCases_Test()
  {
    initErpData();
    Test.startTest();
    List<case> result = ERP_CreatePartsBackOrder_Controller.findPartsRequestCases(
      erp.Id,
      materialIds
    );
    Test.stopTest();
    System.assert( result.size() == 0 );
  }

  @IsTest
  static void findPartsRequestCases_OneCase_Test()
  {
    initErpData();
    Factory_Case.createPartsRequestCase(
      erp.Id,
      erp.AcctSeed__Account__c,
      materials
    );
    Test.startTest();
    List<case> result = ERP_CreatePartsBackOrder_Controller.findPartsRequestCases(
      erp.Id,
      materialIds
    );
    Test.stopTest();
    System.assertEquals( 1, result.size() );
  }

  @IsTest
  static void findPartsRequestCases_OneCaseAndOneCaseWithoutSelectedMaterial_Test()
  {
    initErpData();
    Factory_Case.createPartsRequestCase(
      erp.Id,
      erp.AcctSeed__Account__c,
      materials
    );
    List<Product2> newParts = Factory_Product.createNonSerializedProducts(
      'Part',
      'Electronics',
      1
    );
    gcMaterial.disableTrigger = true;
    List<AcctSeedERP__Material__c> newMaterial = Factory_Material.insertMaterials(
      erp.Id,
      erpTask.Id,
      newParts
    );
    Factory_Case.createPartsRequestCase(
      erp.Id,
      erp.AcctSeed__Account__c,
      newMaterial
    );
    Test.startTest();
    List<case> result = ERP_CreatePartsBackOrder_Controller.findPartsRequestCases(
      erp.Id,
      materialIds
    );
    Test.stopTest();
    List<Case> cases = [
      SELECT
        Id
      FROM Case
      WHERE ERP_Order__c = :erp.Id
    ];

    System.assertEquals( 2, cases.size() );
    System.assertEquals( 1, result.size() );
  }

  @IsTest
  static void buildBackOrderERP_Test()
  {
    initErpData();
    Test.startTest();
    Map<Id, Decimal> quantityMap = new Map<Id, Decimal>();
    for( AcctSeedERP__Material__c mat : materials )
    {
      quantityMap.put( mat.Id, mat.AcctSeedERP__Quantity_Per_Unit__c );
    }
    Map<String, Object> result = ERP_CreatePartsBackOrder_Controller.buildBackOrderERP(
      erp.Id,
      JSON.serialize( quantityMap ),
      '\'This a Back Order Task from Unit Test\''
    );
    Test.stopTest();
    AcctSeed__Project__c resultERP = (AcctSeed__Project__c)result.get('erp');
    AcctSeed__Project_Task__c resultTask = (AcctSeed__Project_Task__c)result.get('task');
    List<AcctSeedERP__Material__c> resultMaterials =
      (List<AcctSeedERP__Material__c>)result.get('materials');

    System.assert( result != null );
    System.assertEquals( erp.Id, resultERP.Original_ERP__c );
    System.assert( resultERP.Name.contains( erp.AcctSeed__Account__r.Name ) );
    System.assert( resultTask.Name.contains( erp.RecordType.Name ) );
    System.assertEquals( true, resultTask.Locked__c );
    System.assertEquals( (materials.size() + 1), resultMaterials.size() );
  }

  @IsTest
  static void createBackOrderERP_Test()
  {
    initErpData();
    AcctSeed__Project__c newErp = new AcctSeed__Project__c(
      RecordTypeId = new Application_RecordType().getERPOrderRecordTypes().getServiceWorkOrderId(),
      Name = erp.AcctSeed__Account__r.Name + '-Back Order',
      AcctSeed__Account__c = erp.AcctSeed__Account__c,
      GMBLASERP__Warehouse__c = erp.GMBLASERP__Warehouse__c,
      GL_Account_Variable_1__c = erp.GL_Account_Variable_1__c,
      GL_Account_Variable_2__c = erp.GL_Account_Variable_2__c,
      GL_Account_Variable_3__c = erp.GL_Account_Variable_3__c,
      Stage__c = 'Pending Diagnostic',
      Job_Status__c = 'Boat Required',
      Original_ERP__c = erp.Id
    );
    AcctSeed__Project_Task__c newTask = new AcctSeed__Project_Task__c(
      Cause_dh__c = 'This a Back Order Task from Unit Test',
      Name = erp.RecordType.Name + ' - Back Order',
      DisplayOnCustomerInvoice__c = true,
      Locked__c = true
    );
    List<AcctSeedERP__Material__c> newMats = new List<AcctSeedERP__Material__c>();
    Decimal total = 0;
    for( AcctSeedERP__Material__c mat : materials )
    {
      newMats.add( new AcctSeedERP__Material__c(
        AcctSeedERP__Product__c = mat.AcctSeedERP__Product__c,
        AcctSeedERP__Quantity_Per_Unit__c = mat.AcctSeedERP__Quantity_Per_Unit__c,
        GMBLASERP__Unit_Price__c = mat.GMBLASERP__Unit_Price__c,
        GMBLASERP__Price_Override__c = mat.GMBLASERP__Price_Override__c,
        AcctSeedERP__Comment__c = mat.AcctSeedERP__Comment__c
      ));
      total += mat.GMBLASERP__Unit_Price__c * mat.AcctSeedERP__Quantity_Per_Unit__c;
    }
    newMats.add( new AcctSeedERP__Material__c(
      AcctSeedERP__Product__c = Utility_Products__c.getOrgDefaults().Back_Order_Credit__c,
      AcctSeedERP__Quantity_Per_Unit__c = 1,
      GMBLASERP__Unit_Price__c = total,
      GMBLASERP__Price_Override__c = true,
      AcctSeedERP__Comment__c = 'Back Order_Credit'
    ));
    Case c = Factory_Case.createPartsRequestCase(
      erp.Id,
      erp.AcctSeed__Account__c,
      materials
    );

    Test.startTest();
    Map<String, Object> result = ERP_CreatePartsBackOrder_Controller.createBackOrderERP(
      newErp,
      newTask,
      newMats,
      new List<Id>{c.Id}
    );
    Test.stopTest();
    AcctSeed__Project__c resultERP = (AcctSeed__Project__c)result.get('erp');
    AcctSeed__Project_Task__c resultTask = (AcctSeed__Project_Task__c)result.get('task');
    List<AcctSeedERP__Material__c> resultMaterials =
      (List<AcctSeedERP__Material__c>)result.get('materials');

    System.assert( result != null );
    System.assertEquals( erp.Id, resultERP.Original_ERP__c );
    System.assert( resultERP.Name.contains( erp.AcctSeed__Account__r.Name ) );
    System.assert( resultTask.Name.contains( erp.RecordType.Name ) );
    System.assertEquals( true, resultTask.Locked__c );
    System.assertEquals( (materials.size() + 1), resultMaterials.size() );
  }

  @IsTest
  static void buildCommissionLines_Test()
  {
    initErpData();
    Decimal totalSale = 0;
    for( AcctSeedERP__Material__c mat : materials )
    {
      totalSale += mat.GMBLASERP__Unit_Price__c * mat.AcctSeedERP__Quantity_Per_Unit__c;
    }
    Test.startTest();
    List<CommissionLineItem2__c> result =
      ERP_CreatePartsBackOrder_Controller.buildCommissionLines( materials );
    Test.stopTest();

    System.assertEquals( 1, result.size() );
    System.assertEquals( totalSale, result[0].Sale_Price__c );
    System.assertEquals( CommissionLineItem2_Service.grossMarginRate, result[0].Commission_Rate__c );
  }

  @IsTest
  static void updateOriginalSale_Test()
  {
    initErpData();
    Decimal totalSale = 0;
    List<Id> deleteMatIds = new List<Id>();
    for( AcctSeedERP__Material__c mat : materials )
    {
      deleteMatIds.add( mat.Id );
      totalSale += mat.GMBLASERP__Unit_Price__c * mat.AcctSeedERP__Quantity_Per_Unit__c;
    }
    List<AcctSeedERP__Material__c> newMats = new List<AcctSeedERP__Material__c>();
    newMats.add( new AcctSeedERP__Material__c(
      AcctSeedERP__Product__c = Utility_Products__c.getOrgDefaults().Back_Order_Prepaid__c,
      AcctSeedERP__Project__c = erp.Id,
      AcctSeedERP__Project_Task__c = erpTask.Id,
      AcctSeedERP__Quantity_Per_Unit__c = 1,
      GMBLASERP__Unit_Price__c = totalSale,
      GMBLASERP__Price_Override__c = true,
      AcctSeedERP__Comment__c = 'Prepaid Back Ordered Items'
    ));
    List<CommissionLineItem2__c> commLines = new List<CommissionLineItem2__c>();
    commLines.add( new CommissionLineItem2__c(
      Comment__c = 'Parts Back Order Entry',
      CommissionRecord2__c = commRec.Id,
      Cost__c = 0,
      Sale_Price__c = totalSale,
      Description__c = 'Parts Back Order Entry',
      Labour_Cost__c = 0,
      Quantity__c = 1,
      Commission_Rate__c = CommissionLineItem2_Service.grossMarginRate
    ));

    Test.startTest();
    ERP_CreatePartsBackOrder_Controller.updateOriginalSale(
      deleteMatIds,
      newMats,
      commLines
    );
    Test.stopTest();

    List<AcctSeedERP__Material__c> mats = [
      SELECT
        Id,
        AcctSeedERP__Product__r.Name
      FROM AcctSeedERP__Material__c
      WHERE AcctSeedERP__Project__c = :erp.Id
    ];
    //one for the boat, one for the back order prepaid
    System.debug( mats[0].AcctSeedERP__Product__r.Name );
    System.assertEquals( 2, mats.size() );
  }

}