force-app/main/default/objects/Account/fields/Is_Internal__c.field-meta.xml
<CustomField>
    <fullName>Is_Internal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Internal?</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__GL_Account__c/AcctSeed__GL_Account__c.object-meta.xml
<CustomObject>
    <description>Used to document the general ledger accounts used by the financial suite accounting application. This is a traditional general ledger account.</description>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Journal_Entry__c/AcctSeed__Journal_Entry__c.object-meta.xml
<CustomObject>
    <description>Used to document accounting related entries into the transaction table.</description>
    <label>Journal Entry</label>
    <nameField>
        <label>Journal Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Journal_Entry__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Journal Entries</relationshipLabel>
    <relationshipName>Journal_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Journal_Entry_Line__c/AcctSeed__Journal_Entry_Line__c.object-meta.xml
<CustomObject>
    <description>Line level entry associated with a journal entry. The aggregation of multiple journal entry lines constitute a journal entry record.</description>
    <label>Journal Entry Line</label>
    <nameField>
        <displayFormat>JEL-{00000}</displayFormat>
        <label>Journal Entry Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Journal Entry Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Journal_Entry_Line__c/fields/AcctSeed__Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Journal Entry Lines</relationshipLabel>
    <relationshipName>Journal_Entry_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Journal_Entry_Line__c/fields/AcctSeed__GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__GL_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Upon posting a debit or credit entry will be made to this account in transaction table depending on the value entered in the debit or credit field.</inlineHelpText>
    <label>GL Account</label>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Journal Entry Lines</relationshipLabel>
    <relationshipName>Journal_Entry_Lines</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Journal_Entry_Line__c/fields/AcctSeed__Journal_Entry__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Journal_Entry__c</fullName>
    <inlineHelpText>Related parent object.</inlineHelpText>
    <label>Journal Entry</label>
    <referenceTo>AcctSeed__Journal_Entry__c</referenceTo>
    <relationshipLabel>Journal Entry Lines</relationshipLabel>
    <relationshipName>Journal_Entry_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Journal_Entry_Line__c/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Related Project or Job for allocation of cost.</inlineHelpText>
    <label>Project</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>AcctSeed__Project__c.AcctSeed__Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Journal Entry Lines</relationshipLabel>
    <relationshipName>Journal_Entry_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Journal_Entry_Line__c/fields/AcctSeed__Project_Task__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Work break down structure for projects, such as: Phases, Deliverables or Roles.</inlineHelpText>
    <label>Project Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AcctSeed__Project__c</field>
            <operation>equals</operation>
            <valueField>AcctSeed__Project_Task__c.AcctSeed__Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Project_Task__c</referenceTo>
    <relationshipLabel>Journal Entry Lines</relationshipLabel>
    <relationshipName>Journal_Entry_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Journal_Entry_Line__c/fields/Is_Internal__c.field-meta.xml
<CustomField>
    <fullName>Is_Internal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify if the JEL is from an Internal ERP or not. That way the transactions created for this line will also be identified as Internal.</description>
    <label>Is Internal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Journal_Entry_Line__c/fields/Journal_Entry_Name__c.field-meta.xml
<CustomField>
    <fullName>Journal_Entry_Name__c</fullName>
    <formula>AcctSeed__Journal_Entry__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Journal Entry Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Journal_Entry_Line__c/fields/Journal_Entry_Project_Id__c.field-meta.xml
<CustomField>
    <fullName>Journal_Entry_Project_Id__c</fullName>
    <formula>AcctSeed__Journal_Entry__r.Project__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Journal Entry Project Id</label>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project__c/fields/AcctSeed__Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Organization for which this project exists for,</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project_Task__c/AcctSeed__Project_Task__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__Labor_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Labor_GL_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Upon posting a Time Card. A debit entry will be made to this GL Account and a corresponding credit entry will be made to the Labor GL Account set in the Accounting Settings Tab for each Time Card Day.</inlineHelpText>
    <label>Expense GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Expense</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <inlineHelpText>Related Parent object.</inlineHelpText>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/classes/gcJournalEntryLine.cls
public without sharing class gcJournalEntryLine {
  public static Boolean disableTrigger {
    get {
      if (disableTrigger == null)
        return false;
      else
        return disableTrigger;
    }
    set {
      if (value == null)
        disableTrigger = false;
      else
        disableTrigger = value;
    }
  }

  public static Boolean allowProjectAndTask {
    get {
      if (allowProjectAndTask == null)
        return false;
      else
        return allowProjectAndTask;
    }
    set {
      if (value == null)
        allowProjectAndTask = false;
      else
        allowProjectAndTask = value;
    }
  }

  public static void triggerHandler(
    map<Id, AcctSeed__Journal_Entry_Line__c> oldMap,
    map<Id, AcctSeed__Journal_Entry_Line__c> newMap,
    list<AcctSeed__Journal_Entry_Line__c> listNew,
    Boolean boolIsBefore,
    Boolean boolIsInsert,
    Boolean boolIsUpdate,
    Boolean boolIsDelete
  ) {
    if (oldMap == null)
      oldMap = new Map<Id, AcctSeed__Journal_Entry_Line__c>();
    if (newMap == null)
      newMap = new Map<Id, AcctSeed__Journal_Entry_Line__c>();
    if (listNew == null)
      listNew = new List<AcctSeed__Journal_Entry_Line__c>();

    updateAndValidate(oldMap, newMap, listNew, boolIsBefore, boolIsInsert, boolIsUpdate, boolIsDelete);

    if (boolIsBefore) {
      if (boolIsInsert) {
        setFinancialAttributes(listNew);
      }
      if (boolIsUpdate) {
        setFinancialAttributes(listNew);
      }
      if (boolIsDelete) {
      }
    } else //i.e. trigger.isAfter
    {
      if (boolIsInsert) {
      }
      if (boolIsUpdate) {
      }
      if (boolIsDelete) {
      }
    }
  }

  private static void setFinancialAttributes(List<AcctSeed__Journal_Entry_Line__c> listNew) {
    gcTransactionParent.setFinancialAttributes(listNew, null, 'AcctSeed__Project_Task__c', 'AcctSeed__GL_Account__c');
  }

  private static void updateAndValidate(
    map<Id, AcctSeed__Journal_Entry_Line__c> oldMap,
    map<Id, AcctSeed__Journal_Entry_Line__c> newMap,
    list<AcctSeed__Journal_Entry_Line__c> listNew,
    Boolean boolIsBefore,
    Boolean boolIsInsert,
    Boolean boolIsUpdate,
    Boolean boolIsDelete
  ) {
    Map<Id, Boolean> mapProjectInternal = new Map<Id, Boolean>();
    Set<Id> setIdProject = new Set<Id>();
    Map<Id, Id> mapJournal = new Map<Id, Id>();
    Map<Id, Id> mapProjectTask = new Map<Id, Id>();
    if (boolIsBefore && (boolIsUpdate || boolIsInsert)) {
      for (AcctSeed__Journal_Entry_Line__c jel : listNew) {
        if (jel.AcctSeed__Project__c != null)
          setIdProject.add(jel.AcctSeed__Project__c);
        mapJournal.put(jel.AcctSeed__Journal_Entry__c, null);
      }
    }
    /// Retrieving JE
    if (!mapJournal.isEmpty()) {
      for (AcctSeed__Journal_Entry__c je : [
        SELECT Id, Project__c
        FROM AcctSeed__Journal_Entry__c
        WHERE Id IN :mapJournal.keySet() AND Project__c != NULL
      ]) {
        mapJournal.put(je.Id, je.Project__c);
        setIdProject.add(je.Project__c);
      }
    }
    // Now look for ERP Account
    if (!setIdProject.isEmpty()) {
      for (AcctSeed__Project__c p : [
        SELECT
          Id,
          AcctSeed__Account__r.Is_Internal__c,
          (SELECT Id FROM AcctSeed__Project_Tasks__r ORDER BY CreatedDate ASC LIMIT 1)
        FROM AcctSeed__Project__c
        WHERE Id IN :setIdProject
      ]) {
        if (p.AcctSeed__Account__r.Is_Internal__c) {
          mapProjectInternal.put(p.Id, true);
        }
        if (!p.AcctSeed__Project_Tasks__r.isEmpty())
          mapProjectTask.put(p.Id, p.AcctSeed__Project_Tasks__r[0].Id);
      }
    }

    if (boolIsBefore && (boolIsUpdate || boolIsInsert)) {
      for (AcctSeed__Journal_Entry_Line__c jel : listNew) {
        System.debug('jel before: ' + jel);
        if (
          jel.AcctSeed__Project__c != null &&
          mapProjectInternal.containsKey(jel.AcctSeed__Project__c) &&
          mapProjectInternal.get(jel.AcctSeed__Project__c)
        )
          jel.Is_Internal__c = true;
        else if (
          jel.AcctSeed__Project__c == null &&
          mapJournal.containsKey(jel.AcctSeed__Journal_Entry__c) &&
          mapJournal.get(jel.AcctSeed__Journal_Entry__c) != null
        ) {
          Id idProject = mapJournal.get(jel.AcctSeed__Journal_Entry__c);
          if (mapProjectInternal.containsKey(idProject) && mapProjectInternal.get(idProject))
            jel.Is_Internal__c = true;
        }
        System.debug('jel after: ' + jel);
        if ((boolIsUpdate && allowProjectAndTask) || boolIsInsert) {
          String journalName = jel.Journal_Entry_Name__c;
          if (
            mapJournal.get(jel.AcctSeed__Journal_Entry__c) != null &&
            !(journalName.startsWith('Job Cost for') ||
            journalName.startsWith('Internal Labour for') ||
            journalName.startsWith('Internal Warranty for'))
          ) {
            Id idPT = mapProjectTask.get(mapJournal.get(jel.AcctSeed__Journal_Entry__c));
            if (jel.AcctSeed__Project__c != mapJournal.get(jel.AcctSeed__Journal_Entry__c))
              jel.AcctSeed__Project__c = mapJournal.get(jel.AcctSeed__Journal_Entry__c);
            if (
              jel.AcctSeed__Project_Task__c == null ||
              (boolIsUpdate && jel.AcctSeed__Project__c != oldMap.get(jel.Id).AcctSeed__Project__c)
            )
              jel.AcctSeed__Project_Task__c = idPT;
          }
        }
      }
    }

    /*if(boolIsBefore && ((boolIsUpdate && allowProjectAndTask) || boolIsInsert))
		{
			Map<Id,Id> mapProjectTask = new Map<Id,Id>();
			for(AcctSeed__Journal_Entry_Line__c jel : listNew){
				String journalName = jel.Journal_Entry_Name__c;
				if(jel.Journal_Entry_Project_Id__c != null && !(journalName.startsWith('Job Cost for') || journalName.startsWith('Internal Labour for') || journalName.startsWith('Internal Warranty for'))){
					mapProjectTask.put(jel.Journal_Entry_Project_Id__c, null);
			}

			if(!mapProjectTask.isEmpty()){
				for(AcctSeed__Project__c p : 
					[SELECT Id, 
						(SELECT Id 
						FROM AcctSeed__Project_Tasks__r 
						ORDER BY CreatedDate ASC 
						LIMIT 1) 
					FROM AcctSeed__Project__c 
					WHERE Id IN:mapProjectTask.keySet()]){
					if(!p.AcctSeed__Project_Tasks__r.isEmpty())
						mapProjectTask.put(p.Id, p.AcctSeed__Project_Tasks__r[0].Id);
				}
				for(AcctSeed__Journal_Entry_Line__c jel : listNew){
					if(jel.Journal_Entry_Project_Id__c != null && mapProjectTask.get(jel.Journal_Entry_Project_Id__c) != null){
						Id idPT = mapProjectTask.get(jel.Journal_Entry_Project_Id__c);
						if(jel.AcctSeed__Project__c != jel.Journal_Entry_Project_Id__c)
							jel.AcctSeed__Project__c = jel.Journal_Entry_Project_Id__c;
						if(jel.AcctSeed__Project_Task__c == null || (boolIsUpdate && jel.AcctSeed__Project__c != oldMap.get(jel.Id).AcctSeed__Project__c))
							jel.AcctSeed__Project_Task__c = idPT;
					}
				}
			}
		}*/
  }

  public static void coverage() {
    integer i;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
  }
}