force-app/main/default/objects/Account/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project__c/fields/AcctSeed__Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Organization for which this project exists for,</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project__c/fields/GMBLASERP__Warehouse__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The FSL Work Order</description>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>ERP Orders</relationshipLabel>
    <relationshipName>ERP_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Warehouse__c/AcctSeedERP__Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Legend_Settings__c/Legend_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Legend Settings</label>
</CustomObject>

force-app/main/default/objects/Legend_Settings__c/fields/Default_Retail_Pricebook__c.field-meta.xml
<CustomField>
    <fullName>Default_Retail_Pricebook__c</fullName>
    <label>Default Retail Pricebook</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Location/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>FSLLocations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Location/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>WorkOrder.Location.RootLocationId</field>
            <operation>equals</operation>
            <valueField>$Source.RootLocationId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/User/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Barrie</fullName>
            </value>
            <value>
                <fullName>Montreal</fullName>
            </value>
            <value>
                <fullName>Whitefish</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/WorkOrder/fields/ERP_Order__c.field-meta.xml
<CustomField>
    <fullName>ERP_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to the ERP Order that the Work Order is Created from</description>
    <label>ERP Order</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/FieldService/classes/WorkOrder/Tests/WorkOrder_Automation_T.cls
/**
 * Created by dave on 2021-06-09.
 */

@IsTest
private class WorkOrder_Automation_T
{

  static Id pbId;
  static Account acct;
  static AcctSeedERP__Warehouse__c warehouse;
  static User barrieUser;

  @testSetup static void dataSetup() {
    new Factory_TestData();
    Factory_CustomSettings.setupInventorySettings();
  }

  private static void init() {
    acct = Factory_Account.insertFullPersonAccount('Testy', 'McTesterson' );
    pbId = Legend_Settings__c.getOrgDefaults().Default_Retail_Pricebook__c;
    warehouse = [SELECT Id, Name FROM AcctSeedERP__Warehouse__c WHERE Name LIKE '%Barrie%' ];
    barrieUser = Factory_User.newUser('fName', 'lName', 'System Administrator', warehouse );
  }

  @IsTest
  static void onInsert()
  {
    init();
    System.runAs( barrieUser )
    {
      Test.startTest();
      WorkOrder wo = Factory_WorkOrder.createNew( acct.Id, pbId );
      Test.stopTest();
      AcctSeed__Project__c[] erps = [ SELECT Id, GMBLASERP__Warehouse__c FROM AcctSeed__Project__c WHERE Work_Order__c = :wo.Id ];
      wo = [ SELECT Id, Location.Warehouse__c FROM WorkOrder WHERE Id = :wo.Id ];
      System.assertEquals( 1, erps.size(), 'One Erp should have been automatically created' );
      System.assertEquals( warehouse.Id, erps[0].GMBLASERP__Warehouse__c, 'ERP Warehouse should be the Users warehouse');
      System.assertEquals( warehouse.Id, wo.Location.Warehouse__c, 'Location on Work Order should be associated to the Users Warehouse' );
    }
  }

  @IsTest
  static void onDelete()
  {
    init();
    TriggerBase.bypass('WorkOrder');
    WorkOrder wo = Factory_WorkOrder.createNew( acct.Id, pbId );
    AcctSeed__Project__c erp = new AcctSeed__Project__c(
      Name = (wo.Account.Name + ' - ' + String.valueOf( wo.WorkOrderNumber)).LEFT(80),
      AcctSeed__Account__c = wo.AccountId,
      Work_Order__c = wo.Id
    );
    gcProject.disableTrigger = true;
    insert erp;
    wo.ERP_Order__c = erp.Id;
    update wo;
    TriggerBase.clearBypass('WorkOrder');

    List<AcctSeed__Project__c> erps = [SELECT Id FROM AcctSeed__Project__c WHERE AcctSeed__Account__c = :acct.Id];

    System.assertEquals( 1, erps.size() );

    Test.startTest();
    delete wo;
    Test.stopTest();

    erps = [SELECT Id FROM AcctSeed__Project__c WHERE AcctSeed__Account__c = :acct.Id];

    System.assertEquals( 0, erps.size() );
  }
}