force-app/main/default/objects/Account/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Product_Part__c/AcctSeed__Product_Part__c.object-meta.xml
<CustomObject>
    <description>Used to document the relationship between products. The primary use of this record is to create product kits which are used in the Accounting Seed ERP application.</description>
    <label>Product Part</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>Product Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Product_Part__c/fields/AcctSeed__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Parts</relationshipLabel>
    <relationshipName>Product_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Product_Part__c/fields/AcctSeed__Product_Part__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Product_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Part</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Parent Product</relationshipLabel>
    <relationshipName>Product_Parts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Serial Number</label>
    <referenceTo>GMBLASERP__Serial_Number__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Inventory_Balance__c/AcctSeedERP__Inventory_Balance__c.object-meta.xml
<CustomObject>
    <label>Inventory Balance</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Inventory Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Balances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Inventory_Balance__c/fields/AcctSeedERP__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inventory Balance</relationshipLabel>
    <relationshipName>Inventory_Balance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Inventory_Balance__c/fields/AcctSeedERP__Warehouse__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Inventory Quantity Available</relationshipLabel>
    <relationshipName>Inventory_Balance</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/AcctSeedERP__Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <displayFormat>MAT-{00000}</displayFormat>
        <label>Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Purchase_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Purchase_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order Line</label>
    <referenceTo>AcctSeedERP__Purchase_Order_Line__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Material__c/fields/GMBLASERP__Lot__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Lot__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lot</label>
    <referenceTo>GMBLASERP__Lot__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Material__c/fields/GMBLASERP__Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Serial_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Serial Number</label>
    <referenceTo>GMBLASERP__Serial_Number__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Material__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>AcctSeedERP__Product__r.Name</formula>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <formula>GMBLASERP__Serial_Number__r.Name</formula>
    <label>Serial Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order__c/AcctSeedERP__Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Purchase_Order__c/fields/AcctSeedERP__Order_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Order_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Order Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Line__c/AcctSeedERP__Purchase_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POL-{00000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeedERP__Purchase_Order_Line__c/fields/AcctSeedERP__Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>AcctSeedERP__Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Purchase_Order_Line__c/fields/GMBLASERP__Lot__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Lot__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lot</label>
    <referenceTo>GMBLASERP__Lot__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Line__c/fields/GMBLASERP__Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Serial_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Serial Number</label>
    <referenceTo>GMBLASERP__Serial_Number__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Line__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <formula>AcctSeedERP__Purchase_Order__r.Warehouse__r.Name</formula>
    <label>Warehouse</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMBLASERP__Inventory_Settings__c/GMBLASERP__Inventory_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Inventory Settings</label>
</CustomObject>

src/Base/main/default/objects/GMBLASERP__Inventory_Settings__c/fields/GMBLASERP__Adjustment_Warehouse_Id__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Adjustment_Warehouse_Id__c</fullName>
    <label>Adjustment Warehouse Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMBLASERP__Inventory_Settings__c/fields/GMBLASERP__Transit_Warehouse_Id__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Transit_Warehouse_Id__c</fullName>
    <label>Transit Warehouse Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMBLASERP__Lot__c/GMBLASERP__Lot__c.object-meta.xml
<CustomObject>
    <label>Lot</label>
    <nameField>
        <label>Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/GMBLASERP__Lot__c/fields/GMBLASERP__Product__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lots</relationshipLabel>
    <relationshipName>Lots</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/GMBLASERP__Serial_Number__c.object-meta.xml
<CustomObject>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GMBLASERP__Serial_Number__c/fields/Available_Retail__c.field-meta.xml
<CustomField>
    <fullName>Available_Retail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available Retail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GMBLASERP__Serial_Number__c/fields/Available_Wholesale__c.field-meta.xml
<CustomField>
    <fullName>Available_Wholesale__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Available Wholesale</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/fields/Dealer_Rigged__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Rigged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Dealer Rigged</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/GMBLASERP__Serial_Number__c/fields/GMBLASERP__Inventory_Balance__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Inventory_Balance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Balance</label>
    <referenceTo>AcctSeedERP__Inventory_Balance__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/fields/GMBLASERP__Lot__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Lot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lot</label>
    <referenceTo>GMBLASERP__Lot__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/fields/GMBLASERP__Product__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GMBLASERP__Serial_Number__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>GMBLASERP__Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Product2/fields/Composite_Type__c.field-meta.xml
<CustomField>
    <fullName>Composite_Type__c</fullName>
    <formula>IF(Parts_Count__c &gt; 0,IF(AcctSeed__Inventory_Product__c,&quot;Assembly&quot;,&quot;Kit&quot;),&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Composite Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Boat.recordType-meta.xml
<RecordType>
    <fullName>Boat</fullName>
    <active>true</active>
    <label>Boat</label>
</RecordType>

force-app/main/default/classes/gcNonInventoryReport_MRP.cls
public without sharing class gcNonInventoryReport_MRP {
	public gcNonInventoryReport_MRP() {}
	
	public List<SelectOption> getListWarehouse()
	{
		List<SelectOption> listOptions = new List<SelectOption>();
		Id idWarehouseAdjustment = GMBLASERP__Inventory_Settings__c.getOrgDefaults().GMBLASERP__Adjustment_Warehouse_Id__c;
		Id idWarehouseTransit = GMBLASERP__Inventory_Settings__c.getOrgDefaults().GMBLASERP__Transit_Warehouse_Id__c;
		listOptions.add(new selectOption('', '-All-'));
		for(AcctSeedERP__Warehouse__c whs : 
			[SELECT Id, Name FROM AcctSeedERP__Warehouse__c WHERE Id !=:idWarehouseAdjustment AND Id !=:idWarehouseTransit ORDER BY Name])
        {
			listOptions.add(new selectOption(whs.Id, whs.Name));
		}

		return listOptions;	
	}

	public List<SelectOption> getListProductType()
	{
		List<SelectOption> listOptions = new List<SelectOption>();
		listOptions.add(new selectOption('Kit', 'Kits'));
		listOptions.add(new selectOption('Non', 'Other Non-Inventory'));

		return listOptions;	
	}

	@RemoteAction @ReadOnly 
	public static list<map<String,String>> retrieveSerialNumbers(list<Id> listIdProduct, Id pIdWarehouse)
	{
		list<map<String,String>> listJSON = new list<map<String,String>>();

		set<Id> setIdProduct = new set<Id>();
		setIdProduct.addAll(listIdProduct);
		for(AcctSeed__Product_Part__c p : [SELECT AcctSeed__Product_Part__c FROM AcctSeed__Product_Part__c WHERE AcctSeed__Product__c IN:listIdProduct AND AcctSeed__Product__r.Composite_Type__c = 'Kit'])
			setIdProduct.add(p.AcctSeed__Product_Part__c);
		setIdProduct.remove(null);
		Boolean checkDeleted = true;
		if(pIdWarehouse == null) checkDeleted = false;
		for(GMBLASERP__Serial_Number__c x :
			[SELECT Id, Name,
					Dealer_Rigged__c,
					Available_Retail__c,
					Available_Wholesale__c,
					GMBLASERP__Product__c,
					Product_Name__c,
					GMBLASERP__Lot__c,
					GMBLASERP__Lot__r.Name,
					GMBLASERP__Inventory_Balance__r.AcctSeedERP__Warehouse__c,
					GMBLASERP__Inventory_Balance__r.AcctSeedERP__Warehouse__r.Name
			 FROM GMBLASERP__Serial_Number__c
			 WHERE GMBLASERP__Inventory_Balance__c != null
			 	AND (IsDeleted =:checkDeleted OR GMBLASERP__Inventory_Balance__r.AcctSeedERP__Warehouse__c =:pIdWarehouse)
			 	AND IsDeleted = false
			   	AND GMBLASERP__Product__c IN :setIdProduct])
		{
			map<String,String> m = new map<String,String>();

			m.put('idSerial',x.Id);
			m.put('serialName',x.Name);
			m.put('dealerRigged',x.Dealer_Rigged__c ? 'true' : 'false');
			m.put('availableRetail',x.Available_Retail__c ? 'true' : 'false');
			m.put('availableWholesale',x.Available_Wholesale__c ? 'true' : 'false');
			m.put('idProduct',x.GMBLASERP__Product__c);
			m.put('productName',x.Product_Name__c);
			m.put('idLot',x.GMBLASERP__Lot__c);
			m.put('lotName',x.GMBLASERP__Lot__r.Name);
			m.put('idWarehouse',x.GMBLASERP__Inventory_Balance__r.AcctSeedERP__Warehouse__c);
			m.put('warehouseName',x.GMBLASERP__Inventory_Balance__r.AcctSeedERP__Warehouse__r.Name);

			listJSON.add(m);
		}

		return listJSON;
	}

	@RemoteAction @ReadOnly 
	public static list<map<String,String>> retrievePurchaseOrders(list<Id> listIdProduct, Id pIdWarehouse)
	{
		list<map<String,String>> listJSON = new list<map<String,String>>();

		set<Id> setIdProduct = new set<Id>();
		setIdProduct.addAll(listIdProduct);
		for(AcctSeed__Product_Part__c p : [SELECT AcctSeed__Product_Part__c FROM AcctSeed__Product_Part__c WHERE AcctSeed__Product__c IN:listIdProduct AND AcctSeed__Product__r.Composite_Type__c = 'Kit'])
			setIdProduct.add(p.AcctSeed__Product_Part__c);
		setIdProduct.remove(null);
		Boolean checkDeleted = true;
		if(pIdWarehouse == null) checkDeleted = false;
		for(AcctSeedERP__Purchase_Order_Line__c x :
			[SELECT AcctSeedERP__Purchase_Order__c,
					AcctSeedERP__Purchase_Order__r.Name,
					AcctSeedERP__Purchase_Order__r.AcctSeedERP__Order_Date__c,
					AcctSeedERP__Purchase_Order__r.AcctSeedERP__Vendor__r.Name,
					AcctSeedERP__Purchase_Order__r.Warehouse__c,
					AcctSeedERP__Purchase_Order__r.Warehouse__r.Name,
					AcctSeedERP__Product__r.Name,
					AcctSeedERP__Quantity__c,
					AcctSeedERP__Quantity_Unreceived__c
			 FROM AcctSeedERP__Purchase_Order_Line__c
			 WHERE AcctSeedERP__Quantity_Unreceived__c > 0
			 	AND (IsDeleted =:checkDeleted 
			 		OR (AcctSeedERP__Purchase_Order__r.Warehouse__c =:pIdWarehouse 
			 			OR AcctSeedERP__Purchase_Order__r.Warehouse__c = null))
			 	AND IsDeleted = false
			   	AND AcctSeedERP__Purchase_Order__r.Locked__c = false
			   	AND AcctSeedERP__Product__r.AcctSeed__Inventory_Product__c = true
			   	AND AcctSeedERP__Product__c IN :setIdProduct])
		{
			map<String,String> m = new map<String,String>();

			m.put('idPurchaseOrder',x.AcctSeedERP__Purchase_Order__c);

			m.put('purchaseOrderName',x.AcctSeedERP__Purchase_Order__r.Name);
			if(x.AcctSeedERP__Purchase_Order__r.Warehouse__c != null){
				m.put('idWarehouse',x.AcctSeedERP__Purchase_Order__r.Warehouse__c);
				m.put('warehouseName',x.AcctSeedERP__Purchase_Order__r.Warehouse__r.Name);
			}
			
			if(x.AcctSeedERP__Purchase_Order__r.AcctSeedERP__Order_Date__c != null)
				m.put('orderDate',x.AcctSeedERP__Purchase_Order__r.AcctSeedERP__Order_Date__c.format());
			if(x.AcctSeedERP__Purchase_Order__r.AcctSeedERP__Vendor__c != null)
				m.put('vendorName',x.AcctSeedERP__Purchase_Order__r.AcctSeedERP__Vendor__r.Name);
			else
				m.put('vendorName','---none---');

			m.put('productName',x.AcctSeedERP__Product__r.Name);

			if(x.AcctSeedERP__Quantity__c != null)
				m.put('qtyOrdered',String.valueOf(x.AcctSeedERP__Quantity__c.setScale(6)));
			else
				m.put('qtyOrdered','0');

			if(x.AcctSeedERP__Quantity_Unreceived__c != null)
				m.put('qtyUnreceived',String.valueOf(x.AcctSeedERP__Quantity_Unreceived__c.setScale(6)));
			else
				m.put('qtyUnreceived','0');

			listJSON.add(m);
		}

		return listJSON;
	}

	@RemoteAction @ReadOnly 
	public static list<map<String,String>> retrieveProjects(list<Id> listIdProduct, Id pIdWarehouse)
	{
		list<map<String,String>> listJSON = new list<map<String,String>>();

		set<Id> setIdProduct = new set<Id>();
		setIdProduct.addAll(listIdProduct);
		for(AcctSeed__Product_Part__c p : [SELECT AcctSeed__Product_Part__c FROM AcctSeed__Product_Part__c WHERE AcctSeed__Product__c IN:listIdProduct AND AcctSeed__Product__r.Composite_Type__c = 'Kit'])
			setIdProduct.add(p.AcctSeed__Product_Part__c);
		setIdProduct.remove(null);
		Boolean checkDeleted = true;
		if(pIdWarehouse == null) checkDeleted = false;
		for(AcctSeedERP__Material__c x :
			[SELECT AcctSeedERP__Project__c,
					AcctSeedERP__Project__r.RecordType.Name,
					AcctSeedERP__Project__r.AcctSeedERP__Work_Order_Number__c,
					AcctSeedERP__Project__r.Serial_Number__c,
					AcctSeedERP__Project__r.Serial_Number__r.Name,
					AcctSeedERP__Project__r.Serial_Number__r.GMBLASERP__Lot__r.Name,
					AcctSeedERP__Project__r.GMBLASERP__Warehouse__c,
					AcctSeedERP__Project__r.GMBLASERP__Warehouse__r.Name,
					AcctSeedERP__Project__r.Name,
					AcctSeedERP__Project__r.CreatedDate,					
					AcctSeedERP__Product__r.Name,
					AcctSeedERP__Product__r.AcctSeed__Inventory_Product__c,
					AcctSeedERP__Product__r.Composite_Type__c,
					AcctSeedERP__Quantity_Per_Unit__c,
					AcctSeedERP__Quantity_Allocated__c
			 FROM AcctSeedERP__Material__c
			 WHERE AcctSeedERP__Quantity_Per_Unit__c > 0
			  	AND AcctSeedERP__Project__r.Locked__c = false
			  	AND AcctSeedERP__Product__c IN :setIdProduct
			 	AND (IsDeleted =:checkDeleted OR AcctSeedERP__Project__r.GMBLASERP__Warehouse__c =:pIdWarehouse)
			 	AND IsDeleted = false])
		{
			map<String,String> m = new map<String,String>();
			m.put('idProject',x.AcctSeedERP__Project__c);
			m.put('idWarehouse',x.AcctSeedERP__Project__r.GMBLASERP__Warehouse__c);
			m.put('nameWarehouse',x.AcctSeedERP__Project__r.GMBLASERP__Warehouse__r.Name);
			if(x.AcctSeedERP__Project__c != null)
			{
				m.put('projectNumber',String.valueOf(Integer.valueOf(x.AcctSeedERP__Project__r.AcctSeedERP__Work_Order_Number__c.replaceAll('[^0-9]',''))));
				m.put('createdDate',x.AcctSeedERP__Project__r.CreatedDate.date().format());
				m.put('projectName',x.AcctSeedERP__Project__r.Name);
				m.put('projectType',x.AcctSeedERP__Project__r.RecordType.Name);
				if(x.AcctSeedERP__Project__r.Serial_Number__c != null){
					m.put('projectSerial',x.AcctSeedERP__Project__r.Serial_Number__r.Name);
					m.put('projectLot',x.AcctSeedERP__Project__r.Serial_Number__r.GMBLASERP__Lot__r.Name);
				}
			}

			m.put('productName',x.AcctSeedERP__Product__r.Name);
			m.put('compositeType',x.AcctSeedERP__Product__r.Composite_Type__c);
			m.put('isInventory',x.AcctSeedERP__Product__r.AcctSeed__Inventory_Product__c ? 'true' : 'false');

			if(x.AcctSeedERP__Quantity_Per_Unit__c != null)
				m.put('qtySpecified',String.valueOf(x.AcctSeedERP__Quantity_Per_Unit__c.setScale(6)));
			else
				m.put('qtySpecified','0');

			if(x.AcctSeedERP__Quantity_Allocated__c != null)
				m.put('qtyAllocated',String.valueOf(x.AcctSeedERP__Quantity_Allocated__c.setScale(6)));
			else
				m.put('qtyAllocated','0');

			listJSON.add(m);
		}
		return listJSON;
	}

	public static Map<Id,cube> retrieveProducts(Set<Id> setIdProduct, Id pIdWarehouse)
	{
		map<Id,cube> mapCube = new map<Id,cube>();

		list<sObject> listAggRes = new list<sObject>();
		String soql = '';
		//listAggRes.clear();
/*		soql = 'SELECT GMBLASERP__Product__c idProduct,	count(Id) qty FROM GMBLASERP__Serial_Number__c';
		soql += ' WHERE GMBLASERP__Product__c IN:setIdProduct AND Dealer_Rigged__c = true';
		soql += ' AND GMBLASERP__Product__r.RecordType.Name = \'Boat\''; 
		soql += ' AND GMBLASERP__Inventory_Balance__c != null';
		if(pIdWarehouse != null)
			soql += ' AND GMBLASERP__Inventory_Balance__r.AcctSeedERP__Warehouse__c =:pIdWarehouse';
		soql += ' GROUP BY GMBLASERP__Product__c';
		
		listAggRes.addAll(Database.query(soql));
		for(sObject aggRes : listAggRes)
		{
			cube cube = new cube();
			cube.rigged = (Decimal)aggRes.get('qty');
			mapCube.put((Id)aggRes.get('idProduct'), cube);
		}
		//list<AggregateResult> listAggRes = new list<AggregateResult>();
		listAggRes.clear();
		soql = 'SELECT GMBLASERP__Product__c idProduct, count(Id) qty FROM GMBLASERP__Serial_Number__c';
		soql += ' WHERE GMBLASERP__Product__c IN:setIdProduct AND Dealer_Rigged__c = false';
		soql += ' AND GMBLASERP__Product__r.RecordType.Name = \'Boat\'';
		soql += ' AND GMBLASERP__Inventory_Balance__c != null';
		if(pIdWarehouse != null)
			soql += ' AND GMBLASERP__Inventory_Balance__r.AcctSeedERP__Warehouse__c =:pIdWarehouse';
		soql += ' GROUP BY GMBLASERP__Product__c';
		
		listAggRes.addAll(Database.query(soql));
		for(sObject aggRes : listAggRes)
		{
			cube cube = mapCube.get((Id)aggRes.get('idProduct'));
			if(cube == null) cube = new cube();
			cube.notrigged = (Decimal)aggRes.get('qty');
			mapCube.put((Id)aggRes.get('idProduct'), cube);
		}
*/
		listAggRes.clear();
		soql = 'SELECT AcctSeedERP__Product__c idProduct, sum(AcctSeedERP__Available_Quantity__c) qty FROM AcctSeedERP__Inventory_Balance__c';
		soql += ' WHERE AcctSeedERP__Product__c IN:setIdProduct';
		soql += ' AND AcctSeedERP__Product__r.RecordType.Name != \'Boat\'';
		soql += ' AND (AcctSeedERP__Available_Quantity__c < 0 OR AcctSeedERP__Available_Quantity__c > 0)';
		if(pIdWarehouse != null)
			soql += ' AND AcctSeedERP__Warehouse__c =:pIdWarehouse';
		soql += ' GROUP BY AcctSeedERP__Product__c';
		soql += ' HAVING sum(AcctSeedERP__Available_Quantity__c) < 0 OR sum(AcctSeedERP__Available_Quantity__c) > 0';
		
		listAggRes.addAll(Database.query(soql));
		for(sObject aggRes : listAggRes)
		{
			cube cube = mapCube.get((Id)aggRes.get('idProduct'));
			if(cube == null) cube = new cube();
			cube.inventoryParts = (Decimal)aggRes.get('qty');
			mapCube.put((Id)aggRes.get('idProduct'), cube);
		}

		listAggRes.clear();
		soql = 'SELECT AcctSeedERP__Product__c idProduct, sum(AcctSeedERP__Quantity_Unreceived__c) qty FROM AcctSeedERP__Purchase_Order_Line__c';
		soql += ' WHERE AcctSeedERP__Product__c IN:setIdProduct';
		soql += ' AND AcctSeedERP__Quantity_Unreceived__c > 0';
		soql += ' AND AcctSeedERP__Purchase_Order__r.Locked__c = false';
		soql += ' AND AcctSeedERP__Product__r.AcctSeed__Inventory_Product__c = true';
		if(pIdWarehouse != null)
			soql += ' AND (AcctSeedERP__Purchase_Order__r.Warehouse__c =:pIdWarehouse OR AcctSeedERP__Purchase_Order__r.Warehouse__c = null)';
		soql += ' GROUP BY AcctSeedERP__Product__c';
		
		listAggRes.addAll(Database.query(soql));
		for(sObject aggRes : listAggRes)
		{
			cube cube = mapCube.get((Id)aggRes.get('idProduct'));
			if(cube == null) cube = new cube();
			cube.purchasing += (Decimal)aggRes.get('qty');
			mapCube.put((Id)aggRes.get('idProduct'), cube);
		}

		listAggRes.clear();
		soql = 'SELECT AcctSeedERP__Product__c idProduct, sum(AcctSeedERP__Quantity_Per_Unit__c) qty FROM AcctSeedERP__Material__c';
		soql += ' WHERE AcctSeedERP__Product__c IN:setIdProduct';
		soql += ' AND AcctSeedERP__Quantity_Per_Unit__c > 0';
		soql += ' AND AcctSeedERP__Project__r.Locked__c = false';
		if(pIdWarehouse != null)
			soql += ' AND AcctSeedERP__Project__r.GMBLASERP__Warehouse__c =:pIdWarehouse';
		soql += ' GROUP BY AcctSeedERP__Product__c';
		soql += ' HAVING sum(AcctSeedERP__Quantity_Per_Unit__c) > 0';
		
		listAggRes.addAll(Database.query(soql));
		for(sObject aggRes : listAggRes)
		{
			cube cube = mapCube.get((Id)aggRes.get('idProduct'));
			if(cube == null) cube = new cube();
			cube.specified += (Decimal)aggRes.get('qty');
			mapCube.put((Id)aggRes.get('idProduct'), cube);
		}

		listAggRes.clear();
		soql = 'SELECT AcctSeedERP__Product__c idProduct, sum(AcctSeedERP__Quantity_Allocated__c) qty FROM AcctSeedERP__Material__c';
		soql += ' WHERE AcctSeedERP__Product__c IN:setIdProduct';
		soql += ' AND AcctSeedERP__Quantity_Allocated__c > 0';
		soql += ' AND AcctSeedERP__Project__r.Locked__c = false';
		if(pIdWarehouse != null)
			soql += ' AND AcctSeedERP__Project__r.GMBLASERP__Warehouse__c =:pIdWarehouse';
		soql += ' GROUP BY AcctSeedERP__Product__c';
		soql += ' HAVING sum(AcctSeedERP__Quantity_Allocated__c) > 0';
		
		listAggRes.addAll(Database.query(soql));
		for(sObject aggRes : listAggRes)
		{
			cube cube = mapCube.get((Id)aggRes.get('idProduct'));
			if(cube == null) cube = new cube();
			cube.consumed += (Decimal)aggRes.get('qty');
			mapCube.put((Id)aggRes.get('idProduct'), cube);
		}

		mapCube.remove(null);

		return mapCube;
	}

	@RemoteAction @ReadOnly 
	public static list<map<String,String>> retrieveProducts(List<Id> listIdProducts, Id pIdWarehouse, String pIdProductType)
	{
		list<map<string,string>> listJSON = new list<map<String,String>>();
		Set<Id> setIdProducts = new Set<Id>();
		if(!listIdProducts.isEmpty())
		{
			for(AcctSeed__Product_Part__c p : [SELECT AcctSeed__Product_Part__c FROM AcctSeed__Product_Part__c WHERE AcctSeed__Product__c IN:listIdProducts])
				setIdProducts.add(p.AcctSeed__Product_Part__c);
		}else
		{
			if(pIdProductType != 'kit')
				for(Product2 p : [SELECT Id FROM Product2 WHERE AcctSeed__Inventory_Product__c = false AND Composite_Type__c != 'Kit'])
					setIdProducts.add(p.Id);
			else
				for(Product2 p : [SELECT Id FROM Product2 WHERE Composite_Type__c = 'Kit'])
					setIdProducts.add(p.Id);			
		}
		
		Map<Id,cube> mapCube = retrieveProducts(setIdProducts,pIdWarehouse);

		for(Product2 p :
			[SELECT Id, Name, Unique_Product_Code__c, Family, RecordType.Name, AcctSeedERP__Default_Vendor__r.Name, AcctSeed__Inventory_Product__c, Composite_Type__c
			 FROM Product2
			 WHERE Id IN:setIdProducts])
		{
			map<String,String> m = new map<String,String>();
			m.put('idProduct',p.Id);
			m.put('productName',p.Name);
			m.put('supplierName',p.AcctSeedERP__Default_Vendor__r.Name);
			m.put('productCode',(p.Unique_Product_Code__c == null ? '' :p.Unique_Product_Code__c));
			m.put('recordType',p.RecordType.Name);
			m.put('productFamily',p.Family);
			m.put('isInventory',p.AcctSeed__Inventory_Product__c ? 'true' : 'false');
			m.put('compositeType',p.Composite_Type__c == null ? '' : p.Composite_Type__c);

			if(mapCube.containsKey(p.Id))
			{
				cube cube = mapCube.get(p.Id);
				m.put('rigged',String.valueOf(cube.rigged.setScale(6)));
				m.put('notrigged',String.valueOf(cube.notrigged.setScale(6)));
				m.put('inventoryParts',String.valueOf(cube.inventoryParts.setScale(6)));
				m.put('purchasing',String.valueOf(cube.purchasing.setScale(6)));
				m.put('specified',String.valueOf(cube.specified.setScale(6)));
				m.put('consumed',String.valueOf(cube.consumed.setScale(6)));
				Decimal required = cube.specified - cube.consumed;
				m.put('required',String.valueOf(required.setScale(6)));

				Decimal inventory = cube.rigged + cube.notrigged + cube.inventoryParts;
				Decimal expected = cube.rigged + cube.notrigged + cube.inventoryParts + cube.purchasing;

				m.put('inventory', String.valueOf(inventory.setScale(6)));
				m.put('expected', String.valueOf(expected.setScale(6)));
				m.put('available', String.valueOf((expected - required).setScale(6)));
			}
			else
			{
				m.put('rigged','0');
				m.put('notrigged','0');
				m.put('inventoryParts','0');
				m.put('inventory','0');
				m.put('purchasing','0');
				m.put('specified','0');
				m.put('consumed','0');		
				m.put('required','0');		

				m.put('expected','0');		
				m.put('available','0');
			}
			listJSON.add(m);
		}

		return listJSON;
	}

	public class cube
	{
		Decimal rigged;
		Decimal notrigged;
		Decimal inventoryParts;
		Decimal purchasing;
		Decimal specified; 
		Decimal consumed; 

		cube()
		{
			rigged = 0;
			notrigged = 0;
			inventoryParts = 0;
			purchasing = 0;
			specified = 0;
			consumed = 0;
		}
	}

	public static void coverage(){
		integer i;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
	}
}