force-app/main/default/objects/Account/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Accounting_Variable__c/AcctSeed__Accounting_Variable__c.object-meta.xml
<CustomObject>
    <description>Used to categorize or group general ledger transactions, profit centers, cost centers, geographies, or lines of offerings based on business need.</description>
    <label>Accounting Variable</label>
    <nameField>
        <label>Accounting Variable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Variables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Accounting_Variable__c/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Tax Zone must be an Accounting Variable of Type 3.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 3</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Tax Zones (GLV3)</relationshipLabel>
    <relationshipName>Accounting_Variables_GLV3</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Accounting_Variable__c/fields/Tax_is_Harmonized__c.field-meta.xml
<CustomField>
    <fullName>Tax_is_Harmonized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax is Harmonized</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Accounting_Variable__c/fields/Tax_Rate_Retail__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_Retail__c</fullName>
    <label>Tax Rate - Retail</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Legend_Settings__c/Legend_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Legend Settings</label>
</CustomObject>

force-app/main/default/objects/Legend_Settings__c/fields/FederalTaxRate__c.field-meta.xml
<CustomField>
    <fullName>FederalTaxRate__c</fullName>
    <label>FederalTaxRate</label>
    <precision>8</precision>
    <scale>4</scale>
    <type>Percent</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Deposit__c.field-meta.xml
<CustomField>
    <fullName>Deposit__c</fullName>
    <description>Amount of Deposit</description>
    <label>Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Finance_Ammortization__c.field-meta.xml
<CustomField>
    <fullName>Finance_Ammortization__c</fullName>
    <defaultValue>120</defaultValue>
    <label>Finance Ammortization</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Finance_Annual_Interest__c.field-meta.xml
<CustomField>
    <fullName>Finance_Annual_Interest__c</fullName>
    <defaultValue>0.0699</defaultValue>
    <label>Finance Annual Interest</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Finance_Term__c.field-meta.xml
<CustomField>
    <fullName>Finance_Term__c</fullName>
    <defaultValue>60</defaultValue>
    <label>Finance Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Insurance_Term__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Term__c</fullName>
    <defaultValue>60</defaultValue>
    <label>Insurance Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Insurance_Total__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Total__c</fullName>
    <formula>Insurance_Sub_Total__c +  Tax_Amount_Retail__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Insurance Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Pickup_Location__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Location__c</fullName>
    <label>Pickup Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Whitefish - Pick-up</fullName>
            </value>
            <value>
                <fullName>Whitefish - Delivery</fullName>
            </value>
            <value>
                <fullName>Barrie - Pick-up</fullName>
            </value>
            <value>
                <fullName>Barrie - Delivery</fullName>
            </value>
            <value>
                <fullName>Montreal - Pick-up</fullName>
            </value>
            <value>
                <fullName>Montreal - Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Pre_Insurance_Total__c.field-meta.xml
<CustomField>
    <fullName>Pre_Insurance_Total__c</fullName>
    <formula>Amount +  TotalTaxes__c   - Insurance_Total__c -  Trade_In_Value__c +  Trade_In_Lien__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pre-Insurance Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Tax_Amount_Federal__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount_Federal__c</fullName>
    <formula>IF( Amount &lt; Trade_In_Value__c, 0, (Taxable_Amount_Federal__c -  Trade_In_Value__c )  *  Tax_Rate_Federal__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Amount (Federal)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Tax_is_Harmonized__c.field-meta.xml
<CustomField>
    <fullName>Tax_is_Harmonized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax_is_Harmonized</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tax_Rate_Provincial__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_Provincial__c</fullName>
    <label>Tax Rate (Provincial)</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalTaxes__c.field-meta.xml
<CustomField>
    <fullName>TotalTaxes__c</fullName>
    <formula>Tax_Amount_Federal__c +  Tax_Amount_Provincial__c + Tax_Amount_Retail__c</formula>
    <label>Total Taxes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Document__c/Opportunity_Document__c.object-meta.xml
<CustomObject>
    <label>Opportunity Document</label>
    <nameField>
        <label>Opportunity Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Document</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Document__c/fields/Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Id__c</fullName>
    <description>The Id of the Document</description>
    <label>Document Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Opportunity_Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Opportunity_Document__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Document</relationshipLabel>
    <relationshipName>Opportunity_Document</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Deposit__c.field-meta.xml
<CustomField>
    <fullName>Deposit__c</fullName>
    <label>Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Finance_Ammortization__c.field-meta.xml
<CustomField>
    <fullName>Finance_Ammortization__c</fullName>
    <label>Finance Ammortization</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Finance_Annual_Interest__c.field-meta.xml
<CustomField>
    <fullName>Finance_Annual_Interest__c</fullName>
    <label>Finance Annual Interest</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Finance_Term__c.field-meta.xml
<CustomField>
    <fullName>Finance_Term__c</fullName>
    <label>Finance Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Quote/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Quote/fields/Insurance_Term__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Term__c</fullName>
    <defaultValue>60</defaultValue>
    <label>Insurance Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Quote/fields/Insurance_Total__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Total__c</fullName>
    <formula>Insurance_Sub_Total__c + Tax_Amount_Retail__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Insurance Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Quote/fields/Pre_Insurance_Total__c.field-meta.xml
<CustomField>
    <fullName>Pre_Insurance_Total__c</fullName>
    <formula>Subtotal  + TotalTaxes__c - Insurance_Total__c - TradeInValue__c + TradeInLien__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pre-Insurance Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Quote/fields/Tax_Rate_Federal__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_Federal__c</fullName>
    <label>Tax Rate (Federal)</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

src/Base/main/default/objects/Quote/fields/Tax_Rate_Provincial__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_Provincial__c</fullName>
    <label>Tax Rate (Provincial)</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

src/Base/main/default/objects/Quote/fields/Tax_Rate_Retail__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_Retail__c</fullName>
    <label>Tax Rate (Retail)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/Base/main/default/objects/Quote/fields/TotalTaxes__c.field-meta.xml
<CustomField>
    <fullName>TotalTaxes__c</fullName>
    <formula>Tax_Amount_Federal__c + Tax_Amount_Provincial__c + Tax_Amount_Retail__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Taxes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trade_In_Record__c/Trade_In_Record__c.object-meta.xml
<CustomObject>
    <label>Trade In Record</label>
    <nameField>
        <displayFormat>TIR-{0000}</displayFormat>
        <label>Trade In Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trade In Records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade_In_Record__c/fields/Lien_Amount__c.field-meta.xml
<CustomField>
    <fullName>Lien_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lien Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trade_In_Record__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Trade In Records</relationshipLabel>
    <relationshipName>Trade_In_Records</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trade_In_Record__c/fields/Total_Value__c.field-meta.xml
<CustomField>
    <fullName>Total_Value__c</fullName>
    <label>Total Value</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Automation/main/default/classes/Opportunity/Tests/Opportunity_Service_T.cls
@isTest
public class Opportunity_Service_T {
  @testSetup
  static void dataSetup() {
    TA_Opportunity_TestHelper.dataSetup();
  }
  @isTest
  static void taxUpdate_Test() {
    TA_Opportunity_TestHelper.init();
    Account personAccount = AccountFactory.insertPersonAccount();
    AcctSeed__Accounting_Variable__c quebecTaxZone = AcctSeed_Settings_Factory.createTaxZone('Quebec', false, 9.975);
    AcctSeed__Accounting_Variable__c othersTaxZone = AcctSeed_Settings_Factory.createTaxZone('Others', false, 0);
    Decimal defaultFedTaxRate = Legend_Settings__c.getOrgDefaults().FederalTaxRate__c;

    System.runAs(TA_Opportunity_TestHelper.whitefishUser) {
      TA_Opportunity_TestHelper.opp = OpportunityFactory.buildBasicRetail(personAccount.id);
      insert TA_Opportunity_TestHelper.opp;
      //Set new tax zone
      Opportunity oppOld = new Opportunity();
      oppOld = TA_Opportunity_TestHelper.getOldList()[0];
      List<Opportunity> oldlist = new List<Opportunity>{ oppOld };
      TA_Opportunity_TestHelper.opp.GL_Account_Variable_3__c = quebecTaxZone.Id;
      TA_Opportunity_TestHelper.opp.Probability = 1;
      update TA_Opportunity_TestHelper.opp;
      new TA_Opportunity_UpdateTax_BU().beforeUpdate(new List<Opportunity>{ TA_Opportunity_TestHelper.opp }, oldlist);

      System.assertEquals(quebecTaxZone.Id, TA_Opportunity_TestHelper.opp.GL_Account_Variable_3__c);
      System.assertEquals(defaultFedTaxRate, TA_Opportunity_TestHelper.opp.Tax_Rate_Federal__c);
      System.assertEquals(false, TA_Opportunity_TestHelper.opp.Tax_Override__c);

      //Override tax rates
      TA_Opportunity_TestHelper.opp.Tax_Override__c = true;
      TA_Opportunity_TestHelper.opp.Tax_Rate_Provincial__c = 1;
      TA_Opportunity_TestHelper.opp.Tax_Rate_Federal__c = 1;
      update TA_Opportunity_TestHelper.opp;
      TA_Opportunity_TestHelper.opp = [
        SELECT
          Id,
          GL_Account_Variable_3__c,
          Tax_is_Harmonized__c,
          Tax_Override__c,
          Tax_Rate_Provincial__c,
          Tax_Rate_Federal__c,
          Probability
        FROM Opportunity
        WHERE Id = :TA_Opportunity_TestHelper.opp.Id
      ];
      System.assertEquals(true, TA_Opportunity_TestHelper.opp.Tax_Override__c);
      System.assertEquals(quebecTaxZone.Id, TA_Opportunity_TestHelper.opp.GL_Account_Variable_3__c);
      System.assertEquals(1, TA_Opportunity_TestHelper.opp.Tax_Rate_Federal__c);

      //delete the taxZone
      TA_Opportunity_TestHelper.opp.Tax_Override__c = false;
      TA_Opportunity_TestHelper.opp.GL_Account_Variable_3__c = null;
      TA_Opportunity_TestHelper.opp.Probability = null;
      TA_Opportunity_TestHelper.opp.Pickup_Location__c = null;
      update TA_Opportunity_TestHelper.opp;
      new TA_Opportunity_UpdateTax_BU().beforeUpdate(new List<Opportunity>{ TA_Opportunity_TestHelper.opp }, oldlist);
      System.assertEquals(false, TA_Opportunity_TestHelper.opp.Tax_Override__c);
      System.assertEquals(defaultFedTaxRate, TA_Opportunity_TestHelper.opp.Tax_Rate_Federal__c);
    }
  }

  @isTest
  static void setPrimaryConInfo_Test() {
    TA_Opportunity_TestHelper.init();
    Test.startTest();
    Account personAccount = AccountFactory.insertPersonAccount();
    Decimal defaultFedTaxRate = Legend_Settings__c.getOrgDefaults().FederalTaxRate__c;
    System.runAs(TA_Opportunity_TestHelper.whitefishUser) {
      TA_Opportunity_TestHelper.opp = OpportunityFactory.buildBasicRetail(personAccount.id);
      TA_Opportunity_TestHelper.opp.ownerId = TA_Opportunity_TestHelper.whitefishUser.id;
      insert TA_Opportunity_TestHelper.opp;
      new TA_Opportunity_Before_Insert().beforeInsert(new List<Opportunity>{ TA_Opportunity_TestHelper.opp });
      new TA_Opportunity_setPrimaryContactInfo_AI().afterInsert(new List<Opportunity>{ TA_Opportunity_TestHelper.opp });
      List<OpportunityContactRole> oppContactRole = [
        SELECT id
        FROM OpportunityContactRole
        WHERE OpportunityId = :TA_Opportunity_TestHelper.opp.id
      ];
      System.assert(!oppContactRole.isEmpty());
    }
  }

  @isTest
  static void insertOpp_Test() {
    TA_Opportunity_TestHelper.init();
    Test.startTest();
    Account personAccount = AccountFactory.insertPersonAccount();
    Opportunity opp2;
    Decimal defaultFedTaxRate = Legend_Settings__c.getOrgDefaults().FederalTaxRate__c;
    System.runAs(TA_Opportunity_TestHelper.whitefishUser) {
      TA_Opportunity_TestHelper.opp = OpportunityFactory.buildBasicRetail(personAccount.id);
      TA_Opportunity_TestHelper.opp.ownerId = TA_Opportunity_TestHelper.whitefishUser.id;
      insert TA_Opportunity_TestHelper.opp;
      new TA_Opportunity_Before_Insert().beforeInsert(new List<Opportunity>{ TA_Opportunity_TestHelper.opp });
      System.assertEquals(TA_Opportunity_TestHelper.whitefishWarehouse.Id, TA_Opportunity_TestHelper.opp.Warehouse__c);
      System.assertEquals(defaultFedTaxRate, TA_Opportunity_TestHelper.opp.Tax_Rate_Federal__c);
    }
    Test.stopTest();
  }

  @isTest
  static void updateAccountToLegendCustomer_Test() {
    TA_Opportunity_TestHelper.init();
    Account customer = Factory_Account.insertFullPersonAccount('Testy', 'McTesterson');
    Account beforeAcct = [SELECT Id, Type FROM Account WHERE Id = :customer.Id];
    TA_Opportunity_TestHelper.opp = Factory_Opportunity.insertOpportunity(customer, Test.getStandardPricebookId());
    List<Opportunity> oldOpportunities = TA_Opportunity_TestHelper.getOldList();
    Test.startTest();
    TA_Opportunity_TestHelper.opp.Approved__c = true;
    update TA_Opportunity_TestHelper.opp;
    new TA_Opportunity_updateAccountsToCust_AU()
      .afterUpdate(new List<Opportunity>{ TA_Opportunity_TestHelper.opp }, oldOpportunities);
    Test.stopTest();

    Account afterAcct = [SELECT Id, Type FROM Account WHERE Id = :customer.Id];

    System.assert(
      beforeAcct.Type != 'Legend Customer',
      'Account type should not be Legend Customer Pending before Sales manager Approval'
    );
    System.assert(afterAcct.Type == 'Legend Customer', 'Account type should now be Legend Customer');
  }

  @isTest
  static void deleteOpportunityDocuments_Test() {
    TA_Opportunity_TestHelper.init();
    Account personAccount = AccountFactory.insertPersonAccount();
    TA_Opportunity_TestHelper.opp = OpportunityFactory.buildBasicRetail(personAccount.id);
    insert TA_Opportunity_TestHelper.opp;
    TA_Opportunity_TestHelper.opp = [
      SELECT
        Id,
        GL_Account_Variable_3__c,
        Tax_is_Harmonized__c,
        Tax_Override__c,
        Tax_Rate_Provincial__c,
        Tax_Rate_Federal__c,
        Warehouse__c
      FROM Opportunity
      WHERE Id = :TA_Opportunity_TestHelper.opp.Id
    ];
    Opportunity_Document__c document = new Opportunity_Document__c(
      Document_Id__c = '0157h000000clFFABY',
      Name = 'Test',
      Document_Type__c = 'Quote',
      Opportunity__c = TA_Opportunity_TestHelper.opp.id
    );
    insert document;
    new TA_Opportunity_DeleteOppDocuments_AD().afterDelete(new List<Opportunity>{ TA_Opportunity_TestHelper.opp });
    List<Opportunity_Document__c> documents = [
      SELECT id
      FROM Opportunity_Document__c
      WHERE Opportunity__c = :TA_Opportunity_TestHelper.opp.id
    ];
    System.assert(documents.isEmpty());
  }

  @isTest
  static void recalculateInsurance_Test() {
    TA_Opportunity_TestHelper.init();
    Account customer = Factory_Account.insertFullPersonAccount('Testy', 'McTesterson');
    Account beforeAcct = [SELECT Id, Type FROM Account WHERE Id = :customer.Id];
    TA_Opportunity_TestHelper.opp = Factory_Opportunity.insertOpportunity(customer,Test_Constants.idRetailPricebook);
    TA_Opportunity_TestHelper.createOpportunityLineItem();
    List<Opportunity> oldOpportunities = TA_Opportunity_TestHelper.getOldList();
    Test.startTest();
    TA_Opportunity_TestHelper.opp.Finance_Term__c = 7;
    TA_Opportunity_TestHelper.opp.Deposit__c = 1000;
    TA_Opportunity_TestHelper.opp.Finance_Annual_Interest__c = 10;
    TA_Opportunity_TestHelper.opp.Finance_Ammortization__c = 100;
    TA_Opportunity_TestHelper.opp.Insurance_Term__c = 9;
    TA_Opportunity_TestHelper.opp.amount = 100;
    TA_Opportunity_TestHelper.opp.amount = 100;
    TA_Opportunity_TestHelper.opp.Tax_Rate_Federal__c = 10;
    TA_Opportunity_TestHelper.opp.Tax_Rate_Retail__c = 10;
    TA_Opportunity_TestHelper.opp.GL_Account_Variable_3__c = gcConstants.idGlv3Ontario;
//    Trade_In_Record__c trade = new Trade_In_Record__c(
//      Lien_Amount__c = 1000,
//      Opportunity__c = TA_Opportunity_TestHelper.opp.id,
//      Total_Value__c = 10000
//    );
//    insert trade;

    update TA_Opportunity_TestHelper.opp;
    TA_Opportunity_TestHelper.opp = [
      SELECT
        id,
        Pre_Insurance_Total__c,
        Name,
        AccountId,
        Pricebook2Id,
        StageName,
        CloseDate,
        Finance_Term__c,
        Finance_Annual_Interest__c,
        Finance_Ammortization__c,
        Insurance_Term__c,
        Amount,
        Tax_Rate_Federal__c,
        Tax_Rate_Retail__c,
        TotalTaxes__c,
        Tax_Amount_Federal__c,
        Tax_Amount_Provincial__c,
        Tax_Amount_Retail__c,
        Insurance_Total__c,
        Trade_In_Value__c,
        Trade_In_Lien__c,
        Deposit__c,
        GL_Account_Variable_3__c
      FROM Opportunity
      WHERE id = :TA_Opportunity_TestHelper.opp.id
    ];
    new TA_Opportunity_RecalcInsuranceLines_AU()
      .afterUpdate(new List<Opportunity>{ TA_Opportunity_TestHelper.opp }, oldOpportunities);
    System.assertEquals(TA_Opportunity_TestHelper.opp.Insurance_Term__c, 9);
    System.assertEquals(TA_Opportunity_TestHelper.opp.Finance_Annual_Interest__c, 10);
    Test.stopTest();
  }
}