force-app/main/default/objects/Account/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Location/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>FSLLocations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Boat_Model_Year__c.field-meta.xml
<CustomField>
    <fullName>Boat_Model_Year__c</fullName>
    <label>Boat Model Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Boat_Specialist_Id__c.field-meta.xml
<CustomField>
    <fullName>Boat_Specialist_Id__c</fullName>
    <formula>Account.Boat_Specialist__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Boat Specialist Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BoatId__c.field-meta.xml
<CustomField>
    <fullName>BoatId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Boat Model</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Business_Manager__c.field-meta.xml
<CustomField>
    <fullName>Business_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The business Manager for this Opportunity</description>
    <label>Business Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contract_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Contract_Start_Date__c</fullName>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Customer_Notes__c.field-meta.xml
<CustomField>
    <fullName>Customer_Notes__c</fullName>
    <label>Customer Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Date the customer received his product</description>
    <label>Delivery Date</label>
    <type>DateTime</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Deposit__c.field-meta.xml
<CustomField>
    <fullName>Deposit__c</fullName>
    <description>Amount of Deposit</description>
    <label>Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Deposit_Method__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Method__c</fullName>
    <label>Deposit Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Master Card</fullName>
            </value>
            <value>
                <fullName>AMEX</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Finance_Ammortization__c.field-meta.xml
<CustomField>
    <fullName>Finance_Ammortization__c</fullName>
    <defaultValue>120</defaultValue>
    <label>Finance Ammortization</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Finance_Annual_Interest__c.field-meta.xml
<CustomField>
    <fullName>Finance_Annual_Interest__c</fullName>
    <defaultValue>0.0699</defaultValue>
    <label>Finance Annual Interest</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Finance_Compound__c.field-meta.xml
<CustomField>
    <fullName>Finance_Compound__c</fullName>
    <defaultValue>12</defaultValue>
    <label>Finance Compound Per Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Finance_Payments_Per_Year__c.field-meta.xml
<CustomField>
    <fullName>Finance_Payments_Per_Year__c</fullName>
    <defaultValue>12</defaultValue>
    <label>Finance Payments Per Year</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Finance_Status__c.field-meta.xml
<CustomField>
    <fullName>Finance_Status__c</fullName>
    <description>Financing status</description>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Payment_Method__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Approved with Conditions</fullName>
            </value>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Balance Owing</fullName>
            </value>
            <value>
                <fullName>Paid in Full</fullName>
            </value>
            <value>
                <fullName>Balance at Pickup</fullName>
            </value>
            <value>
                <fullName>Declined but Working</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Finance_Term__c.field-meta.xml
<CustomField>
    <fullName>Finance_Term__c</fullName>
    <defaultValue>60</defaultValue>
    <label>Finance Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>First_Payment_Date__c</fullName>
    <label>First Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Insurance_Term__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Term__c</fullName>
    <defaultValue>60</defaultValue>
    <label>Insurance Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <displayFormat>INV-{00000}</displayFormat>
    <label>InvoiceNumber</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IsPickupDealershipPartner__c.field-meta.xml
<CustomField>
    <fullName>IsPickupDealershipPartner__c</fullName>
    <formula>NOT( PickupDealership__r.Is_Internal__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Pickup Dealership a Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/On_Water_Orientation__c.field-meta.xml
<CustomField>
    <fullName>On_Water_Orientation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Water Orientation</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <description>Indicates whether the customer is financing or paying cash for the products</description>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>American Express</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
                <default>true</default>
                <label>Finance</label>
            </value>
            <value>
                <fullName>Gift Card</fullName>
            </value>
            <value>
                <fullName>Mastercard</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Pickup_Location__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Location__c</fullName>
    <label>Pickup Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Whitefish - Pick-up</fullName>
            </value>
            <value>
                <fullName>Whitefish - Delivery</fullName>
            </value>
            <value>
                <fullName>Barrie - Pick-up</fullName>
            </value>
            <value>
                <fullName>Barrie - Delivery</fullName>
            </value>
            <value>
                <fullName>Montreal - Pick-up</fullName>
            </value>
            <value>
                <fullName>Montreal - Delivery</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/PickupDealership__c.field-meta.xml
<CustomField>
    <fullName>PickupDealership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Dealership/Partner where the Online Boat Reservation/purchase will be picked up</description>
    <inlineHelpText>The Dealership/Partner where the Online Boat Reservation/purchase will be picked up</inlineHelpText>
    <label>Pickup Dealership</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Pickup Dealership must be a Dealer Account</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Online Boat Sale Opportunities</relationshipLabel>
    <relationshipName>OnlineBoatSalePickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Reference_Number__c</fullName>
    <displayFormat>{000000}</displayFormat>
    <label>Reference Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tax_Rate_Provincial__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate_Provincial__c</fullName>
    <label>Tax Rate (Provincial)</label>
    <precision>5</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>Amount  +  TotalTaxes__c - Trade_In_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trade_In_Amount__c.field-meta.xml
<CustomField>
    <fullName>Trade_In_Amount__c</fullName>
    <label>Trade In Amount</label>
    <summarizedField>Trade_In_Record__c.Total_Applied__c</summarizedField>
    <summaryForeignKey>Trade_In_Record__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trade_In_Value__c.field-meta.xml
<CustomField>
    <fullName>Trade_In_Value__c</fullName>
    <label>Trade In Value</label>
    <summarizedField>Trade_In_Record__c.Total_Value__c</summarizedField>
    <summaryForeignKey>Trade_In_Record__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Trailer_Model_Year__c.field-meta.xml
<CustomField>
    <fullName>Trailer_Model_Year__c</fullName>
    <label>Trailer Model Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Retail.recordType-meta.xml
<RecordType>
    <fullName>Retail</fullName>
    <active>true</active>
    <businessProcess>Retail Sales Process</businessProcess>
    <description>Retail Sale</description>
    <label>Retail</label>
</RecordType>

src/Base/main/default/classes/Opportunity_Selector.cls
/**
 * Created by dave on 2019-08-06.
 */

public inherited sharing class Opportunity_Selector Extends Application_Selector {

  public Opportunity_Selector()
  {
    this.sObjectName = 'Opportunity';
    this.fields = new List<String>{
      'Id',
      'CampaignId',
      'LeadSource',
      'Name',
      'RecordTypeId',
      'RecordType.Name',
      'Trade_In_Amount__c',
      'Trade_In_Value__c',
      'Business_Manager__c',
      'Warehouse__c',
      'Deposit__c',
      'Deposit_Method__c',
      'On_Water_Orientation__c',
      'Finance_Status__c',
      'Customer_Notes__c',
      'Pricebook2Id',
      'ContactEmail__c',
      'OwnerId',
      'Owner.Name',
      'AccountId',
      'Account.Name',
      'Total_Amount__c',
      'BoatId__c',
      'StageName',
      'BoatId__r.Name',
      'Pickup_Location__c',
      'Delivery_Date__c',
      'Payment_Method__c',
      'InvoiceNumber__c',
      'Reference_Number__c',
      'GL_Account_Variable_3__c',
      'Insurance_Term__c',
      'Finance_Term__c',
      'Finance_Annual_Interest__c',
      'Finance_Ammortization__c',
      'Finance_Payments_Per_Year__c',
      'Finance_Compound__c',
      'Tax_Override__c',
      'Tax_Rate_Federal__c',
      'Tax_Rate_Provincial__c',
      'Tax_Rate_Retail__c',
      'Boat_Specialist_Id__c',
      'Boat_Model_Year__c',
      'Trailer_Model_Year__c',
      'IsPickupDealershipPartner__c',
      'PickupDealership__c',
      'PickupDealership__r.Id',
      'PickupDealership__r.Name',
      'Contract_Start_Date__c',
      'First_Payment_Date__c'
    };
  }

  public static Opportunity[] allByIds( Set<Id> ids )
  {
    Opportunity_Selector selector = new Opportunity_Selector();
    selector.addWhereIdIn( ids );
    return selector.query();
  }

  public static Opportunity[] allSchedulableRetailBoatSaleByLocation( String warehouseName )
  {
    String locString = '%' + warehouseName + '%';
    Id oppBoatSaleRT = LGND_Utilities.recordTypeIdFromName('Opportunity', 'Retail');
    Opportunity_Selector selector = new Opportunity_Selector();
    selector
      .addWhere('RecordTYpeId = \'' + oppBoatSaleRT + '\'')
      .addWhere( '(Pickup_Location__c LIKE \'' + locString + '\' OR Pickup_Location__c = null)')
      .addWhere( 'Delivery_Date__c = null')
      .addWhere('Probability > 69')
      .addWhere('Probability < 100')
      .addOrderBy('Pickup_Location__c DESC');
    return selector.query();
  }

  public static Opportunity[] allRetailBoatSaleByLocationAndDeliveryDateRange( String location,
                                                                                Date startDate,
                                                                                Date endDate )
  {
    String locString = '%' + location + '%';
    Opportunity_Selector selector = new Opportunity_Selector();
    selector
      .addWhere('Probability < 100' )
      .addWhere('Probability > 0' )
      .addWhere('Pickup_Location__c LIKE \'' + locString + '\'')
      .addWhere('Delivery_Date__c >= ' + toDateString( startDate ) )
      .addWhere('Delivery_Date__c <= ' + toDateString( endDate ) );
    return selector.query();
  }

  public static Opportunity[] selectAllByIdWithLineItems( Set<Id> oppIds )
  {
    OpportunityLineItem_Selector oliSelector = new OpportunityLineItem_Selector();
    return new Opportunity_Selector()
      .addWhereIdIn( oppIds )
      .addChildQuery( oliSelector )
      .query();
  }

}