force-app/main/default/objects/AcctSeedERP__Material__c/AcctSeedERP__Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <displayFormat>MAT-{00000}</displayFormat>
        <label>Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Project_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Quantity_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Quantity_Per_Unit__c</fullName>
    <label>Quantity Ordered</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/Case_Part__c.field-meta.xml
<CustomField>
    <fullName>Case_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Part</label>
    <referenceTo>Case_Part__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>AcctSeedERP__Material__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Part__c/Case_Part__c.object-meta.xml
<CustomObject>
    <label>Case Part</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Part__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Parts</relationshipLabel>
    <relationshipName>Case_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/objects/Case_Part__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>AcctSeedERP__Material__c</referenceTo>
    <relationshipLabel>Case Parts</relationshipLabel>
    <relationshipName>Case_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Case_Part__c/fields/Order_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Order_Quantity__c</fullName>
    <description>Number of quantity to order automatically in Parts Order from Claim</description>
    <label>Order Quantity</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Case_Part__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Case Parts</relationshipLabel>
    <relationshipName>Case_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Case_Part__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case_Part__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Product2/recordTypes/Part.recordType-meta.xml
<RecordType>
    <fullName>Part</fullName>
    <active>true</active>
    <description>Part</description>
    <label>Part</label>
</RecordType>

src/Base/main/default/classes/Factory_CasePart.cls
/**
 * Created by dave on 2019-11-15.
 */
@IsTest
public class Factory_CasePart
{

  public static List<Case_Part__c> create( Case theCase, Integer count )
  {
    List<Case_Part__c> result = new List<Case_Part__c>();
    for( Product2 p : Factory_Product.createNonSerializedProducts('Part', 'Electronics', count) )
    {
      result.add( new Case_Part__c(
        Case__c = theCase.Id,
        Product__c = p.Id,
        Order_Quantity__c = 1,
        Unit_Price__c = 10
      ) );
    }
    insert result;
    return result;
  }

  public static List<Case_Part__c> create(
    Id caseId,
    List<AcctSeedERP__Material__c> materials
  )
  {
    List<Case_Part__c> result = new List<Case_Part__c>();
    for( AcctSeedERP__Material__c mat : materials )
    {
      result.add( new Case_Part__c(
        Case__c = caseId,
        Material__c = mat.Id,
        Product__c = mat.AcctSeedERP__Product__c,
        Quantity__c = mat.AcctSeedERP__Quantity_Per_Unit__c
      ));
    }
    insert result;
    return result;
  }

}