force-app/main/default/objects/AcctSeedERP__Material__c/AcctSeedERP__Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <displayFormat>MAT-{00000}</displayFormat>
        <label>Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Partner_Program_Settings__c/Partner_Program_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Partner Program Settings</label>
</CustomObject>

force-app/main/default/objects/Partner_Program_Settings__c/fields/Kickstart_Booking_Order_Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Kickstart_Booking_Order_Discount_Percent__c</fullName>
    <description>The discount percentage offered by the Partner Program - Kickstart Booking Order Discount</description>
    <label>Kickstart Booking Order Discount Percent</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/PartnerProgram_Kickstart_Booking.cls
/**
 * Created by dave on 2020-08-28.
 */

public with sharing class PartnerProgram_Kickstart_Booking extends PartnerProgramItem
{

  public PartnerProgram_Kickstart_Booking()
  {
    this.name = 'Kickstart Booking Order Discount';
  }

  public override Boolean isApplicable()
  {
    return this.orderWrapper.isBookingOrder && this.erpWrappers.size() > 0;
  }

  public override List<AcctSeedERP__Material__c> apply()
  {
    return this.doStandardApply();
  }

  protected override void filterApplicableERPs( List<PartnerProgram_Service.ErpWrapper> erpWrappers )
  {
    for( PartnerProgram_Service.ErpWrapper wrapper : erpWrappers )
    {
      if( wrapper.boatLine != null )
        this.erpWrappers.add( wrapper );
    }
  }

  protected override Decimal determineSavingsPercent()
  {
    return Partner_Program_Settings__c.getOrgDefaults().Kickstart_Booking_Order_Discount_Percent__c;
  }

}