force-app/main/default/objects/AcctSeedERP__Material__c/AcctSeedERP__Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <displayFormat>MAT-{00000}</displayFormat>
        <label>Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>AcctSeedERP__Material__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/CommissionLineItem2__c/CommissionLineItem2__c.object-meta.xml
<CustomObject>
    <label>Commission Line Item</label>
    <nameField>
        <displayFormat>CommLineItem-{0000}</displayFormat>
        <label>Commission Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CommissionLineItem2__c/fields/Commission_Rate__c.field-meta.xml
<CustomField>
    <fullName>Commission_Rate__c</fullName>
    <label>Commission Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/Base/main/default/objects/CommissionLineItem2__c/fields/CommissionRecord2__c.field-meta.xml
<CustomField>
    <fullName>CommissionRecord2__c</fullName>
    <label>Commission Record</label>
    <referenceTo>CommissionRecord2__c</referenceTo>
    <relationshipLabel>Commission Line Items</relationshipLabel>
    <relationshipName>Commission_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CommissionLineItem2__c/fields/Labour_Cost__c.field-meta.xml
<CustomField>
    <fullName>Labour_Cost__c</fullName>
    <label>Labour Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CommissionLineItem2__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>AcctSeedERP__Material__c</referenceTo>
    <relationshipLabel>Commission Line Items</relationshipLabel>
    <relationshipName>Commission_Line_Items2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CommissionLineItem2__c/fields/Payment_Based_on_Profit__c.field-meta.xml
<CustomField>
    <fullName>Payment_Based_on_Profit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If TRUE, the commission payment amount is a percentage of the profit amount
if FALSE, the commission payment amount is a percentage of the sale amount</description>
    <label>Payment Based on Profit</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/CommissionLineItem2__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Commission Line Items</relationshipLabel>
    <relationshipName>CommissionLineItems2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/CommissionLineItem2__c/fields/Product_Retail_Rigging_Time__c.field-meta.xml
<CustomField>
    <fullName>Product_Retail_Rigging_Time__c</fullName>
    <formula>Product__r.Rigging_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product_Retail_Rigging_Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CommissionLineItem2__c/fields/Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>Sale_Price__c</fullName>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CommissionLineItem2__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <formula>Quantity__c * ( NULLVALUE( Cost__c, 0 ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CommissionLineItem2__c/fields/Total_Labour__c.field-meta.xml
<CustomField>
    <fullName>Total_Labour__c</fullName>
    <formula>Quantity__c * ( NULLVALUE(  Labour_Cost__c , 0 ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Labour</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CommissionLineItem2__c/fields/Total_Sale__c.field-meta.xml
<CustomField>
    <fullName>Total_Sale__c</fullName>
    <formula>Quantity__c * ( NULLVALUE( Sale_Price__c, 0 ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Sale</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CommissionRecord2__c/CommissionRecord2__c.object-meta.xml
<CustomObject>
    <label>Commission Record</label>
    <nameField>
        <displayFormat>CommRec-{0000}</displayFormat>
        <label>Commission Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommissionRecord2__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Disputed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeedERP__Serialized__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Serialized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Serialized</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Commission_Rate__c.field-meta.xml
<CustomField>
    <fullName>Commission_Rate__c</fullName>
    <description>Field to set the commission percentage available</description>
    <label>Commission Rate</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

src/Base/main/default/objects/Product2/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

src/Base/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field used to determine status of a part</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending_Approval</fullName>
                <default>true</default>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>Approved for Use</fullName>
            </value>
            <value>
                <fullName>Do_Not_Use</fullName>
                <label>Do Not Use</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CommissionLineItem2_Selector.cls
/**
 * Created by dave on 2020-02-05.
 */

public with sharing class CommissionLineItem2_Selector extends Application_Selector
{

  public CommissionLineItem2_Selector()
  {
    this.sObjectName = 'CommissionLineItem2__c';
    this.fields = new List<String>{
      'Id',
      'CommissionRecord2__c',
      'CommissionRecord2__r.Status__c',
      'Quantity__c',
      'Sale_Price__c',
      'Total_Sale__c',
      'Cost__c',
      'Total_Cost__c',
      'Labour_Cost__c',
      'Total_Labour__c',
      'Product_Retail_Rigging_Time__c',
      'Profit__c',
      'Payment_Based_on_Profit__c',
      'Payment_Amount__c',
      'Description__c',
      'Product__c',
      'Product__r.Name',
      'Commission_Rate__c',
      'Comment__c',
      'Material__c',
      'Material__r.Material__c'
    };
  }

  public static List<CommissionLineItem2__c> allById( Set<Id> ids )
  {
    CommissionLineItem2_Selector selector = new CommissionLineItem2_Selector();
    selector
      .addWhere( whereInClauseBuilder(
        'Id',
        (Set<String>)JSON.deserialize( JSON.serialize(ids), Set<String>.class)
      ))
      .addOrderBy( 'Description__c DESC, Product__r.AcctSeedERP__Serialized__c DESC, Product__r.RecordType.Name' );
    return (List<CommissionLineItem2__c>)selector.query();
//    return [ SELECT Id,
//      CommissionRecord2__c,
//      CommissionRecord2__r.Status__c,
//      Quantity__c,
//      Sale_Price__c,
//      Total_Sale__c,
//      Cost__c,
//      Total_Cost__c,
//      Labour_Cost__c,
//      Product_Retail_Rigging_Time__c,
//      Profit__c,
//      Payment_Amount__c,
//      Description__c,
//      Product__c,
//      Product__r.Name,
//      Commission_Rate__c,
//      Comment__c,
//      Material__c,
//      Material__r.Material__c
//    FROM CommissionLineItem2__c
//    WHERE Id In :ids
//    ORDER BY Description__c DESC, Product__r.AcctSeedERP__Serialized__c DESC, Product__r.RecordType.Name];
  }

  public static List<CommissionLineItem2__c> allByCommissionRecordId( String comRecId )
  {
    CommissionLineItem2_Selector selector = new CommissionLineItem2_Selector();
    selector
      .addWhere( 'CommissionRecord2__c = \'' + comRecId + '\'' )
      .addOrderBy( 'Description__c DESC, Product__r.AcctSeedERP__Serialized__c DESC, Product__r.RecordType.Name' );
    return (List<CommissionLineItem2__c>)selector.query();
//    return [ SELECT Id,
//                    CommissionRecord2__c,
//                    CommissionRecord2__r.Status__c,
//                    Quantity__c,
//                    Sale_Price__c,
//                    Total_Sale__c,
//                    Cost__c,
//                    Total_Cost__c,
//                    Labour_Cost__c,
//                    Product_Retail_Rigging_Time__c,
//                    Profit__c,
//                    Payment_Amount__c,
//                    Description__c,
//                    Product__c,
//                    Product__r.Name,
//                    Commission_Rate__c,
//                    Comment__c,
//                    Material__c,
//                    Material__r.Material__c
//             FROM CommissionLineItem2__c
//             WHERE CommissionRecord2__c = :comRecId
//             ORDER BY Description__c DESC, Product__r.AcctSeedERP__Serialized__c DESC, Product__r.RecordType.Name];
  }

  public static List<CommissionLineItem2__c> allByMaterialIds( Set<Id> matIds )
  {
    CommissionLineItem2_Selector selector = new CommissionLineItem2_Selector();
    selector
      .addWhere( whereInClauseBuilder(
        'Material__c',
        (Set<String>)JSON.deserialize( JSON.serialize(matIds), Set<String>.class)
      ))
      .addOrderBy( 'Description__c DESC, Product__r.AcctSeedERP__Serialized__c DESC, Product__r.RecordType.Name' );
    return (List<CommissionLineItem2__c>)selector.query();
//    return [ SELECT Id,
//      CommissionRecord2__c,
//      CommissionRecord2__r.Status__c,
//      Quantity__c,
//      Sale_Price__c,
//      Total_Sale__c,
//      Cost__c,
//      Total_Cost__c,
//      Labour_Cost__c,
//      Product_Retail_Rigging_Time__c,
//      Profit__c,
//      Payment_Amount__c,
//      Description__c,
//      Product__c,
//      Product__r.Name,
//      Commission_Rate__c,
//      Comment__c,
//      Material__c,
//      Material__r.Material__c
//    FROM CommissionLineItem2__c
//    WHERE Material__c IN :matIds
//    ORDER BY Description__c DESC, Product__r.AcctSeedERP__Serialized__c DESC, Product__r.RecordType.Name];
  }
}