force-app/main/default/objects/AcctSeedERP__Material__c/AcctSeedERP__Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <displayFormat>MAT-{00000}</displayFormat>
        <label>Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/Applied_Partner_Program_Discount__c.field-meta.xml
<CustomField>
    <fullName>Applied_Partner_Program_Discount__c</fullName>
    <label>Applied Partner Program Discount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dealer_Order__c/Dealer_Order__c.object-meta.xml
<CustomObject>
    <label>Dealer Order</label>
    <nameField>
        <displayFormat>DealerOrder-{0000}</displayFormat>
        <label>Dealer Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_Order__c/fields/Program_Year__c.field-meta.xml
<CustomField>
    <fullName>Program_Year__c</fullName>
    <label>Program Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/BoatReservation/src/Base/main/default/objects/Partner_Volume_Level__mdt/Partner_Volume_Level__mdt.object-meta.xml
<CustomObject>
    <description>A level representing what percent of discount is applied if the order falls in between the nin and max</description>
    <label>Partner Volume  Level</label>
    <pluralLabel>Partner Volume  Levels</pluralLabel>
</CustomObject>

src/Base/main/default/objects/Partner_Volume_Level__mdt/fields/Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percent__c</fullName>
    <description>The percent discount this level applies</description>
    <inlineHelpText>The percent discount this level applies</inlineHelpText>
    <label>Discount Percent</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/BoatReservation/src/Base/main/default/objects/Partner_Volume_Level__mdt/fields/Lower_Limit__c.field-meta.xml
<CustomField>
    <fullName>Lower_Limit__c</fullName>
    <description>The lowest point at which this level begins, equal to or greater than</description>
    <inlineHelpText>The lowest point at which this level begins, equal to or greater than</inlineHelpText>
    <label>Lower Limit</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/BoatReservation/src/Base/main/default/objects/Partner_Volume_Level__mdt/fields/Partner_Volume_Program__c.field-meta.xml
<CustomField>
    <fullName>Partner_Volume_Program__c</fullName>
    <description>The Volume Program this Level is used with</description>
    <inlineHelpText>The Volume Program this Level is used with</inlineHelpText>
    <label>Partner Volume Program</label>
    <referenceTo>Partner_Volume_Program__mdt</referenceTo>
    <relationshipLabel>Partner Volume  Levels</relationshipLabel>
    <relationshipName>Partner_Volume_Levels</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

src/BoatReservation/src/Base/main/default/objects/Partner_Volume_Level__mdt/fields/Upper_Limit__c.field-meta.xml
<CustomField>
    <fullName>Upper_Limit__c</fullName>
    <description>The point at which this level ends, equal to or greater than.
***Leave blank if you want to express this level applies to anything equal to or greater than the Lower Limit</description>
    <inlineHelpText>The point at which this level ends, equal to or greater than.
***Leave blank if you want to express this level applies to anything equal to or greater than the Lower Limit</inlineHelpText>
    <label>Upper Limit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/BoatReservation/src/Base/main/default/objects/Partner_Volume_Program__mdt/Partner_Volume_Program__mdt.object-meta.xml
<CustomObject>
    <description>Partner Volume Programs based on Program Year</description>
    <label>Partner Volume Program</label>
    <pluralLabel>Partner Volume Programs</pluralLabel>
</CustomObject>

src/BoatReservation/src/Base/main/default/objects/Partner_Volume_Program__mdt/fields/Program_Year__c.field-meta.xml
<CustomField>
    <fullName>Program_Year__c</fullName>
    <description>The Program Year this Program is valid for</description>
    <label>Program Year</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/BoatReservation/src/Base/main/default/objects/Partner_Volume_Program__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>The type of Boat this Volume Program applies to</description>
    <inlineHelpText>The type of Boat this Volume Program applies to</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>V Hull</fullName>
                <default>true</default>
                <label>V Hull</label>
            </value>
            <value>
                <fullName>Pontoon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/classes/PartnerProgramItem.cls
/**
 * Created by dave on 2020-07-24.
 */

public virtual class PartnerProgramItem implements PartnerProgramItem_I, Promise.Deferred
{
  @TestVisible
  protected String name;
  protected String bookingOrderFieldName;
  protected final String volumeType;
  protected Decimal volumeLevel=0;

  public Dealer_Order__c dealerOrder;
  public String programYear;
  public List<PartnerProgram_Service.ErpWrapper> erpWrappers;
  public PartnerProgram_Service.DealerOrderWrapper orderWrapper;

  protected PartnerProgram_Service.ResultMessage resultMessage;
  protected Boolean hasVerifiedBookingOrder = false;
  protected Decimal discountPercent {
    get {
      if( discountPercent == null )
      {
        discountPercent = determineSavingsPercent();
      }
      return discountPercent;
    }
    set {
      if(value == null) discountPercent = 0;
      else discountPercent = value;
    }
  }

  public PartnerProgramItem()
  {
    this.name = 'Default Partner Program Item Name';
  }

  public virtual void init( PartnerProgram_Service.DealerOrderWrapper orderWrapper )
  {
    this.orderWrapper = orderWrapper;
    this.dealerOrder = orderWrapper.dealerOrder;
    this.programYear = orderWrapper.programYear;
    this.erpWrappers = new List<PartnerProgram_Service.ErpWrapper>();
    this.resultMessage = new PartnerProgram_Service.ResultMessage();
    if( !this.orderWrapper.isBookingOrder && this.orderWrapper.bookingOrder != null )
    {
      this.hasVerifiedBookingOrder = true;
    }
    filterApplicableERPs( orderWrapper.erpWrappers );
    this.calculateVolumeLevel();
  }

  public virtual String getName()
  {
    return this.name;
  }

  public PartnerProgram_Service.DealerOrderWrapper getOrderWrapper()
  {
    return this.orderWrapper;
  }

  public virtual String getBookingOrderFieldName()
  {
    return this.bookingOrderFieldName;
  }

  public virtual Decimal getDiscountPercent()
  {
    return this.discountPercent.stripTrailingZeros();
  }

  public virtual PartnerProgram_Service.ResultMessage getResult()
  {
    return this.resultMessage;
  }

  public virtual Boolean isApplicable()
  {
    return false;
  }

  public virtual Boolean wasAppliedPreviously()
  {
    if( this.erpWrappers.size() == 0 ) return false;
    if( this.name == null ) return false;
    if( this.orderWrapper.appliedPrograms.contains( this.name ) ) return true;
    return false;
  }

  public virtual List<AcctSeedERP__Material__c> apply()
  {
    List<AcctSeedERP__Material__c> discounts = new List<AcctSeedERP__Material__c>();
    return discounts;
  }

  public virtual List<AcctSeedERP__Material__c> revert()
  {
    List<AcctSeedERP__Material__c> todelete = new List<AcctSeedERP__Material__c>();
    for( PartnerProgram_Service.ErpWrapper wrapper : this.erpWrappers )
    {
      for( AcctSeedERP__Material__c saving : wrapper.savingLines )
      {
        if( saving.Applied_Partner_Program_Discount__c ==  this.name )
          todelete.add(saving);
      }
    }
    return toDelete;
  }

  public Object resolve( Object dealerOrderWrapper )
  {
    PartnerProgram_Service.DealerOrderWrapper wrapper = (PartnerProgram_Service.DealerOrderWrapper)dealerOrderWrapper;
    Decimal percent = null;
    init( wrapper );
    Boolean updateDealerOrder = false;
    if( this.isApplicable() )
    {
      List<AcctSeedERP__Material__c> discountLines = this.apply();
      if( !wrapper.checkOnly ) upsert discountLines;
      percent = this.getDiscountPercent();
      wrapper.appliedPrograms.add( this.getName() );
      wrapper.result.addAppliedDiscount( this );
      updateDealerOrder = !wrapper.checkOnly;
    }
    else
    {
      if( this.wasAppliedPreviously() )
      {
        List<AcctSeedERP__Material__c> deleteMats = this.revert();
        if( !wrapper.checkOnly ) delete deleteMats;
        wrapper.appliedPrograms.remove( this.getName() );
        updateDealerOrder = !wrapper.checkOnly;
      }
    }

    if( wrapper.isBookingOrder &&
        wrapper.bookingOrder != null &&
        this.getBookingOrderFieldName() != null )
    {
      wrapper.bookingOrder.put(
        this.getBookingOrderFieldName(),
        percent
      );
      if( !wrapper.checkOnly ) upsert wrapper.bookingOrder;
    }
    if( updateDealerOrder )
      wrapper.updateDealerOrder();
    return wrapper;
  }

  protected virtual void filterApplicableERPs( List<PartnerProgram_Service.ErpWrapper> erpWrappers )
  {
    this.erpWrappers = erpWrappers;
  }

  protected virtual Decimal determineSavingsPercent()
  {
    return 0;
  }

  protected virtual Decimal determineSavingsPercentByVolume()
  {
    if( this.hasVerifiedBookingOrder &&
      !this.orderWrapper.isBookingOrder &&
      orderWrapper.bookingOrder.get( this.bookingOrderFieldName ) != null )
    {
      return (Decimal) orderWrapper.bookingOrder.get(this.bookingOrderFieldName);
    }

    Partner_Volume_Program__mdt program;
    try
    {
      program = [
        SELECT
          Id,
        ( SELECT
          Id,
          Label,
          Discount_Percent__c,
          Lower_Limit__c,
          Upper_Limit__c
        FROM Partner_Volume_Levels__r
        ORDER BY Upper_Limit__c
        )
        FROM Partner_Volume_Program__mdt
        WHERE Type__c = :this.volumeType
        AND Program_Year__c = :Integer.valueOf(this.programYear)
      ];
    }
    catch( Exception e )
    {
      return 0;
    }

    for( Partner_Volume_Level__mdt level : program.Partner_Volume_Levels__r )
    {
      if( level.Upper_Limit__c == null && this.volumeLevel >= level.Lower_Limit__c )
        return level.Discount_Percent__c;
      if( this.volumeLevel >= level.Lower_Limit__c && this.volumeLevel <= level.Upper_Limit__c )
        return level.Discount_Percent__c;
    }
    return 0;
  }


  protected virtual void calculateVolumeLevel()
  {
    this.volumeLevel = 0;
  }

  protected List<AcctSeedERP__Material__c> doStandardApply()
  {
    List<AcctSeedERP__Material__c> discounts = new List<AcctSeedERP__Material__c>();
    Decimal totalSavings = 0;
    for( PartnerProgram_Service.ErpWrapper wrapper : this.erpWrappers )
    {
      Decimal savings = ( wrapper.boatCost * ( this.discountPercent / 100 ) )
        .setScale(2, RoundingMode.HALF_UP );

      discounts.add(
        wrapper.buildDiscountLine( this.name, savings )
      );
      totalSavings += savings;
    }
    this.resultMessage.totalSaving = totalSavings;
    this.resultMessage.success = 'This order qualifies for the Legend Boats ' + this.name + ' @ ' + this.discountPercent + '%';
    return discounts;
  }

}