force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <type>DateTime</type>
</CustomField>

src/Base/main/default/objects/Registration__c/fields/isCurrent__c.field-meta.xml
<CustomField>
    <fullName>isCurrent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Current</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/Registration__c/fields/Registered_Date__c.field-meta.xml
<CustomField>
    <fullName>Registered_Date__c</fullName>
    <label>Registered Date</label>
    <type>DateTime</type>
</CustomField>

src/Base/main/default/objects/Registration__c/fields/Registered_Motor__c.field-meta.xml
<CustomField>
    <fullName>Registered_Motor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered Motor</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Registration__c/fields/Registered_Motor_Serial__c.field-meta.xml
<CustomField>
    <fullName>Registered_Motor_Serial__c</fullName>
    <label>Registered Motor Serial</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Registration__c/fields/RegisteredByAccount__c.field-meta.xml
<CustomField>
    <fullName>RegisteredByAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered By Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registrations (RegisteredByAccount)</relationshipLabel>
    <relationshipName>Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/SerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SerialNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Serial Number</label>
    <referenceTo>GMBLASERP__Serial_Number__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SerialNumber_History_Controller_dh.cls
public with sharing class SerialNumber_History_Controller_dh {

  public class HistoryWrapper {
    public String recordId;
    public Registration__c currentRegistration;
    public Registration__c[] registrations;

    public HistoryWrapper( String recordId )
    {
      this.recordId = recordId;
      fetchRegistrations();
    }

    private void fetchRegistrations()
    {
      this.registrations = new List<Registration__c>();
      for( Registration__c reg : [SELECT Id,
                                         Registered_Motor__r.Name,
                                         Registered_Motor_Serial__c,
                                         RegisteredByAccount__r.Name,
                                         Account__c,
                                         Account__r.Name,
                                         Account__r.BillingStreet,
                                         Account__r.BillingCity,
                                         Account__r.BillingState,
                                         Account__r.BillingCountry,
                                         Account__r.BillingPostalCode,
                                         Account__r.IsPersonAccount,
                                         Delivery_Date__c,
                                         Registered_Date__c,
                                         IsCurrent__c
                                  FROM Registration__c
                                  WHERE SerialNumber__c = :this.recordId] )
      {
        if( reg.IsCurrent__c )
          this.currentRegistration = reg;
        else
          this.registrations.add( reg );
      }
    }
  }

  @AuraEnabled
  public static String fetchData( String recordId )
  {
    HistoryWrapper hw = new HistoryWrapper( recordId );
    return JSON.serialize( hw );
  }

}