force-app/main/default/objects/AcctSeed__Ledger__c/AcctSeed__Ledger__c.object-meta.xml
<CustomObject>
    <description>Used to associate and aggregate financial transaction or budget entries with a specific entity.</description>
    <label>Ledger</label>
    <nameField>
        <label>Ledger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Time_Card__c/AcctSeed__Time_Card__c.object-meta.xml
<CustomObject>
    <description>Used to document the time associated with an employee for a given time card period.</description>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Time_Card__c/fields/AcctSeed__Ledger__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Ledger__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Denotes the associated ledger.</inlineHelpText>
    <label>Ledger</label>
    <referenceTo>AcctSeed__Ledger__c</referenceTo>
    <relationshipLabel>Time Cards</relationshipLabel>
    <relationshipName>Time_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>Used in approvals of Time Cards and related detail lines. A value of &quot;Posted&quot; indicates the record is final and a debit and credit line have been entered into the transaction object for each Time Card Day.</inlineHelpText>
    <label>Posting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Plan</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
                <default>true</default>
                <label>In Process</label>
            </value>
            <value>
                <fullName>Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card__c/fields/AcctSeed__Time_Card_Period__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Time_Card_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Used for grouping of Time Card Lines. Currently only 7 day Time card periods are supported.</inlineHelpText>
    <label>Time Card Period</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>This Time Period has been Closed. Please contact your administrator to make any changes to this period.</errorMessage>
        <filterItems>
            <field>AcctSeed__Time_Card_Period__c.AcctSeed__Status__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Time_Card_Period__c</referenceTo>
    <relationshipLabel>Time Cards</relationshipLabel>
    <relationshipName>Time_Cards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card_Day__c/AcctSeed__Time_Card_Day__c.object-meta.xml
<CustomObject>
    <description>Used to document the hours expended by an employee on a given day for a given project and project task. Time card days aggregate to a specific time card line.</description>
    <label>Time Card Day</label>
    <nameField>
        <displayFormat>TCD-{00000}</displayFormat>
        <label>Time Card Day Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Card Days</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Time_Card_Day__c/fields/AcctSeed__Hours__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Hours__c</fullName>
    <label>Hours</label>
    <precision>4</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card_Day__c/fields/AcctSeed__Time_Card_Line__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Time_Card_Line__c</fullName>
    <label>Time Card Line</label>
    <referenceTo>AcctSeed__Time_Card_Line__c</referenceTo>
    <relationshipLabel>Time Card Days</relationshipLabel>
    <relationshipName>Time_Card_Days</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card_Day__c/fields/AcctSeed__Time_Card_Period__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Time_Card_Period__c</fullName>
    <formula>AcctSeed__Time_Card_Line__r.AcctSeed__Time_Card__r.AcctSeed__Time_Card_Period__r.Name</formula>
    <label>Time Card Period</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card_Line__c/AcctSeed__Time_Card_Line__c.object-meta.xml
<CustomObject>
    <description>Used to document the project and project task associated with a time card. Time card lines aggregate to a specific time card.</description>
    <label>Time Card Line</label>
    <nameField>
        <displayFormat>TCL-{00000}</displayFormat>
        <label>Time Card Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Card Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Time_Card_Line__c/fields/AcctSeed__Time_Card__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Time_Card__c</fullName>
    <label>Time Card</label>
    <referenceTo>AcctSeed__Time_Card__c</referenceTo>
    <relationshipName>Time_Card_Line_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card_Period__c/AcctSeed__Time_Card_Period__c.object-meta.xml
<CustomObject>
    <description>Used to capture the specific time frame e.g. start date and end date associated with a time card.</description>
    <label>Time Card Period</label>
    <nameField>
        <label>Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Card Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Time_Card_Period__c/fields/AcctSeed__End_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__End_Date__c</fullName>
    <inlineHelpText>Last day of the Time Card Period. This field is automatically calculated to be 6 days after the start date entered for the Time Card Period.. A value entered directly into this field will be overwritten.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card_Period__c/fields/AcctSeed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Start_Date__c</fullName>
    <inlineHelpText>Beginning of the Time Card Period. Typically a Monday or Sunday.</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card_Period__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>&quot;Open&quot; indicates that Time Cards can be entered for this period. &quot;Closed&quot; indicates that no new Time Cards can be entered for this period.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Time_Card_Entry__c/Time_Card_Entry__c.object-meta.xml
<CustomObject>
    <label>Time Card Entry</label>
    <nameField>
        <displayFormat>TCE-{0000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Card Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/Time_Card_Entry__c/fields/Time_Card_Day__c.field-meta.xml
<CustomField>
    <fullName>Time_Card_Day__c</fullName>
    <label>Time Card Day</label>
    <referenceTo>AcctSeed__Time_Card_Day__c</referenceTo>
    <relationshipLabel>Time Card Entries</relationshipLabel>
    <relationshipName>Time_Card_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Time_Card_Entry__c/fields/Time_In_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Time_In_Picklist__c</fullName>
    <label>Time In</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MIDNIGHT</fullName>
            </value>
            <value>
                <fullName>12:15AM</fullName>
            </value>
            <value>
                <fullName>12:30AM</fullName>
            </value>
            <value>
                <fullName>12:45AM</fullName>
            </value>
            <value>
                <fullName>01:00AM</fullName>
            </value>
            <value>
                <fullName>01:15AM</fullName>
            </value>
            <value>
                <fullName>01:30AM</fullName>
            </value>
            <value>
                <fullName>01:45AM</fullName>
            </value>
            <value>
                <fullName>02:00AM</fullName>
            </value>
            <value>
                <fullName>02:15AM</fullName>
            </value>
            <value>
                <fullName>02:30AM</fullName>
            </value>
            <value>
                <fullName>02:45AM</fullName>
            </value>
            <value>
                <fullName>03:00AM</fullName>
            </value>
            <value>
                <fullName>03:15AM</fullName>
            </value>
            <value>
                <fullName>03:30AM</fullName>
            </value>
            <value>
                <fullName>03:45AM</fullName>
            </value>
            <value>
                <fullName>04:00AM</fullName>
            </value>
            <value>
                <fullName>04:15AM</fullName>
            </value>
            <value>
                <fullName>04:30AM</fullName>
            </value>
            <value>
                <fullName>04:45AM</fullName>
            </value>
            <value>
                <fullName>05:00AM</fullName>
            </value>
            <value>
                <fullName>05:15AM</fullName>
            </value>
            <value>
                <fullName>05:30AM</fullName>
            </value>
            <value>
                <fullName>05:45AM</fullName>
            </value>
            <value>
                <fullName>6:00AM</fullName>
            </value>
            <value>
                <fullName>6:15AM</fullName>
            </value>
            <value>
                <fullName>6:30AM</fullName>
            </value>
            <value>
                <fullName>6:45AM</fullName>
            </value>
            <value>
                <fullName>7:00AM</fullName>
            </value>
            <value>
                <fullName>7:15AM</fullName>
            </value>
            <value>
                <fullName>9:00AM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Card_Entry__c/fields/Time_Out_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Time_Out_Picklist__c</fullName>
    <label>Time Out</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>12:15AM</fullName>
            </value>
            <value>
                <fullName>12:30AM</fullName>
            </value>
            <value>
                <fullName>12:45AM</fullName>
            </value>
            <value>
                <fullName>01:00AM</fullName>
            </value>
            <value>
                <fullName>01:15AM</fullName>
            </value>
            <value>
                <fullName>01:30AM</fullName>
            </value>
            <value>
                <fullName>01:45AM</fullName>
            </value>
            <value>
                <fullName>02:00AM</fullName>
            </value>
            <value>
                <fullName>02:15AM</fullName>
            </value>
            <value>
                <fullName>02:30AM</fullName>
            </value>
            <value>
                <fullName>02:45AM</fullName>
            </value>
            <value>
                <fullName>03:00AM</fullName>
            </value>
            <value>
                <fullName>03:15AM</fullName>
            </value>
            <value>
                <fullName>03:30AM</fullName>
            </value>
            <value>
                <fullName>03:45AM</fullName>
            </value>
            <value>
                <fullName>04:00AM</fullName>
            </value>
            <value>
                <fullName>04:15AM</fullName>
            </value>
            <value>
                <fullName>04:30AM</fullName>
            </value>
            <value>
                <fullName>04:45AM</fullName>
            </value>
            <value>
                <fullName>05:00AM</fullName>
            </value>
            <value>
                <fullName>05:15AM</fullName>
            </value>
            <value>
                <fullName>05:30AM</fullName>
            </value>
            <value>
                <fullName>05:45AM</fullName>
            </value>
            <value>
                <fullName>6:00AM</fullName>
            </value>
            <value>
                <fullName>6:15AM</fullName>
            </value>
            <value>
                <fullName>6:30AM</fullName>
            </value>
            <value>
                <fullName>6:45AM</fullName>
            </value>
            <value>
                <fullName>7:00AM</fullName>
            </value>
            <value>
                <fullName>7:15AM</fullName>
            </value>
            <value>
                <fullName>7:30AM</fullName>
            </value>
            <value>
                <fullName>9:00AM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/gcTest_TimeCard_All.cls
@isTest
private class gcTest_TimeCard_All{

  static Date firstSunday;
  static Date actualDay;

  @testSetup static void dataSetup()
  {
    new Factory_TestData();
    Factory_CustomSettings.setupInventorySettings();
  }

  static {
    firstSunday = Date.today().toStartOfMonth().toStartOfWeek();
    //add a week if "firstMonday" is in last month
    if(firstSunday < date.today().toStartOfmonth())
      firstSunday = firstSunday.addDays(7);
    actualDay = firstSunday.addDays(3);
  }

  static testMethod void coverage_Test()
  {
    gcTimeCard.coverage();
    gcTimeCard_Ext.coverage();
    gcTimeCard_Ext.coverage1();
    gcTimeCardLine.coverage();
    gcTimeCardDay.coverage();
    gcTimeCardEntry.coverage();
    gcTimeCardPeriod.coverage();
    gcTimeCardPeriod_Ext.coverage();
  }

  @isTest
  static void trigger_Test()
  {
    AcctSeed__Time_Card_Period__c tcp = insertTimeCardPeriod();
    AcctSeed__Time_Card__c tc = insertTimeCard( tcp );
    AcctSeed__Time_Card_Line__c tcl = insertTimeCardLine( tc );
    AcctSeed__Time_Card_Day__c tcd = insertTimeCardDay( tcl );
    Time_Card_Entry__c tce = insertTimeCardEntry( tcd );
  }


  private static AcctSeed__Time_Card__c insertTimeCard( AcctSeed__Time_Card_Period__c tcp )
  {
    AcctSeed__Ledger__c ledger = [SELECT Id FROM AcctSeed__Ledger__c LIMIT 1];
    AcctSeed__Time_Card__c tc = new AcctSeed__Time_Card__c(
      AcctSeed__Ledger__c = ledger.Id,
      AcctSeed__Time_Card_Period__c = tcp.Id
    );
    insert tc;
    return tc;
  }


  private static AcctSeed__Time_Card_Day__c insertTimeCardDay( AcctSeed__Time_Card_Line__c tcl )
  {
    AcctSeed__Time_Card_Day__c tcd = new AcctSeed__Time_Card_Day__c(
      AcctSeed__Hours__c = 2,
      AcctSeed__Time_Card_Line__c = tcl.Id,
      AcctSeed__Date__c = actualDay
    );
    insert tcd;
    return tcd;
  }


  private static Time_Card_Entry__c insertTimeCardEntry( AcctSeed__Time_Card_Day__c tcd )
  {
    Time_Card_Entry__c tce = new Time_Card_Entry__c(
      Time_Card_Day__c = tcd.Id,
      Time_In_Picklist__c = '7:00AM',
      Time_Out_Picklist__c = '9:00AM'
    );
    insert tce;
    return tce;
  }

  private static AcctSeed__Time_Card_Line__c insertTimeCardLine( AcctSeed__Time_Card__c tc )
  {
    AcctSeed__Time_Card_Line__c tcl = new AcctSeed__Time_Card_Line__c(
      AcctSeed__Time_Card__c = tc.Id
    );
    //gcTimeCardLine.disableTrigger = true;
    insert tcl;
    return tcl;
  }

  private static AcctSeed__Time_Card_Period__c insertTimeCardPeriod()
  {
    AcctSeed__Time_Card_Period__c tcp = new AcctSeed__Time_Card_Period__c(
      AcctSeed__Status__c = 'Open',
      AcctSeed__Start_Date__c = firstSunday,
      AcctSeed__End_Date__c = firstSunday.addDays(7)
    );
    insert tcp;
    return tcp;
  }

}