src/Base/main/default/objects/Truck_Load__c/Truck_Load__c.object-meta.xml
<CustomObject>
    <label>Truck Load</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Truck Load Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Truck Loads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Truck_Load__c/fields/Delivery_Date2__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date2__c</fullName>
    <label>Delivery Date2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Truck_Load__c/fields/Departure_Date2__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date2__c</fullName>
    <label>Departure Date2</label>
    <type>Date</type>
</CustomField>

src/Base/main/default/objects/Truck_Load__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Luc Broullette</fullName>
            </value>
            <value>
                <fullName>Mike Rancourt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Truck_Load__c/fields/Return_Date2__c.field-meta.xml
<CustomField>
    <fullName>Return_Date2__c</fullName>
    <label>Return Date2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Truck_Load__c/fields/Truck__c.field-meta.xml
<CustomField>
    <fullName>Truck__c</fullName>
    <label>Truck</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TruckLoadLine__c/TruckLoadLine__c.object-meta.xml
<CustomObject>
    <label>Truck Load Line</label>
    <nameField>
        <displayFormat>TLL-{0000}</displayFormat>
        <label>TruckLoadLine Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Truck Load Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TruckLoadLine__c/fields/Truck_Load__c.field-meta.xml
<CustomField>
    <fullName>Truck_Load__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Truck Load</label>
    <referenceTo>Truck_Load__c</referenceTo>
    <relationshipLabel>Truck Load Lines</relationshipLabel>
    <relationshipName>Truck_Load_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Truck_Load_Ext_Test.cls
@isTest
private class Truck_Load_Ext_Test {

  @isTest static void tempTest()
  {
    Truck_Load_Ext.coverage();
    Truck_Load__c tl = new Truck_Load__c(
      Return_Date2__c = Date.today().addDays(10),
      Delivery_Date2__c = Date.today().addDays(5),
      Departure_Date2__c = Date.today(),
      Driver__c = LGND_Utilities.getPickListValues('Truck_Load__c', 'Driver__c')[0],
      Truck__c = LGND_Utilities.getPickListValues('Truck_Load__c', 'Truck__c')[0]
    );
    insert tl;
    TruckLoadLine__c tll = new TruckLoadLine__c(
      Truck_Load__c = tl.Id
    );
    insert tll;
    update [SELECT Id FROM TruckLoadLine__c LIMIT 1][0];
  }

}