force-app/main/default/objects/Truck_Delivery_Item__c/Truck_Delivery_Item__c.object-meta.xml
<CustomObject>
    <label>Truck Delivery Item</label>
    <nameField>
        <displayFormat>TruckDeliveryItem-{0000}</displayFormat>
        <label>Truck Delivery Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Truck Delivery Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Truck_Delivery_Item__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TruckDeliveryItem_Test.cls
@isTest
private class TruckDeliveryItem_Test {

	@isTest static void fakeCoverage_Test() {
		TruckDeliveryItem.coverage();
	}

  @isTest static void triggerCoverage_Test() {
    Truck_Delivery_Item__c item = new Truck_Delivery_Item__c(
      Position__c = LGND_Utilities.getPicklistValues('Truck_Delivery_item__c', 'Position__c')[0]
    );
    insert item;
    item.Position__c =  LGND_Utilities.getPicklistValues('Truck_Delivery_item__c', 'Position__c')[1];
    update item;
  }

}