force-app/main/default/objects/Opportunity/recordTypes/Online.recordType-meta.xml
<RecordType>
    <fullName>Online</fullName>
    <active>true</active>
    <businessProcess>Retail Sales Process</businessProcess>
    <label>Online</label>
</RecordType>

force-app/main/default/objects/Square_Transaction__c/Square_Transaction__c.object-meta.xml
<CustomObject>
    <label>Square Transaction</label>
    <nameField>
        <displayFormat>SQTRANS-{0000}</displayFormat>
        <label>Square Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Square Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Square_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Square Transactions</relationshipLabel>
    <relationshipName>Square_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Square_Transaction__c/fields/sqCreateDate__c.field-meta.xml
<CustomField>
    <fullName>sqCreateDate__c</fullName>
    <label>Payment Create Date</label>
    <type>DateTime</type>
</CustomField>

src/Base/main/default/objects/Square_Transaction__c/fields/sqOrderID__c.field-meta.xml
<CustomField>
    <fullName>sqOrderID__c</fullName>
    <label>Order ID</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Square_Transaction__c/fields/sqReceiptNumber__c.field-meta.xml
<CustomField>
    <fullName>sqReceiptNumber__c</fullName>
    <label>Receipt Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Square_Transaction__c/fields/sqReceiptURL__c.field-meta.xml
<CustomField>
    <fullName>sqReceiptURL__c</fullName>
    <label>Receipt URL</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Square_Transaction__c/fields/sqStatus__c.field-meta.xml
<CustomField>
    <fullName>sqStatus__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COMPLETED</fullName>
            </value>
            <value>
                <fullName>INCOMPLETE</fullName>
                <default>true</default>
                <label>INCOMPLETE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SquareTransaction_Service.cls
/**
 * Created by dave on 2020-06-16.
 */

public without sharing class SquareTransaction_Service
{

  public static Square_Transaction__c newFromOnlineBoatReservation( SquareProcessor.PaymentResult paymentResult )
  {
    Opportunity opp = Opportunity_Selector.allByIds( new Set<Id>{ paymentResult.reference_id } )[0];
    Square_Transaction__c squareTransaction = new Square_Transaction__c(
      Account__c = opp.AccountId,
      Amount__c = paymentResult.amount_money.amount,
      Description__c = opp.Name,
      Notes__c = 'Deposit for Online Boat Reservation',
      sqOrderID__c = paymentResult.order_id,
      sqCreateDate__c = paymentResult.created_at,
      sqReceiptNumber__c = paymentResult.receipt_number,
      sqReceiptURL__c = paymentResult.receipt_url,
      sqStatus__c = 'COMPLETED'
    );
    insert squareTransaction;
    return squareTransaction;
  }
}