force-app/main/default/objects/Dealer_Order_Line__c/Dealer_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Dealer Order Line</label>
    <nameField>
        <displayFormat>DOL-{0000}</displayFormat>
        <label>Dealer Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/Dealer_Order_Line__c/fields/Legend_Transfer_Request__c.field-meta.xml
<CustomField>
    <fullName>Legend_Transfer_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legend Transfer Request</label>
    <referenceTo>Legend_Transfer_Request__c</referenceTo>
    <relationshipLabel>Dealer Order Lines</relationshipLabel>
    <relationshipName>Dealer_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Legend_Transfer_Request__c/Legend_Transfer_Request__c.object-meta.xml
<CustomObject>
    <description>Used for Transferring Serialized Inventory to Another Legend Location</description>
    <label>Legend Transfer Request</label>
    <nameField>
        <displayFormat>LTR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legend Transfer Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Automation/main/default/classes/DealerOrderLine/TA_DealerOrderLine_DelTransferRequests.cls
/**
 * Created by dhavalmacbook on 20/01/22.
 */

public inherited sharing class TA_DealerOrderLine_DelTransferRequests implements TriggerAction.AfterDelete{

    public void afterDelete(List<SObject> oldList) {
        Set<Id> transferIds = new Set<Id>();

        List<Dealer_Order_Line__c> dols = (List<Dealer_Order_Line__c>)Trigger.oldMap.values();

        for( Dealer_Order_Line__c dol : dols ) {
            if (dol.Legend_Transfer_Request__c != null) {
                transferIds.add(dol.Legend_Transfer_Request__c);
            }
        }
        if( transferIds.size() > 0 )
            DealerOrderLine_Service.deleteLegendTransferRequests( transferIds );
    }
}