force-app/main/default/objects/Feature__c/Feature__c.object-meta.xml
<CustomObject>
    <label>Feature</label>
    <nameField>
        <displayFormat>f-{0000}</displayFormat>
        <label>Feature ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/recordTypes/Boat.recordType-meta.xml
<RecordType>
    <fullName>Boat</fullName>
    <active>true</active>
    <label>Boat</label>
</RecordType>

src/Base/main/default/objects/Product_Feature_Map__c/Product_Feature_Map__c.object-meta.xml
<CustomObject>
    <label>Product Feature Map</label>
    <nameField>
        <displayFormat>PFM-{0000}</displayFormat>
        <label>Product Feature Map ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Feature Maps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/Product_Feature_Map__c/fields/Feature_Id__c.field-meta.xml
<CustomField>
    <fullName>Feature_Id__c</fullName>
    <label>Feature Id</label>
    <referenceTo>Feature__c</referenceTo>
    <relationshipLabel>Product Feature Maps</relationshipLabel>
    <relationshipName>Product_Feature_Maps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/objects/Product_Feature_Map__c/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product_Id</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Feature Maps</relationshipLabel>
    <relationshipName>Product_Feature_Maps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductFeatureCtr_Test.cls
@isTest
private class ProductFeatureCtr_Test {

	testMethod static void test1() {
     /* disable the Gimbal Trigger handler gtProduct.trigger
     until Gimbals code gets deployed, this needs to be commented out for production */
    gcProduct.disableTrigger = true;

    InventoryTestFactory factory = new InventoryTestFactory();
    Product2 boat = factory.insertTestBoatWithFeatures(7);
    List<Feature__c> features = factory.buildAllFeatures(10);
    insert features;

    PageReference pageRef = Page.ProductFeatureSelect;
    pageRef.getParameters().put('id', boat.Id);
    Test.setCurrentPageReference(pageRef);
    ProductFeatureCtr ctr = new ProductFeatureCtr();

    System.assertEquals(7, ctr.selectedConstructionFeatures.size() );
    System.assertEquals(7, ctr.selectedConsoleFeatures.size() );
    System.assertEquals(7, ctr.selectedLivewellFeatures.size() );
    System.assertEquals(7, ctr.selectedSeatingFeatures.size() );
    System.assertEquals(7, ctr.selectedDeckFeatures.size() );
    System.assertEquals(7, ctr.selectedSafetyFeatures.size() );
    System.assertEquals(7, ctr.selectedAdditionalFeatures.size() );

    System.assertEquals(10, ctr.availableConstructionFeatures.size() );
    System.assertEquals(10, ctr.availableConsoleFeatures.size() );
    System.assertEquals(10, ctr.availableLivewellFeatures.size() );
    System.assertEquals(10, ctr.availableSeatingFeatures.size() );
    System.assertEquals(10, ctr.availableDeckFeatures.size() );
    System.assertEquals(10, ctr.availableSafetyFeatures.size() );
    System.assertEquals(10, ctr.availableAdditionalFeatures.size() );

    /* add the first 2 availableConstructionfeatures to the selectedFeatures List */
    for(Integer i=0; i < 2; i++){
      ctr.selectedConstructionFeatures.add( new SelectOption( ctr.availableConstructionfeatures[i].getValue(), ctr.availableConstructionfeatures[i].getLabel() ) );
    }

    /* add the first 2 availableDeckfeatures to the selectedFeatures List */
    for(Integer i=0; i < 2; i++){
      ctr.selectedDeckFeatures.add( new SelectOption( ctr.availableDeckFeatures[i].getValue(), ctr.availableDeckFeatures[i].getLabel() ) );
    }

    ctr.save();

    boat = [SELECT Id, (SELECT Id, Feature_Id__c FROM Product_Feature_Maps__r)
            FROM Product2 WHERE Id = :boat.Id];

    System.assertEquals( 53, boat.Product_Feature_Maps__r.size() );

  }

}