src/Base/main/default/objects/CommissionRecord2__c/CommissionRecord2__c.object-meta.xml
<CustomObject>
    <label>Commission Record</label>
    <nameField>
        <displayFormat>CommRec-{0000}</displayFormat>
        <label>Commission Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/CommissionRecord2__c/fields/Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Method__c</fullName>
    <label>Calculation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commission_Calculation_Method</valueSetName>
    </valueSet>
</CustomField>

src/Base/main/default/globalValueSets/Commission_Calculation_Method.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Revenue</fullName>
        <default>true</default>
        <label>Revenue</label>
    </customValue>
    <customValue>
        <fullName>Gross Margin</fullName>
    </customValue>
    <description>Method used to calculate Commission</description>
    <masterLabel>Commission Calculation Method</masterLabel>
</GlobalValueSet>

src/Automation/main/default/classes/CommissionRecord2/TA_CommRec2_CalculationMethodChange.cls
/**
 * Created by dave on 2022-01-13.
 */

public without sharing class TA_CommRec2_CalculationMethodChange implements TriggerAction.AfterUpdate
{
  public void afterUpdate( List<CommissionRecord2__c> newList, List<CommissionRecord2__c> oldList){
    Map<Id, CommissionRecord2__c> oldMap = new Map<Id, CommissionRecord2__c>(oldList);
    Set<Id> calcHasChanged = new Set<Id>();
    for( CommissionRecord2__c rec : newList )
    {
      CommissionRecord2__c oldRec = oldMap.get(rec.Id);
      if (rec.Calculation_Method__c != oldRec.Calculation_Method__c)
      {
        calcHasChanged.add( rec.Id );
      }
    }
    if( calcHasChanged.size() > 0 )
    {
      CommissionLineItem2_Service service = new CommissionLineItem2_Service();
      service.recalculate( calcHasChanged );
    }
  }
}