force-app/main/default/objects/CommissionPayment__c/CommissionPayment__c.object-meta.xml
<CustomObject>
    <label>Commission Payment</label>
    <nameField>
        <displayFormat>CRP-{0000}</displayFormat>
        <label>Commission Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CommissionPayment__c/fields/CommissionRecord__c.field-meta.xml
<CustomField>
    <fullName>CommissionRecord__c</fullName>
    <label>Commission Record</label>
    <referenceTo>CommissionRecord__c</referenceTo>
    <relationshipLabel>Commission Payments</relationshipLabel>
    <relationshipName>CommissionPayments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CommissionPayment__c/fields/Owner__c.field-meta.xml
<CustomField>
    <fullName>Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Commission_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/CommissionRecord__c/CommissionRecord__c.object-meta.xml
<CustomObject>
    <label>Commission Record</label>
    <nameField>
        <label>Commision Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/CommissionRecord__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <label>OpportunityId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BoatId__c.field-meta.xml
<CustomField>
    <fullName>BoatId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Boat Model</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>Date the customer received his product</description>
    <label>Delivery Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Line_Item_Count__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Count__c</fullName>
    <label>Line Item Count</label>
    <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Boat.recordType-meta.xml
<RecordType>
    <fullName>Boat</fullName>
    <active>true</active>
    <label>Boat</label>
</RecordType>

force-app/main/default/classes/OpportunityDetailExt.cls
public with sharing class OpportunityDetailExt {

  private User currentUser;
  private ApexPages.StandardController stdCtrl;
  private Opportunity opp;
  //private CommissionRecord__c[] comRecords;
  public Product2 boat { get; private set; }


	public OpportunityDetailExt(ApexPages.StandardController std) {
    stdCtrl = std;
    opp = getOurOpp();
    currentUser = [SELECT Id, Name, Profile.Name
                   FROM User
                   WHERE Id = :UserInfo.getUserId()];
    //comRecords = [SELECT Id,
    //                    (SELECT Id FROM CommissionPayments__r WHERE Owner__c = :currentUser.Id)
    //              FROM CommissionRecord__c
    //              WHERE OpportunityId__c = :opp.Id];
    boat = findBoat();
	}


  //public Boolean getHasCommission()
  //{
  //  Set<String> allowedProfiles = new Set<String>{'System Administrator', 'Sales and Operations Manager', 'Legend Admin'};
  //  return ( getHasLineItems() &&
  //   ( ( allowedProfiles.contains(currentUser.Profile.Name) && opp.Probability > 0 )
  //    || ( comRecords.size() > 0 && userHasCommissionPayment() ) )
  //  ) ;
  //}

  public Boolean getHasLineItems()
  {
    return opp.Line_Item_Count__c > 0;
  }

  public String getFormattedDeliveryDate()
  {
    if( opp.Delivery_Date__c == null )
    {
      return 'Not Set';
    }
    return opp.Delivery_Date__c.format('MMM d, yyyy @ h:mm a');
  }


  @RemoteAction
  public static Opportunity updateStage(String OppId, String newStage){
    String stageToSet;
    Opportunity o = [SELECT Id, StageName, Probability FROM Opportunity WHERE Id = :oppId];
    if( o.StageName == newStage ){
      Map<String, String> stageRollbackMap = new Map<String,String>{
        'Orientation Specialist Add-On Call' => 'Tagging Pending',
        'Pending Work Order' => 'Orientation Specialist Add-On Call',
        'Pending Rigging' => 'Pending Work Order',
        'Pending Inspection' => 'Pending Rigging',
        'Pending Pickup' => 'Pending Inspection',
        'Picked Up / Won' => 'Pending Pickup'
      };
      stageToSet = stageRollbackMap.get(newStage);
    } else {
      Set<String> stages = new Set<String>();
      Schema.DescribeFieldResult opportunityStageName = Opportunity.StageName.getDescribe();
      for( Schema.PickListEntry ple : opportunityStageName.getPicklistValues() ){
        stages.add( ple.getLabel() );
      }
      if( stages.contains(newStage) ){
        stageToSet = newStage;
      }
    }

    if( stageToSet != null ){
      Map<String, Decimal> probabilityStageNameMap = new Map<String, Decimal>();
      for (OpportunityStage oppStage : [Select MasterLabel, DefaultProbability
                                        From OpportunityStage]) {
        probabilityStageNameMap.put(oppStage.MasterLabel, oppStage.DefaultProbability);
      }
      o.Probability = probabilityStageNameMap.get(stageToSet);
      o.StageName = stageToSet;
      update o;
      return o;
    } else {
      return null;
    }

  }

  private Opportunity getOurOpp()
  {
    if( Test.isRunningTest() )
    {
      return [SELECT Id, Name, BoatId__c, Line_Item_Count__c, Probability, StageName, Delivery_Date__c
              FROM Opportunity
              WHERE Id = :stdCtrl.getId() ];
    }
    else
    {
      stdCtrl.addFields( new List<String>{'BoatId__c', 'Line_Item_Count__c', 'Delivery_Date__c'} );
      return (Opportunity)stdCtrl.getRecord();
    }
  }

  //private Boolean userHasCommissionPayment()
  //{
  //  Boolean result = false;
  //  for(CommissionRecord__c cr : comRecords)
  //  {
  //    if( cr.CommissionPayments__r.size() > 0 )
  //    {
  //      result = true;
  //    }
  //  }
  //  return result;
  //}

  private Product2 findBoat()
  {
    try
    {
      return [SELECT Id, Name, Family FROM Product2 WHERE Id = :opp.BoatId__c];
    }
    catch(Exception e)
    {
      return null;
    }
  }


}