force-app/main/default/objects/Opportunity/fields/Invoice_Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Document_Id__c</fullName>
    <label>Invoice Document Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Document__c/Opportunity_Document__c.object-meta.xml
<CustomObject>
    <label>Opportunity Document</label>
    <nameField>
        <label>Opportunity Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Document</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Document__c/fields/Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Document_Id__c</fullName>
    <description>The Id of the Document</description>
    <label>Document Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Opportunity_Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Opportunity_Document__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Document</relationshipLabel>
    <relationshipName>Opportunity_Document</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityExt_OppDoc.cls
global with sharing class OpportunityExt_OppDoc {
  public ApexPages.StandardController std;
  //public List<Opportunity_Document__c> oppDocs{get;set;}
  public Map<String, List<Opportunity_Document__c>> oppDocs { get; set; }
  public Opportunity_Document__c[] docs { get; private set; }
  public Opportunity opp;
  public Id acctId { get; set; }
  private User currentUser;

	global OpportunityExt_OppDoc(ApexPages.StandardController controller) {
		std = controller;
    Id oppId=std.getId();
    opp = [SELECT Id, AccountId, Invoice_Document_Id__c FROM Opportunity WHERE Id = :oppId];
    this.acctId = opp.AccountId;
    oppDocs = refreshDocList();
    currentUser = [SELECT Id, Name, Profile.Name
                   FROM User
                   WHERE Id = :UserInfo.getUserId()];
	}

  @RemoteAction
  global static void deleteDoc(String docId)
  {
    Opportunity_Document__c toDel = new Opportunity_Document__c(id=docId);
    try {
      delete toDel;
    }
    catch(Exception e){}
  }

  public Boolean getRenderList()
  {
    return !oppDocs.isEmpty();
  }

  //public Boolean getIsBOM_or_ADMIN()
  //{
  //  return new Set<String>{'Business Manager', 'System Administrator', 'Legend Admin'}.contains( currentUser.Profile.Name );
  //}

  //public Boolean getCanCreateInvoice()
  //{
  //  return new Set<String>{'System Administrator', 'Legend Admin'}.contains( currentUser.Profile.Name ) ||
  ////    ( getIsBOM_or_ADMIN() && opp.Invoice_Document_Id__c != null );
  //}

  private Map<String, List<Opportunity_Document__c>> refreshDocList()
  {
    Map<String, List<Opportunity_Document__c>> docMap = new Map<String, List<Opportunity_Document__c>>();
    docs = [SELECT Id, Name, Document_Id__c, Opportunity__c, Document_Type__c
            FROM Opportunity_Document__c
            WHERE Opportunity__c = :opp.Id
            ORDER BY createddate desc];

    for(Opportunity_Document__c od : docs)
    {
      if( !docMap.containsKey(od.Document_Type__c) )
      {
        docMap.put(od.Document_Type__c, new List<Opportunity_Document__c>() );
      }
      docMap.get(od.Document_Type__c).add(od);
    }
    return docMap;
  }

}