force-app/main/default/objects/AcctSeed__GL_Account__c/AcctSeed__GL_Account__c.object-meta.xml
<CustomObject>
    <description>Used to document the general ledger accounts used by the financial suite accounting application. This is a traditional general ledger account.</description>
    <label>GL Account</label>
    <nameField>
        <label>GL Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeedERP__Warehouse__c/AcctSeedERP__Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/GMBLASERP__Inventory_Adjustment__c/GMBLASERP__Inventory_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Inventory Adjustment</label>
    <nameField>
        <displayFormat>ADJ-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GMBLASERP__Inventory_Adjustment__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMBLASERP__Inventory_Adjustment__c/fields/GMBLASERP__Adjustment_Date__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Adjustment_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Adjustment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Inventory_Adjustment__c/fields/GMBLASERP__Adjustment_Type__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Adjustment_Type__c</fullName>
    <label>Adjustment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quantity</fullName>
            </value>
            <value>
                <fullName>Value</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GMBLASERP__Inventory_Adjustment__c/fields/GMBLASERP__GL_Account__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__GL_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>GL Account</label>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Inventory Adjustments</relationshipLabel>
    <relationshipName>Inventory_Adjustments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Inventory_Adjustment__c/fields/GMBLASERP__Product__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inventory Adjustments</relationshipLabel>
    <relationshipName>Inventory_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Inventory_Adjustment__c/fields/GMBLASERP__Warehouse__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Inventory Adjustments</relationshipLabel>
    <relationshipName>Inventory_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Product2/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Part.recordType-meta.xml
<RecordType>
    <fullName>Part</fullName>
    <active>true</active>
    <description>Part</description>
    <label>Part</label>
</RecordType>

force-app/main/default/classes/gcTest_InventoryAdjustment.cls
@isTest
private class gcTest_InventoryAdjustment{

  @testSetup static void dataSetup()
  {
    new Factory_TestData();
    Factory_CustomSettings.setupInventorySettings();
  }

	static testMethod void coverage_Test()
	{
    gcInventoryAdjustment.coverage();
  }

  static testMethod void trigger_Test()
  {
    Product2 part = Factory_Product.createNonSerializedProduct('Part', 'Electronics');
    AcctSeedERP__Warehouse__c wh = [SELECT Id FROM AcctSeedERP__Warehouse__c LIMIT 1];
    AcctSeed__GL_Account__c glA = [SELECT Id
                                   FROM AcctSeed__GL_Account__c
                                   LIMIT 1];
    insert new GMBLASERP__Inventory_Adjustment__c(
      Description__c = 'Test run',
      GMBLASERP__Adjustment_Type__c = 'Quantity',
      GMBLASERP__Adjustment_Date__c = Date.today(),
      GMBLASERP__Product__c = part.Id,
      GMBLASERP__Warehouse__c = wh.Id,
      GMBLASERP__GL_Account__c = glA.Id
    );
  }
}