src/Base/main/default/objects/AcctSeed__Account_Payable__c/AcctSeed__Account_Payable__c.object-meta.xml
<CustomObject>
    <description>Used to document liabilities to outside vendor, contact, or employee.</description>
    <label>Payable</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Payable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Account_Payable__c/fields/AcctSeedERP__Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>AcctSeedERP__Purchase_Order__c</referenceTo>
    <relationshipLabel>Payables</relationshipLabel>
    <relationshipName>Accounts_Payable</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Inventory_Balance__c/AcctSeedERP__Inventory_Balance__c.object-meta.xml
<CustomObject>
    <label>Inventory Balance</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Inventory Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Balances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Inventory_Balance__c/fields/AcctSeedERP__Ledger__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Ledger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ledger</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Ledger__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Transactional</value>
        </filterItems>
        <infoMessage>Only Transactional Ledgers are allowed.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Ledger__c</referenceTo>
    <relationshipLabel>Inventory Quantity Available</relationshipLabel>
    <relationshipName>Inventory_Quantity_Available</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Inventory_Balance__c/fields/AcctSeedERP__Location__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeedERP__Location__c.AcctSeedERP__Warehouse__c</field>
            <operation>equals</operation>
            <valueField>$Source.AcctSeedERP__Warehouse__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeedERP__Location__c</referenceTo>
    <relationshipLabel>Inventory Quantity Available</relationshipLabel>
    <relationshipName>Inventory_Balances</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Inventory_Balance__c/fields/AcctSeedERP__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inventory Balance</relationshipLabel>
    <relationshipName>Inventory_Balance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Inventory_Balance__c/fields/AcctSeedERP__Warehouse__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Inventory Quantity Available</relationshipLabel>
    <relationshipName>Inventory_Balance</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Location__c/AcctSeedERP__Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeedERP__Location__c/fields/AcctSeedERP__Warehouse__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order__c/AcctSeedERP__Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Purchase_Order__c/fields/AcctSeedERP__Ledger__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Ledger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Denotes the associated ledger.</inlineHelpText>
    <label>Ledger</label>
    <referenceTo>AcctSeed__Ledger__c</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Purchase_Order_Inventory_Movement__c/AcctSeedERP__Purchase_Order_Inventory_Movement__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Inventory Movement</label>
    <nameField>
        <displayFormat>PIM-{00000}</displayFormat>
        <label>Purchasing Inventory Movement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Inventory Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Inventory_Movement__c/fields/AcctSeedERP__Inventory_Balance__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Inventory_Balance__c</fullName>
    <label>Inventory Quantity Available</label>
    <referenceTo>AcctSeedERP__Inventory_Balance__c</referenceTo>
    <relationshipLabel>Purchase Order Inventory Movements</relationshipLabel>
    <relationshipName>Purchase_Order_Inventory_Movements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Inventory_Movement__c/fields/AcctSeedERP__Ledger__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Ledger__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ledger</label>
    <referenceTo>AcctSeed__Ledger__c</referenceTo>
    <relationshipLabel>Purchase Order Inventory Movements</relationshipLabel>
    <relationshipName>Purchase_Order_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Inventory_Movement__c/fields/AcctSeedERP__Location__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Location__c</fullName>
    <formula>AcctSeedERP__Inventory_Balance__r.AcctSeedERP__Location__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Inventory_Movement__c/fields/AcctSeedERP__Purchase_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Purchase_Order_Line__c</fullName>
    <label>Purchase Order Line</label>
    <referenceTo>AcctSeedERP__Purchase_Order_Line__c</referenceTo>
    <relationshipLabel>Purchase Order Inventory Movements</relationshipLabel>
    <relationshipName>Purchase_Order_Inventory_Movements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Purchase_Order_Inventory_Movement__c/fields/GMBLASERP__Location__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>AcctSeedERP__Location__c</referenceTo>
    <relationshipLabel>Purchase Order Inventory Movements</relationshipLabel>
    <relationshipName>Purchase_Order_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Purchase_Order_Inventory_Movement__c/fields/GMBLASERP__Product__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Purchase Order Inventory Movements</relationshipLabel>
    <relationshipName>Purchase_Order_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Purchase_Order_Inventory_Movement__c/fields/GMBLASERP__Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>AcctSeedERP__Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Order Inventory Movements</relationshipLabel>
    <relationshipName>Purchase_Order_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Purchase_Order_Inventory_Movement__c/fields/GMBLASERP__Warehouse__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Purchase Order Inventory Movements</relationshipLabel>
    <relationshipName>Purchase_Order_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Line__c/AcctSeedERP__Purchase_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POL-{00000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Line__c/fields/AcctSeedERP__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Purchase_Order_Line__c/fields/AcctSeedERP__Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>AcctSeedERP__Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Line__c/fields/AcctSeedERP__Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Unit_Price__c</fullName>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Line__c/fields/GMBLASERP__Quantity_Received_Non_Inventory__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Quantity_Received_Non_Inventory__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantity Received Non-Inventory</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Inventory_Movement_Cube__c/GMBLASERP__Inventory_Movement_Cube__c.object-meta.xml
<CustomObject>
    <label>Inventory Movement Cube</label>
    <nameField>
        <displayFormat>IMC-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Movement Cubes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/GMBLASERP__Inventory_Movement_Cube__c/fields/GMBLASERP__Inventory_Balance__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Inventory_Balance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Balance</label>
    <referenceTo>AcctSeedERP__Inventory_Balance__c</referenceTo>
    <relationshipLabel>Inventory Movement Cubes</relationshipLabel>
    <relationshipName>Inventory_Movement_Cubes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Inventory_Movement_Cube__c/fields/GMBLASERP__Location__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>AcctSeedERP__Location__c</referenceTo>
    <relationshipLabel>Inventory Movement Cubes</relationshipLabel>
    <relationshipName>Inventory_Movement_Cubes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Inventory_Movement_Cube__c/fields/GMBLASERP__Movement_Date__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Movement_Date__c</fullName>
    <label>Movement Date</label>
    <type>Date</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Inventory_Movement_Cube__c/fields/GMBLASERP__Product__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inventory Movement Cubes</relationshipLabel>
    <relationshipName>Inventory_Movement_Cubes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GMBLASERP__Inventory_Movement_Cube__c/fields/GMBLASERP__Warehouse__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Inventory Movement Cubes</relationshipLabel>
    <relationshipName>Inventory_Movement_Cubes</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/classes/gcAccountPayable_Actions_Test.cls
/**
 * Created by Legend on 20/12/21.
 */

@isTest
private class gcAccountPayable_Actions_Test {
    @TestSetup
    static void testData(){
        new Factory_TestData();
        Factory_CustomSettings.setupInventorySettings();
        new Factory_AccountingVariables();
    }

    static void init()
    {
        map<Id,map<Id,map<Id,Id>>> mapPWLB = new map<Id,map<Id,map<Id,Id>>>();
        Product2 part = Factory_Product.createNonSerializedProduct('Part', 'Hardware');
        Product2 part2 = Factory_Product.createNonSerializedProduct('Part', 'Vehicle and Equipment Parts');
        Id idWarehouse = gcConstants.idWarehouseMontreal;
        AcctSeedERP__Location__c loc = [SELECT Id FROM AcctSeedERP__Location__c WHERE AcctSeedERP__Warehouse__c =:idWarehouse LIMIT 1];

        mapPWLB.put(part.Id, new map<Id,map<Id,Id>>());
        mapPWLB.get(part.Id).put(idWarehouse, new map<Id,Id>());
        mapPWLB.get(part.Id).get(idWarehouse).put(loc.Id,null);

        GCR_InventoryBalance.findOrCreateBalances(mapPWLB);
        Account[] accts = Factory_Account.insertSupplierAccounts(2);
        Account vendor = accts[0];
        Account shipTo = accts[1];
        AcctSeedERP__Purchase_Order__c po = Factory_PurchaseOrder.createMinimalPO( vendor.Id, shipTo.Id );
        AcctSeedERP__Purchase_Order_Line__c pol = new AcctSeedERP__Purchase_Order_Line__c(
                AcctSeedERP__Purchase_Order__c = po.Id,
                AcctSeedERP__Product__c = part.Id,
                AcctSeedERP__Quantity__c = 10,
                AcctSeedERP__Unit_Price__c = 10.00
        );
        AcctSeedERP__Purchase_Order_Line__c pol2 = new AcctSeedERP__Purchase_Order_Line__c(
                AcctSeedERP__Purchase_Order__c = po.Id,
                AcctSeedERP__Product__c = part2.Id,
                AcctSeedERP__Quantity__c = 10,
                AcctSeedERP__Unit_Price__c = 10.00,
                GMBLASERP__Quantity_Received_Non_Inventory__c = 10
        );
        insert new List<AcctSeedERP__Purchase_Order_Line__c>{pol,pol2};
        AcctSeedERP__Purchase_Order_Inventory_Movement__c movement = new AcctSeedERP__Purchase_Order_Inventory_Movement__c(
                AcctSeedERP__Unit_Cost__c = 10,
                GMBLASERP__Cost_Override__c = true,
                AcctSeedERP__Quantity__c = 5,
                AcctSeedERP__Inventory_Balance__c = mapPWLB.get(part.Id).get(idWarehouse).get(loc.Id),
                AcctSeedERP__Ledger__c = gcConstants.idActualLedger,
                GMBLASERP__Warehouse__c = idWarehouse,
                AcctSeedERP__Movement_Date__c = Date.today(),
                GMBLASERP__Product__c = part.Id,
                AcctSeedERP__Purchase_Order_Line__c = pol.Id,
                GMBLASERP__Purchase_Order__c = po.Id
        );
        gcPurchaseOrderInventoryMovement.disableTrigger = true;
        insert new List<AcctSeedERP__Purchase_Order_Inventory_Movement__c>{movement};

        GMBLASERP.gcInventoryMovementCube.allowDML = true;
        GMBLASERP__Inventory_Movement_Cube__c cube = new GMBLASERP__Inventory_Movement_Cube__c();
        cube.GMBLASERP__Inventory_Balance__c = mapPWLB.get(part.Id).get(idWarehouse).get(loc.Id);
        cube.GMBLASERP__Location__c = loc.Id;
        cube.GMBLASERP__Product__c = part.Id;
        cube.GMBLASERP__Movement_Date__c = Date.today();
        cube.GMBLASERP__Warehouse__c = idWarehouse;
        cube.GMBLASERP__Movement_Type__c = 'AcctSeedERP__Purchase_Order_Inventory_Movement__c';
        cube.GMBLASERP__Quantity__c = 10;
        cube.GMBLASERP__Inventory_GL_Amount__c = 100;

        GMBLASERP.gcInventoryMovementCube.disableTrigger = true;
        insert new List<GMBLASERP__Inventory_Movement_Cube__c>{cube};
    }

    @isTest
    static void testScenario1() {
        init();
        AcctSeedERP__Purchase_Order__c po = [SELECT id FROM AcctSeedERP__Purchase_Order__c limit 1];
        ApexPages.StandardController sc = new ApexPages.StandardController(po);
        Test.startTest();
        PageReference pageRef = Page.gpAccountPayable_Actions;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('idFilter',po.Id);
        gcAccountPayable_Actions accountPayableActions = new gcAccountPayable_Actions(sc);
        accountPayableActions.init();
        Test.stopTest();
        AcctSeed__Account_Payable__c[] ap = [SELECT Id FROM AcctSeed__Account_Payable__c WHERE AcctSeedERP__Purchase_Order__c =: po.Id];
        System.assertEquals(ap.size(),1);
    }
}