src/Base/main/default/objects/AcctSeed__Account_Payable__c/AcctSeed__Account_Payable__c.object-meta.xml
<CustomObject>
    <description>Used to document liabilities to outside vendor, contact, or employee.</description>
    <label>Payable</label>
    <nameField>
        <displayFormat>AP-{00000}</displayFormat>
        <label>Payable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Account_Payable__c/fields/AcctSeed__Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <inlineHelpText>Used to record vendor invoice or credit memo date.</inlineHelpText>
    <label>Issue Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Account_Payable__c/fields/AcctSeed__Payee_Reference__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Payee_Reference__c</fullName>
    <inlineHelpText>Used for Vendor Invoice Number or Expense processing date if account payable is generated from expenses.</inlineHelpText>
    <label>Payee Reference</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Account_Payable__c/fields/AcctSeed__Vendor__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Vendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>An Account Payable can have either the Account (Vendor), Contact or User (Employee) as the Payee.  One object must be chosen.</inlineHelpText>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Type__c</field>
            <operation>contains</operation>
            <value>Vendor, Customer and Vendor</value>
        </filterItems>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>Accounts Filtered on Accounting Type=Vendor and Accounting Active=True</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Project_Payable_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Account_Payable__c/fields/AcctSeedERP__Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order</label>
    <referenceTo>AcctSeedERP__Purchase_Order__c</referenceTo>
    <relationshipLabel>Payables</relationshipLabel>
    <relationshipName>Accounts_Payable</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Account_Payable_Line__c/AcctSeed__Account_Payable_Line__c.object-meta.xml
<CustomObject>
    <description>Line item expense associated with an payable. The aggregation of multiple payable lines constitute a payable record.</description>
    <label>Payable Line</label>
    <nameField>
        <displayFormat>APL-{00000}</displayFormat>
        <label>Payable Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payable Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Account_Payable_Line__c/fields/AcctSeed__Account_Payable__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account_Payable__c</fullName>
    <inlineHelpText>Reference to Accounts Payable Header.</inlineHelpText>
    <label>Payable</label>
    <referenceTo>AcctSeed__Account_Payable__c</referenceTo>
    <relationshipName>Project_Account_Payable_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Account_Payable_Line__c/fields/AcctSeed__Amount__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Amount__c</fullName>
    <inlineHelpText>Currency field to record amount of line.</inlineHelpText>
    <label>Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Account_Payable_Line__c/fields/AcctSeed__Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <inlineHelpText>Optional Date used to override the date on the Accounts Payable parent object when posting to the transaction object. Most useful in the Time &amp; Material Billing process to provide date information for the related billing line.</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Account_Payable_Line__c/fields/AcctSeedERP__Purchase_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Purchase_Order_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchase Order Line</label>
    <referenceTo>AcctSeedERP__Purchase_Order_Line__c</referenceTo>
    <relationshipLabel>Account Payable Lines</relationshipLabel>
    <relationshipName>Account_Payable_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Accounting_Settings__c/AcctSeed__Accounting_Settings__c.object-meta.xml
<CustomObject>
    <description>Main record used to define configuration and default settings used in the application.</description>
    <label>Accounting Settings</label>
    <nameField>
        <label>Account Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Accounting_Settings__c/fields/AcctSeed__Vouchers_Payable_GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Vouchers_Payable_GL_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>This GL Account is credited when a Purchase Order product has been received.  Then match a Vendor Invoice by creating a Payable from the Purchase Order page.  This action will then debit Vouchers Payable and credit Accounts Payable.</inlineHelpText>
    <label>Vouchers Payable GL Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__GL_Account__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Balance Sheet</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipLabel>Accounting_Settings (Vouchers Payable)</relationshipLabel>
    <relationshipName>Accounting_Settings1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Transaction__c/AcctSeed__Transaction__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific entry to a ledger. Transaction records are created when a source record is posted i.e. payable, billing, cash disbursement, cash receipt, journal entry, scheduled revenue expense, and time card.</description>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{00000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Transaction__c/fields/AcctSeed__Account_Payable__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account_Payable__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Related source record for the origin of the entry.</inlineHelpText>
    <label>Payable</label>
    <referenceTo>AcctSeed__Account_Payable__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Transaction__c/fields/AcctSeed__Account_Payable_Line__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account_Payable_Line__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Reference to source transaction.</inlineHelpText>
    <label>Payable Line</label>
    <referenceTo>AcctSeed__Account_Payable_Line__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Project_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Transaction__c/fields/AcctSeed__Amount__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Amount__c</fullName>
    <inlineHelpText>Debits are represented as positive amounts and credits are represented as negative amounts.</inlineHelpText>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Transaction__c/fields/AcctSeed__Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Date__c</fullName>
    <inlineHelpText>Transaction Date. Primarily used in billing records and for reporting purposes.</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Transaction__c/fields/AcctSeed__GL_Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__GL_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Major classification for financial reporting.</inlineHelpText>
    <label>GL Account</label>
    <referenceTo>AcctSeed__GL_Account__c</referenceTo>
    <relationshipName>Project_Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Transaction__c/fields/AcctSeedERP__Purchase_Order_Inventory_Movement__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Purchase_Order_Inventory_Movement__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Purchase Order Inventory Movement</label>
    <referenceTo>AcctSeedERP__Purchase_Order_Inventory_Movement__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order__c/AcctSeedERP__Purchase_Order__c.object-meta.xml
<CustomObject>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{00000}</displayFormat>
        <label>Purchase Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Purchase_Order__c/fields/AcctSeedERP__Vendor__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.AcctSeed__Accounting_Type__c</field>
            <operation>equals</operation>
            <value>Vendor, Customer and Vendor</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Purchase_Order_Inventory_Movement__c/AcctSeedERP__Purchase_Order_Inventory_Movement__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Inventory Movement</label>
    <nameField>
        <displayFormat>PIM-{00000}</displayFormat>
        <label>Purchasing Inventory Movement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Inventory Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Inventory_Movement__c/fields/AcctSeedERP__Purchase_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Purchase_Order_Line__c</fullName>
    <label>Purchase Order Line</label>
    <referenceTo>AcctSeedERP__Purchase_Order_Line__c</referenceTo>
    <relationshipLabel>Purchase Order Inventory Movements</relationshipLabel>
    <relationshipName>Purchase_Order_Inventory_Movements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Inventory_Movement__c/fields/GMBLASERP__Account_Payable_Line__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Account_Payable_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Payable Line</label>
    <referenceTo>AcctSeed__Account_Payable_Line__c</referenceTo>
    <relationshipLabel>Purchase Order Inventory Movements</relationshipLabel>
    <relationshipName>Purchase_Order_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Line__c/AcctSeedERP__Purchase_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POL-{00000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeedERP__Purchase_Order_Line__c/fields/AcctSeedERP__Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Purchase_Order__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>AcctSeedERP__Purchase_Order__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/gcAccountPayable_Actions.cls
public with sharing class gcAccountPayable_Actions {
	public gcAccountPayable_Actions() {}
	
	public gcAccountPayable_Actions(ApexPages.StandardController stc){
		idFilter = stc.getId();
		retUrl = '/'+stc.getId();
	}

	public gcAccountPayable_Actions(ApexPages.StandardSetController ssc){
		retUrl = ApexPages.currentPage().getParameters().get('retUrl');
	}
	
	public pageReference back()
	{
		return new pageReference(retUrl);
	}
	
	public pageReference init()
	{
		String processName = ApexPages.currentPage().getParameters().get('processName');
		idFilter = ApexPages.currentPage().getParameters().get('idFilter');

		if(idFilter == null)
		{
	 		ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'No Purchase Order was selected to Create AP.'));
	 		return null;					
	 	}

		if(retUrl == null && idFilter != null)
			retUrl = '/'+idFilter;

		return createAP();
	}
	
	private Id idFilter{get;set;}
	private String retUrl{get;set;}

	public pageReference createAP()
	{
		if(!AcctSeed__Account_Payable__c.sObjectType.getDescribe().accessible)
		{
	 		ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'The current user does not have access to the Account Payable object.'));
	 		return null;					
		}

		AcctSeedERP__Purchase_Order__c po = [SELECT Id, Name, AcctSeedERP__Vendor__c, AcctSeedERP__Vendor__r.Name FROM AcctSeedERP__Purchase_Order__c WHERE Id =:idFilter][0];
		String vendorInvoiceNumber = po.Name + '-' + po.AcctSeedERP__Vendor__r.Name + String.valueOf(DateTime.now().getTime());
		AcctSeed__Account_Payable__c ap = new AcctSeed__Account_Payable__c(
												AcctSeed__Vendor__c = po.AcctSeedERP__Vendor__c,
												AcctSeed__Date__c = date.Today(),
												Approval_Date__c = date.Today(),
												Approved__c = true,
												AcctSeed__Payee_Reference__c = vendorInvoiceNumber,
												AcctSeedERP__Purchase_Order__c = po.Id);
		insert ap;

		//get the Vouchers Payable account
		Id idGLVP = [SELECT AcctSeed__Vouchers_Payable_GL_Account__c FROM AcctSeed__Accounting_Settings__c][0].AcctSeed__Vouchers_Payable_GL_Account__c;

		//get the VP balance for each Purchase Order Line
		list<AggregateResult> listAggRes = new list<AggregateResult>();

		listAggRes.addAll(
			[SELECT AcctSeedERP__Purchase_Order_Inventory_Movement__r.AcctSeedERP__Purchase_Order_Line__c idPOL,
					sum(AcctSeedERP__Purchase_Order_Inventory_Movement__r.AcctSeedERP__Quantity__c) qty,
					sum(AcctSeed__Amount__c) amt
			 FROM AcctSeed__Transaction__c
			 WHERE AcctSeed__GL_Account__c = :idGLVP
			   AND AcctSeedERP__Purchase_Order_Inventory_Movement__r.AcctSeedERP__Purchase_Order_Line__r.AcctSeedERP__Purchase_Order__c = :po.Id
			   AND AcctSeedERP__Purchase_Order_Inventory_Movement__r.GMBLASERP__Account_Payable_Line__c = null
			   AND (AcctSeed__Amount__c < 0 OR AcctSeed__Amount__c > 0)
			 GROUP BY AcctSeedERP__Purchase_Order_Inventory_Movement__r.AcctSeedERP__Purchase_Order_Line__c]);

		list<AcctSeed__Account_Payable_Line__c> listAPL = new list<AcctSeed__Account_Payable_Line__c>();
		map<Id,AcctSeedERP__Purchase_Order_Line__c> mapPOL = new map<Id,AcctSeedERP__Purchase_Order_Line__c>();

		//create the new AP Lines
		for(AggregateResult aggRes : listAggRes)
		{
			Decimal amt = (Decimal)aggRes.get('amt');

			if(amt != null && amt != 0)
			{
				mapPOL.put((Id)aggRes.get('idPOL'), null);
				listAPL.add(new AcctSeed__Account_Payable_Line__c(
					AcctSeed__Account_Payable__c = ap.Id,
					AcctSeed__Amount__c = amt * (-1),
					AcctSeed__Expense_GL_Account__c = idGLVP,
					AcctSeed__Quantity__c = (Decimal)aggRes.get('qty'),
					AcctSeedERP__Purchase_Order_Line__c = (Id)aggRes.get('idPOL')
				));
			}
		}

		//retrieve additional PO line details, to be used to populate the AP lines
		for(AcctSeedERP__Purchase_Order_Line__c pol : 
			[SELECT Id,
					AcctSeedERP__Product__c, 
					AcctSeedERP__Project__c, 
					AcctSeedERP__Project_Task__c
			 FROM AcctSeedERP__Purchase_Order_Line__c
			 WHERE Id IN : mapPOL.keySet()])
		{
			mapPOL.put(pol.Id,pol);
		}

		//transfer the details of the PO lines to the new AP lines
		for(AcctSeed__Account_Payable_Line__c apl : listAPL)
		{
			AcctSeedERP__Purchase_Order_Line__c pol = mapPOL.get(apl.AcctSeedERP__Purchase_Order_Line__c);
			apl.AcctSeed__Product__c = pol.AcctSeedERP__Product__c;
			apl.AcctSeed__Project__c = pol.AcctSeedERP__Project__c;
			apl.AcctSeed__Project_Task__c = pol.AcctSeedERP__Project_Task__c;
		}

		Id idGLExpenseDefault = null;
		for(AcctSeed__GL_Account__c gl :[SELECT Id FROM AcctSeed__GL_Account__c WHERE AcctSeed__Type__c = 'Expense' AND AcctSeed__Active__c = true ORDER BY Name LIMIT 1])
			idGLExpenseDefault = gl.Id;
		if(idGLExpenseDefault == null)
		{
	 		ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'There must be at least one active GL Account of type Expense, in order to process an AP.'));
	 		return null;					
		}

		//retrieve PO lines for non-inventory products, and create AP lines for them
		for(AcctSeedERP__Purchase_Order_Line__c pol : 
			[SELECT Id, Name,
				    AcctSeedERP__Product__c,
				    AcctSeedERP__Product__r.AcctSeed__Expense_GL_Account__c,
				    AcctSeedERP__Product__r.Name,
				    AcctSeedERP__Project__c,
				    AcctSeedERP__Project_Task__c,
				    AcctSeedERP__Unit_Price__c,
				    GMBLASERP__Quantity_Received_Non_Inventory__c,
				    (SELECT AcctSeed__Amount__c, AcctSeed__Quantity__c FROM AcctSeedERP__Account_Payable_Lines__r WHERE AcctSeed__Expense_GL_Account__c != :idGLVP)
			 FROM AcctSeedERP__Purchase_Order_Line__c
			 WHERE AcctSeedERP__Purchase_Order__c = : po.Id
			   AND GMBLASERP__Quantity_Received_Non_Inventory__c != 0
			   AND GMBLASERP__Quantity_Received_Non_Inventory__c != null
			   AND AcctSeedERP__Unit_Price__c != 0
			   AND AcctSeedERP__Unit_Price__c != null])
		{
			Decimal qtyPaid = 0;
			Decimal amtPaid = 0;
			for(AcctSeed__Account_Payable_Line__c apl : pol.AcctSeedERP__Account_Payable_Lines__r)
			{
				if(apl.AcctSeed__Amount__c != null) amtPaid += apl.AcctSeed__Amount__c;
				if(apl.AcctSeed__Quantity__c != null) qtyPaid += apl.AcctSeed__Quantity__c;
			}

			Decimal qtyReceived = pol.GMBLASERP__Quantity_Received_Non_Inventory__c;
			Decimal amtReceived = pol.GMBLASERP__Quantity_Received_Non_Inventory__c * pol.AcctSeedERP__Unit_Price__c;

			Id idGL = pol.AcctSeedERP__Product__r.AcctSeed__Expense_GL_Account__c;
			if(idGL == null) idGL = idGLExpenseDefault;

			if(amtPaid.setScale(6) < amtReceived.setScale(6))
			listAPL.add(new AcctSeed__Account_Payable_Line__c(
				AcctSeed__Account_Payable__c = ap.Id,
				AcctSeed__Amount__c = (amtReceived - amtPaid).setScale(6),
				AcctSeed__Quantity__c = (qtyReceived - qtyPaid).setScale(6),
				AcctSeed__Expense_GL_Account__c = idGL,
				AcctSeed__Product__c = pol.AcctSeedERP__Product__c,
				AcctSeed__Project__c = pol.AcctSeedERP__Project__c,
				AcctSeed__Project_Task__c = pol.AcctSeedERP__Project_Task__c,
				AcctSeedERP__Purchase_Order_Line__c = pol.Id
			));
		}

		insert listAPL;

		//prepare to update the Purchase Order Inventory Movements with the new AP Lines
		map<Id,Id> mapPOLtoAPL = new map<Id,Id>();
		for(AcctSeed__Account_Payable_Line__c apl : listAPL)
		{
			mapPOLtoAPL.put(apl.AcctSeedERP__Purchase_Order_Line__c, apl.Id);
		}

		//update the Purchase Order Inventory Movements
		list<AcctSeedERP__Purchase_Order_Inventory_Movement__c> listMove = new list<AcctSeedERP__Purchase_Order_Inventory_Movement__c>();
		for(AcctSeedERP__Purchase_Order_Inventory_Movement__c move :
			[SELECT Id, AcctSeedERP__Purchase_Order_Line__c, GMBLASERP__Account_Payable_Line__c
			 FROM AcctSeedERP__Purchase_Order_Inventory_Movement__c
			 WHERE AcctSeedERP__Purchase_Order_Line__c IN : mapPOLtoAPL.keySet()
			   AND GMBLASERP__Account_Payable_Line__c = null])
		{
			move.GMBLASERP__Account_Payable_Line__c = mapPOLtoAPL.get(move.AcctSeedERP__Purchase_Order_Line__c);
			listMove.add(move);
		}

		GMBLASERP.gcPurchaseOrderInventoryMovement.disableTrigger = true;
		update listMove;
		GMBLASERP.gcPurchaseOrderInventoryMovement.disableTrigger = false;
 		//ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.CONFIRM, 'Account Payable has been created. <a target="_blank" href="/'+ap.Id+'">Click here to view AP detail.</a>'));
 		return new pageReference('/'+ap.Id);
	}

	public static void coverage(){
		integer i;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
	}
}