force-app/main/default/objects/AcctSeedERP__Inbound_Inventory_Movement__c/AcctSeedERP__Inbound_Inventory_Movement__c.object-meta.xml
<CustomObject>
    <label>Inbound Inventory Movement</label>
    <nameField>
        <displayFormat>IIM-{00000}</displayFormat>
        <label>Inbound Inventory Movement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Inventory Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeedERP__Inbound_Inventory_Movement__c/fields/Inventory_Adjustment_Import__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Adjustment_Import__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Adjustment Import</label>
    <referenceTo>Inventory_Adjustment_Import__c</referenceTo>
    <relationshipLabel>Inbound Inventory Movements</relationshipLabel>
    <relationshipName>Inbound_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory_Adjustment_Import__c/Inventory_Adjustment_Import__c.object-meta.xml
<CustomObject>
    <label>Import Adjustment Quantity</label>
    <nameField>
        <displayFormat>IAI-{0000}</displayFormat>
        <label>IAI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Import Adjustment Quantities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/classes/importUpdateWithInboundBatch.cls
global without sharing class importUpdateWithInboundBatch implements Schedulable, Database.Batchable<sObject> {
  global importUpdateWithInboundBatch() {
  }

  global Database.QueryLocator start(Database.BatchableContext BC) {
    String query = 'SELECT Id, Inventory_Adjustment_Import__c FROM AcctSeedERP__Inbound_Inventory_Movement__c WHERE Inventory_Adjustment_Import__c != null';
    return Database.getQueryLocator(query);
  }

  global void execute(Database.BatchableContext BC, List<sObject> scope) {
    List<Inventory_Adjustment_Import__c> listImport = new List<Inventory_Adjustment_Import__c>();
    for (SObject sObj : scope) {
      AcctSeedERP__Inbound_Inventory_Movement__c imp = (AcctSeedERP__Inbound_Inventory_Movement__c) sObj;
      listImport.add(
        new Inventory_Adjustment_Import__c(Id = imp.Inventory_Adjustment_Import__c, Has_Inbound__c = true)
      );
    }

    if (!listImport.isEmpty()) {
      update listImport;
    }
  }

  global void execute(SchedulableContext sc) {
    importUpdateWithInboundBatch b = new importUpdateWithInboundBatch();
    database.executeBatch(b, 1);
  }

  global void finish(Database.BatchableContext BC) {
  }

  global static void coverage() {
    integer i;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
  }
}