force-app/main/default/objects/AcctSeedERP__Inbound_Inventory_Movement__c/AcctSeedERP__Inbound_Inventory_Movement__c.object-meta.xml
<CustomObject>
    <label>Inbound Inventory Movement</label>
    <nameField>
        <displayFormat>IIM-{00000}</displayFormat>
        <label>Inbound Inventory Movement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Inventory Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeedERP__Inbound_Inventory_Movement__c/fields/GMBLASERP__Inventory_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Inventory_Adjustment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Adjustment</label>
    <referenceTo>GMBLASERP__Inventory_Adjustment__c</referenceTo>
    <relationshipLabel>Inbound Inventory Movements</relationshipLabel>
    <relationshipName>Inbound_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Inbound_Inventory_Movement__c/fields/GMBLASERP__Product__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inbound Inventory Movements</relationshipLabel>
    <relationshipName>Inbound_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Inventory_Adjustment__c/GMBLASERP__Inventory_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Inventory Adjustment</label>
    <nameField>
        <displayFormat>ADJ-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/GMBLASERP__Inventory_Adjustment__c/fields/GMBLASERP__Adjustment_Type__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Adjustment_Type__c</fullName>
    <label>Adjustment Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Quantity</fullName>
            </value>
            <value>
                <fullName>Value</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Inventory_Adjustment__c/fields/GMBLASERP__Product__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inventory Adjustments</relationshipLabel>
    <relationshipName>Inventory_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeed__Inventory_Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Inventory_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes whether the product is a managed inventory product</description>
    <inlineHelpText>Denotes whether the product is a managed inventory product</inlineHelpText>
    <label>Inventory Product</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/classes/gcAdjustment_Actions.cls
public with sharing class gcAdjustment_Actions {
  public gcAdjustment_Actions() {
  }

  public gcAdjustment_Actions(ApexPages.StandardController stc) {
    idFilter = stc.getId();
    retUrl = '/' + stc.getId();
  }

  public gcAdjustment_Actions(ApexPages.StandardSetController ssc) {
    retUrl = ApexPages.currentPage().getParameters().get('retUrl');
  }

  public pageReference back() {
    return new pageReference(retUrl);
  }

  public pageReference init() {
    idFilter = ApexPages.currentPage().getParameters().get('idFilter');

    if (idFilter == null) {
      ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'No Adjustment has been selected.'));
      return null;
    }

    if (retUrl == null && idFilter != null)
      retUrl = '/' + idFilter;

    return createBlankAdjustment();
  }

  private Id idFilter { get; set; }
  private String retUrl { get; set; }

  public pageReference createBlankAdjustment() {
    for (GMBLASERP__Inventory_Adjustment__c adjustment : [
      SELECT
        Id,
        GMBLASERP__Adjustment_Type__c,
        GMBLASERP__Product__c,
        GMBLASERP__Product__r.AcctSeed__Inventory_Product__c,
        (SELECT Id FROM GMBLASERP__Inbound_Inventory_Movements__r LIMIT 1)
      FROM GMBLASERP__Inventory_Adjustment__c
      WHERE Id = :idFilter
    ]) {
      if (!adjustment.GMBLASERP__Inbound_Inventory_Movements__r.isEmpty()) {
        ApexPages.addMessage(
          new ApexPages.message(ApexPages.Severity.ERROR, 'Adjustment has already started. Cannot create blank line.')
        );
        return null;
      }
      if (adjustment.GMBLASERP__Adjustment_Type__c != 'Quantity') {
        ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'Adjustment type must be Quantity.'));
        return null;
      }
      if (adjustment.GMBLASERP__Product__c == null) {
        ApexPages.addMessage(
          new ApexPages.message(
            ApexPages.Severity.ERROR,
            'A product must be defined in Adjustment to create a blank adjustment.'
          )
        );
        return null;
      }
      if (!adjustment.GMBLASERP__Product__r.AcctSeed__Inventory_Product__c) {
        ApexPages.addMessage(
          new ApexPages.message(
            ApexPages.Severity.ERROR,
            'The product must be an inventory product to create a blank adjustment.'
          )
        );
        return null;
      }

      GMBLASERP.gcInventoryAdjustment_Ext.createAdjustment(adjustment.Id, adjustment.GMBLASERP__Product__c);
      return new pageReference(retUrl);
    }
    ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, 'Adjustment was not found.'));
    return null;
  }
}