src/Base/main/default/objects/CommissionLineItem__c/CommissionLineItem__c.object-meta.xml
<CustomObject>
    <label>Commission Line Item</label>
    <nameField>
        <label>Commission Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CommissionLineItem__c/fields/CommissionRecord__c.field-meta.xml
<CustomField>
    <fullName>CommissionRecord__c</fullName>
    <label>Commission Record</label>
    <referenceTo>CommissionRecord__c</referenceTo>
    <relationshipLabel>Commission Line Items</relationshipLabel>
    <relationshipName>CommissionLineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CommissionLineItem__c/fields/IsInsurance__c.field-meta.xml
<CustomField>
    <fullName>IsInsurance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsInsurance</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/CommissionLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Commission Line Items</relationshipLabel>
    <relationshipName>Commission_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/CommissionRecord__c/CommissionRecord__c.object-meta.xml
<CustomObject>
    <label>Commission Record</label>
    <nameField>
        <label>Commision Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/CommissionRecord__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <label>OpportunityId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/CommissionRecord__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Retail Sales</fullName>
            </value>
            <value>
                <fullName>Business Office</fullName>
            </value>
            <value>
                <fullName>Counter Sale</fullName>
            </value>
            <value>
                <fullName>Partner Sales</fullName>
            </value>
            <value>
                <fullName>Retail Counter Sale</fullName>
            </value>
            <value>
                <fullName>Partner Counter Sale</fullName>
            </value>
            <value>
                <fullName>Service Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Insurance_Rate__c/Insurance_Rate__c.object-meta.xml
<CustomObject>
    <label>Insurance Rate</label>
    <nameField>
        <displayFormat>IR-{0000}</displayFormat>
        <label>Insurance Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insurance Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insurance_Rate__c/fields/Joint__c.field-meta.xml
<CustomField>
    <fullName>Joint__c</fullName>
    <label>Joint</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insurance_Rate__c/fields/Lower_Finance_Term__c.field-meta.xml
<CustomField>
    <fullName>Lower_Finance_Term__c</fullName>
    <label>Lower Finance Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Insurance_Rate__c/fields/Lower_Term__c.field-meta.xml
<CustomField>
    <fullName>Lower_Term__c</fullName>
    <label>Lower Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Insurance_Rate__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Insurance Rates</relationshipLabel>
    <relationshipName>Insurance_Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insurance_Rate__c/fields/Single__c.field-meta.xml
<CustomField>
    <fullName>Single__c</fullName>
    <label>Single</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Insurance_Rate__c/fields/Tax_Zone__c.field-meta.xml
<CustomField>
    <fullName>Tax_Zone__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Tax Zone used to calculate rate.  ( GLV3 )</description>
    <label>Tax Zone</label>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Insurance Rates</relationshipLabel>
    <relationshipName>Insurance_Rates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insurance_Rate__c/fields/Upper_Finance_Term__c.field-meta.xml
<CustomField>
    <fullName>Upper_Finance_Term__c</fullName>
    <label>Upper Finance Term</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Insurance_Rate__c/fields/Upper_Term__c.field-meta.xml
<CustomField>
    <fullName>Upper_Term__c</fullName>
    <label>Upper Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/InsurancePlan__c/InsurancePlan__c.object-meta.xml
<CustomObject>
    <label>Insurance Plan</label>
    <nameField>
        <label>Insurance Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Calculate_Insurance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Calculate_Insurance_Amount__c</fullName>
    <formula>Amount + TotalTaxes__c -  Insurance_Total__c -  Deposit__c + Trade_In_Lien__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Calculate Insurance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Deposit__c.field-meta.xml
<CustomField>
    <fullName>Deposit__c</fullName>
    <description>Amount of Deposit</description>
    <label>Deposit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Finance_Term__c.field-meta.xml
<CustomField>
    <fullName>Finance_Term__c</fullName>
    <defaultValue>60</defaultValue>
    <label>Finance Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Insurance_Term__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Term__c</fullName>
    <defaultValue>60</defaultValue>
    <label>Insurance Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Invoice_Document_Id__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Document_Id__c</fullName>
    <label>Invoice Document Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Opportunity/fields/Pre_Insurance_Total__c.field-meta.xml
<CustomField>
    <fullName>Pre_Insurance_Total__c</fullName>
    <formula>Amount +  TotalTaxes__c   - Insurance_Total__c -  Trade_In_Value__c +  Trade_In_Lien__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pre-Insurance Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TotalTaxes__c.field-meta.xml
<CustomField>
    <fullName>TotalTaxes__c</fullName>
    <formula>Tax_Amount_Federal__c +  Tax_Amount_Provincial__c + Tax_Amount_Retail__c</formula>
    <label>Total Taxes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/OpportunityLineItem/fields/BoatBuilderItem__c.field-meta.xml
<CustomField>
    <fullName>BoatBuilderItem__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This Item was add from the Boat Builder</description>
    <label>BoatBuilderItem</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Finance_Term__c.field-meta.xml
<CustomField>
    <fullName>Finance_Term__c</fullName>
    <formula>Opportunity.Finance_Term__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Finance Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/OpportunityLineItem/fields/Insurance_Rate__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Rate__c</fullName>
    <label>Insurance Rate</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/OpportunityLineItem/fields/Insurance_Term__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Term__c</fullName>
    <formula>Opportunity.Insurance_Term__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Insurance Term</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/InsuranceCoverage__c.field-meta.xml
<CustomField>
    <fullName>InsuranceCoverage__c</fullName>
    <label>InsuranceCoverage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Joint</fullName>
            </value>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>Buyer Only</fullName>
                <isActive>false</isActive>
                <label>Buyer Only</label>
            </value>
            <value>
                <fullName>Co-Buyer Only</fullName>
                <isActive>false</isActive>
                <label>Co-Buyer Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/OpportunityLineItem/fields/isDiscount__c.field-meta.xml
<CustomField>
    <fullName>isDiscount__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDiscount</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/TotalTaxes__c.field-meta.xml
<CustomField>
    <fullName>TotalTaxes__c</fullName>
    <formula>IF( PricebookEntry.Product2.Taxable__c,
  IF( IsInsurance__c,
    IF( ISPICKVAL(Opportunity.taxationProvince__c , &apos;Quebec&apos;), 0,  TotalPrice *  Opportunity.ProvincialTaxRate__c ),
    TotalPrice * ( Opportunity.ProvincialTaxRate__c +   $Setup.Legend_Settings__c.FederalTaxRate__c ) ),
  0 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TotalTaxes</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Product2/fields/InsurancePlan__c.field-meta.xml
<CustomField>
    <fullName>InsurancePlan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insurance Plan</label>
    <referenceTo>InsurancePlan__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>InsuranceProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Fees.recordType-meta.xml
<RecordType>
    <fullName>Fees</fullName>
    <active>true</active>
    <description>Fees</description>
    <label>Fees</label>
</RecordType>

src/Base/main/default/objects/Product_Option__c/Product_Option__c.object-meta.xml
<CustomObject>
    <label>Product Option</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Product Option ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Option__c/fields/From_Product__c.field-meta.xml
<CustomField>
    <fullName>From_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is generally the optional product (ie accessory)</description>
    <label>From_Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Options (From Product)</relationshipLabel>
    <relationshipName>From_Product_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Option__c/fields/To_Product__c.field-meta.xml
<CustomField>
    <fullName>To_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is generally the &#39;boat&#39; product an optional product is getting attached to</description>
    <label>To Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Product Options (To Product)</relationshipLabel>
    <relationshipName>To_Product_Options</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityExt_FI.cls
global with sharing class OpportunityExt_FI {

  public class WarrantyAndServiceItem {
    public String OpportunityId { get; set; }
    public String PricebookEntryId { get; set; }
    public String ProductName { get; set; }
    public Decimal UnitPrice { get; set; }
    public String OpportunityLineItemId { get; set; }
    public Boolean isSelected { get; set; }

    public WarrantyAndServiceItem(){
      this.isSelected = false;
      this.OpportunityLineItemId = '';
    }

  }

  private final ApexPages.StandardController std;
  public Id oppId { get; set; }
  public String oppPricebookId { get; set; }
  public OpportunityLineItem[] fiItems{ get; set; }
  public WarrantyAndServiceItem[] warAndServItems { get; set; }
  public Boolean hasInvoice { get; set; }
  public String planId {get; set;}
  public Map<String, Map<String, Set<String>>> planOptionsMap { get; set; }
  public Map<Id, PricebookEntry> planItems { get; set; }
  public OpportunityLineItem ppsaFee { get; set; }
  transient Opportunity opp;
  public Id ppsaFeePricebookEntryId { get; set; }
  public String pbName { get; set; }

  global OpportunityExt_FI(ApexPages.StandardController stdCrl) {
    this.std = stdCrl;
    this.oppId = std.getId();
    if(oppId != null)
    {
      opp = [SELECT Id, Invoice_Document_Id__c, Pricebook2Id, Pricebook2.Name FROM Opportunity WHERE Id = :oppId];
      this.oppPricebookId = opp.Pricebook2Id;
      this.pbName = opp.Pricebook2.Name;
      this.ppsaFeePricebookEntryId = findPpsaPricebookEntryId();
      this.ppsaFee = findPpsaFee();
      this.hasInvoice = opp.Invoice_Document_Id__c != null;
      this.fiItems = [SELECT Id,
                             Description,
                             Quantity,
                             InsuranceCoverage__c,
                             PricebookEntryId,
                             Insurance_Rate__c,
                             PricebookEntry.Product2Id,
                             PricebookEntry.Product2.Name,
                             PricebookEntry.Product2.InsurancePlan__c,
                             PricebookEntry.Product2.InsurancePlan__r.Name,
                             UnitPrice
                       FROM OpportunityLineItem
                       WHERE OpportunityId = :this.oppId
                       AND isInsurance__c = true];
      this.warAndServItems = fetchAvailableWarranyAndServiceItems(oppId);
      if( !fiItems.isEmpty() )
      {
        planId = fiItems[0].PricebookEntry.Product2.InsurancePlan__c;
        planItems = fetchPlanItems(planId, oppPricebookId);
      }
    }
  }

  public Map<Id,InsurancePlan__c> getPlans()
  {
    Map<Id, InsurancePlan__c> plans = new Map<Id, InsurancePlan__c>([SELECT Id, Name FROM InsurancePlan__c]);
    return plans;
  }

  public List<String> getCoverageOptions()
  {
    return LGND_Utilities.getPicklistValues('OpportunityLineItem', 'InsuranceCoverage__c');
  }

  public String getJSONcoverageOptions()
  {
    return JSON.serialize( getCoverageOptions() );
  }

  public Map<String, Map<String,String>> getPlanOptions()
  {
    if( planId == null || planId == '')
    {
      return null;
    }
    return groupedPlanOptions(planId, oppPricebookId);
  }

  public Boolean getRenderTable()
  {
    return planId == null || planId == '' ? false : true;
  }

  public void planChanged()
  {
    planId = Apexpages.currentPage().getParameters().get('planId');
    List<OpportunityLineItem> items = [SELECT Id
                                       FROM OpportunityLineItem
                                       WHERE OpportunityId = :oppId
                                       AND isInsurance__c = true];
    delete items;
    fiItems = new List<OpportunityLineItem>();
  }

  public PageReference updateInvoiceAndReturn()
  {
    try
    {
      Opportunity opp = [Select Id, Name FROM Opportunity WHERE Id = :oppId];
      //String fileName = opp.Name + ' - ' + Datetime.Now().format() + '.pdf';
      Document doc = OpportunityDocumentBuilder.buildInvoicePDF(opp, 'english');
      opp.Invoice_Document_Id__c = doc.Id;
      update opp;
      return new PageReference('/' + opp.Id);
    }
    catch(Exception e)
    {
      ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, e.getMessage() );
      ApexPages.addmessage(myMsg);
      return null;
    }
  }

  /* +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                  REMOTE ACTIONS
   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */

  @RemoteAction
  global static Map<String, Map<String,String>> planSelectOptions(String planId, String pbId)
  {
    return groupedPlanOptions(planId, pbId);
  }

  @RemoteAction
  global static OpportunityLineItem selectWarrantyOrServiceItem(String pricebookEntryId, String oppId)
  {
    PricebookEntry pbe = [SELECT Id, UnitPrice, Product2.Name
                          FROM PricebookEntry
                          WHERE Id = :pricebookEntryId];
    OpportunityLineItem oli = new OpportunityLineItem( PricebookEntryId = pbe.Id,
                                                        UnitPrice = pbe.UnitPrice,
                                                        Quantity = 1,
                                                        Description = pbe.Product2.Name,
                                                        OpportunityId = oppId,
                                                        BoatBuilderItem__c = true
                                                        );
    insert oli;
    //try {
    //   CommissionRecord__c cRecord  = [SELECT Id
    //                                    FROM CommissionRecord__c
    //                                    WHERE OpportunityId__c = : oppId
    //                                    AND Type__c = 'Business Office' ];
    //  CommissionLineItem__c cli = CommissionLineItem.newFromOpportunitylineItemId( oli.Id );
    //  cli.CommissionRecord__c = cRecord.Id;
    //  insert cli;
    //}
    //catch(Exception e){}

    //createCommissionLineItem(oli);
    return oli;
  }

  @RemoteAction
  global static OpportunityLineItem removeWarrantyOrServiceItem(String oppLineItemId)
  {
    OpportunityLineItem oli = [SELECT Id FROM OpportunityLineItem WHERE Id = :oppLineItemId];
    delete oli;
    return oli;
  }

  @RemoteAction
  global static OpportunityLineItem saveItem(String jsonData)
  {
      system.debug(jsonData);
     OpportunityLineItem item = (OpportunityLineItem)JSON.deserialize(jsonData, OpportunityLineItem.class);
     upsert item;
     return [SELECT Id,
                    Description,
                    Quantity,
                    InsuranceCoverage__c,
                    PricebookEntryId,
                    PricebookEntry.Product2Id,
                    PricebookEntry.Product2.Name,
                    PricebookEntry.Product2.InsurancePlan__c,
                    PricebookEntry.Product2.InsurancePlan__r.Name,
                    UnitPrice
             FROM OpportunityLineItem
             WHERE Id = :item.Id];
  }

  @RemoteAction
  global static void deleteItem(String itemId)
  {
    OpportunityLineItem item = [SELECT Id FROM OpportunityLineItem WHERE Id = :itemId];
    delete item;
  }

  @RemoteAction
  global static OpportunityLineItem savePPSA( String jsonData )
  {
    OpportunityLineItem oli = (OpportunityLineItem)JSON.Deserialize( jsonData, OpportunityLineItem.class);
    if( oli.UnitPrice == null || oli.UnitPrice == 0 )
    {
      delete oli;
      return null;
    }
    oli.isDiscount__c = false;
    oli.quantity = 1;
    //oli.BoatBuilderItem__c = true;
    upsert oli;
    return oli;
  }

/* +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                  PRIVATES
   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ */

  private Id findPpsaPricebookEntryId()
  {
    try
    {
      return [SELECT Id
              FROM PricebookEntry
              WHERE Pricebook2Id = :opp.Pricebook2Id
              AND Product2.Family = 'Bank Registration PPSA Fee'
              AND Product2.RecordType.Name = 'Fees' ].Id;
    }
    catch(Exception e)
    {
      return null;
    }
  }

  private OpportunityLineItem findPpsaFee()
  {
    if( this.ppsaFeePricebookEntryId != null )
    {
      try
      {
        return [SELECT Id, UnitPrice, OpportunityId, PricebookEntryId
                FROM OpportunityLineItem
                WHERE OpportunityId = :this.oppId
                AND PricebookEntryId = :this.ppsaFeePricebookEntryId];
      }
      catch( Exception e)
      {
        return new OpportunityLineItem(
          OpportunityId = this.oppId,
          PricebookEntryId = this.ppsaFeePricebookEntryId
        );
      }
    }
    return null;
  }

  private static Map<String, Map<String, String>> groupedPlanOptions(String planId, String pbId)
  {

    System.debug('Enter in group plan optionnn');
    Map<Id, PricebookEntry> planItems = fetchPlanItems(planId, pbId);
    Map<String, Map<String, String>> planOptionsMap = new Map<String, Map<String, String>>();
    for( PricebookEntry pItem :planItems.values() )
    {
      if( !planOptionsMap.containsKey(pItem.Product2.Family) )
      {
        planOptionsMap.put(pItem.Product2.Family, new Map<string,String>() );
      }
      planOptionsMap.get(pItem.Product2.Family).put(pItem.Id, pItem.Product2.Name);
    }

    return planOptionsMap;
  }


  private static Map<Id, PricebookEntry> fetchPlanItems( String planId, String pbId )
  {
    return new Map<Id, PricebookEntry>([SELECT Id,
                                               Product2.Name,
                                               Product2Id,
                                               Product2.Family
                                        FROM PricebookEntry
                                        WHERE Pricebook2Id = :pbId
                                        AND Product2.InsurancePlan__c = :planId]);
  }

  private WarrantyAndServiceItem[] fetchAvailableWarranyAndServiceItems(Id oppId)
  {
    WarrantyAndServiceItem[] availItems = new List<WarrantyAndServiceItem>();
    OpportunityLineItem[] oppLineItems = [ SELECT Id,
                                                  PricebookEntryId,
                                                  PricebookEntry.Pricebook2Id,
                                                  PricebookEntry.Product2Id,
                                                  OpportunityId
                                           FROM OpportunityLineItem
                                           WHERE OpportunityId = :oppId ];

    if( !oppLineItems.isEmpty() )
    {
      //map of <Product2Id, OpportunityLineItemId> for later use
      Map<Id, Id> p2Ids = new Map<Id, Id>();
      Id pbId = oppLineItems[0].PricebookEntry.Pricebook2Id;
      for( OpportunityLineItem oli : oppLineItems )
      {
        p2Ids.put(oli.PricebookEntry.Product2Id, oli.Id);
      }

      Product_Option__c[] options = [SELECT Id, From_Product__c
                                     FROM Product_Option__c
                                     WHERE To_Product__c IN :p2Ids.keySet()
                                     AND  ( From_Product__r.Family = 'Extended Warranty'
                                           OR From_Product__r.RecordType.Name = 'Protection and Services')
                                     ];

      if( !options.isEmpty() )
      {
        Set<Id> availIds = new Set<Id>();
        for( Product_Option__c po : options )
        {
          availIds.add(po.From_Product__c);
        }

        PricebookEntry[] pbItems = [SELECT Id, Product2Id, Product2.Name, UnitPrice
                      FROM PricebookEntry
                      WHERE Pricebook2Id = :pbId
                      AND Product2Id IN :availIds];

        for(PricebookEntry pbe : pbItems)
        {
          WarrantyAndServiceItem wsItem = new WarrantyAndServiceItem();
          wsItem.OpportunityId = oppId;
          wsItem.PricebookEntryId = pbe.id;
          wsItem.ProductName = pbe.Product2.Name;
          wsItem.UnitPrice = pbe.UnitPrice;
          if( p2Ids.containsKey(pbe.Product2Id) )
          {
            wsItem.isSelected = true;
            wsItem.OpportunityLineItemId = p2Ids.get(pbe.Product2Id);
          }
          availItems.add( wsItem );
        }
      }

    }
    return availItems;

  }

  @RemoteAction
  public static Decimal populateAmount(String priceBookId, String coverage , String oppId, string LineItemId) {

    PricebookEntry objPriceBookEntry = [Select Product2Id from PricebookEntry WHERE id =: priceBookId];

    Decimal amount = 0.0;

    Opportunity objOpp = [SELECT Id,
                                 GL_Account_Variable_3__c,
                                 Calculate_Insurance_Amount__c,
                                 Deposit__c,
                                 Pre_Insurance_Total__c,
                                 TotalTaxes__c,
                                 Finance_Term__c
                            FROM Opportunity
                           WHERE Id =: oppId ];

    for(Insurance_Rate__c objCompanion : [SELECT Id,
                                                 Joint__c,
                                                 Single__c
                                            FROM Insurance_Rate__c
                                           WHERE Product__c =: objPriceBookEntry.Product2Id
                                             AND Lower_Term__c <=: objOpp.Insurance_Term__c
                                             AND Upper_Term__c >=: objOpp.Insurance_Term__c
                                             AND Lower_Finance_Term__c <=: objOpp.Finance_Term__c
                                             AND Upper_Finance_Term__c >=: objOpp.Finance_Term__c
                                             AND Tax_Zone__c =: objOpp.GL_Account_Variable_3__c ])
    {
      if(coverage == 'Joint') {
        amount = (objCompanion.Joint__c * objOpp.Calculate_Insurance_Amount__c ) / 100;
        if(LineItemId != 'new'){
          OpportunityLineItem opl = new OpportunityLineItem();
          opl.Id = LineItemId;
          opl.Insurance_Rate__c  = objCompanion.Joint__c ;
          update opl;
        }
      } else if(coverage == 'Single') {
        amount = (objCompanion.Single__c * objOpp.Calculate_Insurance_Amount__c) / 100;
        if(LineItemId != 'new') {
          OpportunityLineItem opl = new OpportunityLineItem();
          opl.Id = LineItemId;
          opl.Insurance_Rate__c  = objCompanion.Single__c;
          update opl;
        }
      }
    }
    return amount;
  }
}