force-app/main/default/objects/Performance_Tracker__c/Performance_Tracker__c.object-meta.xml
<CustomObject>
    <description>This object is used to track performance data for all boat and motor water tests</description>
    <label>Performance Tracker</label>
    <nameField>
        <displayFormat>PERF - {00000}</displayFormat>
        <label>Performance Test Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Performance Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Performance_Tracker__c/fields/Boat_Type__c.field-meta.xml
<CustomField>
    <fullName>Boat_Type__c</fullName>
    <description>This will hold the boat type for eg &quot;Full Windshield&quot;,&quot;Pontoon&quot;,&quot;Side Console&quot;  and &quot;Utility&quot;</description>
    <inlineHelpText>This will hold the boat type for eg &quot;Full Windshield&quot;,&quot;Pontoon&quot;,&quot;Side Console&quot;  and &quot;Utility&quot;</inlineHelpText>
    <label>Boat Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Performance_Tracker__c/fields/Number_of_People__c.field-meta.xml
<CustomField>
    <fullName>Number_of_People__c</fullName>
    <description>Indicates the number of people in the boat at time of testing</description>
    <inlineHelpText>Indicates the number of people in the boat at time of testing</inlineHelpText>
    <label>Number of People</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
                <default>true</default>
                <label>2</label>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/mobilePerformanceViewerControllerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class mobilePerformanceViewerControllerTest {

    static testMethod void myUnitTest() {
        Performance_Tracker__c obj = new Performance_Tracker__c();
        obj.Boat_Type__c = 'test boat';
        insert obj;
        Apexpages.Standardcontroller controller = new Apexpages.Standardcontroller(obj);
        //Pagereference p = Page.PerformanceViewer_2;
        //Test.setCurrentPageReference(p);
        mobilePerformanceViewerController con = new mobilePerformanceViewerController(controller);
        mobilePerformanceViewerController.performanceTracker perTracker = new mobilePerformanceViewerController.performanceTracker();
        mobilePerformanceViewerController.getBoats('test');
        mobilePerformanceViewerController.getMotors('test');
        mobilePerformanceViewerController.getOptions('Number_of_People__c');
        mobilePerformanceViewerController.getPropellers('test');
        mobilePerformanceViewerController.createPerformance(perTracker);
        mobilePerformanceViewerController.getRecord(obj.Id);
    }
}