force-app/main/default/objects/AcctSeedERP__Inventory_Balance__c/AcctSeedERP__Inventory_Balance__c.object-meta.xml
<CustomObject>
    <label>Inventory Balance</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Inventory Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Balances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Inventory_Balance__c/fields/AcctSeedERP__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Inventory Balance</relationshipLabel>
    <relationshipName>Inventory_Balance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Inventory_Balance__c/fields/AcctSeedERP__Warehouse__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Inventory Quantity Available</relationshipLabel>
    <relationshipName>Inventory_Balance</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Warehouse__c/AcctSeedERP__Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GMBLASERP__Lot__c/GMBLASERP__Lot__c.object-meta.xml
<CustomObject>
    <label>Lot</label>
    <nameField>
        <label>Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/GMBLASERP__Lot__c/fields/GMBLASERP__Product__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lots</relationshipLabel>
    <relationshipName>Lots</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/GMBLASERP__Serial_Number__c.object-meta.xml
<CustomObject>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/GMBLASERP__Serial_Number__c/fields/GMBLASERP__Inventory_Balance__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Inventory_Balance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inventory Balance</label>
    <referenceTo>AcctSeedERP__Inventory_Balance__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/fields/GMBLASERP__Lot__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Lot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lot</label>
    <referenceTo>GMBLASERP__Lot__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/fields/GMBLASERP__Product__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GMBLASERP__Serial_Number__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>BLANKVALUE( GMBLASERP__Inventory_Balance__r.AcctSeedERP__Warehouse__r.Name , &#39;OUT&#39;)</formula>
    <label>Location</label>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/fields/Nest__c.field-meta.xml
<CustomField>
    <fullName>Nest__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nest</label>
    <referenceTo>GMBLASERP__Serial_Number__c</referenceTo>
    <relationshipLabel>Nested Serial Numbers</relationshipLabel>
    <relationshipName>Nested_Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GMBLASERP__Serial_Number__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>GMBLASERP__Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GMBLASERP__Serial_Number__c/fields/Product_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Record_Type__c</fullName>
    <formula>GMBLASERP__Product__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Record Type</label>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of serialized inventory items that indicate whether it is a display model, to be repaired, return to supplier, or specials list if we are selling as is.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>At Supplier</fullName>
            </value>
            <value>
                <fullName>Available for Sale</fullName>
            </value>
            <value>
                <fullName>Boatopia</fullName>
            </value>
            <value>
                <fullName>Boat Show</fullName>
            </value>
            <value>
                <fullName>Consignment</fullName>
                <isActive>false</isActive>
                <label>Consignment</label>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>Display Model</fullName>
            </value>
            <value>
                <fullName>In Showroom</fullName>
                <isActive>false</isActive>
                <label>In Showroom</label>
            </value>
            <value>
                <fullName>Reserved for Retail</fullName>
                <isActive>false</isActive>
                <label>Reserved for Retail</label>
            </value>
            <value>
                <fullName>Return to Supplier</fullName>
            </value>
            <value>
                <fullName>Specials List</fullName>
            </value>
            <value>
                <fullName>Stolen</fullName>
            </value>
            <value>
                <fullName>To Be Repaired</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Product2/fields/Can_be_Nest__c.field-meta.xml
<CustomField>
    <fullName>Can_be_Nest__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Serial Numbers of this Product can be the Nest for Serial Numbers of another product.</inlineHelpText>
    <label>Can be Nest</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/Product2/fields/Can_be_Nested__c.field-meta.xml
<CustomField>
    <fullName>Can_be_Nested__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Serial Numbers of this Product can be nested to Serial Numbers of other products.</inlineHelpText>
    <label>Can be Nested</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/Product2/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

src/Base/main/default/objects/Product2/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Field used to determine status of a part</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending_Approval</fullName>
                <default>true</default>
                <label>Pending Approval</label>
            </value>
            <value>
                <fullName>Approved for Use</fullName>
            </value>
            <value>
                <fullName>Do_Not_Use</fullName>
                <label>Do Not Use</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Registration__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registered To Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/ErpOrder__c.field-meta.xml
<CustomField>
    <fullName>ErpOrder__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>ErpOrder</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Registration__c/fields/isCurrent__c.field-meta.xml
<CustomField>
    <fullName>isCurrent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Current</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/Registration__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>SerialNumber__r.Product_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/ProductMake__c.field-meta.xml
<CustomField>
    <fullName>ProductMake__c</fullName>
    <formula>SerialNumber__r.GMBLASERP__Product__r.Make__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ProductMake</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/SerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SerialNumber__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Serial Number</label>
    <referenceTo>GMBLASERP__Serial_Number__c</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/lgnd_inventory.cls
public with sharing class lgnd_inventory {

	/* ------------
		 	Wrappers
	------------ */

	public List<wrapProduct> wrapProductList {get; set;}
	public List<Registration__c> selectedRegistrations {get; set;}

	public class wrapProduct implements Comparable {
    public Registration__c reg {get; set;}
    public String orderField {get; set;}
    public String orderDir {get; set;}
    public Integer pageCount {get; set;}
    public Integer recordCount {get; set;}
    public List<wrapProduct> nestedItems {get; set;}

    public wrapProduct(Registration__c r, String o, String d, List<wrapProduct> n) {
    	reg = r;
    	orderField = o;
    	orderDir = d;
    	nestedItems = n;
    }

    public Integer compareTo(Object compareTo) {
    	wrapProduct wrapProduct = (wrapProduct)compareTo;
    	Integer returnValue = 0;

    	if (orderField == 'SerialNumber__c') {
    		if (reg.SerialNumber__r.Name > wrapProduct.reg.SerialNumber__r.Name) {
	    		returnValue = (orderDir == 'ASC') ? 1 : -1 ;
	    	} else if (reg.SerialNumber__r.Name < wrapProduct.reg.SerialNumber__r.Name) {
	    		returnValue = (orderDir == 'ASC') ? -1 : 1 ;
	    	}
    	}

    	if (orderField == 'Product_Record_Type__c') {
    		if (reg.SerialNumber__r.Product_Record_Type__c > wrapProduct.reg.SerialNumber__r.Product_Record_Type__c) {
	    		returnValue = (orderDir == 'ASC') ? 1 : -1 ;
	    	} else if (reg.SerialNumber__r.Product_Record_Type__c < wrapProduct.reg.SerialNumber__r.Product_Record_Type__c) {
	    		returnValue = (orderDir == 'ASC') ? -1 : 1 ;
	    	}
    	}

    	if (orderField == 'Product_Name__c') {
    		if (reg.SerialNumber__r.Product_Name__c > wrapProduct.reg.SerialNumber__r.Product_Name__c) {
	    		returnValue = (orderDir == 'ASC') ? 1 : -1 ;
	    	} else if (reg.SerialNumber__r.Product_Name__c < wrapProduct.reg.SerialNumber__r.Product_Name__c) {
	    		returnValue = (orderDir == 'ASC') ? -1 : 1 ;
	    	}
    	}

    	if (orderField == 'Location__c') {
    		if (reg.SerialNumber__r.Location__c > wrapProduct.reg.SerialNumber__r.Location__c) {
	    		returnValue = (orderDir == 'ASC') ? 1 : -1 ;
	    	} else if (reg.SerialNumber__r.Location__c < wrapProduct.reg.SerialNumber__r.Location__c) {
	    		returnValue = (orderDir == 'ASC') ? -1 : 1 ;
	    	}
    	}

    	return returnValue;
    }
  }

	/* -----------------
			Registrations
	----------------- */

	@AuraEnabled
	public static String getDetailedRegistrations(String orderField,
                                                String orderDir,
                                                Integer perPage,
                                                Integer pageNum,
                                                String filter,
                                                String sernoFilter) {

		List<wrapProduct> Nests = new List<wrapProduct>();
		List<wrapProduct> AllProducts = new List<wrapProduct>();

    Id accountId;

    Integer startingPoint = (Integer.valueOf(pageNum) - 1) * (Integer.valueOf(perPage));
		Integer endingPoint = startingPoint + (Integer.valueOf(perPage));

    try {
      accountId = [SELECT AccountId FROM User WHERE Id = :Userinfo.getUserId()].AccountId;
    }
    catch( Exception e ){
    	System.debug(e);
    }

    if (sernoFilter == null) {
    	sernoFilter = '%';
  	} else {
    	sernoFilter = '%' + sernoFilter + '%';
    }

    System.debug(sernoFilter);

		for (Registration__c reg : [SELECT Account__r.Name, 
																			 Account__r.Id, 
																			 Account__r.Type,
																			 ErpOrder__c,
																			 Id,
																			 isCurrent__c,
																			 Name,
																			 ProductMake__c,
																			 CreatedDate,
																			 SerialNumber__r.Id,
																			 SerialNumber__r.Name,
																			 SerialNumber__r.Product_Name__c,
																			 SerialNumber__r.Description__c,
																			 SerialNumber__r.Status__c,
																			 SerialNumber__r.GMBLASERP__Lot__c,
																			 SerialNumber__r.GMBLASERP__Lot__r.Name,
																			 SerialNumber__r.Product_Record_Type__c,
																			 SerialNumber__r.Location__c,
																			 SerialNumber__r.OwnerId,
																			 SerialNumber__r.GMBLASERP__Product__c,
																			 SerialNumber__r.GMBLASERP__Product__r.Name,
																			 SerialNumber__r.GMBLASERP__Product__r.Can_be_Nest__c,
																			 SerialNumber__r.GMBLASERP__Product__r.Can_be_Nested__c,
																			 SerialNumber__r.GMBLASERP__Product__r.Id,
																			 SerialNumber__r.Nest__c,
																			 SerialNumber__r.GMBLASERP__Inventory_Balance__r.AcctSeedERP__Warehouse__r.Name
																FROM Registration__c
																WHERE Account__c = :accountId
																And isCurrent__c = true
																And (SerialNumber__r.Name LIKE :sernoFilter OR SerialNumber__r.Product_Name__c LIKE :sernoFilter) 
																]) {

			String serno = String.valueOf(reg.get('SerialNumber__c'));

			List<wrapProduct> nestedItems;

			if (filter == 'All' || filter == reg.SerialNumber__r.Product_Record_Type__c) {
				AllProducts.add(new wrapProduct(reg, orderField, orderDir, nestedItems));
				if (reg.SerialNumber__r.Nest__c == null) {
					Nests.add(new wrapProduct(reg, orderField, orderDir, nestedItems));
				}
			}
		}

		Nests.sort();
		AllProducts.sort();

		// Nesting
		for (wrapProduct nest : Nests) {
			nest.nestedItems = new List<wrapProduct>();
			for (wrapProduct item : AllProducts) {
				if (nest.reg.SerialNumber__r.Id == item.reg.SerialNumber__r.Nest__c) {
					nest.nestedItems.add(item);
				}
			}
		}

		if (Nests.size() < Integer.valueOf(endingPoint)) {
			endingPoint = Integer.valueOf(Nests.size());
		}

		List<wrapProduct> ProductListSubset = new List<wrapProduct>();

		for (Integer i = startingPoint; i < endingPoint; i++) {
			ProductListSubset.add(Nests[i]);
		}

		Integer aa = Integer.valueOf( Nests.size() );
    Integer bb = Integer.valueOf( perPage );
    Integer pageCount = aa / bb;
    if( Math.mod( aa, bb) > 0 )
      pageCount++;

		ProductListSubset[0].pageCount = pageCount;

		ProductListSubset[0].recordCount = Nests.size();

		return JSON.serialize(ProductListSubset);
	}

	@AuraEnabled
  public static String getAccountRegistrations (String recordId) {
    List<wrapProduct> ProductList = new List<wrapProduct>();

    List<wrapProduct> nestedItems;

		for (Registration__c reg : [SELECT 	Account__c,
																				ErpOrder__c,
																				Id,
																				isCurrent__c,
																				Name,
																				ProductMake__c,
																				SerialNumber__c,
																				SerialNumber__r.Id,
																				SerialNumber__r.Name,
																				SerialNumber__r.Product_Name__c,
																				SerialNumber__r.Description__c,
																				SerialNumber__r.Status__c,
																				SerialNumber__r.GMBLASERP__Lot__c,
																				SerialNumber__r.GMBLASERP__Lot__r.Name,
																				SerialNumber__r.Product_Record_Type__c,
																				SerialNumber__r.Location__c,
																				SerialNumber__r.OwnerId,
																				SerialNumber__r.GMBLASERP__Product__c,
																				SerialNumber__r.Nest__c,
																				CreatedDate
																FROM Registration__c
																WHERE Account__c = :recordId And isCurrent__c = true]) {

			String serno = String.valueOf(reg.get('SerialNumber__c'));

			ProductList.add(new wrapProduct(reg, 'SerialNumber__c', 'ASC', nestedItems));
		}

		return JSON.serialize(ProductList);
  }

	/* -----------------
			User Info
	----------------- */

	@AuraEnabled
	public static String getUserId() {
		return userinfo.getUserId();
	}

}