force-app/main/default/objects/AcctSeedERP__Inventory_Balance__c/AcctSeedERP__Inventory_Balance__c.object-meta.xml
<CustomObject>
    <label>Inventory Balance</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Inventory Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Balances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Inventory_Balance__c/fields/AcctSeedERP__Ledger__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Ledger__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ledger</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Ledger__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Transactional</value>
        </filterItems>
        <infoMessage>Only Transactional Ledgers are allowed.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Ledger__c</referenceTo>
    <relationshipLabel>Inventory Quantity Available</relationshipLabel>
    <relationshipName>Inventory_Quantity_Available</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Purchase_Order_Inventory_Movement__c/AcctSeedERP__Purchase_Order_Inventory_Movement__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Inventory Movement</label>
    <nameField>
        <displayFormat>PIM-{00000}</displayFormat>
        <label>Purchasing Inventory Movement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Inventory Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Inventory_Movement__c/fields/AcctSeedERP__Inventory_Balance__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Inventory_Balance__c</fullName>
    <label>Inventory Quantity Available</label>
    <referenceTo>AcctSeedERP__Inventory_Balance__c</referenceTo>
    <relationshipLabel>Purchase Order Inventory Movements</relationshipLabel>
    <relationshipName>Purchase_Order_Inventory_Movements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Inventory_Movement__c/fields/AcctSeedERP__Ledger__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Ledger__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ledger</label>
    <referenceTo>AcctSeed__Ledger__c</referenceTo>
    <relationshipLabel>Purchase Order Inventory Movements</relationshipLabel>
    <relationshipName>Purchase_Order_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Inventory_Movement__c/fields/AcctSeedERP__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Purchase Order Inventory Movements</relationshipLabel>
    <relationshipName>Purchase_Order_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Inventory_Movement__c/fields/AcctSeedERP__Project_Task__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Project_Task__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AcctSeedERP__Project__c</field>
            <operation>equals</operation>
            <valueField>AcctSeed__Project_Task__c.AcctSeed__Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Project_Task__c</referenceTo>
    <relationshipLabel>Purchase Order Inventory Movements</relationshipLabel>
    <relationshipName>Purchase_Order_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Inventory_Movement__c/fields/AcctSeedERP__Purchase_Order_Line__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Purchase_Order_Line__c</fullName>
    <label>Purchase Order Line</label>
    <referenceTo>AcctSeedERP__Purchase_Order_Line__c</referenceTo>
    <relationshipLabel>Purchase Order Inventory Movements</relationshipLabel>
    <relationshipName>Purchase_Order_Inventory_Movements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Line__c/AcctSeedERP__Purchase_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Line</label>
    <nameField>
        <displayFormat>POL-{00000}</displayFormat>
        <label>Purchase Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Line__c/fields/AcctSeedERP__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Purchase_Order_Line__c/fields/AcctSeedERP__Project_Task__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Project_Task__c.AcctSeed__Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.AcctSeedERP__Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Project_Task__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/classes/Factory_PurchaseOrderInventoryMovement.cls
/**
 * Created by dave on 2021-07-26.
 */
@IsTest
public class Factory_PurchaseOrderInventoryMovement
{

  public static AcctSeedERP__Purchase_Order_Inventory_Movement__c createMovement(
    Id purchaseOrderLineId,
    Decimal quantity,
    Id erpId,
    Id erpTaskId,
    Id balanceId,
    Decimal unitCost
  )
  {

    AcctSeedERP__Purchase_Order_Inventory_Movement__c movement = new AcctSeedERP__Purchase_Order_Inventory_Movement__c(
      AcctSeedERP__Purchase_Order_Line__c = purchaseOrderLineId,
      AcctSeedERP__Ledger__c = Test_Constants.idLedger,
      AcctSeedERP__Quantity__c = quantity,
      AcctSeedERP__Project_Task__c = erpTaskId,
      AcctSeedERP__Project__c = erpId,
      AcctSeedERP__Unit_Cost__c = unitCost,
      AcctSeedERP__Movement_Date__c = Date.today(),
      AcctSeedERP__Inventory_Balance__c = balanceId
    );
    GMBLASERP.gcPurchaseOrderInventoryMovement.disableTrigger = true;
    gcPurchaseOrderInventoryMovement.disableTrigger = true;
    insert movement;
    return movement;
  }
}