force-app/main/default/objects/AcctSeedERP__Inventory_Balance__c/AcctSeedERP__Inventory_Balance__c.object-meta.xml
<CustomObject>
    <label>Inventory Balance</label>
    <nameField>
        <displayFormat>INV-{00000}</displayFormat>
        <label>Inventory Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Balances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Manufacturing_Inventory_Movement__c/AcctSeedERP__Manufacturing_Inventory_Movement__c.object-meta.xml
<CustomObject>
    <label>Manufacturing Inventory Movement</label>
    <nameField>
        <displayFormat>MIM-{00000}</displayFormat>
        <label>Manufacturing Inventory Movement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manufacturing Inventory Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeedERP__Manufacturing_Inventory_Movement__c/fields/AcctSeedERP__Inventory_Balance__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Inventory_Balance__c</fullName>
    <label>Inventory Quantity Available</label>
    <referenceTo>AcctSeedERP__Inventory_Balance__c</referenceTo>
    <relationshipLabel>Manufacturing Inventory Movements</relationshipLabel>
    <relationshipName>Manufacturing_Inventory_Movements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Manufacturing_Inventory_Movement__c/fields/AcctSeedERP__ProductId__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__ProductId__c</fullName>
    <formula>AcctSeedERP__Inventory_Balance__r.AcctSeedERP__Product__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ProductId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Manufacturing_Inventory_Movement__c/fields/AcctSeedERP__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Status__c</fullName>
    <label>Posting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
                <default>true</default>
                <label>Approved</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Manufacturing_Inventory_Movement__c/fields/GMBLASERP__Product__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Manufacturing Inventory Movements</relationshipLabel>
    <relationshipName>Manufacturing_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Outbound_Inventory_Movement__c/AcctSeedERP__Outbound_Inventory_Movement__c.object-meta.xml
<CustomObject>
    <label>Outbound Inventory Movement</label>
    <nameField>
        <displayFormat>OIM-{00000}</displayFormat>
        <label>Outbound Inventory Movement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outbound Inventory Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Outbound_Inventory_Movement__c/fields/AcctSeedERP__Inventory_Balance__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Inventory_Balance__c</fullName>
    <label>Inventory Balance</label>
    <referenceTo>AcctSeedERP__Inventory_Balance__c</referenceTo>
    <relationshipName>Outbound_Inventory_Movements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Outbound_Inventory_Movement__c/fields/GMBLASERP__Product__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Outbound Inventory Movements</relationshipLabel>
    <relationshipName>Outbound_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

src/FieldService/classes/AcctSeedMovementWrapper_FSL.cls
/**
 * Created by aminrubel on 2019-08-23.
 */

public with sharing class AcctSeedMovementWrapper_FSL {

    public SObject obj{get;set;}
    public String objId{get;set;}
    public String idBalance{get;set;}
    public String idProduct{get;set;}
    public String moveStatus{get;set;}
    public Decimal qtyNew{get;set;}

    public AcctSeedMovementWrapper_FSL(SObject pObj, Boolean isNegative)
    {
        this.obj = pObj;
        this.objId = (String) pObj.get('Id');
        this.moveStatus = (String) pObj.get('AcctSeedERP__Status__c');
        this.idBalance = (String) pObj.get('AcctSeedERP__Inventory_Balance__c');
        this.idProduct = (String) pObj.get('GMBLASERP__Product__c');
        if(this.idProduct == null)
            this.idProduct = (String) pObj.get('AcctSeedERP__ProductId__c');
        Decimal newQty = (Decimal) pObj.get('AcctSeedERP__Quantity__c');
        if(isNegative) newQty = newQty * -1;
        this.qtyNew = newQty;
    }

    public static List<AcctSeedMovementWrapper_FSL> generateMovementWrapperVoid(List<SObject> listMovements) {
        Boolean negativeMove = false;
        if (listMovements.getSObjectType() == AcctSeedERP__Manufacturing_Inventory_Movement__c.SObjectType)
            negativeMove = true;
        else if (listMovements.getSObjectType() == AcctSeedERP__Outbound_Inventory_Movement__c.SObjectType)
            negativeMove = true;

        if(Trigger.isExecuting && Trigger.isDelete)
            negativeMove = true;
        List<AcctSeedMovementWrapper_FSL> listWrapMoves = new List<AcctSeedMovementWrapper_FSL>();
        for (SObject obj : listMovements) {
            AcctSeedMovementWrapper_FSL wm = new AcctSeedMovementWrapper_FSL(obj, negativeMove);
            listWrapMoves.add(wm);
        }

        return listWrapMoves;
    }
}