force-app/main/default/objects/Dealer_Order__c/Dealer_Order__c.object-meta.xml
<CustomObject>
    <label>Dealer Order</label>
    <nameField>
        <displayFormat>DealerOrder-{0000}</displayFormat>
        <label>Dealer Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Dealer_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account not found or not a Dealer Account</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Orders</relationshipLabel>
    <relationshipName>Dealer_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Booking_Order__c/Partner_Booking_Order__c.object-meta.xml
<CustomObject>
    <label>Partner Booking Order</label>
    <nameField>
        <label>Program Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Booking Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/Partner_Booking_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The partner account placing this booking order</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Booking Orders</relationshipLabel>
    <relationshipName>Partner_Booking_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Booking_Order__c/fields/Dealer_Order__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Order__c</fullName>
    <label>Dealer Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Dealer Order Account must be the same as the Booking Order Account</errorMessage>
        <filterItems>
            <field>Dealer_Order__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Dealer_Order__c.Is_Booking_Order__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dealer_Order__c</referenceTo>
    <relationshipLabel>Partner Booking Orders</relationshipLabel>
    <relationshipName>Partner_Booking_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Booking_Order__c/fields/Pontoon_Volume_Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Pontoon_Volume_Discount_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Pontoon Volume Discount Percent</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Partner_Booking_Order__c/fields/Uniquifier__c.field-meta.xml
<CustomField>
    <fullName>Uniquifier__c</fullName>
    <label>Uniquifier</label>
    <length>23</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Partner_Booking_Order__c/fields/V_Hull_Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>V_Hull_Discount_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>V Hull Discount Percent</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/Base/main/default/classes/Selectors/PartnerBookingOrder_Selector.cls
/**
 * Created by dave on 2021-05-07.
 */

public virtual class PartnerBookingOrder_Selector extends Application_Selector
{


  private final List<String> defaultFields = new List<String>
  {
    'Id',
    'Name',
    'Dealer_Order__c',
    'Account__c',
    'V_Hull_Discount_Percent__c',
    'Pontoon_Volume_Discount_Percent__c',
    'Uniquifier__c'
  };

  public PartnerBookingOrder_Selector()
  {
    this.sObjectName = 'Partner_Booking_Order__c';
    this.fields = defaultFields;
  }

  public static Partner_Booking_Order__c getUnique( String uniquifier )
  {
    List<SObject> results = new PartnerBookingOrder_Selector()
      .addWhere( 'Uniquifier__c = \'' + uniquifier + '\'')
      .query();
    return (Partner_Booking_Order__c)results[0];
  }
}