force-app/main/default/objects/Dealer_Order__c/Dealer_Order__c.object-meta.xml
<CustomObject>
    <label>Dealer Order</label>
    <nameField>
        <displayFormat>DealerOrder-{0000}</displayFormat>
        <label>Dealer Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Dealer_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account not found or not a Dealer Account</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Orders</relationshipLabel>
    <relationshipName>Dealer_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Dealer_Order__c/fields/Is_Booking_Order__c.field-meta.xml
<CustomField>
    <fullName>Is_Booking_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Booking Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dealer_Order__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dealer_Order__c/fields/Program_Year__c.field-meta.xml
<CustomField>
    <fullName>Program_Year__c</fullName>
    <label>Program Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dealer_Order__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending Financing</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Filled</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
                <isActive>false</isActive>
                <label>Processed</label>
            </value>
            <value>
                <fullName>Reviewed</fullName>
                <isActive>false</isActive>
                <label>Reviewed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Automation/main/default/classes/DealerOrderLine/Tests/TA_DealerOrderLine_HandlePartnerPro_T.cls
@isTest
public class TA_DealerOrderLine_HandlePartnerPro_T {
    @testSetup static void dataSetup(){
        TA_DealerOrderLine_TestHelper.dataSetup();
    }
    @isTest
    static void handlePartnerProgram_afterInsert_Test(){

        TA_DealerOrderLine_TestHelper.init();
        TA_DealerOrderLine_TestHelper.buildBoat('Pontoon', 50000, null);
        TA_DealerOrderLine_TestHelper.buildDealerOrder(true, 'Draft');
        TA_DealerOrderLine_TestHelper.order = [Select id,Account__c,Payment_Method__c,Program_Year__c,Is_Booking_Order__c,Stage__c from Dealer_Order__c where id= :TA_DealerOrderLine_TestHelper.order.id ];
        TA_DealerOrderLine_TestHelper.createDealerOrderLines(TA_DealerOrderLine_TestHelper.order,2);
        new TA_DealerOrderLine_HandlePartnerPro().afterInsert(TA_DealerOrderLine_TestHelper.dealerOrderLines);
    }

    @isTest
    static void handlePartnerProgram_afterDelete_Test(){

        TA_DealerOrderLine_TestHelper.init();
        TA_DealerOrderLine_TestHelper.buildBoat('Pontoon', 50000, null);
        TA_DealerOrderLine_TestHelper.buildDealerOrder(true, 'Draft');
        TA_DealerOrderLine_TestHelper.order = [Select id,Account__c,Payment_Method__c,Program_Year__c,Is_Booking_Order__c,Stage__c from Dealer_Order__c where id= :TA_DealerOrderLine_TestHelper.order.id ];
        TA_DealerOrderLine_TestHelper.createDealerOrderLines(TA_DealerOrderLine_TestHelper.order,2);
        new TA_DealerOrderLine_HandlePartnerPro().afterDelete(TA_DealerOrderLine_TestHelper.dealerOrderLines);
    }
    @isTest
    static void handlePartnerProgram_afterUpdate_Test(){

        TA_DealerOrderLine_TestHelper.init();
        TA_DealerOrderLine_TestHelper.buildBoat('Pontoon', 50000, null);
        TA_DealerOrderLine_TestHelper.buildDealerOrder(true, 'Draft');
        TA_DealerOrderLine_TestHelper.order = [Select id,Account__c,Payment_Method__c,Program_Year__c,Is_Booking_Order__c,Stage__c from Dealer_Order__c where id= :TA_DealerOrderLine_TestHelper.order.id ];
        TA_DealerOrderLine_TestHelper.createDealerOrderLines(TA_DealerOrderLine_TestHelper.order,2);
        new TA_DealerOrderLine_HandlePartnerPro().afterUpdate(TA_DealerOrderLine_TestHelper.dealerOrderLines,TA_DealerOrderLine_TestHelper.dealerOrderLines);
    }
}