force-app/main/default/objects/GMBLASERP__Lot__c/GMBLASERP__Lot__c.object-meta.xml
<CustomObject>
    <label>Lot</label>
    <nameField>
        <label>Lot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/GMBLASERP__Lot__c/fields/GMBLASERP__Product__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Lots</relationshipLabel>
    <relationshipName>Lots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lot_Exchange__c/Lot_Exchange__c.object-meta.xml
<CustomObject>
    <label>Lot Exchange</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Lot Exchange Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lots Exchange</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Lot_Exchange__c/fields/Exchange_Date__c.field-meta.xml
<CustomField>
    <fullName>Exchange_Date__c</fullName>
    <label>Exchange Date</label>
    <type>Date</type>
</CustomField>

src/Base/main/default/objects/Lot_Exchange__c/fields/Exchange_Type__c.field-meta.xml
<CustomField>
    <fullName>Exchange_Type__c</fullName>
    <label>Exchange Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lot</fullName>
                <default>true</default>
                <label>Lot</label>
            </value>
            <value>
                <fullName>Product</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Lot_Exchange__c/fields/Lot_From__c.field-meta.xml
<CustomField>
    <fullName>Lot_From__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lot From</label>
    <referenceTo>GMBLASERP__Lot__c</referenceTo>
    <relationshipLabel>Lots Exchange (From)</relationshipLabel>
    <relationshipName>Lots_Exchange</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Lot_Exchange__c/fields/Lot_To__c.field-meta.xml
<CustomField>
    <fullName>Lot_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lot To</label>
    <referenceTo>GMBLASERP__Lot__c</referenceTo>
    <relationshipLabel>Lots Exchange (To)</relationshipLabel>
    <relationshipName>Lots_Exchange_To</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/classes/gcLotExchange.cls
public without sharing class gcLotExchange {
  public static Boolean disableTrigger {
    get {
      if (disableTrigger == null)
        return false;
      else
        return disableTrigger;
    }
    set {
      if (value == null)
        disableTrigger = false;
      else
        disableTrigger = value;
    }
  }

  public static void triggerHandler(
    map<Id, Lot_Exchange__c> oldMap,
    map<Id, Lot_Exchange__c> newMap,
    list<Lot_Exchange__c> listNew,
    Boolean boolIsBefore,
    Boolean boolIsInsert,
    Boolean boolIsUpdate,
    Boolean boolIsDelete
  ) {
    if (oldMap == null)
      oldMap = new Map<Id, Lot_Exchange__c>();
    if (newMap == null)
      newMap = new Map<Id, Lot_Exchange__c>();
    if (listNew == null)
      listNew = new List<Lot_Exchange__c>();

    updateAndValidate(oldMap, newMap, listNew, boolIsBefore, boolIsInsert, boolIsUpdate, boolIsDelete);

    if (boolIsBefore) {
      if (boolIsInsert) {
      }
      if (boolIsUpdate) {
      }
      if (boolIsDelete) {
      }
    } else //i.e. trigger.isAfter
    {
      if (boolIsInsert) {
      }
      if (boolIsUpdate) {
      }
      if (boolIsDelete) {
      }
    }
  }

  private static void updateAndValidate(
    map<Id, Lot_Exchange__c> oldMap,
    map<Id, Lot_Exchange__c> newMap,
    list<Lot_Exchange__c> listNew,
    Boolean boolIsBefore,
    Boolean boolIsInsert,
    Boolean boolIsUpdate,
    Boolean boolIsDelete
  ) {
    if (boolIsBefore && (boolIsInsert || boolIsUpdate)) {
      refreshStatics(listNew);
      for (Lot_Exchange__c tl : listNew) {
        Lot_Exchange__c oldRec = oldMap.get(tl.Id);
        if (tl.Lot_From__c == null)
          tl.Lot_From__c.addError('You must specify a Lot to transfer from.');
        else if (tl.Lot_To__c == null)
          tl.Lot_To__c.addError('You must specify a Lot to transfer to.');
        else if (tl.Lot_From__c == tl.Lot_To__c)
          tl.Lot_To__c.addError('You must specify a different Lot to transfer to.');
        //else if(mapLot.get(tl.Lot_From__c).GMBLASERP__Product__c != mapLot.get(tl.Lot_To__c).GMBLASERP__Product__c && tl.Exchange_Type__c == 'Lot')
        //	tl.addError('The lot From and Lot to must be from the same product for Exchange Type Lot.');
        //else if(mapLot.get(tl.Lot_From__c).GMBLASERP__Product__c == mapLot.get(tl.Lot_To__c).GMBLASERP__Product__c && tl.Exchange_Type__c == 'Product')
        //	tl.addError('The lot From and Lot to must be from different products for Exchange Type Product.');
        if (boolIsInsert && tl.Exchange_Date__c == null)
          tl.Exchange_Date__c = Date.today();
        if (boolIsUpdate && tl.Exchange_Date__c == null)
          tl.Exchange_Date__c = oldRec.Exchange_Date__c;
      }
    }
  }

  private static map<Id, GMBLASERP__Lot__c> mapLot;

  private static void refreshStatics(list<Lot_Exchange__c> listNew) {
    if (mapLot == null) {
      mapLot = new Map<Id, GMBLASERP__Lot__c>();
    }
    Set<Id> setIdLot = new Set<Id>();
    for (Lot_Exchange__c tl : listNew) {
      if (tl.Lot_From__c != null && !mapLot.containsKey(tl.Lot_From__c))
        setIdLot.add(tl.Lot_From__c);
      if (tl.Lot_To__c != null && !mapLot.containsKey(tl.Lot_To__c))
        setIdLot.add(tl.Lot_To__c);
    }
    setIdLot.remove(null);

    if (!setIdLot.isEmpty())
      for (GMBLASERP__Lot__c lot : [SELECT Id, GMBLASERP__Product__c FROM GMBLASERP__Lot__c WHERE Id IN :setIdLot]) {
        mapLot.put(lot.Id, lot);
      }
  }

  public static void coverage() {
    integer i;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
  }
}