src/Base/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project_Task__c/AcctSeed__Project_Task__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <inlineHelpText>Related Parent object.</inlineHelpText>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Dealer_Motor_Request__c/Dealer_Motor_Request__c.object-meta.xml
<CustomObject>
    <label>Dealer Motor Request</label>
    <nameField>
        <displayFormat>DMR-{0000}</displayFormat>
        <label>Dealer Motor Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Motor Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_Order__c/Dealer_Order__c.object-meta.xml
<CustomObject>
    <label>Dealer Order</label>
    <nameField>
        <displayFormat>DealerOrder-{0000}</displayFormat>
        <label>Dealer Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Dealer_Order__c/fields/Is_Booking_Order__c.field-meta.xml
<CustomField>
    <fullName>Is_Booking_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Booking Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dealer_Order_Line__c/Dealer_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Dealer Order Line</label>
    <nameField>
        <displayFormat>DOL-{0000}</displayFormat>
        <label>Dealer Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/Dealer_Order_Line__c/fields/Dealer_Motor_Request__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Motor_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer Motor Request</label>
    <referenceTo>Dealer_Motor_Request__c</referenceTo>
    <relationshipLabel>Dealer Order Lines</relationshipLabel>
    <relationshipName>Dealer_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Dealer_Order_Line__c/fields/Dealer_Order__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Order__c</fullName>
    <label>Dealer Order</label>
    <referenceTo>Dealer_Order__c</referenceTo>
    <relationshipLabel>Dealer Order Lines</relationshipLabel>
    <relationshipName>Dealer_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/objects/Dealer_Order_Line__c/fields/ERP_Order__c.field-meta.xml
<CustomField>
    <fullName>ERP_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ERP Order</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Dealer Order Lines</relationshipLabel>
    <relationshipName>Dealer_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Dealer_Order_Line__c/fields/Is_For_Factory_Store__c.field-meta.xml
<CustomField>
    <fullName>Is_For_Factory_Store__c</fullName>
    <formula>Dealer_Order__r.Account__r.Is_Internal__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is For Factory Store</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/Dealer_Order_Line__c/fields/Legend_Transfer_Request__c.field-meta.xml
<CustomField>
    <fullName>Legend_Transfer_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legend Transfer Request</label>
    <referenceTo>Legend_Transfer_Request__c</referenceTo>
    <relationshipLabel>Dealer Order Lines</relationshipLabel>
    <relationshipName>Dealer_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer_Order_Line__c/fields/Line_Total_No_Fees_or_Discounts__c.field-meta.xml
<CustomField>
    <fullName>Line_Total_No_Fees_or_Discounts__c</fullName>
    <label>Line Total No Fees or Discounts</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Dealer_Order_Line__c/fields/Line_Total_NoFeesOrDiscountsCalc__c.field-meta.xml
<CustomField>
    <fullName>Line_Total_NoFeesOrDiscountsCalc__c</fullName>
    <formula>ERP_Order__r.Order_Item_Total_NO_Fees_Or_Discounts__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line Total No Fees or Discounts Calc</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Dealer_Order_Line__c/fields/Line_Total_Pre_Tax__c.field-meta.xml
<CustomField>
    <fullName>Line_Total_Pre_Tax__c</fullName>
    <formula>ERP_Order__r.Order_Item_Total__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Line Total Pre Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Legend_Transfer_Request__c/Legend_Transfer_Request__c.object-meta.xml
<CustomObject>
    <description>Used for Transferring Serialized Inventory to Another Legend Location</description>
    <label>Legend Transfer Request</label>
    <nameField>
        <displayFormat>LTR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Legend Transfer Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/classes/Services/DealerOrderLine_Service.cls
/**
 * Created by dhavalmacbook on 20/01/22.
 */

public inherited sharing class DealerOrderLine_Service {
  public static void setLineTotal(List<Dealer_Order_Line__c> lines) {
    System.debug('DealerOrderLine_Service.setLineTotal');
    for (Dealer_Order_Line__c dol : lines) {
      dol.Line_Total__c = dol.Line_Total_Pre_Tax__c;
      dol.Line_Total_No_Fees_or_Discounts__c = dol.Line_Total_NoFeesOrDiscountsCalc__c;
    }
  }

  public static void handlePartnerProgram(List<Dealer_Order_Line__c> listNew) {
    Set<Id> dealerOrderIds = new Set<Id>();
    for (Dealer_Order_Line__c dol : listNew) {
      if (dol.ERP_Order__c != null && !dol.Is_For_Factory_Store__c) {
        dealerOrderIds.add(dol.Dealer_Order__c);
      }
    }
    applyPartnerProgram(dealerOrderIds);
  }

  @Future
  public static void applyPartnerProgram(Set<Id> dealerOrderIds) {
    Map<Id, Dealer_Order__c> dealerOrders = new Map<Id, Dealer_Order__c>(
      [SELECT Id FROM Dealer_Order__c WHERE Id IN :dealerOrderIds AND Is_Booking_Order__c = TRUE]
    );
    PartnerProgram_Service ppService = new PartnerProgram_Service(dealerOrders.keySet());
    ppService.checkAndApply();
  }

  public static void deleteErps(Set<Id> erpIds) {
    delete [SELECT Id FROM AcctSeed__Project_Task__c WHERE AcctSeed__Project__c IN :erpIds];
    delete [SELECT Id FROM AcctSeed__Project__c WHERE Id IN :erpIds];
  }

  public static void deleteLegendTransferRequests(Set<Id> transferIds) {
    Legend_Transfer_Request__c[] ltrs = [SELECT Id FROM Legend_Transfer_Request__c WHERE Id IN :transferIds];
    delete ltrs;
  }

  public static void deleteDealerMotorRequests(Set<Id> motorRequestIds) {
    Dealer_Motor_Request__c[] dmrs = [SELECT Id FROM Dealer_Motor_Request__c WHERE Id IN :motorRequestIds];
    delete dmrs;
  }
}