src/Base/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommissionPayment2__c/CommissionPayment2__c.object-meta.xml
<CustomObject>
    <label>Commission Payment</label>
    <nameField>
        <displayFormat>CommPayment-{0000}</displayFormat>
        <label>Commission Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CommissionPayment2__c/fields/Commission_Record2__c.field-meta.xml
<CustomField>
    <fullName>Commission_Record2__c</fullName>
    <label>Commission Record</label>
    <referenceTo>CommissionRecord2__c</referenceTo>
    <relationshipLabel>Commission Payments</relationshipLabel>
    <relationshipName>Commission_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/objects/CommissionRecord2__c/CommissionRecord2__c.object-meta.xml
<CustomObject>
    <label>Commission Record</label>
    <nameField>
        <displayFormat>CommRec-{0000}</displayFormat>
        <label>Commission Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/CommissionRecord2__c/fields/Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Method__c</fullName>
    <label>Calculation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commission_Calculation_Method</valueSetName>
    </valueSet>
</CustomField>

src/Base/main/default/objects/CommissionRecord2__c/fields/Department_GLV2__c.field-meta.xml
<CustomField>
    <fullName>Department_GLV2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department (GLV2)</label>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Commission Records</relationshipLabel>
    <relationshipName>Commission_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CommissionRecord2__c/fields/Factory_Pricebook__c.field-meta.xml
<CustomField>
    <fullName>Factory_Pricebook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Factory Pricebook Used to calculate cost on this record</description>
    <label>Factory Pricebook</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Commission Records (Factory Pricebook)</relationshipLabel>
    <relationshipName>Commission_Records1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CommissionRecord2__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Commission Records</relationshipLabel>
    <relationshipName>Commission_Records1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/CommissionRecord2__c/fields/Project_Task__c.field-meta.xml
<CustomField>
    <fullName>Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <referenceTo>AcctSeed__Project_Task__c</referenceTo>
    <relationshipLabel>Commission Records</relationshipLabel>
    <relationshipName>Commission_Records1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/CommissionRecord2__c/fields/Retail_Pricebook__c.field-meta.xml
<CustomField>
    <fullName>Retail_Pricebook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Retail Pricebook used for this commission record</description>
    <label>Retail Pricebook</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Commission Records</relationshipLabel>
    <relationshipName>Commission_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/globalValueSets/Commission_Calculation_Method.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Revenue</fullName>
        <default>true</default>
        <label>Revenue</label>
    </customValue>
    <customValue>
        <fullName>Gross Margin</fullName>
    </customValue>
    <description>Method used to calculate Commission</description>
    <masterLabel>Commission Calculation Method</masterLabel>
</GlobalValueSet>

src/Automation/main/default/classes/CommissionRecord2/Tests/TA_CommRec2_CreateInitialPayments_T.cls
/**
 * Created by dave on 2022-01-12.
 */

@IsTest
private class TA_CommRec2_CreateInitialPayments_T
{

  @testSetup
  static void dataSetup() {
    TA_CommRec2_TestHelper.testDataSetup();
  }

  @IsTest
  static void TA_afterInsert()
  {
    TA_CommRec2_TestHelper helper = new TA_CommRec2_TestHelper();
    CommissionRecord2__c record = new CommissionRecord2__c(
      Project_Task__c = helper.tasks[0].Id,
      Project__c = helper.tasks[0].AcctSeed__Project__c,
      Calculation_Method__c = helper.tasks[0].Commission_Calculation_Method__c,
      Department_GLV2__c = helper.tasks[0].AcctSeed__GL_Account_Variable_2__c,
      Retail_Pricebook__c = Test_Constants.idRetailPricebook,
      Factory_Pricebook__c = Test_Constants.idFactoryPricebook
    );
    TriggerBase.bypass('CommissionRecord2__c');
    insert record;
    TriggerBase.clearBypass('CommissionRecord2__c');

    List<CommissionRecord2__c> newList = new List<CommissionRecord2__c>
    {
      record
    };

    Test.startTest();
    new TA_CommRec2_CreateInitialPayments().afterInsert(newList);
    Test.stopTest();

    List<CommissionPayment2__c> payments = [SELECT Id FROM CommissionPayment2__c WHERE Commission_Record2__c = :record.Id];

    System.assert(payments.size() > 0);
  }
}