src/Base/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>Used in filtered look ups to limit the selection of inactive projects.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Shop</fullName>
            </value>
            <value>
                <fullName>Pending Repair</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Ready For Accounting</fullName>
            </value>
            <value>
                <fullName>Ready to Finalize W/O</fullName>
            </value>
            <value>
                <fullName>At Supplier</fullName>
            </value>
            <value>
                <fullName>In Storage</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card__c/AcctSeed__Time_Card__c.object-meta.xml
<CustomObject>
    <description>Used to document the time associated with an employee for a given time card period.</description>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC-{00000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Time_Card__c/fields/AcctSeed__Employee__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Look up to Salesforce User.</inlineHelpText>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Time_Cards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>Used in approvals of Time Cards and related detail lines. A value of &quot;Posted&quot; indicates the record is final and a debit and credit line have been entered into the transaction object for each Time Card Day.</inlineHelpText>
    <label>Posting Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Plan</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
                <default>true</default>
                <label>In Process</label>
            </value>
            <value>
                <fullName>Waiting for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card__c/fields/AcctSeed__Time_Card_Period__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Time_Card_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Used for grouping of Time Card Lines. Currently only 7 day Time card periods are supported.</inlineHelpText>
    <label>Time Card Period</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>This Time Period has been Closed. Please contact your administrator to make any changes to this period.</errorMessage>
        <filterItems>
            <field>AcctSeed__Time_Card_Period__c.AcctSeed__Status__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Time_Card_Period__c</referenceTo>
    <relationshipLabel>Time Cards</relationshipLabel>
    <relationshipName>Time_Cards</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card_Line__c/AcctSeed__Time_Card_Line__c.object-meta.xml
<CustomObject>
    <description>Used to document the project and project task associated with a time card. Time card lines aggregate to a specific time card.</description>
    <label>Time Card Line</label>
    <nameField>
        <displayFormat>TCL-{00000}</displayFormat>
        <label>Time Card Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Card Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Time_Card_Line__c/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Time Card Lines</relationshipLabel>
    <relationshipName>Time_Card_Line_Details</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card_Line__c/fields/AcctSeed__Time_Card__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Time_Card__c</fullName>
    <label>Time Card</label>
    <referenceTo>AcctSeed__Time_Card__c</referenceTo>
    <relationshipName>Time_Card_Line_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card_Line__c/fields/AcctSeed__Time_Card_Variable_2__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Time_Card_Variable_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Time Card Variable 2</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Accounting Variable must have a Type of &quot;Time Card Variable 2&quot;.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>Time Card Variable 2</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Time Card Lines (Time Card Variable 2)</relationshipLabel>
    <relationshipName>Time_Card_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card_Line__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <formula>AcctSeed__Time_Card__r.AcctSeed__Employee__r.LastName + &quot;, &quot;+  AcctSeed__Time_Card__r.AcctSeed__Employee__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Employee</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card_Line__c/fields/Uniquefier__c.field-meta.xml
<CustomField>
    <fullName>Uniquefier__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Uniquefier</label>
    <length>90</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card_Period__c/AcctSeed__Time_Card_Period__c.object-meta.xml
<CustomObject>
    <description>Used to capture the specific time frame e.g. start date and end date associated with a time card.</description>
    <label>Time Card Period</label>
    <nameField>
        <label>Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Card Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Time_Card_Period__c/fields/AcctSeed__End_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__End_Date__c</fullName>
    <inlineHelpText>Last day of the Time Card Period. This field is automatically calculated to be 6 days after the start date entered for the Time Card Period.. A value entered directly into this field will be overwritten.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card_Period__c/fields/AcctSeed__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Start_Date__c</fullName>
    <inlineHelpText>Beginning of the Time Card Period. Typically a Monday or Sunday.</inlineHelpText>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Time_Card_Period__c/fields/AcctSeed__Status__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Status__c</fullName>
    <inlineHelpText>&quot;Open&quot; indicates that Time Cards can be entered for this period. &quot;Closed&quot; indicates that no new Time Cards can be entered for this period.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesforce User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Wage_Rate__c/Employee_Wage_Rate__c.object-meta.xml
<CustomObject>
    <label>Employee Wage Rate</label>
    <nameField>
        <displayFormat>EWR-{0000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Wage Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Wage_Rate__c/fields/Apprentice_Rate__c.field-meta.xml
<CustomField>
    <fullName>Apprentice_Rate__c</fullName>
    <label>Apprentice Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Employee_Wage_Rate__c/fields/Base__c.field-meta.xml
<CustomField>
    <fullName>Base__c</fullName>
    <label>Base</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Employee_Wage_Rate__c/fields/Benefits__c.field-meta.xml
<CustomField>
    <fullName>Benefits__c</fullName>
    <label>Benefits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Employee_Wage_Rate__c/fields/Effective_Time_Card_Period__c.field-meta.xml
<CustomField>
    <fullName>Effective_Time_Card_Period__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Effective Time Card Period</label>
    <referenceTo>AcctSeed__Time_Card_Period__c</referenceTo>
    <relationshipLabel>Employee Wage Rates</relationshipLabel>
    <relationshipName>Employee_Wage_Rates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Wage_Rate__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Employee Wage Rates</relationshipLabel>
    <relationshipName>Employee_Wage_Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Wage_Rate__c/fields/Holiday_Hours__c.field-meta.xml
<CustomField>
    <fullName>Holiday_Hours__c</fullName>
    <label>Holiday Hours</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Employee_Wage_Rate__c/fields/Medical_Fringe__c.field-meta.xml
<CustomField>
    <fullName>Medical_Fringe__c</fullName>
    <label>Medical Fringe</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Employee_Wage_Rate__c/fields/PTO_Hours__c.field-meta.xml
<CustomField>
    <fullName>PTO_Hours__c</fullName>
    <label>PTO Hours</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Employee_Wage_Rate__c/fields/Uniquefier__c.field-meta.xml
<CustomField>
    <fullName>Uniquefier__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Uniquefier</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/Base/main/default/classes/gcEmployeeWageRate.cls
public with sharing class gcEmployeeWageRate {

    public static Boolean disableTrigger{
        get{
            if(disableTrigger == null) return false;
            else return disableTrigger;
        }
        set{
            if(value == null) disableTrigger = false;
            else disableTrigger = value;
        }
    }

    public static void triggerHandler
        (map<Id,Employee_Wage_Rate__c> oldMap,
         map<Id,Employee_Wage_Rate__c> newMap,
         list<Employee_Wage_Rate__c> listNew,
         Boolean boolIsBefore,
         Boolean boolIsInsert,
         Boolean boolIsUpdate,
         Boolean boolIsDelete)
    {
        if(oldMap == NULL) oldMap = new map<Id,Employee_Wage_Rate__c>();
        if(newMap == NULL) newMap = new map<Id,Employee_Wage_Rate__c>();
        if(listNew == NULL) listNew = new list<Employee_Wage_Rate__c>();

        updateAndValidate(oldMap,newMap,listNew,boolIsBefore,boolIsInsert,boolIsUpdate,boolIsDelete);
        
        if(boolIsBefore)
        {
            if(boolIsInsert)
            {

            }
            if(boolIsUpdate)
            {

            }
            if(boolIsDelete)
            {

            }
        }
        else //i.e. trigger.isAfter
        {
            if(boolIsInsert)
            {
                
            }
            if(boolIsUpdate)
            {

            }
            if(boolIsDelete)
            {

            }
        }           
    }

    private static map<Id,AcctSeed__Time_Card_Period__c> mapTcp;
    private static map<Id,Employee__c> mapEmployee;

    private static void retrieveTimeCardPeriods(list<Employee_Wage_Rate__c> listEwr)
    {
        if(mapTcp == null)
           mapTcp = new map<Id,AcctSeed__Time_Card_Period__c>();

        set<Id> setIdTcp = new set<Id>();
        for(Employee_Wage_Rate__c ewr : listEwr)
        {
            if(!mapTcp.containsKey(ewr.Effective_Time_Card_Period__c))
                setIdTcp.add(ewr.Effective_Time_Card_Period__c);
        }

        if(setIdTcp.size() > 0)
        for(AcctSeed__Time_Card_Period__c tcp : 
            [SELECT Id,
                    AcctSeed__Start_Date__c,
                    AcctSeed__End_Date__c,
                    AcctSeed__Status__c
             FROM AcctSeed__Time_Card_Period__c
             WHERE Id IN :setIdTcp])
        {
            mapTcp.put(tcp.Id,tcp);
        }
    }

    private static void retrieveEmployees(list<Employee_Wage_Rate__c> listEwr)
    {
        if(mapEmployee == null)
        {
           mapEmployee = new map<Id,Employee__c>();
        }

        set<Id> setIdEmployee = new set<Id>();
        for(Employee_Wage_Rate__c ewr : listEwr)
        {
            if(!mapEmployee.containsKey(ewr.Employee__c))
                setIdEmployee.add(ewr.Employee__c);
        }

        if(setIdEmployee.size() > 0)
        for(Employee__c emp :
            [SELECT Id, User__c
             FROM Employee__c
             WHERE Id IN :setIdEmployee])
        {
            mapEmployee.put(emp.Id,emp);
        }
    }

    private static void updateAndValidate
        (map<Id,Employee_Wage_Rate__c> oldMap,
         map<Id,Employee_Wage_Rate__c> newMap,
         list<Employee_Wage_Rate__c> listNew,
         Boolean boolIsBefore,
         Boolean boolIsInsert,
         Boolean boolIsUpdate,
         Boolean boolIsDelete)
    {
        list<Employee_Wage_Rate__c> listEwr = new list<Employee_Wage_Rate__c>();
        listEwr.addAll(listNew);
        listEwr.addAll(oldMap.values());

        retrieveTimeCardPeriods(listEwr);

        if(boolIsBefore)
        {
            for(Employee_Wage_Rate__c ewr : listNew)
            {
                AcctSeed__Time_Card_Period__c tcp = mapTcp.get(ewr.Effective_Time_Card_Period__c);

                if(boolIsInsert || boolIsUpdate)
                {
                    if(ewr.Effective_Time_Card_Period__c == null)
                        ewr.addError('Effective Time Card Period is a required field.');
                    else if(ewr.Base__c == null || ewr.Base__c < 0)
                        ewr.addError('Base is required and must be greater or equal to zero.');
                    //else if(ewr.Benefits__c == null || ewr.Benefits__c < 0)
                    //    ewr.addError('Benefits is required and must be greater or equal to zero.');

                    ewr.Uniquefier__c = ewr.Employee__c + '-' + ewr.Effective_Time_Card_Period__c;

                    //Calculate the benefits
                    Decimal base = (ewr.Base__c != null) ? ewr.Base__c : 0;
                    Decimal ptoHours = (ewr.PTO_Hours__c != null) ? ewr.PTO_Hours__c : 0;
                    Decimal holidayHours = (ewr.Holiday_Hours__c != null) ? ewr.Holiday_Hours__c : 0;
                    Decimal medicalFringe = (ewr.Medical_Fringe__c != null) ? ewr.Medical_Fringe__c : 0;

                    Decimal benefits = (((ptoHours + holidayHours) * base) + (medicalFringe * 12)) / 2080;
                    ewr.Benefits__c = benefits.setScale(2);
                }

                if(boolIsInsert)
                {
                    if(tcp.AcctSeed__Status__c != 'Open')
                        tcp.addError('An Employee Wage Rate cannot be inserted for a Time Card Period that is Closed.');
                }

                if(boolIsUpdate)
                {
                    if(ewr.Employee__c != oldMap.get(ewr.Id).Employee__c)
                        ewr.addError('Employee cannot be changed.');
                    else if(ewr.Effective_Time_Card_Period__c != oldMap.get(ewr.Id).Effective_Time_Card_Period__c)
                        ewr.addError('The Effective Time Card Period cannot be changed.');

                    if(tcp.AcctSeed__Status__c != 'Open' &&
                       (ewr.Base__c != oldMap.get(ewr.Id).Base__c ||
                        ewr.PTO_Hours__c != oldMap.get(ewr.Id).PTO_Hours__c ||
                        ewr.Holiday_Hours__c != oldMap.get(ewr.Id).Holiday_Hours__c ||
                        ewr.Medical_Fringe__c != oldMap.get(ewr.Id).Medical_Fringe__c ||
                        ewr.Benefits__c != oldMap.get(ewr.Id).Benefits__c ||
                        ewr.Apprentice_Rate__c != oldMap.get(ewr.Id).Apprentice_Rate__c))
                    {
                        ewr.addError('An Employee\'s Base, PTO Hours, Holiday Hours, Medical Fringe, Benefit, and Apprentice Rates cannot be changed for a Time Card Period period that is Closed.');
                    }
                }
            }

            if(boolIsDelete)
            {
                for(Employee_Wage_Rate__c ewr : oldMap.values())
                {
                    AcctSeed__Time_Card_Period__c tcp = mapTcp.get(ewr.Effective_Time_Card_Period__c);

                    if(tcp.AcctSeed__Status__c != 'Open')
                    {
                        ewr.addError('An Employee Wage Rate cannot be deleted for a Time Card Period that is Closed.');
                    }
                }
            }
        }
        else //i.e. after context
        {
            if(boolIsUpdate || boolIsDelete)
            {
                retrieveTimeCardPeriods(oldMap.values());
                retrieveEmployees(oldMap.values());

                map<Id,Date> mapUserEarliestDate = new map<Id,Date>();
                Date dateEarliest;

                for(Employee_Wage_Rate__c ewr : oldMap.values())
                {
                    Date dateStart = mapTcp.get(ewr.Effective_Time_Card_Period__c).AcctSeed__Start_Date__c;
                    Id idUser = mapEmployee.get(ewr.Employee__c).User__c;

                    if(mapUserEarliestDate.get(idUser) == null || mapUserEarliestDate.get(idUser) > dateStart)
                        mapUserEarliestDate.put(idUser,dateStart);

                    if(dateEarliest == null || dateEarliest > dateStart)
                        dateEarliest = dateStart;
                }

                list<AcctSeed__Time_Card_Line__c> listTcl = new list<AcctSeed__Time_Card_Line__c>();
                for(AcctSeed__Time_Card_Line__c tcl :
                    [SELECT Id,
                            AcctSeed__Project__c, 
                            AcctSeed__Time_Card__c,
                            AcctSeed__Time_Card__r.AcctSeed__Employee__c,
                            AcctSeed__Time_Card__r.AcctSeed__Time_Card_Period__r.AcctSeed__Start_Date__c,
                            AcctSeed__Time_Card_Variable_2__c 
                     FROM AcctSeed__Time_Card_Line__c 
                     WHERE AcctSeed__Time_Card__r.AcctSeed__Employee__c IN : mapUserEarliestDate.keySet()
                       AND AcctSeed__Time_Card__r.AcctSeed__Time_Card_Period__r.AcctSeed__Start_Date__c >= :dateEarliest
                       AND AcctSeed__Time_Card__r.AcctSeed__Time_Card_Period__r.AcctSeed__Status__c = 'Open'])
                {
                    Date dateEarliestUser = mapUserEarliestDate.get(tcl.AcctSeed__Time_Card__r.AcctSeed__Employee__c);
                    if(tcl.AcctSeed__Time_Card__r.AcctSeed__Time_Card_Period__r.AcctSeed__Start_Date__c >= dateEarliestUser)
                        listTcl.add(tcl);
                }

                gcTimeCardLine.updateWage(listTCL);

                Boolean boolOld = gcTimeCardLine.disableTrigger;
                gcTimeCardLine.disableTrigger = true;
                update listTCL;
                gcTimeCardLine.disableTrigger = boolOld;

            }
        }
    }


}