src/Base/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project__c/fields/AcctSeed__Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Organization for which this project exists for,</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The FSL Work Order</description>
    <label>Work Order</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>ERP Orders</relationshipLabel>
    <relationshipName>ERP_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project_Task__c/AcctSeed__Project_Task__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <inlineHelpText>Related Parent object.</inlineHelpText>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/Work_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order Line Item</label>
    <referenceTo>WorkOrderLineItem</referenceTo>
    <relationshipLabel>ERP Order Tasks</relationshipLabel>
    <relationshipName>ERP_Order_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Legend_Settings__c/Legend_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Legend Settings</label>
</CustomObject>

force-app/main/default/objects/Legend_Settings__c/fields/Default_Retail_Pricebook__c.field-meta.xml
<CustomField>
    <fullName>Default_Retail_Pricebook__c</fullName>
    <label>Default Retail Pricebook</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/WorkOrder/fields/ERP_Order__c.field-meta.xml
<CustomField>
    <fullName>ERP_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to the ERP Order that the Work Order is Created from</description>
    <label>ERP Order</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/WorkOrderLineItem/fields/ERP_Order_Task__c.field-meta.xml
<CustomField>
    <fullName>ERP_Order_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ERP Order Task</label>
    <referenceTo>AcctSeed__Project_Task__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/FieldService/classes/WorkOrderLine/Tests/WorkOrderLineItem_Automation_T.cls
/**
 * Created by dave on 2021-06-08.
 */

@IsTest
private class WorkOrderLineItem_Automation_T {
  private static WorkOrder wo;
  private static AcctSeed__Project__c erp;

  @testSetup
  static void dataSetup() {
    new Factory_TestData();
    Factory_CustomSettings.setupInventorySettings();
    Id pbId = Legend_Settings__c.getOrgDefaults().Default_Retail_Pricebook__c;
    Account acct = Factory_Account.insertFullPersonAccount('Testy', 'McTesterson');
    TriggerBase.bypass('WorkOrder');
    WorkOrder wo = Factory_WorkOrder.createNew(acct.Id, pbId);
    AcctSeed__Project__c erp = new AcctSeed__Project__c(
      Name = (wo.Account.Name + ' - ' + String.valueOf(wo.WorkOrderNumber)).LEFT(80),
      AcctSeed__Account__c = wo.AccountId,
      Work_Order__c = wo.Id
    );
    gcProject.disableTrigger = true;
    insert erp;
    wo.ERP_Order__c = erp.Id;
    update wo;
    TriggerBase.clearBypass('WorkOrder');
  }

  private static void createWoliAndTask() {
    TriggerBase.bypass('WorkOrderLineItem');
    AcctSeed__Project_Task__c orderTask = Factory_ERPOrderTask.buildProjectTask(erp.Id, 'WOLI Unit Test');
    WorkOrderLineItem woli = Factory_WorkOrder.createLineItems(wo.Id, 1)[0];
    orderTask.Work_Order_Line_Item__c = woli.Id;
    insert orderTask;
    woli.ERP_Order_Task__c = orderTask.Id;
    update woli;
    TriggerBase.clearBypass('WorkOrderLineItem');
  }

  private static void fetchWorkOrder() {
    wo = [SELECT Id, ERP_Order__c, (SELECT Id FROM WorkOrderLineItems) FROM WorkOrder LIMIT 1];
  }

  private static void fetchErpOrder() {
    erp = [SELECT Id, (SELECT Id FROM AcctSeed__Project_Tasks__r) FROM AcctSeed__Project__c LIMIT 1];
  }

  @IsTest
  static void afterInsert_Test() {
    fetchWorkOrder();
    Test.startTest();
    WorkOrderLineItem woli = Factory_WorkOrder.createLineItems(wo.Id, 1)[0];
    Test.stopTest();

    List<AcctSeed__Project_Task__c> orderTasks = [
      SELECT Id
      FROM AcctSeed__Project_Task__c
      WHERE AcctSeed__Project__c = :wo.ERP_Order__c
    ];

    woli = [SELECT Id, ERP_Order_Task__c FROM WorkOrderLineItem WHERE Id = :woli.Id];

    System.assertEquals(1, orderTasks.size());
    System.assert(woli.ERP_Order_Task__c != null);
  }

  @IsTest
  static void beforeDelete_Test() {
    fetchWorkOrder();
    fetchErpOrder();
    createWoliAndTask();
    fetchWorkOrder();
    fetchErpOrder();

    System.assertEquals(1, wo.WorkOrderLineItems.size());
    System.assertEquals(1, erp.AcctSeed__Project_Tasks__r.size());

    Test.startTest();
    delete wo.WorkOrderLineItems[0];
    Test.stopTest();

    fetchWorkOrder();
    fetchErpOrder();

    System.assertEquals(0, wo.WorkOrderLineItems.size());
    System.assertEquals(0, erp.AcctSeed__Project_Tasks__r.size());
  }
}