src/Base/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Project__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destination</label>
    <referenceTo>Truck_Destination__c</referenceTo>
    <relationshipLabel>ERP Orders</relationshipLabel>
    <relationshipName>ERP_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/AcctSeedERP__Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <displayFormat>MAT-{00000}</displayFormat>
        <label>Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Project_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Project_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Material__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>AcctSeedERP__Product__r.Name</formula>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Truck_Destination__c/Truck_Destination__c.object-meta.xml
<CustomObject>
    <label>Truck Destination</label>
    <nameField>
        <displayFormat>TruckDest-{0000}</displayFormat>
        <label>Truck Destination Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Truck Destinations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Truck_Destination__c/fields/Travel_Days__c.field-meta.xml
<CustomField>
    <fullName>Travel_Days__c</fullName>
    <formula>Account__r.Total_Travel_Time_in_Days__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Travel Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Truck_Driver__c/Truck_Driver__c.object-meta.xml
<CustomObject>
    <label>Truck Driver</label>
    <nameField>
        <label>Truck Driver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Truck Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Truck_Driver__c/fields/CalBgColor__c.field-meta.xml
<CustomField>
    <fullName>CalBgColor__c</fullName>
    <description>Truck Schedule Event background color</description>
    <inlineHelpText>Must be CSS compatible ( red, #EEFF09, rgba(237, 134, 098, 0.4) )</inlineHelpText>
    <label>Calendar Background Color</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Truck_Load__c/Truck_Load__c.object-meta.xml
<CustomObject>
    <label>Truck Load</label>
    <nameField>
        <displayFormat>TL-{0000}</displayFormat>
        <label>Truck Load Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Truck Loads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Truck_Load__c/fields/Delivery_Date2__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date2__c</fullName>
    <label>Delivery Date2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Truck_Load__c/fields/Departure_Date2__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date2__c</fullName>
    <label>Departure Date2</label>
    <type>Date</type>
</CustomField>

src/Base/main/default/objects/Truck_Load__c/fields/Destination__c.field-meta.xml
<CustomField>
    <fullName>Destination__c</fullName>
    <label>Destination</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

src/Base/main/default/objects/Truck_Load__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Luc Broullette</fullName>
            </value>
            <value>
                <fullName>Mike Rancourt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Truck_Load__c/fields/Return_Date2__c.field-meta.xml
<CustomField>
    <fullName>Return_Date2__c</fullName>
    <label>Return Date2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Truck_Load__c/fields/Trailer__c.field-meta.xml
<CustomField>
    <fullName>Trailer__c</fullName>
    <label>Trailer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TRL1</fullName>
            </value>
            <value>
                <fullName>TRL2</fullName>
            </value>
            <value>
                <fullName>TRL3</fullName>
            </value>
            <value>
                <fullName>TRL4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Truck_Load__c/fields/Travel_Days__c.field-meta.xml
<CustomField>
    <fullName>Travel_Days__c</fullName>
    <label>Travel Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Truck_Load__c/fields/Truck__c.field-meta.xml
<CustomField>
    <fullName>Truck__c</fullName>
    <label>Truck</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Truck_Trip__c/Truck_Trip__c.object-meta.xml
<CustomObject>
    <label>Truck Trip</label>
    <nameField>
        <label>Truck Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Truck Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Truck_Trip__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <label>Departure Date</label>
    <type>Date</type>
</CustomField>

src/Base/main/default/objects/Truck_Trip__c/fields/Distance_KM__c.field-meta.xml
<CustomField>
    <fullName>Distance_KM__c</fullName>
    <description>Distance in KM</description>
    <label>Distance (KM)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Truck_Trip__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2nd Outside Carrier</fullName>
                <color>#0B6FCE</color>
                <label>2nd Outside Carrier</label>
            </value>
            <value>
                <fullName>Luc Brouillette</fullName>
                <color>#78C953</color>
                <label>Luc Brouillette</label>
            </value>
            <value>
                <fullName>Mike Rancourt</fullName>
                <color>#E27001</color>
                <label>Mike Rancourt</label>
            </value>
            <value>
                <fullName>Bill Gaudreau</fullName>
                <color>#A845DC</color>
                <label>Bill Gaudreau</label>
            </value>
            <value>
                <fullName>Dealer_Pickup</fullName>
                <color>#F3D904</color>
                <label>Dealer Pickup</label>
            </value>
            <value>
                <fullName>Outside Carrier</fullName>
                <color>#A53711</color>
                <label>Outside Carrier</label>
            </value>
            <value>
                <fullName>Campion</fullName>
                <color>#66E9BD</color>
                <label>Campion</label>
            </value>
            <value>
                <fullName>3rd Outside Carrier</fullName>
                <color>#0B24BE</color>
                <label>3rd Outside Carrier</label>
            </value>
            <value>
                <fullName>2nd Dealer Pickup</fullName>
                <color>#419249</color>
                <label>2nd Dealer Pickup</label>
            </value>
            <value>
                <fullName>Mike_Lavallee</fullName>
                <color>#B6E32E</color>
                <label>Mike Lavallee</label>
            </value>
            <value>
                <fullName>Marianne</fullName>
                <color>#641CCF</color>
                <label>Marianne</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Truck_Trip__c/fields/Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Return_Date__c</fullName>
    <label>Return Date</label>
    <type>Date</type>
</CustomField>

src/Base/main/default/objects/Truck_Trip__c/fields/Trailer__c.field-meta.xml
<CustomField>
    <fullName>Trailer__c</fullName>
    <label>Trailer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trailer 2 Newer SSU</fullName>
            </value>
            <value>
                <fullName>Trailer 3Q Quebec</fullName>
            </value>
            <value>
                <fullName>Trailer 6Q Quebec</fullName>
            </value>
            <value>
                <fullName>Trailer 7 on loan Smoker</fullName>
            </value>
            <value>
                <fullName>Trailer 4 Pontoon hauler</fullName>
            </value>
            <value>
                <fullName>Trailer 5 Older SSU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Truck_Trip__c/fields/Truck__c.field-meta.xml
<CustomField>
    <fullName>Truck__c</fullName>
    <label>Truck</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Truck 2 Older Sterling</fullName>
            </value>
            <value>
                <fullName>Truck 4 2008 Freightliner</fullName>
            </value>
            <value>
                <fullName>Truck 5 2009 Freightliner</fullName>
            </value>
            <value>
                <fullName>Truck 6 Argosy Freightliner</fullName>
            </value>
            <value>
                <fullName>Truck 7 Argosy Freightliner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Truck_Trip__c/fields/Truck_Driver__c.field-meta.xml
<CustomField>
    <fullName>Truck_Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Truck Driver</label>
    <referenceTo>Truck_Driver__c</referenceTo>
    <relationshipLabel>Truck Trips</relationshipLabel>
    <relationshipName>Truck_Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TruckLoadLine__c/TruckLoadLine__c.object-meta.xml
<CustomObject>
    <label>Truck Load Line</label>
    <nameField>
        <displayFormat>TLL-{0000}</displayFormat>
        <label>TruckLoadLine Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Truck Load Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/TruckLoadLine__c/fields/ERP_Order__c.field-meta.xml
<CustomField>
    <fullName>ERP_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ERP Order</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Truck Load Lines</relationshipLabel>
    <relationshipName>Truck_Load_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TruckLoadLine__c/fields/Travel_Days__c.field-meta.xml
<CustomField>
    <fullName>Travel_Days__c</fullName>
    <formula>ERP_Order__r.AcctSeed__Account__r.Total_Travel_Time_in_Days__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Travel Days</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TruckLoadLine__c/fields/Truck_Load__c.field-meta.xml
<CustomField>
    <fullName>Truck_Load__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Truck Load</label>
    <referenceTo>Truck_Load__c</referenceTo>
    <relationshipLabel>Truck Load Lines</relationshipLabel>
    <relationshipName>Truck_Load_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TruckLoadLine__c/fields/TruckPosition__c.field-meta.xml
<CustomField>
    <fullName>TruckPosition__c</fullName>
    <label>Truck Position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/classes/TruckSchedule.cls
public with sharing class TruckSchedule {
  public class TruckScheduleException extends Exception {
  }

  public class EventData {
    public String id { get; set; }
    public String name { get; set; }
    public String driver { get; set; }
    public String truckDriverId { get; set; }
    public String truck { get; set; }
    public String trailer { get; set; }
    public Decimal distance { get; set; }
    public Date startDateTime { get; set; }
    public String startDate { get; set; }
    //public Date deliveryDateTime { get; set; }
    //public String deliveryDate { get; set; }
    public Date endDateTime { get; set; }
    public String endDate { get; set; }
    //public String destination { get; set; }
    //public Decimal travelDays { get; set; }
    //public Map<String, List<String>> loadContents { get; set; }

    //public EventData(Truck_Load__c tl)
    //{
    //  this.id = tl.Id;
    //  this.name = tl.Name;
    //  this.travelDays = tl.Travel_Days__c  <= 1 ? 1 : tl.Travel_Days__c;
    //  this.driver = tl.Driver__c;
    //  this.truck = tl.Truck__c;
    //  this.trailer = tl.Trailer__c;
    //  this.startDateTime = tl.Departure_Date2__c;
    //  this.startDate = dateToString( tl.Departure_Date2__c );
    //  this.deliveryDateTime = tl.Delivery_Date2__c;
    //  this.deliveryDate = dateToString( tl.Delivery_Date2__c );
    //  this.endDateTime = tl.Return_Date2__c;
    //  this.endDate = dateToString( tl.Return_Date2__c );
    //  this.destination = tl.Destination__c;
    //  if( tl.Truck_Load_Lines__r != null && tl.Truck_Load_Lines__r.size() > 0 )
    //  {
    //    buildLoadContents( tl.Truck_Load_Lines__r);
    //  }
    //}

    public EventData(Truck_Trip__c trip) {
      this.id = trip.Id;
      this.name = trip.Name;
      this.driver = trip.Driver__c;
      this.truckDriverId = trip.Truck_Driver__c;
      this.truck = trip.Truck__c;
      this.trailer = trip.Trailer__c;
      this.distance = trip.Distance_KM__c;
      this.startDateTime = trip.Departure_Date__c;
      this.startDate = dateToString(trip.Departure_Date__c);
      this.endDateTime = trip.Return_Date__c;
      this.endDate = dateToString(trip.Return_Date__c);
    }

    private String dateToString(Date d) {
      if (d != null) {
        return DateTime.newInstance(d.year(), d.month(), d.day()).format('MM/dd/yy');
      }
      return null;
    }

    //private void buildLoadContents( TruckLoadLine__c[] tlls )
    //{
    //  this.loadContents = new Map<String, List<String>>();
    //  for( String trailerPos : LGND_Utilities.getPicklistValues('TruckLoadLine__c', 'TruckPosition__c') )
    //  {
    //    this.loadContents.put( trailerPos, new List<String>() );
    //  }

    //  Map<Id, TruckLoadLine__c> truckLoadLineErpOrderMap = new Map<Id, truckLoadLine__c>();
    //  Set<Id> productRTs = new Set<Id>{
    //    LGND_Utilities.recordTypeIdFromName('Product2', 'Trailer'),
    //    LGND_Utilities.recordTypeIdFromName('Product2', 'Boat')
    //  };
    //  for( TruckLoadLine__c tll : tlls )
    //  {
    //    truckLoadLineErpOrderMap.put( tll.ERP_Order__c, tll );
    //  }
    //  AcctSeed__Project__c[] erps = [SELECT Id,
    //                                 (SELECT Id,
    //                                        AcctSeedERP__Product__r.RecordType.Name,
    //                                        Product_Name__c
    //                                  FROM AcctSeedERP__Project_Materials__r
    //                                  WHERE AcctSeedERP__Product__r.RecordTypeId IN :productRTs)
    //                                FROM AcctSeed__Project__c
    //                                WHERE Id IN :truckLoadLineErpOrderMap.keySet() ];
    //  for( AcctSeed__Project__c erp : erps )
    //  {
    //    String boatName = '';
    //    String trailerName = '';
    //    String result = '';
    //    for( AcctSeedERP__Material__c mat : erp.AcctSeedERP__Project_Materials__r )
    //    {
    //      if( mat.AcctSeedERP__Product__r.RecordType.Name == 'Boat' )
    //        boatName = mat.Product_Name__c;
    //      if( mat.AcctSeedERP__Product__r.RecordType.Name == 'Trailer' )
    //        trailerName = mat.Product_Name__c;
    //    }
    //    if( boatName != '' && boatName != 'Loose Items' )
    //      result += boatName + ' / ';
    //    result += trailerName;
    //    this.loadContents.get( truckLoadLineErpOrderMap.get(erp.Id).TruckPosition__c ).add( result );
    //  }
    //}
  }

  public Truck_Trip__c[] scheduables { get; set; }
  public Map<String, Boolean> crudPermissions { get; set; }
  public Map<String, Map<String, String>> truckDrivers { get; set; }

  public TruckSchedule() {
  }

  public TruckSchedule(ApexPages.StandardController std) {
    scheduables = fetchScheduables();
    truckDrivers = TruckSchedule.fetchTruckDrivers();
    setCrudPermissions();
  }

  public String getCrudPermissionsJSON() {
    return JSON.serialize(crudPermissions);
  }

  private void setCrudPermissions() {
    Schema.DescribeSObjectResult tripObj = Schema.sObjectType.Truck_Trip__c;
    Schema.DescribeSObjectResult destObj = Schema.sObjectType.Truck_Destination__c;
    Schema.DescribeSObjectResult matObj = Schema.sObjectType.AcctSeedERP__Material__c;
    crudPermissions = new Map<String, Boolean>();
    crudPermissions.put('canEditTrips', tripObj.isUpdateable());
    crudPermissions.put('canDeleteTrips', tripObj.isDeletable());
    crudPermissions.put('canCreateDestinations', destObj.isCreateable());
    crudPermissions.put('canEditDestinations', destObj.isUpdateable());
    crudPermissions.put('canDeleteDestinations', destObj.isDeletable());
    crudPermissions.put('canEditMaterials', matObj.isUpdateable());
  }

  public List<String> getDrivers() {
    return LGND_Utilities.getPicklistValues('Truck_Trip__c', 'Driver__c');
  }

  public String getTruckDriversJSON() {
    return JSON.serialize(truckDrivers);
  }

  public static Map<String, Map<String, String>> fetchTruckDrivers() {
    Map<String, Map<String, String>> drivers = new Map<String, Map<String, String>>();
    for (Truck_Driver__c td : [
      SELECT Id, Name, CalBgColor__c, CalBorderColor__c, CalTextColor__c
      FROM Truck_Driver__c
      ORDER BY Name DESC
    ]) {
      Map<String, String> details = new Map<String, String>();
      details.put('Id', td.Id);
      details.put('Name', td.Name);
      details.put('BgColor', td.CalBgColor__c);
      details.put('BorderColor', td.CalBorderColor__c);
      details.put('TextColor', td.CalTextColor__c);
      drivers.put(td.Id, details);
    }
    return drivers;
  }

  @RemoteAction
  @Readonly
  public static List<EventData> fetchAllTrips(Long startAt, Long endAt, Id truckDriverId) {
    Date sDateTime = DateTime.newInstance(startAt).date();
    Date eDateTime = DateTime.newInstance(endAt).date();
    System.debug(sDateTime);
    System.debug(eDateTime);
    List<EventData> result = new List<EventData>();
    List<Truck_Trip__c> trips = [
      SELECT
        Id,
        Name,
        Driver__c,
        Distance_KM__c,
        Truck_Driver__c,
        Truck__c,
        Trailer__c,
        Departure_Date__c,
        Return_Date__c
      FROM Truck_Trip__c
      WHERE Departure_Date__c >= :sDateTime AND Departure_Date__c <= :eDateTime AND Truck_Driver__c = :truckDriverId
    ];
    for (Truck_Trip__c trip : trips) {
      result.add(new EventData(trip));
    }
    return result;
  }

  @RemoteAction
  @Readonly
  public static Truck_Trip__c fetchTrip(String tripId) {
    return TripBuilderController.fetchTrip(Id.valueOf(tripId));
  }

  @RemoteAction
  public static EventData changedByDays(String tripId, Integer numDays) {
    if (Schema.sObjectType.Truck_Trip__c.isUpdateable()) {
      Truck_Trip__c trip = [
        SELECT Id, Distance_KM__c, Departure_Date__c, Return_Date__c, Truck__c, Trailer__c, Truck_Driver__c
        FROM Truck_Trip__c
        WHERE Id = :tripId
      ];
      trip.Departure_Date__c = trip.Departure_Date__c.addDays(numDays);
      trip.Return_Date__c = trip.Return_Date__c.addDays(numDays);
      String errorMsg = findSchedulingConflicts(trip);
      if (errorMsg != null)
        throw new TruckScheduleException(errorMsg);

      update trip;
      return new EventData(trip);
    }
    throw new TruckScheduleException('You do not have the required access on the Truck Trip object');
  }

  @RemoteAction
  public static EventData addedDays(String tripId, Integer numDays) {
    if (Schema.sObjectType.Truck_Trip__c.isUpdateable()) {
      Truck_Trip__c trip = [
        SELECT Id, Distance_KM__c, Departure_Date__c, Return_Date__c, Truck__c, Trailer__c, Truck_Driver__c
        FROM Truck_Trip__c
        WHERE Id = :tripId
      ];
      trip.Return_Date__c = trip.Return_Date__c.addDays(numDays);
      String errorMsg = findSchedulingConflicts(trip);
      if (errorMsg != null)
        throw new TruckScheduleException(errorMsg);

      update trip;
      return new EventData(trip);
    }
    throw new TruckScheduleException('You do not have the required access on the Truck Trip object');
  }

  @RemoteAction
  public static List<Truck_Trip__c> unschedule(String tripId) {
    if (Schema.sObjectType.Truck_Trip__c.isUpdateable()) {
      Truck_Trip__c trip = [SELECT Id FROM Truck_Trip__c WHERE Id = :tripId];
      trip.Driver__c = null;
      trip.Distance_KM__c = null;
      trip.Departure_Date__c = null;
      trip.Return_Date__c = null;
      trip.Truck__c = null;
      trip.Trailer__c = null;
      update trip;
      return fetchScheduables();
    }
    throw new TruckScheduleException('You do not have the required access on the Truck Trip object');
  }

  //@RemoteAction
  //public static List<Truck_Load__c> unschedule(String tlId)
  //{
  //  Truck_Load__c tl = [SELECT Id FROM Truck_Load__c WHERE Id = :tlId];
  //  tl.Departure_Date2__c = null;
  //  tl.Delivery_Date2__c = null;
  //  tl.Return_Date2__c = null;
  //  tl.Truck__c = null;
  //  tl.Trailer__c = null;
  //  update tl;
  //  return fetchScheduables();
  //}

  private static List<Truck_Trip__c> fetchScheduables() {
    if (Schema.sObjectType.Truck_Trip__c.isUpdateable()) {
      return [SELECT Id, Name, Truck__c, Trailer__c, Driver__c FROM Truck_Trip__c WHERE Departure_Date__c = NULL];
    }
    return null; //new List<Truck_Trip__c>();
  }

  public static String findSchedulingConflicts(Truck_Trip__c tt) {
    Truck_Driver__c driver = [
      SELECT Id, AllowSchedulingConflicts__c
      FROM Truck_Driver__c
      WHERE Id = :tt.Truck_Driver__c
    ];
    if (!driver.AllowSchedulingConflicts__c) {
      List<String> errors = new List<String>();
      Truck_Trip__c[] conflicts = [
        SELECT Id, Truck_Driver__c, Truck_Driver__r.Name, Trailer__c, Truck__c, Departure_Date__c, Return_Date__c
        FROM Truck_Trip__c
        WHERE
          Id != :tt.Id
          AND ((Return_Date__c >= :tt.Departure_Date__c
          AND Departure_Date__c <= :tt.Departure_Date__c)
          OR (Departure_Date__c <= :tt.Return_Date__c
          AND Return_Date__c >= :tt.Return_Date__c))
          AND (Truck_Driver__c = :tt.Truck_Driver__c
          OR Truck__c = :tt.Truck__c
          OR Trailer__c = :tt.Trailer__c)
      ];
      for (Truck_Trip__c conflict : conflicts) {
        if (tt.Truck_Driver__c != null && tt.Truck_Driver__c == conflict.Truck_Driver__c)
          errors.add(conflict.Truck_Driver__r.Name + ' is already scheduled');
        if (tt.Truck__c != null && tt.Truck__c == conflict.Truck__c)
          errors.add('Truck ' + tt.Truck__c + ' is already in use');
        if (tt.Trailer__c != null && tt.Trailer__c == conflict.Trailer__c)
          errors.add('Trailer ' + tt.Trailer__c + ' is already in use');
      }
      if (errors.size() > 0) {
        return String.join(errors, ', ');
      }
      return null;
    }
    return null;
  }

  public static void coverage() {
    integer i;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
    i = 1;
  }
}