src/Base/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Quoting</fullName>
            </value>
            <value>
                <fullName>Pending Review</fullName>
            </value>
            <value>
                <fullName>Pending Diagnostic</fullName>
            </value>
            <value>
                <fullName>Pending Financing</fullName>
            </value>
            <value>
                <fullName>Plan Load</fullName>
            </value>
            <value>
                <fullName>Tagging Pending</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Pending Work Order</fullName>
            </value>
            <value>
                <fullName>Pending Authorization</fullName>
            </value>
            <value>
                <fullName>Pending Pick and Pack</fullName>
            </value>
            <value>
                <fullName>Parts Required</fullName>
            </value>
            <value>
                <fullName>Parts to be Ordered</fullName>
            </value>
            <value>
                <fullName>Parts On Order</fullName>
            </value>
            <value>
                <fullName>Pending Scheduling</fullName>
            </value>
            <value>
                <fullName>Pending Standard Rig</fullName>
            </value>
            <value>
                <fullName>Pending Rigging</fullName>
            </value>
            <value>
                <fullName>Ready to Ship</fullName>
            </value>
            <value>
                <fullName>Pending Final Rigging</fullName>
            </value>
            <value>
                <fullName>Pending Retail Rig</fullName>
            </value>
            <value>
                <fullName>Service Completed</fullName>
            </value>
            <value>
                <fullName>Repair Completed</fullName>
            </value>
            <value>
                <fullName>Pending Delivery</fullName>
            </value>
            <value>
                <fullName>Picked up / Won</fullName>
            </value>
            <value>
                <fullName>Delivered / Won</fullName>
            </value>
            <value>
                <fullName>Paused for Season</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Awaiting Parts Return</fullName>
            </value>
            <value>
                <fullName>Awaiting Boat Return</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Case/fields/Parts_Order_ERP__c.field-meta.xml
<CustomField>
    <fullName>Parts_Order_ERP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parts Order ERP</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Project__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Legend Partner Parts Order</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Cases (Parts Order ERP)</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Recoverable_ERP__c.field-meta.xml
<CustomField>
    <fullName>Recoverable_ERP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recoverable ERP</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Cases (Recoverable ERP)</relationshipLabel>
    <relationshipName>Warranty_Recoverable_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Warranty_ERP__c.field-meta.xml
<CustomField>
    <fullName>Warranty_ERP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warranty ERP</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Warranty Cases</relationshipLabel>
    <relationshipName>Warranty_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Automation/main/default/classes/Case/TA_Case_CloseLostERPOnDenied.cls
/**
 * Created by dave on 2022-01-07.
 */

public inherited sharing class TA_Case_CloseLostERPOnDenied implements TriggerAction.AfterUpdate
{
  public void afterUpdate( List<Case> newList, List<Case> oldList ){
    Map<Id, Case> oldMap = new Map<Id, Case>(oldList);
    List<AcctSeed__Project__c> erps = new List<AcctSeed__Project__c>();
    for( Case c : newList )
    {
      Case oldCase = oldMap.get(c.Id);
      if( c.Status == 'Denied' &&
        oldCase.Status != 'Denied' )
      {
        if( c.Warranty_ERP__c != null )
        {
          erps.add( new AcctSeed__Project__c(
            Id = c.Warranty_ERP__c,
            Stage__c = 'Closed Lost'
          ));
        }
        if( c.Recoverable_ERP__c != null )
        {
          erps.add( new AcctSeed__Project__c(
            Id = c.Recoverable_ERP__c,
            Stage__c = 'Closed Lost'
          ));
        }
        if( c.Parts_Order_ERP__c != null )
        {
          erps.add( new AcctSeed__Project__c(
            Id = c.Parts_Order_ERP__c,
            Stage__c = 'Closed Lost'
          ));
        }
      }
      update erps;
    }
  }
}