src/Base/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project_Task__c/AcctSeed__Project_Task__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <inlineHelpText>Related Parent object.</inlineHelpText>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project_Task__c/fields/DisplayOnCustomerInvoice__c.field-meta.xml
<CustomField>
    <fullName>DisplayOnCustomerInvoice__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Display on Customer Invoice</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/IsFinishedGoodTask__c.field-meta.xml
<CustomField>
    <fullName>IsFinishedGoodTask__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsFinishedGoodTask</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parts List</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/Work_Order_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Work_Order_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order Line Item</label>
    <referenceTo>WorkOrderLineItem</referenceTo>
    <relationshipLabel>ERP Order Tasks</relationshipLabel>
    <relationshipName>ERP_Order_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/WorkOrder/fields/ERP_Order__c.field-meta.xml
<CustomField>
    <fullName>ERP_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reference to the ERP Order that the Work Order is Created from</description>
    <label>ERP Order</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/WorkOrder/fields/Manufacturing_Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Manufacturing_Product_Id__c</fullName>
    <formula>Serial_Number__r.GMBLASERP__Product__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Manufacturing Product Id</label>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/WorkOrderLineItem/fields/ERP_Order_Task__c.field-meta.xml
<CustomField>
    <fullName>ERP_Order_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ERP Order Task</label>
    <referenceTo>AcctSeed__Project_Task__c</referenceTo>
    <relationshipLabel>Work Order Line Items</relationshipLabel>
    <relationshipName>Work_Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/WorkOrderLineItem/fields/Visible_to_Customer__c.field-meta.xml
<CustomField>
    <fullName>Visible_to_Customer__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls whether this work order line and all associated Products are displayed on the customer facing invoice</description>
    <inlineHelpText>Controls whether this work order line and all associated Products are displayed on the customer facing invoice</inlineHelpText>
    <label>Visible to Customer</label>
    <type>Checkbox</type>
</CustomField>

src/FieldService/classes/ProjectTask/ProjectTask_ServiceFSL.cls
/**
 * Created by dave on 2022-03-08.
 */
/* TODO: REQUIRES UNIT TESTS */
/* TODO: MERGE INTO PROJECTTASK_SERVICE WHEN FSL MOVES TO PROD */
public with sharing class ProjectTask_ServiceFSL {
  public static List<AcctSeed__Project_Task__c> newFromWorkOrderLineItemIds(Set<Id> workOrderLineitemIds) {
    List<WorkOrderLineItem> wolis = WorkOrderLineItem_Selector.selectAllById_includingWorkOrderWithERP(
      workOrderLineitemIds
    );
    return createFromWorkOrderLineItems(wolis);
  }
  public static void newFromWorkOrderLineItemIds_queue(Set<Id> workOrderLineItemIds) {
    if (Test.isRunningTest()) {
      CreateProjectTasksQueue cptq = new CreateProjectTasksQueue(workOrderLineItemIds);
      cptq.execute(null);
    } else {
      QueueableUtil.enqueueJob(new CreateProjectTasksQueue(workOrderLineItemIds));
    }
  }

  public static void deleteERPOrderTask(List<WorkOrderLineItem> wolis) {
    Set<Id> setIdTask = new Set<Id>();
    for (WorkOrderLineItem woli : wolis) {
      if (woli.ERP_Order_Task__c != null)
        setIdTask.add(woli.ERP_Order_Task__c);
    }
    if (!setIdTask.isEmpty()) {
      delete [SELECT Id FROM AcctSeed__Project_Task__c WHERE Id IN :setIdTask];
    }
  }

  private static List<AcctSeed__Project_Task__c> createFromWorkOrderLineItems(List<WorkOrderLineItem> wolis) {
    Map<Id, AcctSeed__Project_Task__c> woliId_task_map = new Map<Id, AcctSeed__Project_Task__c>();
    for (WorkOrderLineItem woli : wolis) {
      AcctSeed__Project_Task__c pt = buildFromWorkOrderLineItem(woli);
      System.debug(LoggingLevel.ERROR, 'pt:' + pt);
      woliId_task_map.put(woli.Id, pt);
    }
    insert woliId_task_map.values();
    for (WorkOrderLineItem woli : wolis) {
      woli.ERP_Order_Task__c = woliId_task_map.get(woli.Id).Id;
    }
    update wolis;
    return woliId_task_map.values();
  }

  private static AcctSeed__Project_Task__c buildFromWorkOrderLineItem(WorkOrderLineItem woli) {
    /** TODO: figure out how to handle DisplayOnCustomerInvoice **/
    String taskName = woli.WorkTypeId != null
      ? woli.WorkType.Name.left(80)
      : (woli.Description != null ? woli.Description.left(80) : 'Unknown');
    AcctSeed__Project_Task__c pTask = new AcctSeed__Project_Task__c(
      DisplayOnCustomerInvoice__c = woli.Visible_to_Customer__c,
      Name = taskName,
      Work_Order_Line_item__c = woli.Id,
      AcctSeed__Project__c = woli.WorkOrder.ERP_Order__c,
      IsFinishedGoodTask__c = true
    );
    return pTask;
  }
  // Always use in after context
  public static AcctSeed__Project_Task__c buildFromMFGWorkOrder(WorkOrder wo, WorkOrderLineItem woli) {
    return new AcctSeed__Project_Task__c(
      DisplayOnCustomerInvoice__c = woli.Visible_to_Customer__c,
      Name = 'PRE-RIG',
      Work_Order_Line_item__c = woli.Id,
      Product__c = wo.Manufacturing_Product_Id__c,
      AcctSeed__Project__c = wo.ERP_Order__c
    );
  }

  public class CreateProjectTasksQueue implements Queueable {
    public final Set<Id> recordIds;

    public CreateProjectTasksQueue(Set<Id> recordIds) {
      this.recordIds = recordIds;
    }

    public void execute(QueueableContext context) {
      ProjectTask_ServiceFSL.newFromWorkOrderLineItemIds(this.recordIds);
    }
  }
}