src/Base/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project__c/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The value selected for Tax Zone (GLV3) must be an Accounting Variable of Type 3.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 3</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>ERP Orders</relationshipLabel>
    <relationshipName>ERP_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Warehouse__c/AcctSeedERP__Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Warehouse__c/fields/GL_Account_Variable_3__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Zone (GLV3)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Tax Zone must be an Accounting Variable of Type 3.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 3</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Warehouses</relationshipLabel>
    <relationshipName>Warehouses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CommissionPayment2__c/CommissionPayment2__c.object-meta.xml
<CustomObject>
    <label>Commission Payment</label>
    <nameField>
        <displayFormat>CommPayment-{0000}</displayFormat>
        <label>Commission Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CommissionPayment2__c/fields/Commission_Record2__c.field-meta.xml
<CustomField>
    <fullName>Commission_Record2__c</fullName>
    <label>Commission Record</label>
    <referenceTo>CommissionRecord2__c</referenceTo>
    <relationshipLabel>Commission Payments</relationshipLabel>
    <relationshipName>Commission_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/objects/CommissionRecord2__c/CommissionRecord2__c.object-meta.xml
<CustomObject>
    <label>Commission Record</label>
    <nameField>
        <displayFormat>CommRec-{0000}</displayFormat>
        <label>Commission Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommissionRecord2__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Commission Records</relationshipLabel>
    <relationshipName>Commission_Records1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/GMBLASERP__Serial_Number__c.object-meta.xml
<CustomObject>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/classes/CommissionPayment2_Selector_T.cls
/**
 * Created by dave on 2020-03-25.
 */

@IsTest
private class CommissionPayment2_Selector_T
{

  static AcctSeed__Project__c project;
  static CommissionRecord2__c commissionRecord;

  @testSetup static void dataSetup()
  {
    new Factory_TestData();
    Factory_CustomSettings.setupInventorySettings();
    Account customer = Factory_Account.insertCustomerAccounts(1)[0];
    AcctSeedERP__Warehouse__c warehouse = [ SELECT Id, Name, GL_Account_Variable_3__c FROM AcctSeedERP__Warehouse__c WHERE Name = 'Whitefish'];
    GMBLASERP__Serial_Number__c serial = Factory_SerialNumber.insertFullSerial('Boat', 'Pontoon', 'test12345');
    Factory_ERPOrder.insertRetailBoatSale( customer, warehouse, DateTime.now().addMonths(1), serial );
  }

  private static void addCustomPermission(){
    CustomPermissionsReader cpr = new CustomPermissionsReader();
    Boolean hasCommissionCanSeeManagerValue = false;
    if(cpr.hasPermission('CommissionCanSeeManagerValue'))
      hasCommissionCanSeeManagerValue = true;
    if(!hasCommissionCanSeeManagerValue){
      PermissionSet ps = new PermissionSet();
      ps.Name = 'ManagersPermissionForJE';
      ps.Label = 'ManagersPermissionForJE';
      insert ps;

      SetupEntityAccess sea = new SetupEntityAccess();
      sea.ParentId = ps.Id;
      sea.SetupEntityId = [select Id from CustomPermission where DeveloperName = 'CommissionCanSeeManagerValue'][0].Id;
      insert sea;
      PermissionSetAssignment psa = new PermissionSetAssignment();
      psa.AssigneeId = UserInfo.getUserId();
      psa.PermissionSetId = ps.Id;
      insert psa;
    }
  }

  private static void init()
  {
    project = [SELECT Id FROM AcctSeed__Project__c LIMIT 1];
    commissionRecord = [SELECT Id FROM CommissionRecord2__c WHERE Project__c = :project.Id LIMIT 1];
    addCustomPermission();
  }

  @IsTest
  static void allByIds_Test()
  {
    init();
    Map<Id, CommissionPayment2__c> paymentMap = new Map<Id, CommissionPayment2__c>([
      SELECT Id FROM CommissionPayment2__c WHERE Commission_Record2__c = :commissionRecord.Id
    ]);

    Test.startTest();
    List<CommissionPayment2__c> result = CommissionPayment2_Selector.allByIds( paymentMap.keySet() );
    Test.stopTest();

    System.assertEquals( paymentMap.size(), result.size() );
  }

  @IsTest
  static void allByCommissionRecordId_Test()
  {
    init();
    List<CommissionPayment2__c> payments =
    [
      SELECT Id
      FROM CommissionPayment2__c
      WHERE Commission_Record2__c = :commissionRecord.Id
    ];

    Test.startTest();
    List<CommissionPayment2__c> result = CommissionPayment2_Selector.allByCommissionRecordId( commissionRecord.Id );
    Test.stopTest();

    System.assertEquals( payments.size(), result.size() );
  }

  @IsTest
  static void allByCommissionRecordIds_Test()
  {
    init();
    List<CommissionPayment2__c> payments =
    [
      SELECT Id
      FROM CommissionPayment2__c
      WHERE Commission_Record2__c = :commissionRecord.Id
    ];

    Test.startTest();
    List<CommissionPayment2__c> result =
      CommissionPayment2_Selector.allByCommissionRecordIds(
        new Set<Id>{commissionRecord.Id}
      );
    Test.stopTest();

    System.assertEquals( payments.size(), result.size() );
  }

  @IsTest
  static void allNewByCommissionRecordIds_Test()
  {
    init();
    List<CommissionPayment2__c> payments =
    [
      SELECT Id
      FROM CommissionPayment2__c
      WHERE Commission_Record2__c = :commissionRecord.Id
    ];

    Test.startTest();
    List<CommissionPayment2__c> result =
      CommissionPayment2_Selector.allNewByCommissionRecordIds(
        new Set<Id>{commissionRecord.Id}
      );
    Test.stopTest();

    System.assertEquals( payments.size(), result.size() );
  }
}