src/Base/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project__c/fields/AcctSeed__Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Organization for which this project exists for,</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project__c/recordTypes/BoatSale.recordType-meta.xml
<RecordType>
    <fullName>BoatSale</fullName>
    <active>true</active>
    <label>Retail Boat Sale</label>
</RecordType>

force-app/main/default/objects/AcctSeed__Project_Task__c/AcctSeed__Project_Task__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <inlineHelpText>Related Parent object.</inlineHelpText>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/AcctSeedERP__Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <displayFormat>MAT-{00000}</displayFormat>
        <label>Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Automation/main/default/classes/RetailBoatSaleFundedEvent/Tests/RetailBoatSaleFundedEvent_T.cls
/**
 * Created by dave on 2022-04-04.
 */

@IsTest
private class RetailBoatSaleFundedEvent_T {
  static Id boatSaleId;

  @testSetup
  static void dataSetup() {
    new Factory_TestData();
    Factory_CustomSettings.setupInventorySettings();
  }

  @IsTest
  static void afterInsert() {
    boatSaleId = RetailBoatSaleFunded_TestHelper.testDataCreate();
    AcctSeed__Project__c boatSale = [
      SELECT Id, Name, AcctSeed__Account__c
      FROM AcctSeed__Project__c
      WHERE Id = :boatSaleId
    ];

    List<Task> tasks = [SELECT Id FROM Task WHERE WhatId = :boatSaleId];
    Integer beforeTaskCount = tasks.size();

    Retail_Boat_Sale_Funded_Event__e evt = new Retail_Boat_Sale_Funded_Event__e(ProjectId__c = boatSaleId);

    Test.startTest();
    TriggerBase.bypass('AcctSeed__Project__c');
    TriggerBase.bypass('AcctSeed__Project_Task__c');
    TriggerBase.bypass('AcctSeedERP__Material__c');
    Database.SaveResult sr = EventBus.publish(evt);
    TriggerBase.clearAllBypasses();
    Test.stopTest();

    tasks = [SELECT Id FROM Task WHERE WhatId = :boatSaleId];

    List<AcctSeed__Project__c> accountERPs = [
      SELECT Id
      FROM AcctSeed__Project__c
      WHERE AcctSeed__Account__c = :boatSale.AcctSeed__Account__c
    ];

    System.assertEquals(true, sr.isSuccess());
    System.assertEquals(2, tasks.size() - beforeTaskCount);
    System.assertEquals(2, accountERPs.size());
  }
}