force-app/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project__c/recordTypes/Service.recordType-meta.xml
<RecordType>
    <fullName>Service</fullName>
    <active>true</active>
    <label>Legend Service Work Order</label>
</RecordType>

force-app/main/default/objects/AcctSeed__Project_Task__c/AcctSeed__Project_Task__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <inlineHelpText>Related Parent object.</inlineHelpText>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/AcctSeedERP__Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <displayFormat>MAT-{00000}</displayFormat>
        <label>Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Project_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Project_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Project_Task__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Project_Task__c.AcctSeed__Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.AcctSeedERP__Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Project_Task__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Quantity_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Quantity_Per_Unit__c</fullName>
    <label>Quantity Ordered</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/GMBLASERP__Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/Case/fields/ERP_Order__c.field-meta.xml
<CustomField>
    <fullName>ERP_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Erp order the parts are request for</description>
    <label>ERP Order</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Parts Requests</relationshipLabel>
    <relationshipName>Parts_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Part__c/Case_Part__c.object-meta.xml
<CustomObject>
    <label>Case Part</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Case Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Part__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Parts</relationshipLabel>
    <relationshipName>Case_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/objects/Case_Part__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>AcctSeedERP__Material__c</referenceTo>
    <relationshipLabel>Case Parts</relationshipLabel>
    <relationshipName>Case_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Case_Part__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Case Parts</relationshipLabel>
    <relationshipName>Case_Parts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Case_Part__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/CommissionLineItem2__c/CommissionLineItem2__c.object-meta.xml
<CustomObject>
    <label>Commission Line Item</label>
    <nameField>
        <displayFormat>CommLineItem-{0000}</displayFormat>
        <label>Commission Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CommissionLineItem2__c/fields/Commission_Rate__c.field-meta.xml
<CustomField>
    <fullName>Commission_Rate__c</fullName>
    <label>Commission Rate</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

src/Base/main/default/objects/CommissionLineItem2__c/fields/CommissionRecord2__c.field-meta.xml
<CustomField>
    <fullName>CommissionRecord2__c</fullName>
    <label>Commission Record</label>
    <referenceTo>CommissionRecord2__c</referenceTo>
    <relationshipLabel>Commission Line Items</relationshipLabel>
    <relationshipName>Commission_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CommissionLineItem2__c/fields/Labour_Cost__c.field-meta.xml
<CustomField>
    <fullName>Labour_Cost__c</fullName>
    <label>Labour Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CommissionLineItem2__c/fields/Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>Sale_Price__c</fullName>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CommissionRecord2__c/CommissionRecord2__c.object-meta.xml
<CustomObject>
    <label>Commission Record</label>
    <nameField>
        <displayFormat>CommRec-{0000}</displayFormat>
        <label>Commission Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/CommissionRecord2__c/fields/Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Calculation_Method__c</fullName>
    <label>Calculation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commission_Calculation_Method</valueSetName>
    </valueSet>
</CustomField>

src/Base/main/default/objects/CommissionRecord2__c/fields/Project_Task__c.field-meta.xml
<CustomField>
    <fullName>Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <referenceTo>AcctSeed__Project_Task__c</referenceTo>
    <relationshipLabel>Commission Records</relationshipLabel>
    <relationshipName>Commission_Records1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Commission_Rate__c.field-meta.xml
<CustomField>
    <fullName>Commission_Rate__c</fullName>
    <description>Field to set the commission percentage available</description>
    <label>Commission Rate</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

src/Base/main/default/objects/Product2/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Rigging_Time__c.field-meta.xml
<CustomField>
    <fullName>Rigging_Time__c</fullName>
    <description>Expected time to rig or prepare an item</description>
    <label>Rigging Time</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Labour.recordType-meta.xml
<RecordType>
    <fullName>Labour</fullName>
    <active>true</active>
    <description>Services</description>
    <label>Labour</label>
</RecordType>

force-app/main/default/objects/Utility_Products__c/Utility_Products__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Product Id which get used as not products ( ie Freight, Discount ... )</description>
    <label>Utility Products</label>
</CustomObject>

force-app/main/default/objects/Utility_Products__c/fields/Back_Order_Credit__c.field-meta.xml
<CustomField>
    <fullName>Back_Order_Credit__c</fullName>
    <description>The Id of the product used to offset the cost of back ordered parts</description>
    <externalId>true</externalId>
    <label>Back Order Credit</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Utility_Products__c/fields/Back_Order_Prepaid__c.field-meta.xml
<CustomField>
    <fullName>Back_Order_Prepaid__c</fullName>
    <description>The Product used on the Retail / Service ERP that represents the cost of the items that where backordered</description>
    <label>Back Ordered Prepaid</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/globalValueSets/Commission_Calculation_Method.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Revenue</fullName>
        <default>true</default>
        <label>Revenue</label>
    </customValue>
    <customValue>
        <fullName>Gross Margin</fullName>
    </customValue>
    <description>Method used to calculate Commission</description>
    <masterLabel>Commission Calculation Method</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ERP_CreatePartsBackOrder_Controller.cls
/**
 * Created by dave on 2021-03-29.
 */

public with sharing class ERP_CreatePartsBackOrder_Controller
{
  @AuraEnabled(Cacheable=true)
  public static Map<String, Object> fetchMaterials( String recordId )
  {
    Map<String, Object> result = new Map<String, Object>();
    Application_RecordType appRT = new Application_RecordType();
    Application_RecordType.ProductRTs productRts = appRT.getProductRecordTypes();
    Application_RecordType.ERPOrderRTs erpRts = appRT.getERPOrderRecordTypes();

    Utility_Products__c utilityProducts = Utility_Products__c.getOrgDefaults();
    Set<String> ignoreFamilies = new Set<String>{
      'Labour',
      'Premium Package',
      'Service Package',
      'Discount'
    };
    List<AcctSeedERP__Material__c> materials = new Material_Selector()
      .addWhere( 'AcctSeedERP__Project__c = \'' + recordId + '\'')
      .addWhereFieldNotIn( 'AcctSeedERP__Product__r.Family', ignoreFamilies, 'AND' )
      .addWhere( 'AcctSeedERP__Product__r.RecordTypeId = \'' + productRts.getPartId() + '\'' )
      .query();
    AcctSeed__Project__c project = Project_Selector.allByIdsWithTasks( new Set<Id>{Id.valueOf(recordId)} )[0];
    if( project.RecordTypeId == erpRts.getRetailBoatSaleId() )
    {
      result.put('saleType', 'retail');
    }
    if( project.RecordTypeId == erpRts.getServiceWorkOrderId() )
    {
      result.put('saleType', 'service');
    }

    result.put( 'materials', materials );
    result.put(
      'retailERP',
      project
    );
    result.put(
      'creditProductId',
      utilityProducts.Back_Order_Credit__c
    );
    result.put(
      'prepaidProductId',
      utilityProducts.Back_Order_Prepaid__c
    );
    return result;
  }

  @AuraEnabled
  public static List<Case> findPartsRequestCases(
    Id originalErpId,
    List<Id> materialIds )
  {
    List<Case> cases = Case_Selector.allByErpOrderIdIncludingCasePartsWithMaterial(
      originalErpId,
      new Set<Id>(materialIds) );
    for( Integer i=0; i<cases.size(); i++  )
    {
      if( cases[i].Case_Parts__r.size() == 0 )
      {
        cases.remove(i);
      }
    }
    return cases;
  }

  @AuraEnabled
  public static Map<String, Object> buildBackOrderERP(
    Id originalErpId,
    String transferredQuantityByMaterialId,
    String taskCause
  )
  {
    Map<Id,Decimal> quantityMap = (Map<Id,Decimal>)JSON.deserialize(
      transferredQuantityByMaterialId,
      Map<Id,Decimal>.class
    );
    Map<String, Object> result = new Map<String, Object>();
    AcctSeed__Project__c originalERP = Project_Selector.allByIdWithMaterialsById(
      new Set<Id>{ originalErpId },
      quantityMap.keySet()
    )[0];

    result.put('erp', Project_Service.buildBackOrder( originalERP ) );
    result.put('task', ProjectTask_Service.buildBackOrderTask(
      originalERP.RecordType.Name + ' - Back Order',
      taskCause
    ));
    result.put('materials', Material_Service.buildForBackOrder(
      originalERP.AcctSeedERP__Project_Materials__r,
      quantityMap
    ));
    return result;
  }

  @AuraEnabled
  public static Map<String, Object> createBackOrderERP(
    AcctSeed__Project__c erp,
    AcctSeed__Project_Task__c task,
    List<AcctSeedERP__Material__c> materials,
    List<Id> caseIds
  )
  {
    insert erp;

    task.AcctSeed__Project__c = erp.Id;
    insert task;

    for( AcctSeedERP__Material__c mat : materials )
    {
      mat.AcctSeedERP__Project__c = erp.Id;
      mat.AcctSeedERP__Project_Task__c = task.Id;
    }
    Boolean origState = gcMaterial.disableTaskLockCheck;
    gcMaterial.disableTaskLockCheck = true;
    insert materials;
    gcMaterial.disableTaskLockCheck = origState;

    if( caseIds.size() > 0 )
    {
      List<Case> updateCases = new List<Case>();
      for( Id caseId : caseIds )
      {
        updateCases.add( new Case(
          Id = caseId,
          ERP_Order__c = erp.Id
        ));
      }
      update updateCases;
    }

    Map<String, Object> result = new Map<String, Object>();
    result.put(
      'erp',
      Project_Selector.allByIds( new Set<Id>{erp.Id} )[0]
    );
    result.put(
      'task',
      task
    );
    result.put(
      'materials',
      Material_Selector.selectAllByTaskId( new Set<Id>{ task.Id} )
    );
    return result;
  }

  @AuraEnabled
  public static List<CommissionLineItem2__c> buildCommissionLines
    ( List<AcctSeedERP__Material__c>  materials)
  {
    List<CommissionLineItem2__c> result = new List<CommissionLineItem2__c>();
    Map<Id, List<AcctSeedERP__Material__c>> materialsByTaskId = new Map<Id, List<AcctSeedERP__Material__c>>();
    Set<Id> productIds = new Set<Id>();
    for( AcctSeedERP__Material__c mat : materials )
    {
      System.debug( mat.AcctSeedERP__Product__r.Name);
      System.debug( mat.AcctSeedERP__Project_Task__c);
      productIds.add( mat.AcctSeedERP__Product__c );
      if( !materialsByTaskId.containsKey( mat.AcctSeedERP__Project_Task__c ) )
      {
        materialsByTaskId.put(
          mat.AcctSeedERP__Project_Task__c,
          new List<AcctSeedERP__Material__c>()
        );
      }
      materialsByTaskId.get( mat.AcctSeedERP__Project_Task__c ).add( mat );
    }
    Map<Id, CommissionRecord2__c> comRecordIdByTaskId = new Map<Id, CommissionRecord2__c>();
    for( CommissionRecord2__c cr : CommissionRecord2_Selector.allByProjectTaskIds( materialsByTaskId.keySet() ) )
    {
      comRecordIdByTaskId.put( cr.Project_Task__c, cr );
    }
    Map<Id, PricebookEntry> pricebookEntryByProductId = new Map<Id, PricebookEntry>();
    for( PricebookEntry pbe : PricebookEntry_Selector.allFactoryEntriesByProductId( productIds ) )
    {
      pricebookEntryByProductId.put( pbe.Product2Id, pbe );
    }

    for( String taskId : materialsByTaskId.keySet() )
    {
      Decimal cost = 0;
      Decimal sale = 0;
      Decimal labour = 0;
      for( AcctSeedERP__Material__c mat : materialsByTaskId.get( taskId ) )
      {
        Decimal riggingTime;
        if( pricebookEntryByProductId.containsKey( mat.AcctSeedERP__Product__c) )
        {
          riggingTime = pricebookEntryByProductId.get(mat.AcctSeedERP__Product__c).Product2.Rigging_Time__c;
          cost += pricebookEntryByProductId.get(mat.AcctSeedERP__Product__c).UnitPrice * mat.AcctSeedERP__Quantity_Per_Unit__c;
        }
        sale += mat.GMBLASERP__Unit_Price__c * mat.AcctSeedERP__Quantity_Per_Unit__c;

        labour += riggingTime == null ? 0 : riggingTime;
      }
      Decimal rate = comRecordIdByTaskId.get( taskId ).Calculation_Method__c == 'Gross Margin' ?
        CommissionLineItem2_Service.grossMarginRate :
        CommissionLineItem2_Service.partsRate;
      result.add( new CommissionLineItem2__c(
          Comment__c = 'Parts Back Order Entry',
          CommissionRecord2__c = comRecordIdByTaskId.get( taskId ).Id,
          CommissionRecord2__r = comRecordIdByTaskId.get( taskId ),
          Cost__c = cost,
          Sale_Price__c = sale,
          Description__c = 'Parts Back Order Entry',
          Labour_Cost__c = labour * LGND_Constants.retailLabourRate,
          Quantity__c = 1,
          Commission_Rate__c = rate
        )
      );
    }
    return result;
  }

  @AuraEnabled
  public static void updateOriginalSale(
    List<Id> deleteMaterialIds,
    List<AcctSeedERP__Material__c> newMaterials,
    List<CommissionLineItem2__c> newCommissionLines
  )
  {
    Boolean disableTaskLockCheck = gcMaterial.disableTaskLockCheck;
    Boolean allowKitPartDelete = gcMaterial.allowKitPartDelete;
    Boolean disableProjectLockCheck = gcProject.disableLockedCheck;
    Boolean disableCommission = gcMaterial.disableCommission;
    gcMaterial.disableTaskLockCheck = true;
    gcMaterial.allowKitPartDelete = true;
    gcProject.disableLockedCheck = true;
    gcMaterial.disableCommission = true;
    List<AcctSeedERP__Material__c> deleteMats = new List<AcctSeedERP__Material__c>();
    for( Id matId : deleteMaterialIds )
    {
      deleteMats.add( new AcctSeedERP__Material__c(
        Id = matId
      ));
    }
    delete deleteMats;
    insert newMaterials;
    insert newCommissionLines;
    gcMaterial.disableTaskLockCheck = disableTaskLockCheck;
    gcMaterial.allowKitPartDelete =  allowKitPartDelete;
    gcProject.disableLockedCheck = disableProjectLockCheck;
    gcMaterial.disableCommission = disableCommission;
  }

}