force-app/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project_Task__c/AcctSeed__Project_Task__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__GL_Account_Variable_2__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__GL_Account_Variable_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Traditional Sub-General Ledger account segment used to report on divisions, departments, geographies, cost centers, profit centers or business units.</inlineHelpText>
    <label>GL Variable 2</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Accounting Variable must have a Type of &quot;GL Account Variable 2&quot; and must have a status of Active. One or more of these conditions have not been met.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 2</value>
        </filterItems>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Project Tasks (GL Account Variable 2)</relationshipLabel>
    <relationshipName>Project_Tasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <inlineHelpText>Related Parent object.</inlineHelpText>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/Commission_Calculation_Method__c.field-meta.xml
<CustomField>
    <fullName>Commission_Calculation_Method__c</fullName>
    <label>Commission Calculation Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Commission_Calculation_Method</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeed__Project_Task__c/fields/DisplayOnCustomerInvoice__c.field-meta.xml
<CustomField>
    <fullName>DisplayOnCustomerInvoice__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Display on Customer Invoice</label>
    <type>Checkbox</type>
</CustomField>

src/Base/main/default/globalValueSets/Commission_Calculation_Method.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Revenue</fullName>
        <default>true</default>
        <label>Revenue</label>
    </customValue>
    <customValue>
        <fullName>Gross Margin</fullName>
    </customValue>
    <description>Method used to calculate Commission</description>
    <masterLabel>Commission Calculation Method</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Factory_ERPOrderTask.cls
/**
 * Created by dave on 2020-01-29.
 */

public with sharing class Factory_ERPOrderTask
{
  public static AcctSeed__Project_Task__c buildProjectTask( Id erpId, String taskName )
  {
    return new AcctSeed__Project_Task__c(
      AcctSeed__Project__c = erpId,
      DisplayOnCustomerInvoice__c = true,
      Name = taskName
    );
  }

  public static AcctSeed__Project_Task__c buildRetailSaleTask( Id erpId )
  {
    AcctSeed__Project_Task__c task = buildProjectTask( erpId, 'Retail Sale' );
    task.AcctSeed__GL_Account_Variable_2__c = LGND_Constants.GLV2Id_Sales;
    task.Commission_Calculation_Method__c = 'Gross Margin';
    return task;
  }

  public static AcctSeed__Project_Task__c buildBusinessOfficeTask( Id erpId )
  {
    AcctSeed__Project_Task__c task = buildProjectTask( erpId, 'Business Office' );
    task.AcctSeed__GL_Account_Variable_2__c = LGND_Constants.GLV2Id_BusinessOffice;
    task.Commission_Calculation_Method__c = 'Revenue';
    return task;
  }

  public static List<AcctSeed__Project_Task__c> insertDefaultRetailBoatSaleTasks( Id erpId )
  {
    List<AcctSeed__Project_Task__c> tasks = new List<AcctSeed__Project_Task__c>{
      buildRetailSaleTask( erpId ),
      buildBusinessOfficeTask( erpId )
    };
    insert tasks;
    return tasks;
  }
}