force-app/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AcctSeed__Project_Task__c/AcctSeed__Project_Task__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <inlineHelpText>Related Parent object.</inlineHelpText>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project_Task__c/fields/GMBLASERP__Product__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parts List</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/AcctSeedERP__Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <displayFormat>MAT-{00000}</displayFormat>
        <label>Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Project_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Project_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Project_Task__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Project_Task__c.AcctSeed__Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.AcctSeedERP__Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Project_Task__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Quantity_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Quantity_Per_Unit__c</fullName>
    <label>Quantity Ordered</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/Applied_Partner_Program_Discount__c.field-meta.xml
<CustomField>
    <fullName>Applied_Partner_Program_Discount__c</fullName>
    <label>Applied Partner Program Discount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Material__c/fields/GMBLASERP__Price_Override__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Price_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Price Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/GMBLASERP__Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Dealer_Order__c/Dealer_Order__c.object-meta.xml
<CustomObject>
    <label>Dealer Order</label>
    <nameField>
        <displayFormat>DealerOrder-{0000}</displayFormat>
        <label>Dealer Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Dealer_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Account not found or not a Dealer Account</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealer Orders</relationshipLabel>
    <relationshipName>Dealer_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/Dealer_Order__c/fields/Applied_Partner_Program_Discounts__c.field-meta.xml
<CustomField>
    <fullName>Applied_Partner_Program_Discounts__c</fullName>
    <label>Applied Partner Program Discounts</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Dealer_Order__c/fields/Is_Booking_Order__c.field-meta.xml
<CustomField>
    <fullName>Is_Booking_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Booking Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dealer_Order__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dealer_Order__c/fields/Program_Year__c.field-meta.xml
<CustomField>
    <fullName>Program_Year__c</fullName>
    <label>Program Year</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dealer_Order_Line__c/Dealer_Order_Line__c.object-meta.xml
<CustomObject>
    <label>Dealer Order Line</label>
    <nameField>
        <displayFormat>DOL-{0000}</displayFormat>
        <label>Dealer Order Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/Dealer_Order_Line__c/fields/Dealer_Order__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Order__c</fullName>
    <label>Dealer Order</label>
    <referenceTo>Dealer_Order__c</referenceTo>
    <relationshipLabel>Dealer Order Lines</relationshipLabel>
    <relationshipName>Dealer_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/Base/main/default/objects/Dealer_Order_Line__c/fields/ERP_Order__c.field-meta.xml
<CustomField>
    <fullName>ERP_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ERP Order</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Dealer Order Lines</relationshipLabel>
    <relationshipName>Dealer_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Booking_Order__c/Partner_Booking_Order__c.object-meta.xml
<CustomObject>
    <label>Partner Booking Order</label>
    <nameField>
        <label>Program Year</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Booking Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/Partner_Booking_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The partner account placing this booking order</description>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dealer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Booking Orders</relationshipLabel>
    <relationshipName>Partner_Booking_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Booking_Order__c/fields/Dealer_Order__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Order__c</fullName>
    <label>Dealer Order</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Dealer Order Account must be the same as the Booking Order Account</errorMessage>
        <filterItems>
            <field>Dealer_Order__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Dealer_Order__c.Is_Booking_Order__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Dealer_Order__c</referenceTo>
    <relationshipLabel>Partner Booking Orders</relationshipLabel>
    <relationshipName>Partner_Booking_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Booking_Order__c/fields/Pontoon_Volume_Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Pontoon_Volume_Discount_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Pontoon Volume Discount Percent</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Partner_Booking_Order__c/fields/Uniquifier__c.field-meta.xml
<CustomField>
    <fullName>Uniquifier__c</fullName>
    <label>Uniquifier</label>
    <length>23</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Partner_Booking_Order__c/fields/V_Hull_Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>V_Hull_Discount_Percent__c</fullName>
    <defaultValue>0</defaultValue>
    <label>V Hull Discount Percent</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeedERP__Serialized__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Serialized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Serialized</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Stack_Size__c.field-meta.xml
<CustomField>
    <fullName>Stack_Size__c</fullName>
    <label>Stack Size</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PartnerProgram_Service.cls
/**
 * Created by dave on 2020-07-24.
 */

public with sharing class PartnerProgram_Service
{
  public Set<Id> dealerOrderIds;
  public Map<Id, Dealer_Order__c> dealerOrderMap;
  public Map<Id, DealerOrderWrapper> dealerOrderWrappers;
  public Map<String, Partner_Booking_Order__c> bookingOrderMap;
  public Map<Id, List<AcctSeed__Project__c>> erpsByDealerOrder;
  public Map<Id, Result> result;

  public class Result
  {
    public List<String> appliedDiscountNames;
    public List<Map<String, Object>> appliedDiscounts;
    public List<String> errors;
    public Decimal totalSavings;

    public Result()
    {
      this.totalSavings = 0;
      this.appliedDiscountNames = new List<String>();
      this.appliedDiscounts = new List<Map<String, Object>>();
      this.errors = new List<String>();
    }

    public void addAppliedDiscount( PartnerProgramItem_I promo )
    {
      if(promo.getResult().totalSaving != null && promo.getResult().totalSaving <> 0) {
        this.appliedDiscountNames.add(promo.getDiscountPercent() + '% - ' + promo.getName());
        this.totalSavings += promo.getResult().totalSaving == null ? 0 : promo.getResult().totalSaving;
        this.appliedDiscounts.add(new Map<String, Object>{
            'name' => promo.getName(),
            'percentage' => promo.getDiscountPercent()
        });
      }
    }

    public void addError( String err )
    {
      this.errors.add( err );
    }

  }

  public class ErpWrapper
  {
    public AcctSeed__Project__c erp;
    public Id boatId;
    public String boatFamily;
    public Decimal boatCost;
    public AcctSeedERP__Material__c boatLine;
    public List<AcctSeedERP__Material__c> allLines;
    public List<AcctSeedERP__Material__c> savingLines;

    public ErpWrapper( AcctSeed__Project__c erp )
    {
      Id boatRtId = LGND_Constants.productRtId_Boat;
      Id savingsProductId = LGND_Constants.savingsProductId;
      this.erp = erp;
      this.allLines = erp.AcctSeedERP__Project_Materials__r;
      this.savingLines = new List<AcctSeedERP__Material__c>();
      for( AcctSeedERP__Material__c mat : this.erp.AcctSeedERP__Project_Materials__r )
      {
        if(mat.AcctSeedERP__Product__r.RecordTypeId == boatRtId )
        {
          this.boatLine = mat;
          this.boatId = mat.AcctSeedERP__Product__c;
          this.boatCost = mat.GMBLASERP__Unit_Price__c;
          this.boatFamily = mat.AcctSeedERP__Product__r.Family;
        }
        if( mat.AcctSeedERP__Product__r.Id == savingsProductId )
        {
          this.savinglines.add( mat );
        }
      }
    }

    public Boolean promotionClaimed( String programItemName )
    {
      Boolean result = false;
      if( this.savingLines.size() == 0 ) return result;
      for( AcctSeedERP__Material__c mat : this.savingLines )
      {
        if( mat.Applied_Partner_Program_Discount__c == programItemName )
        {
          result = true;
          break;
        }
      }
      return result;
    }

    public AcctSeedERP__Material__c buildDiscountLine( String programItemName,
                                                       Decimal amount )
    {
      Id discountProdId = LGND_Constants.savingsProductId;
      AcctSeedERP__Material__c mat = new AcctSeedERP__Material__c(
        Id = findExistingSavingsId( programItemName ),
        AcctSeedERP__Project__c = this.erp.Id,
        AcctSeedERP__Project_Task__c = this.erp.AcctSeed__Project_Tasks__r[0].Id,
        GMBLASERP__Unit_Price__c = -1 * amount,
        GMBLASERP__Price_Override__c = true,
        AcctSeedERP__Comment__c = programItemName,
        Applied_Partner_Program_Discount__c = programItemName,
        AcctSeedERP__Product__c = discountProdId,
        AcctSeedERP__Quantity_Per_Unit__c = 1
      );
      if( mat.Id == null )
        this.allLines.add( mat );
      return mat;
    }

    private Id findExistingSavingsId( String programItemName )
    {
      Id matId = null;
      for( AcctSeedERP__Material__c mat : this.savingLines )
      {
        if( mat.Applied_Partner_Program_Discount__c == programItemName )
        {
          matId = mat.Id;
          break;
        }
      }
      return matId;
    }
  }

  public class ResultMessage
  {
    public String success;
    public List<String> errors;
    public Decimal totalSaving;
    public Account updateAccount;
    public ResultMessage()
    {
      this.errors = new List<String>();
    }
  }

  public class DealerOrderWrapper
  {
    public Dealer_Order__c dealerOrder;
    public Date createdDate;
    public Id dealerOrderId;
    public Boolean isBookingOrder;
    public Boolean isCashOrder;
    public String programYear;
    public String bookingOrderUniquifier;
    public Partner_Booking_Order__c bookingOrder;
    public PartnerProgram_Service.Result result;
    public Set<String> appliedPrograms;
    public List<PartnerProgram_Service.ErpWrapper> erpWrappers;

    public DealerOrderWrapper( Dealer_Order__c dealerOrder,
                               List<AcctSeed__Project__c> erps,
                               Partner_Booking_Order__c bookingOrder )
    {
      this.result = new PartnerProgram_Service.Result();
      this.dealerOrder = dealerOrder;
      this.appliedPrograms = new Set<String>();
      if( dealerOrder.Applied_Partner_Program_Discounts__c != null )
      {
        this.appliedPrograms = new Set<String>(
          dealerOrder.Applied_Partner_Program_Discounts__c.split(';')
        );
      }
      this.erpWrappers = new List<PartnerProgram_Service.ErpWrapper>();
      this.dealerOrderId = dealerOrder.Id;
      this.isBookingOrder = dealerOrder.Is_Booking_Order__c;
      this.isCashOrder = dealerOrder.Payment_Method__c == 'Cash';
      this.createdDate = Date.newInstance(
        dealerOrder.CreatedDate.year(),
        dealerOrder.CreatedDate.month(),
        dealerOrder.CreatedDate.day()
      );
      this.programYear = dealerOrder.Program_Year__c;
      this.bookingOrderUniquifier = this.programYear + '-' + dealerOrder.Account__c;
      if( this.isBookingOrder && bookingOrder == null )
      {
        this.bookingOrder = new Partner_Booking_Order__c(
          Dealer_Order__c = this.dealerOrderId,
          Name = this.programYear,
          Account__c = dealerOrder.Account__c
        );
      }
      else
      {
        this.bookingOrder = bookingOrder;
      }
      if( erps != null )
        wrapERPs( erps );
    }

    public void updateDealerOrder()
    {
      if( this.appliedPrograms.size() > 0 )
      {
        this.dealerOrder.Applied_Partner_Program_Discounts__c = setToMultiSelect(this.appliedPrograms);
        TriggerHandler.bypass('DealerOrder_TriggerHandler');
        update this.dealerOrder;
        TriggerHandler.clearBypass('DealerOrder_TriggerHandler');
      }
    }

    private void wrapERPs( List<AcctSeed__Project__c> erps )
    {
      for( AcctSeed__Project__c erp : erps )
      {
        PartnerProgram_Service.ErpWrapper wrapper = new PartnerProgram_Service.ErpWrapper( erp );
        this.erpWrappers.add( wrapper );
      }
    }

    private String setToMultiSelect( Set<String> names )
    {
      String result = '';
      for( String name : names )
      {
        result += name + ';';
      }
      result = result.removeEnd(';');
      return result;
    }

  }


  public PartnerProgram_Service( Set<Id> dealerOrderIds )
  {
    this.dealerOrderIds = dealerOrderIds;
    this.dealerOrderWrappers = new Map<Id, DealerOrderWrapper>();
    this.bookingOrderMap = new Map<String, Partner_Booking_Order__c>();
    this.result = new Map<Id,Result>();
    this.erpsByDealerOrder = new Map<Id, List<AcctSeed__Project__c>>();
    init();
  }

  private void init()
  {
    fetchDealerOrders();
    fetchBookingOrders();
    fetchErps();
    for( Id doId : this.dealerOrderIds )
    {
      Dealer_Order__c theDO = this.dealerOrderMap.get(doId);
      String uniq = theDO.Program_Year__c + '-' + theDO.Account__c;
      Partner_Booking_Order__c pbo = this.bookingOrderMap.containsKey( uniq ) ?
        this.bookingOrderMap.get( uniq ) : null;

      this.dealerOrderWrappers.put( doId, new DealerOrderWrapper(
        this.dealerOrderMap.get( doId ),
        this.erpsByDealerOrder.get( doId ),
        pbo
      ) );
      this.result.put( doId, new Result() );
    }
  }

  public void checkAndApply()
  {
    for( Id doId : this.dealerOrderIds )
    {
      new PartnerProgram_Executor().execute(
        this.dealerOrderWrappers.get( doId )
      );
    }
  }

  private void fetchDealerOrders()
  {
    this.dealerOrderMap = new Map<Id, Dealer_Order__c>(
      [ SELECT
          Id,
          CreatedDate,
          Is_Booking_Order__c,
          Program_Year__c,
          Account__c,
          Payment_Method__c,
          Applied_Partner_Program_Discounts__c
        FROM Dealer_Order__c
        WHERE Id IN :this.dealerOrderIds ]
    );
  }

  private void fetchBookingOrders()
  {
    Set<Id> acctIds = new Set<Id>();
    for( Dealer_Order__c dOrder : this.dealerOrderMap.values() )
    {
      acctIds.add( dOrder.Account__c );
    }
    for( Partner_Booking_Order__c pbo : [ SELECT Id,
                                                 Name,
                                                 Account__c,
                                                 Pontoon_Volume_Discount_Percent__c,
                                                 V_Hull_Discount_Percent__c,
                                                 Dealer_Order__c,
                                                 Uniquifier__c
                                          FROM Partner_Booking_Order__c
                                          WHERE Account__c IN :acctIds ])
    {
      this.bookingOrderMap.put( pbo.Uniquifier__c, pbo );
    }
  }

  private void fetchERPs()
  {
    Map<Id, Id> erpId2DealerOrderId = new Map<Id, Id>();
    for( Dealer_Order_Line__c dol : [ SELECT Id,
                                             ERP_Order__c,
                                             Dealer_Order__c
                                      FROM Dealer_Order_Line__c
                                      WHERE Dealer_Order__c IN :this.dealerOrderIds ] )
    {
      erpId2DealerOrderId.put( dol.ERP_Order__c, dol.Dealer_Order__c );
    }
    for( AcctSeed__Project__c erp : [ SELECT Id, Name,
                                      ( SELECT Id
                                        FROM AcctSeed__Project_Tasks__r ),
                                      ( SELECT Id,
                                        AcctSeedERP__Project__c,
                                        AcctSeedERP__Project_Task__c,
                                        GMBLASERP__Unit_Price__c,
                                        AcctSeedERP__Comment__c,
                                        Applied_Partner_Program_Discount__c,
                                        AcctSeedERP__Product__c,
                                        AcctSeedERP__Product__r.Id,
                                        AcctSeedERP__Product__r.Stack_Size__c,
                                        AcctSeedERP__Product__r.Name,
                                        AcctSeedERP__Product__r.RecordTypeId,
                                        AcctSeedERP__Product__r.Family,
                                        AcctSeedERP__Product__r.AcctSeedERP__Serialized__c
                                      FROM AcctSeedERP__Project_Materials__r )
                                      FROM AcctSeed__Project__c
                                      WHERE Id IN :erpId2DealerOrderId.keySet() ] )
    {
      if( !this.erpsByDealerOrder.containsKey( erpId2DealerOrderId.get(erp.Id) ) )
        this.erpsByDealerOrder.put( erpId2DealerOrderId.get(erp.Id), new List<AcctSeed__Project__c>() );
      this.erpsByDealerOrder.get( erpId2DealerOrderId.get(erp.Id) ).add( erp );
    }
  }

}