force-app/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project__c/fields/AcctSeed__Account__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Organization for which this project exists for,</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project__c/fields/GMBLASERP__Warehouse__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Warehouse__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>AcctSeedERP__Warehouse__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project_Task__c/AcctSeed__Project_Task__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <inlineHelpText>Related Parent object.</inlineHelpText>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project_Task__c/fields/GMBLASERP__Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Serial_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Serial Number</label>
    <referenceTo>GMBLASERP__Serial_Number__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/AcctSeedERP__Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <displayFormat>MAT-{00000}</displayFormat>
        <label>Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Project_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Project_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Project_Task__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Project_Task__c.AcctSeed__Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.AcctSeedERP__Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Project_Task__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Quantity_Allocated__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Quantity_Allocated__c</fullName>
    <label>Quantity Allocated</label>
    <summarizedField>AcctSeedERP__Manufacturing_Inventory_Movement__c.AcctSeedERP__Quantity__c</summarizedField>
    <summaryForeignKey>AcctSeedERP__Manufacturing_Inventory_Movement__c.AcctSeedERP__Material__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Quantity_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Quantity_Per_Unit__c</fullName>
    <label>Quantity Ordered</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Material__c/fields/GMBLASERP__Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Serial_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Serial Number</label>
    <referenceTo>GMBLASERP__Serial_Number__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Material__c/fields/GMBLASERP__Total_Price__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Total_Price__c</fullName>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/GMBLASERP__Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/Return_Parent__c.field-meta.xml
<CustomField>
    <fullName>Return_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Return Parent</label>
    <referenceTo>AcctSeedERP__Material__c</referenceTo>
    <relationshipLabel>Materials (Return Parent)</relationshipLabel>
    <relationshipName>ReturndMaterials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dealer_Order__c/Dealer_Order__c.object-meta.xml
<CustomObject>
    <label>Dealer Order</label>
    <nameField>
        <displayFormat>DealerOrder-{0000}</displayFormat>
        <label>Dealer Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealer Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/GMBLASERP__Serial_Number__c.object-meta.xml
<CustomObject>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/Partner_Program_Settings__c/Partner_Program_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Partner Program Settings</label>
</CustomObject>

force-app/main/default/objects/Product2/fields/AcctSeed__Inventory_Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Inventory_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes whether the product is a managed inventory product</description>
    <inlineHelpText>Denotes whether the product is a managed inventory product</inlineHelpText>
    <label>Inventory Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/AcctSeedERP__Serialized__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Serialized__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Serialized</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Boat.recordType-meta.xml
<RecordType>
    <fullName>Boat</fullName>
    <active>true</active>
    <label>Boat</label>
</RecordType>

force-app/main/default/classes/POSReturn_Promise_T.cls
/**
 * Created by aminrubel on 10/12/20.
 */
@IsTest
public class POSReturn_Promise_T
{
    static Partner_Program_Settings__c programSettings = Partner_Program_Settings__c.getOrgDefaults();
    static String customerAccountName = 'Dave R';
    static Account partner;
    static User partnerUser;
    static Product2 boat;
    static PricebookEntry pbe;
    static Dealer_Order__c order;
    static List<AcctSeed__Project__c> erps;
    static AcctSeed__Project__c project;

    @testSetup static void dataSetup()
    {
        new Factory_TestData();
        Factory_CustomSettings.setupInventorySettings();
        TriggerHandler.bypass('CommissionPayment2_TriggerHandler');
        TriggerHandler.bypass('CommissionRecord2_TriggerHandler');
        project = ProjectTestFactory.insertCounterSale();
        System.debug('projectm');
        System.debug(project);
    }

    @IsTest
    static void testStepOnePromise()
    {
        AcctSeed__Project__c pr = [SELECT Id, AcctSeed__Account__c, GMBLASERP__Warehouse__c FROM AcctSeed__Project__c WHERE Id =:project.Id][0];
        Id idAccount = pr.AcctSeed__Account__c;
        List<POSReturn_Promise.materialData> listMaterials = new List<POSReturn_Promise.materialData>();
        for(AcctSeedERP__Material__c matl :
        [SELECT Id,
            AcctSeedERP__Project__c,
            AcctSeedERP__Project__r.Name,
            AcctSeedERP__Product__c,
            AcctSeedERP__Product__r.RecordType.Name,
            AcctSeedERP__Product__r.AcctSeed__Inventory_Product__c,
            AcctSeedERP__Product__r.AcctSeedERP__Serialized__c,
            AcctSeedERP__Product__r.Name,
            GMBLASERP__Serial_Number__c,
            GMBLASERP__Serial_Number__r.Name,
            AcctSeedERP__Project_Task__r.Name,
            AcctSeedERP__Quantity_Per_Unit__c,
            AcctSeedERP__Quantity_Allocated__c,
            GMBLASERP__Unit_Price__c,
            GMBLASERP__Total_Price__c,
        (SELECT AcctSeedERP__Quantity_Per_Unit__c, AcctSeedERP__Quantity_Allocated__c FROM ReturndMaterials__r)
        FROM AcctSeedERP__Material__c
        WHERE AcctSeedERP__Project__c =:project.Id
        AND Return_Parent__c = null
        AND (AcctSeedERP__Product__r.AcctSeed__Inventory_Product__c = false
        OR (AcctSeedERP__Product__r.AcctSeed__Inventory_Product__c = true
        AND AcctSeedERP__Quantity_Allocated__c > 0))
        LIMIT 1])
        {
            POSReturn_Promise.materialData md = new POSReturn_Promise.materialData();
            md.matId = matl.Id;
            md.matQuantity = matl.AcctSeedERP__Quantity_Allocated__c;
            md.returnQuantity = 1;
            md.pricePerQuantity = matl.GMBLASERP__Unit_Price__c;
            md.serialized = matl.AcctSeedERP__Product__r.AcctSeedERP__Serialized__c;
            md.totalPrice = matl.GMBLASERP__Unit_Price__c;
            md.productName = matl.AcctSeedERP__Product__r.Name;
            md.projectName = matl.AcctSeedERP__Project__r.Name;
            listMaterials.add(md);
        }

        POSReturn_Promise.promiseData pd = new POSReturn_Promise.promiseData();
        pd.idAccount = idAccount;
        pd.idFilter = project.Id;
        pd.paymentMethod = 'Cash';
        pd.pIdWarehouse = pr.GMBLASERP__Warehouse__c;
        pd.allMaterials = listMaterials;
        Test.startTest();
        new POSReturn_Promise().Test_ERPTaskAndBilling(pd);
        Test.stopTest();
    }
}