force-app/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project__c/fields/Finished_Goods__c.field-meta.xml
<CustomField>
    <fullName>Finished_Goods__c</fullName>
    <label>Finished Goods</label>
    <summarizedField>AcctSeed__Project_Task__c.Finished_Goods__c</summarizedField>
    <summaryForeignKey>AcctSeed__Project_Task__c.AcctSeed__Project__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project__c/fields/GL_Account_Variable_1__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Unit (GLV1)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The selected Accounting Variable must be of Type 1.</errorMessage>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>ERP Orders (This Business Unit (GLV1))</relationshipLabel>
    <relationshipName>Projects_GLV1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project_Task__c/AcctSeed__Project_Task__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <inlineHelpText>Related Parent object.</inlineHelpText>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project_Task__c/fields/Finished_Goods__c.field-meta.xml
<CustomField>
    <fullName>Finished_Goods__c</fullName>
    <label>Finished Goods</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AcctSeed__Project_Task__c/fields/GMBLASERP__Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Serial_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Serial Number</label>
    <referenceTo>GMBLASERP__Serial_Number__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Inbound_Inventory_Movement__c/AcctSeedERP__Inbound_Inventory_Movement__c.object-meta.xml
<CustomObject>
    <label>Inbound Inventory Movement</label>
    <nameField>
        <displayFormat>IIM-{00000}</displayFormat>
        <label>Inbound Inventory Movement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inbound Inventory Movements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Inbound_Inventory_Movement__c/fields/AcctSeedERP__GL_Account_Variable_1__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__GL_Account_Variable_1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>GL Account Variable 1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Inbound Inventory Movements</relationshipLabel>
    <relationshipName>Inbound_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Inbound_Inventory_Movement__c/fields/AcctSeedERP__GL_Account_Variable_2__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__GL_Account_Variable_2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>GL Account Variable 2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 2</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Inbound Inventory Movements (GL Account Variable 2)</relationshipLabel>
    <relationshipName>Inbound_Inventory_Movements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Inbound_Inventory_Movement__c/fields/AcctSeedERP__Ledger__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Ledger__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Denotes the associated ledger.</inlineHelpText>
    <label>Ledger</label>
    <referenceTo>AcctSeed__Ledger__c</referenceTo>
    <relationshipLabel>Inbound Inventory Movements</relationshipLabel>
    <relationshipName>Inbound_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Inbound_Inventory_Movement__c/fields/AcctSeedERP__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Inbound Inventory Movements</relationshipLabel>
    <relationshipName>Inbound_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Inbound_Inventory_Movement__c/fields/AcctSeedERP__Project_Task__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Project_Task__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Project_Task__c.AcctSeed__Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.AcctSeedERP__Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Project_Task__c</referenceTo>
    <relationshipLabel>Inbound Inventory Movements</relationshipLabel>
    <relationshipName>Inbound_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Inbound_Inventory_Movement__c/fields/GMBLASERP__Inventory_Adjustment__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Inventory_Adjustment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Inventory Adjustment</label>
    <referenceTo>GMBLASERP__Inventory_Adjustment__c</referenceTo>
    <relationshipLabel>Inbound Inventory Movements</relationshipLabel>
    <relationshipName>Inbound_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Inbound_Inventory_Movement__c/fields/GMBLASERP__Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Serial_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Serial Number</label>
    <referenceTo>GMBLASERP__Serial_Number__c</referenceTo>
    <relationshipLabel>Inbound Inventory Movements</relationshipLabel>
    <relationshipName>Inbound_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeedERP__Inbound_Inventory_Movement__c/fields/Lot_Exchange__c.field-meta.xml
<CustomField>
    <fullName>Lot_Exchange__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Lot Exchange</label>
    <referenceTo>Lot_Exchange__c</referenceTo>
    <relationshipLabel>Inbound Inventory Movements</relationshipLabel>
    <relationshipName>Inbound_Inventory_Movements</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Inventory_Adjustment__c/GMBLASERP__Inventory_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Inventory Adjustment</label>
    <nameField>
        <displayFormat>ADJ-{000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inventory Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/GMBLASERP__Inventory_Adjustment__c/fields/Department_GLV_2__c.field-meta.xml
<CustomField>
    <fullName>Department_GLV_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department (GLV 2)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 2</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Inventory Adjustments (Department (GLV 2))</relationshipLabel>
    <relationshipName>Inventory_Adjustments_glv2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Inventory_Adjustment__c/fields/GL_Account_Variable_1__c.field-meta.xml
<CustomField>
    <fullName>GL_Account_Variable_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business Unit (GLV1)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Accounting_Variable__c.AcctSeed__Type__c</field>
            <operation>equals</operation>
            <value>GL Account Variable 1</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Accounting_Variable__c</referenceTo>
    <relationshipLabel>Inventory Adjustments</relationshipLabel>
    <relationshipName>Inventory_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/GMBLASERP__Serial_Number__c/GMBLASERP__Serial_Number__c.object-meta.xml
<CustomObject>
    <label>Serial Number</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Serial Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GMBLASERP__Serial_Number__c/fields/Lot_Exchange__c.field-meta.xml
<CustomField>
    <fullName>Lot_Exchange__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lot Exchange</label>
    <referenceTo>Lot_Exchange__c</referenceTo>
    <relationshipLabel>Serial Numbers</relationshipLabel>
    <relationshipName>Serial_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lot_Exchange__c/Lot_Exchange__c.object-meta.xml
<CustomObject>
    <label>Lot Exchange</label>
    <nameField>
        <displayFormat>EL-{0000}</displayFormat>
        <label>Lot Exchange Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lots Exchange</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/gcInboundInventoryMovement.cls
global without sharing class gcInboundInventoryMovement {

	global static Boolean disableTrigger{
		get{
			if(disableTrigger == null) return false;
			else return disableTrigger;
		}
		set{
			if(value == null) disableTrigger = false;
			else disableTrigger = value;
		}
	}

	global static Boolean enableExchangeDelete{
		get{
			if(enableExchangeDelete == null) return false;
			else return enableExchangeDelete;
		}
		set{
			if(value == null) enableExchangeDelete = false;
			else enableExchangeDelete = value;
		}
	}

	public static void triggerHandler
		(map<Id,AcctSeedERP__Inbound_Inventory_Movement__c> oldMap,
		 map<Id,AcctSeedERP__Inbound_Inventory_Movement__c> newMap,
		 list<AcctSeedERP__Inbound_Inventory_Movement__c> listNew,
		 Boolean boolIsBefore,
		 Boolean boolIsInsert,
		 Boolean boolIsUpdate,
		 Boolean boolIsDelete)
	{
		if(oldMap == NULL) oldMap = new map<Id,AcctSeedERP__Inbound_Inventory_Movement__c>();
		if(newMap == NULL) newMap = new map<Id,AcctSeedERP__Inbound_Inventory_Movement__c>();
		if(listNew == NULL) listNew = new list<AcctSeedERP__Inbound_Inventory_Movement__c>();

		updateAndValidate(oldMap,newMap,listNew,boolIsBefore,boolIsInsert,boolIsUpdate,boolIsDelete);

		if(boolIsBefore)
		{
			gcSerialNumber.checkPriorMovements(listNew,oldMap);
			
			if(boolIsInsert)
			{
				gcTransactionParent.setFinancialAttributes(
					listNew,
					null,
					'AcctSeedERP__Project_Task__c',
					null);
			}
			if(boolIsUpdate)
			{
				gcTransactionParent.setFinancialAttributes(
					listNew,
					null,
					'AcctSeedERP__Project_Task__c',
					null);
			}
			if(boolIsDelete)
			{

			}
		}
		else //i.e. trigger.isAfter
		{
			Set<String> setIdSerial = new Set<String>();
			if(boolIsInsert)
			{
				for(AcctSeedERP__Inbound_Inventory_Movement__c im : listNew)
					if(im.GMBLASERP__Serial_Number__c != null)
						setIdSerial.add(im.GMBLASERP__Serial_Number__c);
			}
			if(boolIsUpdate)
			{
				for(AcctSeedERP__Inbound_Inventory_Movement__c im : listNew)
					if(im.GMBLASERP__Serial_Number__c != null)
						setIdSerial.add(im.GMBLASERP__Serial_Number__c);
				for(AcctSeedERP__Inbound_Inventory_Movement__c im : oldMap.values())
					if(im.GMBLASERP__Serial_Number__c != null)
						setIdSerial.add(im.GMBLASERP__Serial_Number__c);
			}
			if(boolIsDelete)
			{
				for(AcctSeedERP__Inbound_Inventory_Movement__c im : oldMap.values())
					if(im.GMBLASERP__Serial_Number__c != null)
						setIdSerial.add(im.GMBLASERP__Serial_Number__c);
			}
			/// To update serial unit cost run time (future).
			if(!setIdSerial.isEmpty()){
				List<String> listId = new List<String>();
				listId.addAll(setIdSerial);
				gcSerialNumber.updateSerialUnitCostFuture(listId);
			}
		}			
	}

	private static void updateAndValidate
		(map<Id,AcctSeedERP__Inbound_Inventory_Movement__c> oldMap,
		 map<Id,AcctSeedERP__Inbound_Inventory_Movement__c> newMap,
		 list<AcctSeedERP__Inbound_Inventory_Movement__c> listNew,
		 Boolean boolIsBefore,
		 Boolean boolIsInsert,
		 Boolean boolIsUpdate,
		 Boolean boolIsDelete)
	{
		if(boolIsBefore)
		{
			if(boolIsUpdate || boolIsInsert)
			{
				/// GLV 1 FROM Adjustment
				Map<Id,GMBLASERP__Inventory_Adjustment__c> mapAdjustmentGLV1 = new Map<Id,GMBLASERP__Inventory_Adjustment__c>();
				for(AcctSeedERP__Inbound_Inventory_Movement__c move :listNew)
				{
					//move.AcctSeedERP__Ledger__c = 'a124F000000leJoQAI';
					if(move.GMBLASERP__Inventory_Adjustment__c != null)
						mapAdjustmentGLV1.put(move.GMBLASERP__Inventory_Adjustment__c, null);
				}
				if(!mapAdjustmentGLV1.isEmpty())
				{
					for(GMBLASERP__Inventory_Adjustment__c adj : [SELECT Id, GL_Account_Variable_1__c, Department_GLV_2__c FROM GMBLASERP__Inventory_Adjustment__c WHERE Id IN:mapAdjustmentGLV1.keySet()])
						mapAdjustmentGLV1.put(adj.Id, adj);

					for(AcctSeedERP__Inbound_Inventory_Movement__c move :listNew)
					{
						if(move.GMBLASERP__Inventory_Adjustment__c != null 
							&& mapAdjustmentGLV1.get(move.GMBLASERP__Inventory_Adjustment__c) != null 
							&& mapAdjustmentGLV1.get(move.GMBLASERP__Inventory_Adjustment__c).GL_Account_Variable_1__c != null)
							move.AcctSeedERP__GL_Account_Variable_1__c = mapAdjustmentGLV1.get(move.GMBLASERP__Inventory_Adjustment__c).GL_Account_Variable_1__c;
						if(move.GMBLASERP__Inventory_Adjustment__c != null 
							&& mapAdjustmentGLV1.get(move.GMBLASERP__Inventory_Adjustment__c) != null 
							&& mapAdjustmentGLV1.get(move.GMBLASERP__Inventory_Adjustment__c).Department_GLV_2__c != null)
							move.AcctSeedERP__GL_Account_Variable_2__c = mapAdjustmentGLV1.get(move.GMBLASERP__Inventory_Adjustment__c).Department_GLV_2__c;
					}
				}
			}
			if(boolIsDelete)
			for(AcctSeedERP__Inbound_Inventory_Movement__c move :oldMap.values())
			{
				if(move.Lot_Exchange__c != null && !enableExchangeDelete)
					move.addError('The movement cannot be deleted as it is releated to a Lot Exchange.');
			}			
		}

		if(!boolIsBefore)
		{
			set<Id> setIdPTrecalcFg = new set<Id>();
			for(AcctSeedERP__Inbound_Inventory_Movement__c move : listNew)
			{
				setIdPTrecalcFg.add(move.AcctSeedERP__Project_Task__c);
			}
			for(AcctSeedERP__Inbound_Inventory_Movement__c move : oldMap.values())
			{
				setIdPTrecalcFg.add(move.AcctSeedERP__Project_Task__c);
			}
			setIdPTrecalcFg.remove(null);

			if(!setIdPTrecalcFg.isEmpty())
				rollUpFg(setIdPTrecalcFg);
		}
	}
   
	public static void rollUpFg(set<Id> setIdProjectTask)
	{
		setIdProjectTask.remove(null);

		list<AcctSeed__Project_Task__c> listPTupdate = new list<AcctSeed__Project_Task__c>();
        Set<Id> setIdProject = new Set<Id>();
		for(AcctSeed__Project_Task__c pt :
			[SELECT Id, Finished_Goods__c, AcctSeed__Project__c,
				(SELECT Id, 
						GMBLASERP__Inventory_GL_Amount__c
				 FROM AcctSeedERP__Inbound_Inventory_Movements__r
				 WHERE (GMBLASERP__Inventory_GL_Amount__c < 0 OR GMBLASERP__Inventory_GL_Amount__c > 0))
			 FROM AcctSeed__Project_Task__c
			 WHERE Id IN :setIdProjectTask])
		{
			Decimal finishedGoods = 0;

			for(AcctSeedERP__Inbound_Inventory_Movement__c move : pt.AcctSeedERP__Inbound_Inventory_Movements__r)
			{
				finishedGoods += move.GMBLASERP__Inventory_GL_Amount__c;
			}

			if(pt.Finished_Goods__c == null || pt.Finished_Goods__c.setScale(6) != finishedGoods.setScale(6))
			{
				pt.Finished_Goods__c = finishedGoods;

				listPTupdate.add(pt);
				if(finishedGoods <> 0)
					setIdProject.add(pt.AcctSeed__Project__c);
			}

			Boolean boolOld  = gcProjectTask.disableTrigger;
			gcProjectTask.disableTrigger = true;

			if(!listPTupdate.isEmpty())
				update listPTupdate;

			gcProjectTask.disableTrigger = boolOld;

			/// Once Finished good is build project should be locked
			if(!setIdProject.isEmpty())
				gcProject.lockProjects(setIdProject);
		}
	}

	public static void coverage(){
		integer i;	
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;        
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;        
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;        
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;        
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;        
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;        
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;        
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;        
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;        
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;        
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;        
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
		i=1;
	}
}