src/Base/main/default/objects/Account/fields/AccountEmail__c.field-meta.xml
<CustomField>
    <fullName>AccountEmail__c</fullName>
    <label>Account Email</label>
    <type>Email</type>
</CustomField>

src/Base/main/default/objects/Account/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <description>Animals they have or like</description>
    <label>Animals</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cat(s)</fullName>
            </value>
            <value>
                <fullName>Dog(s)</fullName>
            </value>
            <value>
                <fullName>Lizard(s)</fullName>
            </value>
            <value>
                <fullName>Snake(s)</fullName>
            </value>
            <value>
                <fullName>Turtle(s)</fullName>
            </value>
            <value>
                <fullName>Fish</fullName>
            </value>
            <value>
                <fullName>Bird(s)</fullName>
            </value>
            <value>
                <fullName>Hamster(s)</fullName>
            </value>
            <value>
                <fullName>Gerbil(s)</fullName>
            </value>
            <value>
                <fullName>Guinea Pig(s)</fullName>
            </value>
            <value>
                <fullName>Rat(s)</fullName>
            </value>
            <value>
                <fullName>Ferret(s)</fullName>
            </value>
            <value>
                <fullName>Rabbit(s)</fullName>
            </value>
            <value>
                <fullName>Pig(s)</fullName>
            </value>
            <value>
                <fullName>Cow(s)</fullName>
            </value>
            <value>
                <fullName>Horse(s)</fullName>
            </value>
            <value>
                <fullName>Sheep</fullName>
            </value>
            <value>
                <fullName>Other (add in WOW Notes)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Account/fields/Emotional_Motivation__c.field-meta.xml
<CustomField>
    <fullName>Emotional_Motivation__c</fullName>
    <description>To aid in Marketing Development and WOW Notes</description>
    <inlineHelpText>Check all the applicable emotional motivations that apply to your customer.  This will aid in Marketing Development and your WOW! Notes</inlineHelpText>
    <label>Emotional Motivation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cruising</fullName>
            </value>
            <value>
                <fullName>Fishing</fullName>
            </value>
            <value>
                <fullName>Hanging out with buddies</fullName>
            </value>
            <value>
                <fullName>Relaxing</fullName>
            </value>
            <value>
                <fullName>Spending time with family</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Hobbies__c.field-meta.xml
<CustomField>
    <fullName>Hobbies__c</fullName>
    <description>Used to aid in Marketing Development and WOW Notes</description>
    <inlineHelpText>Please check off the hobbies your customer noted.  This is to aid in Marketing Development and your WOW! Notes</inlineHelpText>
    <label>Hobbies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ATV</fullName>
            </value>
            <value>
                <fullName>Boating</fullName>
            </value>
            <value>
                <fullName>Camping</fullName>
            </value>
            <value>
                <fullName>Computers</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Cottage</fullName>
            </value>
            <value>
                <fullName>Family Time</fullName>
            </value>
            <value>
                <fullName>Fishing</fullName>
            </value>
            <value>
                <fullName>Hunting</fullName>
            </value>
            <value>
                <fullName>Ice Fishing</fullName>
            </value>
            <value>
                <fullName>Movies</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>Skiing</fullName>
            </value>
            <value>
                <fullName>Sledding</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
            <value>
                <fullName>Water Skiing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Internal__c.field-meta.xml
<CustomField>
    <fullName>Is_Internal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Internal?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Children__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Children__c</fullName>
    <description>Used to aid in Marketing Development and WOW Notes</description>
    <inlineHelpText>Enter the number of children the customer has to aid in Marketing Development and your WOW! Notes</inlineHelpText>
    <label>Number of Children</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Account/fields/Occupation__c.field-meta.xml
<CustomField>
    <fullName>Occupation__c</fullName>
    <description>What do they do for a living?</description>
    <label>Occupation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <label>Preferred_Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Preferred_Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <description>Used to assist in Marketing Data as well as WOW information</description>
    <inlineHelpText>Let us know the relationship status of the customer to aid in our Marketing development</inlineHelpText>
    <label>Relationship Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>In a Relationship</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Account/fields/Teams__c.field-meta.xml
<CustomField>
    <fullName>Teams__c</fullName>
    <description>The Team(s) that they follow and how involved/passionate they are</description>
    <label>Teams</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tow_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Tow_Vehicle__c</fullName>
    <description>To aid in Marketing Development and WOW Notes</description>
    <inlineHelpText>Check the box indicating what your customer plans to tow their new boat with. This will aid in Marketing Development and your WOW! Notes</inlineHelpText>
    <label>Tow Vehicle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Car</fullName>
            </value>
            <value>
                <fullName>Minivan</fullName>
            </value>
            <value>
                <fullName>Pick Up Truck</fullName>
            </value>
            <value>
                <fullName>SUV</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Preferred_Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>English</fullName>
        <default>true</default>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>Afrikaans</fullName>
    </customValue>
    <customValue>
        <fullName>Albanian</fullName>
    </customValue>
    <customValue>
        <fullName>Albanian - Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Iraq</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Libya</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Morocco</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Qatar</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Saudi Arabia</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Sudan</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Syria</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Tunisia</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - United Arab Emirates</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Yemen</fullName>
    </customValue>
    <customValue>
        <fullName>Armenian</fullName>
    </customValue>
    <customValue>
        <fullName>Basque</fullName>
    </customValue>
    <customValue>
        <fullName>Belarusian</fullName>
    </customValue>
    <customValue>
        <fullName>Belarusian - Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgarian - Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Catalan</fullName>
    </customValue>
    <masterLabel>Preferred Language</masterLabel>
</GlobalValueSet>

src/Base/main/default/classes/Account_Selector.cls
/**
 * Created by dave on 2020-06-09.
 */

public virtual class Account_Selector extends Application_Selector
{

  private final List<String> defaultFields = new List<String>{
    'Id',
    'RecordTypeId',
    'Name',
    'Phone',
    'BillingStreet',
    'BillingCity',
    'BillingState',
    'BillingStateCode',
    'BillingCountry',
    'BillingCountryCode',
    'BillingPostalCode'
  };

  private final List<String> defaultPersonFields = new List<String>{
    'PersonEmail',
    'FirstName',
    'LastName',
    'PersonHomePhone',
    'PersonMobilePhone',
    'PersonOtherPhone',
    'Preferred_Language__c',
    'Relationship_Status__c',
    'Number_Of_Children__c',
    'Hobbies__c',
    'Emotional_Motivation__c',
    'Occupation__c',
    'Animals__c',
    'Teams__c',
    'Tow_Vehicle__c',
    'WOW_Notes__pc',
    'Gender__pc',
    'Tax_Exempt_Status_Card_Number__pc'
  };

  private final List<String> defaultBusinessFields = new List<String>{
    'AccountEmail__c',
    'Fax',
    'ShippingStreet',
    'ShippingCity',
    'ShippingState',
    'ShippingStateCode',
    'ShippingCountry',
    'ShippingCountryCode',
    'ShippingPostalCode'
  };

  private final List<String> defaultDealerFields = new List<String>{
    'Is_Internal__c'
  };

  public Account_Selector()
  {
    this.sObjectName = 'Account';
    this.fields = defaultFields;
  }


  public virtual class PersonAccount_Selector extends Account_Selector
  {
    public PersonAccount_Selector()
    {
      super();
      this.fields.addAll( defaultPersonFields );
    }
  }

  public virtual class DealerAccount_Selector extends Account_Selector
  {
    public DealerAccount_Selector()
    {
      super();
      Id rtId = new Application_RecordType()
        .getAccountRecordTypes()
        .getDealerId();
      this.fields.addAll( defaultDealerFields );
      this.addWhere('RecordTypeId =\'' + rtId + '\'');
    }
  }

  public virtual class BusinessAccount_Selector extends Account_Selector
  {
    public BusinessAccount_Selector()
    {
      super();
      this.fields.addAll( defaultBusinessFields );
    }
  }


  public static Account[] allByIds( Set<Id> ids )
  {
    PersonAccount_Selector selector = new PersonAccount_Selector();
    selector.addWhereIdIn( ids );
    return selector.query();
  }

  public static Account[] allPersonAccountsByIds( Set<Id> ids )
  {
    PersonAccount_Selector selector = new PersonAccount_Selector();
    selector.addWhereIdIn( ids );
    return selector.query();
  }

  public static Account personAccountById( Id recordId )
  {
    List<Account> result = allPersonAccountsByIds(
      new Set<Id>{recordId}
    );
    if( result.size() == 0 )
    {
      String msg = 'No Account record found with supplied Id';
      Application_Selector.SelectorException ex =
        new Application_Selector.SelectorException( msg );
      ex.setMessage(msg);
      throw ex;
    }
    else
    {
      return result[0];
    }
  }

  public static Account[] allActiveDealers()
  {
    return new DealerAccount_Selector()
      .addWhere('Active__c = true')
      .query();
  }

  public static Account businessAccountWithContactsById( Id recordId )
  {
    BusinessAccount_Selector selector = new BusinessAccount_Selector();
    selector.addWhereIdIn( new Set<Id>{ recordId } )
    .addChildQuery(
      '(SELECT Id, FirstName, LastName, Email, Phone, MobilePhone, Title FROM Contacts)'
    );
    List<SObject> result = selector.query();
    if( result.size() == 0 )
    {
      throw new Application_Selector.SelectorException(
        'No Account record found with supplied Id'
      );
    }
    else
    {
      return (Account)result[0];
    }
  }


}