src/Base/main/default/objects/Account/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <description>Animals they have or like</description>
    <label>Animals</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cat(s)</fullName>
            </value>
            <value>
                <fullName>Dog(s)</fullName>
            </value>
            <value>
                <fullName>Lizard(s)</fullName>
            </value>
            <value>
                <fullName>Snake(s)</fullName>
            </value>
            <value>
                <fullName>Turtle(s)</fullName>
            </value>
            <value>
                <fullName>Fish</fullName>
            </value>
            <value>
                <fullName>Bird(s)</fullName>
            </value>
            <value>
                <fullName>Hamster(s)</fullName>
            </value>
            <value>
                <fullName>Gerbil(s)</fullName>
            </value>
            <value>
                <fullName>Guinea Pig(s)</fullName>
            </value>
            <value>
                <fullName>Rat(s)</fullName>
            </value>
            <value>
                <fullName>Ferret(s)</fullName>
            </value>
            <value>
                <fullName>Rabbit(s)</fullName>
            </value>
            <value>
                <fullName>Pig(s)</fullName>
            </value>
            <value>
                <fullName>Cow(s)</fullName>
            </value>
            <value>
                <fullName>Horse(s)</fullName>
            </value>
            <value>
                <fullName>Sheep</fullName>
            </value>
            <value>
                <fullName>Other (add in WOW Notes)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Account/fields/Emotional_Motivation__c.field-meta.xml
<CustomField>
    <fullName>Emotional_Motivation__c</fullName>
    <description>To aid in Marketing Development and WOW Notes</description>
    <inlineHelpText>Check all the applicable emotional motivations that apply to your customer.  This will aid in Marketing Development and your WOW! Notes</inlineHelpText>
    <label>Emotional Motivation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cruising</fullName>
            </value>
            <value>
                <fullName>Fishing</fullName>
            </value>
            <value>
                <fullName>Hanging out with buddies</fullName>
            </value>
            <value>
                <fullName>Relaxing</fullName>
            </value>
            <value>
                <fullName>Spending time with family</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Financing_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Financing_Vendor__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This indicates the account as one of our Financing Institutions.  This will populate the Financing Institution select list in the Business Office form on the Retail Boat Sale ERP</description>
    <inlineHelpText>This indicates the account as one of our Financing Institutions.  This will populate the Financing Institution select list in the Business Office form on the Retail Boat Sale ERP</inlineHelpText>
    <label>Financing Vendor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Hobbies__c.field-meta.xml
<CustomField>
    <fullName>Hobbies__c</fullName>
    <description>Used to aid in Marketing Development and WOW Notes</description>
    <inlineHelpText>Please check off the hobbies your customer noted.  This is to aid in Marketing Development and your WOW! Notes</inlineHelpText>
    <label>Hobbies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ATV</fullName>
            </value>
            <value>
                <fullName>Boating</fullName>
            </value>
            <value>
                <fullName>Camping</fullName>
            </value>
            <value>
                <fullName>Computers</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Cottage</fullName>
            </value>
            <value>
                <fullName>Family Time</fullName>
            </value>
            <value>
                <fullName>Fishing</fullName>
            </value>
            <value>
                <fullName>Hunting</fullName>
            </value>
            <value>
                <fullName>Ice Fishing</fullName>
            </value>
            <value>
                <fullName>Movies</fullName>
            </value>
            <value>
                <fullName>RV</fullName>
            </value>
            <value>
                <fullName>Skiing</fullName>
            </value>
            <value>
                <fullName>Sledding</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
            <value>
                <fullName>Water Skiing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Children__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Children__c</fullName>
    <description>Used to aid in Marketing Development and WOW Notes</description>
    <inlineHelpText>Enter the number of children the customer has to aid in Marketing Development and your WOW! Notes</inlineHelpText>
    <label>Number of Children</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/Base/main/default/objects/Account/fields/Occupation__c.field-meta.xml
<CustomField>
    <fullName>Occupation__c</fullName>
    <description>What do they do for a living?</description>
    <label>Occupation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Preferred_Language__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Language__c</fullName>
    <label>Preferred_Language</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Preferred_Language</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Relationship_Status__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Status__c</fullName>
    <description>Used to assist in Marketing Data as well as WOW information</description>
    <inlineHelpText>Let us know the relationship status of the customer to aid in our Marketing development</inlineHelpText>
    <label>Relationship Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>In a Relationship</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/Base/main/default/objects/Account/fields/Teams__c.field-meta.xml
<CustomField>
    <fullName>Teams__c</fullName>
    <description>The Team(s) that they follow and how involved/passionate they are</description>
    <label>Teams</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tow_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Tow_Vehicle__c</fullName>
    <description>To aid in Marketing Development and WOW Notes</description>
    <inlineHelpText>Check the box indicating what your customer plans to tow their new boat with. This will aid in Marketing Development and your WOW! Notes</inlineHelpText>
    <label>Tow Vehicle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Car</fullName>
            </value>
            <value>
                <fullName>Minivan</fullName>
            </value>
            <value>
                <fullName>Pick Up Truck</fullName>
            </value>
            <value>
                <fullName>SUV</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Dealer.recordType-meta.xml
<RecordType>
    <fullName>Dealer</fullName>
    <active>true</active>
    <label>Dealer</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <description>Suppliers</description>
    <label>Supplier</label>
</RecordType>

force-app/main/default/globalValueSets/Preferred_Language.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>English</fullName>
        <default>true</default>
        <label>English</label>
    </customValue>
    <customValue>
        <fullName>French</fullName>
    </customValue>
    <customValue>
        <fullName>Afrikaans</fullName>
    </customValue>
    <customValue>
        <fullName>Albanian</fullName>
    </customValue>
    <customValue>
        <fullName>Albanian - Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Egypt</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Iraq</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Jordan</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Kuwait</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Lebanon</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Libya</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Morocco</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Oman</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Qatar</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Saudi Arabia</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Sudan</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Syria</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Tunisia</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - United Arab Emirates</fullName>
    </customValue>
    <customValue>
        <fullName>Arabic - Yemen</fullName>
    </customValue>
    <customValue>
        <fullName>Armenian</fullName>
    </customValue>
    <customValue>
        <fullName>Basque</fullName>
    </customValue>
    <customValue>
        <fullName>Belarusian</fullName>
    </customValue>
    <customValue>
        <fullName>Belarusian - Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgarian</fullName>
    </customValue>
    <customValue>
        <fullName>Bulgarian - Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>Catalan</fullName>
    </customValue>
    <masterLabel>Preferred Language</masterLabel>
</GlobalValueSet>

src/Base/main/default/classes/UnitTestFactories/Factory_Account.cls
@isTest
public class Factory_Account {
  public static Account[] buildDealerAccounts(Integer count) {
    return buildAccounts(count, 'Dealer');
  }

  public static Account[] insertDealerAccounts(Integer count) {
    return insertAccounts(count, 'Dealer');
  }

  public static Account[] insertSupplierAccounts(Integer count) {
    return insertAccounts(count, 'Supplier');
  }

  public static Account[] insertFinancialInstitutions(Integer count) {
    Account[] result = new List<Account>();
    for (Account acct : buildAccounts(count, 'Supplier')) {
      acct.Financing_Vendor__c = true;
      result.add(acct);
    }
    insert result;
    return result;
  }

  public static Account[] insertCustomerAccounts(Integer count) {
    String aType = 'Person Account';
    Id rtId = LGND_Utilities.recordTypeIdFromName('Account', aType);
    Account[] result = new List<Account>();
    for (Integer i = 0; i < count; i++) {
      result.add(
        new Account(
          RecordTypeId = rtId,
          FirstName = aType,
          LastName = aType + ' - ' + String.valueOf(i),
          Type = aType,
          PersonEmail = 'noemail@legendboats.com'
        )
      );
    }
    insert result;
    return result;
  }

  public static Account[] buildAccounts(Integer count, String aType) {
    Id rtId = LGND_Utilities.recordTypeIdFromName('Account', aType);
    Account[] result = new List<Account>();
    for (Integer i = 0; i < count; i++) {
      result.add(
        new Account(RecordTypeId = rtId, Name = aType + ' - ' + String.valueOf(i), Type = aType, Active__c = true)
      );
    }
    return result;
  }

  private static Account[] insertAccounts(Integer count, String aType) {
    Account[] result = buildAccounts(count, aType);
    insert result;
    return result;
  }

  public static Account insertAccountWithContacts(String name, Id acctRecordTypeId, Integer contactCount) {
    Account a = new Account(
      RecordTypeId = acctRecordTypeId,
      Name = name,
      Phone = '111-111-1111',
      Fax = '222-222-2222',
      BillingStreet = '1 Test Street',
      BillingCity = 'Test City',
      BillingState = 'Ontario',
      BillingCountry = 'Canada',
      BillingPostalCode = 'a1b 2c3',
      ShippingStreet = '2 Test Street',
      ShippingCity = 'Test City',
      ShippingState = 'Ontario',
      ShippingCountry = 'Canada',
      ShippingPostalCode = 'a2b 5c6'
    );
    insert a;
    Contact[] conts = new List<Contact>();
    for (Integer i = 0; i < contactCount; i++) {
      conts.add(
        Factory_Contact.newContact(a.Id, 'contFirstName' + String.valueOf(i), 'contLastName' + String.valueOf(i))
      );
    }
    insert conts;
    return a;
  }

  public static Account insertBusinessAccountWithContacts(String name, Integer contactCount) {
    Id rTid = new Application_RecordType().getAccountRecordTypes().getBusinessAccountId();
    return insertAccountWithContacts(name, rTid, contactCount);
  }

  public static Account insertSupplierAccountWithContacts(String name, Integer contactCount) {
    Id rTid = new Application_RecordType().getAccountRecordTypes().getSupplierId();
    return insertAccountWithContacts(name, rTid, contactCount);
  }

  public static Account buildFullPersonAccount(String fName, String lName) {
    String[] hobbies = LGND_Utilities.getPicklistValues('Account', 'Hobbies__c');
    String[] emoMoto = LGND_Utilities.getPicklistValues('Account', 'Emotional_Motivation__c');
    String[] animals = LGND_Utilities.getPicklistValues('Account', 'Animals__c');
    String[] towVehicles = LGND_Utilities.getPicklistValues('Account', 'Tow_Vehicle__c');
    String[] relStatuses = LGND_Utilities.getPicklistValues('Account', 'Relationship_Status__c');
    String[] langs = LGND_Utilities.getPicklistValues('Account', 'Preferred_Language__c');
    String[] genders = LGND_Utilities.getPicklistValues('Account', 'Gender__pc');
    Id rTid = LGND_Utilities.recordTypeIdFromName('Account', 'Person Account');

    return new Account(
      RecordTypeId = rTid,
      FirstName = fName,
      LastName = lName,
      PersonEmail = fname.toLowerCase() + '@' + lname.toLowerCase() + '.com',
      Phone = '111-111-1111',
      PersonMobilePhone = '222-222-2222',
      Gender__pc = genders[0],
      Preferred_Language__c = langs[0],
      Relationship_Status__c = relStatuses[0],
      Number_Of_Children__c = 2,
      Occupation__c = 'Code Wizard',
      Tow_Vehicle__c = towVehicles[0],
      Emotional_Motivation__c = emoMoto[0],
      Hobbies__c = hobbies[0],
      Animals__c = animals[0],
      Teams__c = 'No Sports',
      BillingStreet = '139 Fittons Rd West',
      BillingCity = 'Orillia',
      BillingState = 'Ontario',
      BillingCountry = 'Canada',
      BillingPostalCode = 'L3V 3V3'
    );
  }

  public static Account insertFullPersonAccount(String fName, String lName) {
    Account a = buildFullPersonAccount(fName, lName);
    insert a;
    return a;
  }
}