src/Base/main/default/objects/Account/fields/GMBLASERP__Pricebook__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Pricebook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pricebook</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project__c/AcctSeed__Project__c.object-meta.xml
<CustomObject>
    <description>Used to document and track time, expense, and revenue associated with projects.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeed__Project__c/fields/GMBLASERP__Pricebook__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Pricebook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/AcctSeed__Project__c/recordTypes/Service.recordType-meta.xml
<RecordType>
    <fullName>Service</fullName>
    <active>true</active>
    <label>Legend Service Work Order</label>
</RecordType>

force-app/main/default/objects/AcctSeed__Project_Task__c/AcctSeed__Project_Task__c.object-meta.xml
<CustomObject>
    <description>Used to document a specific task associated with a project. Aggregations of project tasks constitute a project.</description>
    <label>Project Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/AcctSeed__Project_Task__c/fields/AcctSeed__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeed__Project__c</fullName>
    <inlineHelpText>Related Parent object.</inlineHelpText>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Project Tasks</relationshipLabel>
    <relationshipName>Project_Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/AcctSeedERP__Material__c.object-meta.xml
<CustomObject>
    <label>Material</label>
    <nameField>
        <displayFormat>MAT-{00000}</displayFormat>
        <label>Material Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Product__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Project_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Project__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>AcctSeed__Project__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Project_Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Project_Task__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AcctSeed__Project_Task__c.AcctSeed__Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.AcctSeedERP__Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AcctSeed__Project_Task__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/AcctSeedERP__Quantity_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>AcctSeedERP__Quantity_Per_Unit__c</fullName>
    <label>Quantity Ordered</label>
    <precision>18</precision>
    <required>true</required>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/GMBLASERP__Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>GMBLASERP__Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AcctSeedERP__Material__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>AcctSeedERP__Material__c</referenceTo>
    <relationshipLabel>Materials</relationshipLabel>
    <relationshipName>Materials</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/CommissionLineItem2__c/CommissionLineItem2__c.object-meta.xml
<CustomObject>
    <label>Commission Line Item</label>
    <nameField>
        <displayFormat>CommLineItem-{0000}</displayFormat>
        <label>Commission Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/CommissionLineItem2__c/fields/CommissionRecord2__c.field-meta.xml
<CustomField>
    <fullName>CommissionRecord2__c</fullName>
    <label>Commission Record</label>
    <referenceTo>CommissionRecord2__c</referenceTo>
    <relationshipLabel>Commission Line Items</relationshipLabel>
    <relationshipName>Commission_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CommissionLineItem2__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>AcctSeedERP__Material__c</referenceTo>
    <relationshipLabel>Commission Line Items</relationshipLabel>
    <relationshipName>Commission_Line_Items2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CommissionLineItem2__c/fields/Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>Sale_Price__c</fullName>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/CommissionLineItem__c/CommissionLineItem__c.object-meta.xml
<CustomObject>
    <label>Commission Line Item</label>
    <nameField>
        <label>Commission Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commission Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/Base/main/default/objects/CommissionLineItem__c/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>AcctSeedERP__Material__c</referenceTo>
    <relationshipLabel>Commission Line Items</relationshipLabel>
    <relationshipName>Commission_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

src/Base/main/default/objects/CommissionLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Commission Line Items</relationshipLabel>
    <relationshipName>Commission_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CommissionLineItem__c/fields/Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>Sale_Price__c</fullName>
    <label>Sale_Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/Base/main/default/objects/CommissionRecord2__c/CommissionRecord2__c.object-meta.xml
<CustomObject>
    <label>Commission Record</label>
    <nameField>
        <displayFormat>CommRec-{0000}</displayFormat>
        <label>Commission Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commission Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/Base/main/default/objects/CommissionRecord2__c/fields/Project_Task__c.field-meta.xml
<CustomField>
    <fullName>Project_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Task</label>
    <referenceTo>AcctSeed__Project_Task__c</referenceTo>
    <relationshipLabel>Commission Records</relationshipLabel>
    <relationshipName>Commission_Records1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Legend_Settings__c/Legend_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Legend Settings</label>
</CustomObject>

force-app/main/default/objects/Legend_Settings__c/fields/Default_Retail_Pricebook__c.field-meta.xml
<CustomField>
    <fullName>Default_Retail_Pricebook__c</fullName>
    <label>Default Retail Pricebook</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/Base/main/default/objects/Product2/recordTypes/Part.recordType-meta.xml
<RecordType>
    <fullName>Part</fullName>
    <active>true</active>
    <description>Part</description>
    <label>Part</label>
</RecordType>

src/Base/main/default/classes/CommissionLineItem2_Service_T.cls
/**
 * Created by dave on 2020-01-30.
 */

@IsTest
private class CommissionLineItem2_Service_T
{
  static Integer partsCount = 4;

  @testSetup static void dataSetup()
  {
    new Factory_TestData();
    Factory_CustomSettings.setupInventorySettings();
    List<Product2> parts = Factory_Product.createNonSerializedProducts('Part', 'Hardware', partsCount );
    Factory_PricebookEntry.createAllDefaultEntriesEntries( parts, 100 );
    List<AcctSeed__Project__c> projects = new List<AcctSeed__Project__c>();
    for( Account customer : Factory_Account.insertCustomerAccounts(4) )
    {
      AcctSeed__Project__c project = Factory_ERPOrder.buildERP( customer, null, gcConstants.idRtProjectBoatSale );
      project.GMBLASERP__Pricebook__c = Legend_Settings__c.getOrgDefaults().Default_Retail_Pricebook__c;
      projects.add( project );
    }
    insert projects;
    List<AcctSeed__Project_Task__c> tasks = new List<AcctSeed__Project_Task__c>();
    for( AcctSeed__Project__c project : projects )
    {
      tasks.add( Factory_ERPOrderTask.buildRetailSaleTask( project.Id ) );
    }
    Boolean orig = gcProjectTask.ignoreCommissions;
    gcProjectTask.ignoreCommissions = true;
    insert tasks;
    gcProjectTask.ignoreCommissions = orig;
    List<CommissionRecord2__c> commissionRecords = new List<CommissionRecord2__c>();
    List<AcctSeedERP__Material__c> materials = new List<AcctSeedERP__Material__c>();
    for( AcctSeed__Project_Task__c task : tasks )
    {
      commissionRecords.add( new CommissionRecord2__c(
        Project_Task__c = task.Id
      ));
      for( Product2 p : parts )
      {
        materials.add( new AcctSeedERP__Material__c(
          AcctSeedERP__Project_Task__c = task.Id,
          AcctSeedERP__Quantity_Per_Unit__c = 1,
          GMBLASERP__Unit_Price__c = 200,
          AcctSeedERP__Product__c = p.Id,
          AcctSeedERP__Project__c = task.AcctSeed__Project__c
        ));
      }
    }
    insert commissionRecords;
    insert materials;
  }


  @IsTest
  static void saveRecords_New_Test()
  {
    List<AcctSeedERP__Material__c> materials = [ SELECT Id,
                                                        AcctSeedERP__Project_Task__c,
                                                        AcctSeedERP__Product__c,
                                                        AcctSeedERP__Quantity_Per_Unit__c,
                                                        GMBLASERP__Unit_Price__c
                                                  FROM AcctSeedERP__Material__c ];
    System.debug( 'Material Size = ' + materials.size());
    Test.startTest();
    CommissionLineItem2_Service service = new CommissionLineItem2_Service();
    service.addMaterials( materials );
    service.saveRecords();
    Test.stopTest();

    List<CommissionRecord2__c> commissionRecords = [ SELECT Id,
                                                    ( SELECT Id FROM Commission_Line_Items__r )
                                                    FROM CommissionRecord2__c ];
    System.debug( commissionRecords.size() );
    for( CommissionRecord2__c cr : commissionRecords )
    {
      System.assertEquals( partsCount, cr.Commission_Line_Items__r.size() );
    }
  }

  @IsTest
  static void saveRecords_Update_Test()
  {
    AcctSeedERP__Material__c material =  [ SELECT Id,
                                                  AcctSeedERP__Project__c,
                                                  AcctSeedERP__Project_Task__c,
                                                  AcctSeedERP__Product__c,
                                                  AcctSeedERP__Quantity_Per_Unit__c,
                                                  GMBLASERP__Unit_Price__c
                                          FROM AcctSeedERP__Material__c
                                          LIMIT 1];
    //lets make sure our data is correct
    CommissionLineItem2__c[] clis = [SELECT Id, Sale_Price__c FROM CommissionLineItem2__c WHERE Material__c = :material.Id];
    System.assertEquals( 1, clis.size() );
    System.assertEquals( material.GMBLASERP__Unit_Price__c, clis[0].Sale_Price__c );

    material.GMBLASERP__Unit_Price__c = 1000;
    update material;

    Test.startTest();
    CommissionLineItem2_Service service = new CommissionLineItem2_Service();
    service.addMaterials( new List<AcctSeedERP__Material__c>{ material } );
    service.saveRecords();
    Test.stopTest();

    clis = [SELECT Id, Sale_Price__c FROM CommissionLineItem2__c WHERE Material__c = :material.Id];
    System.assertEquals( 1, clis.size() );
    System.assertEquals( 1000, clis[0].Sale_Price__c );
  }
}